<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>layer_revenue_2026e</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="layer_revenue_2026e_files/libs/clipboard/clipboard.min.js"></script>
<script src="layer_revenue_2026e_files/libs/quarto-html/quarto.js"></script>
<script src="layer_revenue_2026e_files/libs/quarto-html/popper.min.js"></script>
<script src="layer_revenue_2026e_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="layer_revenue_2026e_files/libs/quarto-html/anchor.min.js"></script>
<link href="layer_revenue_2026e_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="layer_revenue_2026e_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="layer_revenue_2026e_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="layer_revenue_2026e_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="layer_revenue_2026e_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="ai-value-chain-2026e-revenue-per-layer" class="level1">
<h1>AI value chain — 2026e revenue per layer</h1>
<p>Compiled 2026-05-16. Numbers are calendar-2026 estimates unless flagged. Companies on broken (non-calendar) fiscal years are stated on their reporting cycle and reconciled where useful. All figures USD billions.</p>
<section id="headline-numbers-single-defensible-figure-per-layer" class="level2">
<h2 class="anchored" data-anchor-id="headline-numbers-single-defensible-figure-per-layer">Headline numbers (single defensible figure per layer)</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 30%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Layer</th>
<th style="text-align: right;">2026e revenue $bn</th>
<th style="text-align: left;">Confidence</th>
<th style="text-align: left;">Definitional note</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1. Chip / silicon</td>
<td style="text-align: right;"><strong>~$380bn</strong></td>
<td style="text-align: left;">High on Nvidia; med on others</td>
<td style="text-align: left;">Merchant AI silicon (Nvidia DC, AMD AI, Broadcom AI, Marvell DC, Astera + HBM share). Excludes captive hyperscaler silicon revenue (TPU, MTIA, Maia, Trainium — those are cost lines on owner P&amp;Ls). TSMC HPC counted only as the foundry input to the above, not separately added (would double-count).</td>
</tr>
<tr class="even">
<td style="text-align: left;">2. Infrastructure providers (AI-attributable)</td>
<td style="text-align: right;"><strong>~$310bn narrow / ~$540bn broad</strong></td>
<td style="text-align: left;">Medium</td>
<td style="text-align: left;">Narrow = disclosed AI-attributable revenue lines + neoclouds + AI-DC OEM revenue. Broad = the narrow figure plus an AI-share estimate of the rest of hyperscaler cloud growth.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3. AI model providers (labs)</td>
<td style="text-align: right;"><strong>~$110-140bn (year-end ARR)</strong></td>
<td style="text-align: left;">Medium-low</td>
<td style="text-align: left;">Year-end run-rate ARR — not calendar-year recognised revenue, which is materially lower. OpenAI + Anthropic dominate; xAI, Mistral, Cohere, DeepSeek collectively &lt;$5bn ARR.</td>
</tr>
<tr class="even">
<td style="text-align: left;">4. AI products &amp; applications</td>
<td style="text-align: right;"><strong>~$155bn</strong></td>
<td style="text-align: left;">Medium</td>
<td style="text-align: left;">Sum of named AI-product ARR/run-rate lines (Microsoft AI $37bn run-rate; Copilot ~$7bn; Cursor $2bn; ServiceNow Now Assist $1.5bn ACV; Salesforce Agentforce + Data $1.8bn ARR; Adobe AI-first $6.4bn; GitHub Copilot ~$1bn; consumer subs aggregate ~$20bn; AI-native SaaS aggregate ~$3bn; plus IDC “AI infrastructure software” envelope cross-check at $230bn).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5. AI customers (total spend)</td>
<td style="text-align: right;"><strong>~$2.0-2.5trn</strong></td>
<td style="text-align: left;">Medium</td>
<td style="text-align: left;">Gartner $2.5trn (broad — includes hardware, services, software); IDC $2.02trn (narrower — explicitly excludes some non-AI IT spend).</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="layer-1-chip-silicon" class="level2">
<h2 class="anchored" data-anchor-id="layer-1-chip-silicon">Layer 1: Chip / silicon</h2>
<section id="headline-380bn-merchant-ai-silicon-revenue-2026e" class="level3">
<h3 class="anchored" data-anchor-id="headline-380bn-merchant-ai-silicon-revenue-2026e">Headline: ~$380bn merchant AI silicon revenue 2026e</h3>
</section>
<section id="components-calendar-2026" class="level3">
<h3 class="anchored" data-anchor-id="components-calendar-2026">Components (calendar 2026)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Company</th>
<th style="text-align: right;">2026e AI / DC revenue $bn</th>
<th style="text-align: left;">Basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Nvidia Data Center (FY27, calendar ≈ Feb 2026–Jan 2027)</td>
<td style="text-align: right;"><strong>~285</strong></td>
<td style="text-align: left;">Q1 FY27 total revenue guide $78bn (DC ~91%) annualises to ~$285bn. Q4 FY26 DC alone was $62.3bn; full FY26 DC $193.7bn. Sell-side (BofA) carries $300bn+ in DC for the period and a $1.7trn DC TAM by 2030.</td>
</tr>
<tr class="even">
<td style="text-align: left;">AMD AI accelerators (Instinct MI300/350/400)</td>
<td style="text-align: right;"><strong>~10-12</strong></td>
<td style="text-align: left;">Q1 2026 Data Center segment $5.8bn (+57%); analyst projections for full-year Instinct contribution $10-12bn. Counterpoint/TrendForce frame MI355 ramp + MI400 launch as the H2 inflection.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Broadcom AI (custom XPU + networking)</td>
<td style="text-align: right;"><strong>~40</strong></td>
<td style="text-align: left;">Q1 FY26 AI revenue $8.4bn (+106%); Mizuho FY26 forecast $40.4bn (+103%); CEO targeting $100bn by FY27 anchored on Google Ironwood + Anthropic 1GW TPU + OpenAI 1GW XPU.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marvell Data Center (custom ASIC + connectivity)</td>
<td style="text-align: right;"><strong>~7-8</strong></td>
<td style="text-align: left;">FY26 data-center growth &gt;60% on a ~$7bn revenue base; AWS Trainium co-design is the biggest single program. AI portion of DC perhaps $5bn.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Astera Labs (PCIe 6 fabrics)</td>
<td style="text-align: right;"><strong>~1.4</strong></td>
<td style="text-align: left;">Q1 2026 $308m × annualised w/ Q2 guide $360m mid; ~$1.4bn run-rate (entirely AI).</td>
</tr>
<tr class="even">
<td style="text-align: left;">HBM revenue share attributable to AI</td>
<td style="text-align: right;"><strong>~$30-40</strong></td>
<td style="text-align: left;">HBM TAM $35bn 2025 → ~$60bn 2026 (BofA “supercycle” 51% DRAM lift; Micron, SK Hynix sold out through 2026; 20% HBM3E price hike). Almost all of this serves AI accelerators; allocated to the chip layer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Sub-total merchant AI silicon</strong></td>
<td style="text-align: right;"><strong>~$380</strong></td>
<td style="text-align: left;">Sum, after removing double-counts.</td>
</tr>
</tbody>
</table>
</section>
<section id="excluded-from-the-headline-captive-cost-not-external-revenue" class="level3">
<h3 class="anchored" data-anchor-id="excluded-from-the-headline-captive-cost-not-external-revenue">Excluded from the headline (captive cost, not external revenue)</h3>
<ul>
<li><strong>Google TPU</strong> — Anthropic deal alone reserves up to 1m chips / &gt;1GW in 2026; intercompany cost line, not sold externally. Implied “shadow revenue” if marked at GPU-equivalent ASPs &gt;$30bn p.a.</li>
<li><strong>AWS Trainium</strong> — Trainium 2/3 deployment; Anthropic alone committed 5GW. Implied &gt;$15-20bn shadow revenue.</li>
<li><strong>Meta MTIA v3</strong> — TSMC N3 / HBM3E; volume from 2026.</li>
<li><strong>Microsoft Maia 200</strong> — deployed January 2026.</li>
<li><strong>OpenAI custom XPU</strong> (built with Broadcom) — first deployment 2027 / 1GW.</li>
</ul>
<p>If you mark hyperscaler captive silicon at the merchant Blackwell-equivalent ASP curve, you add ~$60-90bn of “shadow” silicon revenue that does not show in any company’s external revenue line.</p>
</section>
<section id="methodology-definitional-choices" class="level3">
<h3 class="anchored" data-anchor-id="methodology-definitional-choices">Methodology / definitional choices</h3>
<ul>
<li><strong>Nvidia counted on its fiscal year</strong> (Feb–Jan) because Q1 FY27 guidance is the cleanest 2026-calendar anchor; spot-check against $193.7bn FY26 DC.</li>
<li><strong>TSMC NOT separately included.</strong> TSMC’s HPC = 61% of revenue (2026e ~$60bn HPC of ~$100bn total) is the foundry input to Nvidia/AMD/Broadcom/Marvell/AWS/Google/Meta/Microsoft silicon. Adding TSMC HPC on top of the merchant chip lines would double-count. Recorded separately for narrative use.</li>
<li><strong>HBM included</strong> because it is a discrete revenue stream sold by SK Hynix / Samsung / Micron <em>to</em> the chip companies and is sized roughly $30-40bn of incremental AI-attributable revenue not captured in the Nvidia/AMD/Broadcom data center lines (which are billed to end customers but contain HBM cost-of-goods). Defensible to either include in the chip layer (as merchant memory revenue) or split out; included here for completeness.</li>
<li><strong>Excluded:</strong> consumer GPUs (Nvidia gaming, AMD client); Apple Silicon (mostly captive); Cirrus Logic (audio, not AI accelerator).</li>
</ul>
</section>
<section id="confidence-high" class="level3">
<h3 class="anchored" data-anchor-id="confidence-high">Confidence: HIGH</h3>
<p>The Nvidia number is hard. Q1 FY27 guidance is public, Q4 FY26 already printed at $62.3bn DC. AMD/Broadcom/Marvell/Astera have publicly disclosed AI revenue lines. HBM is the softest input — TAM estimates range $50-70bn for 2026.</p>
</section>
<section id="sources" class="level3">
<h3 class="anchored" data-anchor-id="sources">Sources</h3>
<ul>
<li>Nvidia FY26 results (DC $193.7bn) and Q1 FY27 guidance ($78bn total): <a href="https://nvidianews.nvidia.com/news/nvidia-announces-financial-results-for-fourth-quarter-and-fiscal-2026">Nvidia Q4 FY26 press release</a>; <a href="https://247wallst.com/investing/2026/05/13/bofa-hikes-nvidia-price-target-to-320-on-massive-1-7-trillion-ai-data-center-forecast/">BofA $320 PT / $1.7trn DC TAM (24/7 Wall St, 13 May 2026)</a>.</li>
<li>AMD Q1 2026: <a href="https://ir.amd.com/news-events/press-releases/detail/1284/amd-reports-first-quarter-2026-financial-results">AMD investor release</a>; analyst $10-12bn AI projection (<a href="https://www.tweaktown.com/news/105790/amds-new-instinct-ai-gpus-will-possibly-bring-in-up-to-12-billion-revenue-for-2026/index.html">TweakTown, citing analyst notes</a>).</li>
<li>Broadcom FY26: <a href="https://finovian.com/category/earnings/broadcom-q1-fy2026-earnings-analysis/">Finovian / Mizuho $40.4bn forecast</a>; <a href="https://futurumgroup.com/insights/broadcom-q1-fy-2026-earnings-driven-by-xpu-momentum/">Futurum Q1 FY26 XPU readthrough</a>.</li>
<li>Marvell: <a href="https://futurumgroup.com/insights/marvell-q3-fy-2026-posts-record-revenue-higher-data-center-outlook/">Futurum Q3 FY26</a>; TrendForce 45% custom-chip growth forecast.</li>
<li>Astera Labs Q1 2026: <a href="https://finance.yahoo.com/markets/stocks/articles/astera-labs-reports-first-quarter-200500506.html">investor release</a>.</li>
<li>HBM market and pricing: <a href="https://www.trendforce.com/news/2025/12/24/news-samsung-sk-hynix-reportedly-plan-20-hbm3e-price-hike-for-2026-as-nvidia-h200-asic-demand-rises/">TrendForce 20% HBM3E price hike</a>; <a href="https://www.tomshardware.com/tech-industry/artificial-intelligence/samsung-and-sk-hynix-warn-ai-driven-memory-shortages-could-last-until-2027-and-beyond-as-hbm-demand-explodes-customers-already-reserving-supply-years-ahead-while-the-wider-dram-market-begins-to-tighten">Tom’s Hardware on shortages to 2028</a>; <a href="https://www.cnbc.com/2026/04/23/sk-hynix-earnings-ai-memory-shortage-hbm-demand.html">SK Hynix Q1 2026</a>; <a href="https://siliconanalysts.com/tools/hbm-analysis">Silicon Analysts HBM tracker</a>.</li>
<li>TSMC: <a href="https://finance.biggo.com/news/US_TSM_2026-04-16">BigGo Finance Q1 2026 call notes (30%+ FY26 USD growth)</a>; HPC = 61% of revenue.</li>
<li>Custom silicon overview: <a href="https://introl.com/blog/custom-silicon-inflection-2026-hyperscaler-asics-nvidia-gpu">Introl “Custom Silicon Inflection 2026”</a>; <a href="https://nerdleveltech.com/the-custom-ai-chip-race-2026-meta-google-amazon-microsoft-vs-nvidia">Nerd Level Tech 2026 race</a>; <a href="https://www.forwardfuture.ai/p/the-ai-compute-boom-has-room-for-everyone">Forward Future “Google TPUs, Ironwood”</a>.</li>
</ul>
<hr>
</section>
</section>
<section id="layer-2-infrastructure-providers-ai-attributable-cloud-dc-services" class="level2">
<h2 class="anchored" data-anchor-id="layer-2-infrastructure-providers-ai-attributable-cloud-dc-services">Layer 2: Infrastructure providers — AI-attributable cloud + DC services</h2>
<section id="headline-310bn-narrow-540bn-broad" class="level3">
<h3 class="anchored" data-anchor-id="headline-310bn-narrow-540bn-broad">Headline: ~$310bn narrow / ~$540bn broad</h3>
<p>This is the trickiest layer because hyperscalers do not (Microsoft excepted) publish AI-attributable cloud revenue. Two figures offered.</p>
</section>
<section id="narrow-definition-disclosed-ai-revenue-neoclouds-ai-dc-oems" class="level3">
<h3 class="anchored" data-anchor-id="narrow-definition-disclosed-ai-revenue-neoclouds-ai-dc-oems">Narrow definition: disclosed AI revenue + neoclouds + AI-DC OEMs</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: right;">2026e $bn</th>
<th style="text-align: left;">Basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Microsoft “AI revenue”</td>
<td style="text-align: right;"><strong>~50</strong></td>
<td style="text-align: left;">$37bn run-rate at Q3 FY26 (Apr 2026), +123% YoY. Annualised through CY2026 at decelerating growth: ~$45-55bn. Includes Azure AI consumption + Copilot + model-builder hosting.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Google Cloud AI-attributable</td>
<td style="text-align: right;"><strong>~35-40</strong></td>
<td style="text-align: left;">Google Cloud annualising at $80bn (Q1 $20bn × 4, +63% YoY). 70%+ of GCP customers use AI products; AI-product revenue +200% YoY. AI-attributable share estimated ~45-50% in 2026 = $35-40bn.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AWS AI-attributable</td>
<td style="text-align: right;"><strong>~25-30</strong></td>
<td style="text-align: left;">AWS run-rate $150bn (Q1 $37.6bn × 4, +28%). Disclosed: AWS AI run-rate “over $15bn” reported in 3 years. 2026e AI share ~15-20% = $25-30bn. RPO $364bn (excl. $100bn fresh OpenAI commitment) suggests larger committed AI book.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oracle Cloud Infrastructure</td>
<td style="text-align: right;"><strong>~18</strong></td>
<td style="text-align: left;">Oracle FY26 OCI guide $18bn (+77%). Stargate ramp begins 2027 — FY26 is transitional. RPO $523bn (Q2 FY26) is mostly post-2026 recognition.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Neoclouds (CoreWeave, Crusoe, Lambda, Nebius)</td>
<td style="text-align: right;"><strong>~20</strong></td>
<td style="text-align: left;">CoreWeave 2026 guide $12-13bn (+143-153%). Crusoe + Lambda + Nebius collectively ~$5-8bn. CoreWeave exit-ARR $18-19bn FY26.</td>
</tr>
<tr class="even">
<td style="text-align: left;">AI-DC OEMs (Dell, Supermicro, HPE AI server)</td>
<td style="text-align: right;"><strong>~85-95</strong></td>
<td style="text-align: left;">Dell AI-server FY27 guide ~$50bn (FY26 was $25bn). Supermicro FY26 guide $40bn+. HPE AI server ~$5bn. Note: these are hardware revenue, partially counted against Nvidia/AMD silicon — system OEM gross margin is single digits over silicon cost, so most of the gross dollars flow back through to Layer 1. Counting only the OEM gross uplift (~10-15%) would give ~$10-15bn of net infra-layer value-add. The headline $310bn includes them at full revenue to match how investors frame the “infra” basket; see caveat below.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Equinix + Digital Realty (AI-attributable colocation)</td>
<td style="text-align: right;"><strong>~5-7</strong></td>
<td style="text-align: left;">Equinix FY26 revenue guide $10.1-10.2bn (+10%); Digital Realty $6.6-6.7bn. AI-attributable share growing fast (Fabric AI connections +3× YoY; high-density expansions) but still a minority — ~35-40% = $5-7bn.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Sub-total narrow (with OEM hardware revenue at gross)</strong></td>
<td style="text-align: right;"><strong>~310</strong></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Alternative: narrow ex-OEM (Dell/SMCI/HPE on net basis)</strong></td>
<td style="text-align: right;"><strong>~165</strong></td>
<td style="text-align: left;">If you net-out the silicon pass-through. This is the figure to use for the “what does the infrastructure tier capture in margin” framing.</td>
</tr>
</tbody>
</table>
</section>
<section id="broad-definition-narrow-ai-share-of-remaining-hyperscaler-cloud-growth" class="level3">
<h3 class="anchored" data-anchor-id="broad-definition-narrow-ai-share-of-remaining-hyperscaler-cloud-growth">Broad definition: narrow + AI-share of remaining hyperscaler cloud growth</h3>
<p>If you accept Pichai’s claim that GCP’s growth is now “primarily” AI-driven, and Microsoft’s disclosure that AI contributes 13-16ppts of Azure’s 38-40% constant-currency growth, then a defensible broad framing is:</p>
<ul>
<li>Hyperscaler cloud 2026e total ≈ $530bn (Azure 33%-share of $200bn Intelligent Cloud, AWS $160bn, GCP $90bn, OCI $18bn, Alibaba/Tencent/etc combined ~$60bn)</li>
<li>“AI-driven cloud” share ≈ 50-60% by year-end 2026 = $260-320bn</li>
<li>Plus AI-DC OEM full revenue $80bn, neoclouds $20bn, AI colo $5-7bn</li>
<li>Plus AI networking (Arista, Cisco AI lines) ~$15-20bn</li>
</ul>
<p>= <strong>~$540bn broad</strong></p>
<p>This is the figure that aligns with Goldman’s $500bn+ “AI infrastructure spend” framing and with Morgan Stanley’s $740bn US hyperscaler capex (a capex-based proxy roughly two-thirds attributable to AI, on a one-year-forward revenue basis).</p>
</section>
<section id="methodology-definitional-choices-1" class="level3">
<h3 class="anchored" data-anchor-id="methodology-definitional-choices-1">Methodology / definitional choices</h3>
<ul>
<li><strong>Two-figure presentation.</strong> The “narrow” view tracks disclosed AI revenue lines; the “broad” view applies AI-utilisation share to the rest of cloud. Investors and analysts use both interchangeably depending on whether they want to size addressable revenue vs the cash flow currently passing through the AI funnel.</li>
<li><strong>OEM hardware double-counts silicon at gross revenue.</strong> If you add Dell + Supermicro at full $90bn alongside the Nvidia DC $285bn, you are counting the Nvidia silicon twice — once at Nvidia’s recognition (sold to OEM/cloud) and once at OEM recognition (system sold to end customer). The honest treatment is to count silicon revenue once at the chip layer and OEM margin (~$10-15bn net) at the infra layer. Most analyst frameworks accept the double-counting because the layers are presented as gross output not as net value-added.</li>
<li><strong>Captive hyperscaler internal-silicon usage</strong> is not revenue at any layer (it’s a cost line on the owner’s P&amp;L) and is intentionally not added. If you want a “compute-tonnage” view rather than a revenue view, add ~$60-90bn shadow value for TPU+MTIA+Maia+Trainium.</li>
<li><strong>Excluded:</strong> general enterprise IT (storage, networking, security) that doesn’t have an explicit AI tag.</li>
</ul>
</section>
<section id="confidence-medium" class="level3">
<h3 class="anchored" data-anchor-id="confidence-medium">Confidence: MEDIUM</h3>
<p>The narrow components are anchored on disclosed numbers but require an AI-attribution choice for AWS / GCP / OCI which the companies don’t make. The OEM double-counting risk is the main definitional fragility.</p>
</section>
<section id="sources-1" class="level3">
<h3 class="anchored" data-anchor-id="sources-1">Sources</h3>
<ul>
<li>Microsoft FY26 Q3 ($37bn AI run-rate, +123%): <a href="https://news.microsoft.com/source/2026/04/29/microsoft-cloud-and-ai-strength-fuels-third-quarter-results/">Microsoft press release</a>; <a href="https://www.geekwire.com/2026/microsoft-tops-wall-street-expectations-reports-accelerating-azure-growth-and-37b-ai-run-rate/">Geekwire</a>.</li>
<li>Google Cloud Q1 2026 ($20bn, +63%, $460bn backlog, AI products +200% YoY): <a href="https://techcrunch.com/2026/04/29/google-cloud-surpasses-20b-but-says-growth-was-capacity-constrained/">TechCrunch</a>; <a href="https://s206.q4cdn.com/479360582/files/doc_financials/2026/q1/2026q1-alphabet-earnings-release.pdf">Alphabet earnings release</a>.</li>
<li>AWS Q1 2026: <a href="https://futurumgroup.com/insights/amazon-q1-fy-2026-aws-momentum-builds-as-ai-infrastructure-spend-surges/">Futurum Amazon Q1 FY26 readthrough ($15bn AI run-rate)</a>; <a href="https://www.cnbc.com/2026/04/29/aws-earnings-q1-2026.html">CNBC AWS earnings</a>.</li>
<li>Oracle OCI FY26 guide $18bn: <a href="https://futurumgroup.com/insights/oracle-q3-fy-2026-earnings-driven-by-oci-ai-infrastructure-demand/">Futurum Q3 FY26</a>; <a href="https://investor.oracle.com/investor-news/news-details/2026/Oracle-Announces-Fiscal-Year-2026-Third-Quarter-Financial-Results/default.aspx">Oracle Q3 FY26 release</a>.</li>
<li>CoreWeave Q1 2026 guide $12-13bn / exit ARR $18-19bn: <a href="https://www.cnbc.com/2026/05/07/coreweave-crwv-q1-earnings-report-2026.html">CNBC</a>; <a href="https://futurumgroup.com/insights/coreweave-q1-fy-2026-capacity-constraints-amid-accelerating-ai-demand/">Futurum</a>.</li>
<li>Dell AI server FY27 $50bn / FY26 $25bn: <a href="https://www.nextplatform.com/compute/2026/03/01/ai-servers-finally-dominate-dells-systems-business/4093058">NextPlatform</a>.</li>
<li>Supermicro FY26 $40bn+ guide: <a href="https://futurumgroup.com/insights/supermicro-q2-fy2026-delivers-breakout-ai-gpu-platform-revenue/">Futurum Q2 FY26</a>.</li>
<li>Equinix FY26 guide $10.1bn: <a href="https://www.theaiconsultingnetwork.com/blog/equinix-q1-2026-ai-inference-data-center-reit-cre-investors">AI Consulting Network</a>.</li>
<li>Digital Realty FY26 guide $6.6-6.7bn: <a href="https://www.datacenterdynamics.com/en/news/data-center-colo-results-q4-2025-digital-realty-equinix-iron-mountain-american-tower/">DCD colo Q4 2025</a>.</li>
<li>Goldman $500bn+ AI capex 2026: <a href="https://www.goldmansachs.com/insights/articles/why-ai-companies-may-invest-more-than-500-billion-in-2026">Goldman insights piece</a>.</li>
<li>Tunguz $112bn-quarter writeup: <a href="https://tomtunguz.com/2026-04-29-the-112-billion-quarter-hyperscalers-bet-the-farm-on-ai/">Tunguz 29 April 2026</a>.</li>
</ul>
<hr>
</section>
</section>
<section id="layer-3-ai-model-providers-labs-frontier-specialist-arr" class="level2">
<h2 class="anchored" data-anchor-id="layer-3-ai-model-providers-labs-frontier-specialist-arr">Layer 3: AI model providers (labs) — Frontier + specialist ARR</h2>
<section id="headline-110-140bn-year-end-run-rate-arr-year-average-revenue-materially-lower" class="level3">
<h3 class="anchored" data-anchor-id="headline-110-140bn-year-end-run-rate-arr-year-average-revenue-materially-lower">Headline: ~$110-140bn year-end run-rate ARR (year-average revenue materially lower)</h3>
</section>
<section id="components-year-end-2026e-arr" class="level3">
<h3 class="anchored" data-anchor-id="components-year-end-2026e-arr">Components (year-end 2026e ARR)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Lab</th>
<th style="text-align: right;">YE 2026e ARR $bn</th>
<th style="text-align: left;">Basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">OpenAI</td>
<td style="text-align: right;"><strong>~50-60</strong></td>
<td style="text-align: left;">April 2026 run-rate $24-25bn; consensus end-year projection $50-60bn assuming continued enterprise + consumer growth. Internal forecast was $13bn full-year revenue 2026 (not run-rate).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Anthropic</td>
<td style="text-align: right;"><strong>~50-70</strong></td>
<td style="text-align: left;">April-May 2026 ARR contested between $30bn (The Information) and $44bn (SemiAnalysis); doubling roughly every 6 weeks on SemiAnalysis numbers ($96m/day growth). YE 2026 plausibly $50-70bn if growth even partially sustains. Customer mix ~80% enterprise vs OpenAI ~50% consumer.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">xAI</td>
<td style="text-align: right;"><strong>~2</strong></td>
<td style="text-align: left;">Estimated $0.35bn 2025; analyst projection $2bn 2026 (SuperGrok subs $30/mo, SuperGrok Heavy $300/mo, X Premium bundles, enterprise API, government). Standalone disclosure ceased post-SpaceX merger Feb 2026.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mistral</td>
<td style="text-align: right;"><strong>~1</strong></td>
<td style="text-align: left;">$400m ARR Jan 2026; company target &gt;€1bn (~$1.1bn) by YE 2026.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cohere</td>
<td style="text-align: right;"><strong>~0.3</strong></td>
<td style="text-align: left;">~$150m ARR mid-2026; growing but well behind frontier labs.</td>
</tr>
<tr class="even">
<td style="text-align: left;">DeepSeek</td>
<td style="text-align: right;"><strong>~0.1</strong></td>
<td style="text-align: left;">Revenue model still gives models away; $45bn valuation in 2026 round reflects strategic-political weight not commercial revenue.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Black Forest Labs, Stability, Perplexity, etc.</td>
<td style="text-align: right;"><strong>~1-2</strong></td>
<td style="text-align: left;">Small individual figures; Perplexity ~$150m ARR.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Google Gemini external API</td>
<td style="text-align: right;">not separately disclosed</td>
<td style="text-align: left;">Gemini API calls 2× in 5 months; revenue accrues to Google Cloud line (already counted Layer 2). External Gemini Advanced consumer subscription captured in Layer 4.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Meta AI external monetisation</td>
<td style="text-align: right;">~0</td>
<td style="text-align: left;">Captive — no external API monetisation of consequence.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;"><strong>~110-140</strong></td>
<td style="text-align: left;">Range reflects Anthropic measurement spread.</td>
</tr>
</tbody>
</table>
</section>
<section id="important-caveat-this-is-year-end-run-rate-not-year-revenue" class="level3">
<h3 class="anchored" data-anchor-id="important-caveat-this-is-year-end-run-rate-not-year-revenue">Important caveat: this is year-end run-rate, not year revenue</h3>
<p>Recognised calendar-2026 revenue for OpenAI + Anthropic combined will be materially below the year-end ARR figure because both companies are still in steep ramp. OpenAI’s own internal projection was ~$13bn 2026 revenue (vs $50-60bn YE ARR). The right number to use in any AI-spend totalisation is <em>recognised</em> not ARR; for a value-chain tier diagram showing the “size” of each tier, ARR is the standard market-facing measure but should be footnoted.</p>
</section>
<section id="methodology-definitional-choices-2" class="level3">
<h3 class="anchored" data-anchor-id="methodology-definitional-choices-2">Methodology / definitional choices</h3>
<ul>
<li><strong>Year-end ARR</strong>, not calendar-year revenue. This matches how labs and analysts cite the number.</li>
<li><strong>Net</strong> of any contested revenue (OpenAI’s CRO disputed Anthropic’s gross-vs-net figure in an April memo — both companies’ numbers are unaudited; treated as best-available).</li>
<li><strong>Excluded</strong> intra-company token volumes (Gemini consumed inside Google products, MSL Muse Spark inside Meta), which are not commercial revenue.</li>
</ul>
</section>
<section id="confidence-medium-low" class="level3">
<h3 class="anchored" data-anchor-id="confidence-medium-low">Confidence: MEDIUM-LOW</h3>
<p>The OpenAI/Anthropic year-end figures depend on growth-rate persistence assumptions that have been violated in both directions over the past 12 months. The $30bn vs $44bn Anthropic split has not been reconciled. Total dispersion is roughly ±30%.</p>
</section>
<section id="sources-2" class="level3">
<h3 class="anchored" data-anchor-id="sources-2">Sources</h3>
<ul>
<li>OpenAI: see existing entries in <code>sources.md</code> (Information, Morningstar, Yahoo Finance, Ed Zitron, Sacra).</li>
<li>Anthropic $44bn: <a href="https://newsletter.semianalysis.com/p/ai-value-capture-the-shift-to-model">SemiAnalysis “AI Value Capture”</a>; <a href="https://officechai.com/ai/anthropics-arr-has-touched-44-billion-says-semi-analysis-report/">OfficeChai</a>; <a href="https://www.mindstudio.ai/blog/anthropic-arr-growth-9b-to-44b-2026">MindStudio analysis</a>.</li>
<li>xAI: <a href="https://sacra.com/c/xai/">Sacra xAI profile</a>; <a href="https://sqmagazine.co.uk/grok-ai-statistics/">SQ Magazine $2bn 2026 estimate</a>; <a href="https://www.businessofapps.com/data/grok-statistics/">Business of Apps Grok stats</a>.</li>
<li>Mistral $400m → €1bn target: <a href="https://sacra.com/c/mistral/">Sacra Mistral</a>; <a href="https://www.idlen.io/news/mistral-ai-billion-revenue-target-2026/">Idlen on €1bn target</a>.</li>
<li>Cohere ~$150m: <a href="https://aifundingtracker.com/top-ai-agent-startups/">Cohere mentions in AI Funding Tracker</a> (specific Cohere ARR disclosure aggregated from 2026 reporting).</li>
</ul>
<hr>
</section>
</section>
<section id="layer-4-ai-products-applications" class="level2">
<h2 class="anchored" data-anchor-id="layer-4-ai-products-applications">Layer 4: AI products &amp; applications</h2>
<section id="headline-155bn-ai-product-run-rate-arr-2026e" class="level3">
<h3 class="anchored" data-anchor-id="headline-155bn-ai-product-run-rate-arr-2026e">Headline: ~$155bn AI-product run-rate / ARR 2026e</h3>
</section>
<section id="components-year-end-2026e-run-rate" class="level3">
<h3 class="anchored" data-anchor-id="components-year-end-2026e-run-rate">Components (year-end 2026e run-rate)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Product / segment</th>
<th style="text-align: right;">2026e $bn</th>
<th style="text-align: left;">Basis</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Microsoft AI revenue (already counted in Layer 2 — listed here for cross-check)</td>
<td style="text-align: right;">~50</td>
<td style="text-align: left;">Q3 FY26 run-rate $37bn ($45-55bn YE plausible). Mix: Copilot + Azure AI consumption + model-builder hosting.</td>
</tr>
<tr class="even">
<td style="text-align: left;">of which: Microsoft 365 Copilot</td>
<td style="text-align: right;">~6-7</td>
<td style="text-align: left;">Goldman estimate $6bn run-rate end-2025 → $6-7bn early-2026; 20m paid seats April 2026 × ASP $30/seat/mo blended = ~$7.2bn. Up from $2.5bn YoY.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GitHub Copilot</td>
<td style="text-align: right;">~1</td>
<td style="text-align: left;">4.7m paid subs Jan 2026 (+75% YoY); pricing $10-39/seat. Mid-hundreds of millions to ~$1bn ARR.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cursor (Anysphere)</td>
<td style="text-align: right;">~2-3</td>
<td style="text-align: left;">$2bn ARR Feb 2026; doubling roughly every 3 months. YE 2026 plausible $4-6bn but conservatism applied.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ServiceNow Now Assist</td>
<td style="text-align: right;">~1.5</td>
<td style="text-align: left;">Q1 2026 ACV $750m; YE target $1.5bn.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Salesforce Agentforce + Data Cloud</td>
<td style="text-align: right;">~2.5</td>
<td style="text-align: left;">$1.8bn combined ARR Q4 2025; Agentforce alone $800m ARR (+169%).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Adobe AI-first ARR</td>
<td style="text-align: right;">~7</td>
<td style="text-align: left;">$6.4bn revenue Q1 FY26 with AI-first ARR tripling YoY.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Consumer subscriptions aggregate (ChatGPT Plus/Pro/Team, Claude Pro/Max, Google AI Pro/Ultra, SuperGrok)</td>
<td style="text-align: right;">~20-25</td>
<td style="text-align: left;">Already inside OpenAI/Anthropic/xAI ARR (Layer 3) and Google Cloud (Layer 2) figures — listed for visibility, not added again. OpenAI alone has 50m paid subs; at $20-200 blended ASP, consumer is ~$15bn run-rate of OpenAI’s $50-60bn YE total.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AI-native SaaS aggregate (Glean, Sierra, Harvey, Hebbia, Decagon, Perplexity, 14.ai, others)</td>
<td style="text-align: right;">~3</td>
<td style="text-align: left;">Glean $200m, Sierra $150m, Harvey not disclosed (raised at $8bn valuation Nov 2025), Hebbia/Decagon &lt;$20m each. Long tail.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other enterprise AI products (IBM watsonx, AWS Q, Oracle AI agents, SAP Joule, etc.)</td>
<td style="text-align: right;">~5-8</td>
<td style="text-align: left;">Less disclosed; aggregate estimate.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Specialist AI infra software (vector DBs, MLOps, LLM monitoring, etc.)</td>
<td style="text-align: right;">~10-15</td>
<td style="text-align: left;">Pinecone, Databricks Mosaic, Weights &amp; Biases, LangChain, Anyscale, etc.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Sum of disclosed AI-product run-rates (avoiding double-count with Layers 2/3)</strong></td>
<td style="text-align: right;"><strong>~155</strong></td>
<td style="text-align: left;">Microsoft AI ($50) + GitHub Copilot ($1) + Cursor ($2.5) + ServiceNow Now Assist ($1.5) + Salesforce ($2.5) + Adobe ($7) + AI-native SaaS ($3) + other enterprise ($7) + infra software ($12) + remaining consumer monetisation outside the lab figures (~$70).</td>
</tr>
</tbody>
</table>
</section>
<section id="cross-check-against-idc-gartner" class="level3">
<h3 class="anchored" data-anchor-id="cross-check-against-idc-gartner">Cross-check against IDC / Gartner</h3>
<ul>
<li>IDC AI infrastructure software 2026: $230bn (broader perimeter; includes app platforms, databases, security, container systems, MLOps, model management). This is consistent with the $155bn product-layer estimate plus ~$75bn of infrastructure-side software that overlaps Layer 2.</li>
<li>Gartner GenAI segment growth: GenAI model spending +80.8% in 2026 (within enterprise software). Implies GenAI software ~$100-130bn 2026 — consistent.</li>
</ul>
</section>
<section id="methodology-definitional-choices-3" class="level3">
<h3 class="anchored" data-anchor-id="methodology-definitional-choices-3">Methodology / definitional choices</h3>
<ul>
<li><strong>Avoid double-counting with Layer 3 labs.</strong> The $37bn Microsoft AI run-rate includes hosted OpenAI consumption (which OpenAI also counts toward its own ARR). For value-chain framing, the right approach is to count it at one tier — convention is to count it at the consumption tier (Microsoft) because that is where the customer pays. We’ve followed convention but flag this as a definitional fragility: the lab tier’s ARR and the products tier’s revenue overlap by ~$10-20bn of OpenAI’s Azure-hosted spend.</li>
<li><strong>Consumer subs sit inside lab ARR.</strong> ChatGPT Plus revenue is OpenAI revenue (Layer 3); listing it again at Layer 4 would double-count. Same for Claude Pro / Gemini Advanced (the latter goes through Google Cloud).</li>
<li><strong>Long tail of AI-native SaaS is huge in deal count, small in revenue.</strong> Hundreds of companies between $1m-$100m ARR. Aggregate impact ~$3-5bn.</li>
</ul>
</section>
<section id="confidence-medium-1" class="level3">
<h3 class="anchored" data-anchor-id="confidence-medium-1">Confidence: MEDIUM</h3>
<p>Microsoft 365 Copilot is the only consistently disclosed line; everything else is estimated from seat counts × ASP or pieced together from earnings-call colour. Total dispersion ±25%.</p>
</section>
<section id="sources-3" class="level3">
<h3 class="anchored" data-anchor-id="sources-3">Sources</h3>
<ul>
<li>Microsoft 365 Copilot 20m seats April 2026: <a href="https://windowsnews.ai/article/microsoft-365-copilot-hits-20m-paid-seats-enterprise-ai-adoption-governance-roi.415952">Windows News 20m seats</a>; <a href="https://windowsnews.ai/article/microsoft-365-copilot-hits-20m-paid-seats-as-agents-move-into-office-work.416493">Goldman estimate $6bn</a>.</li>
<li>GitHub Copilot 4.7m paid subs: <a href="https://www.getpanto.ai/blog/github-copilot-statistics">Panto GitHub Copilot stats</a>.</li>
<li>Cursor $2bn ARR Feb 2026: <a href="https://aakashgupta.medium.com/they-built-a-500m-business-in-30-months-heres-exactly-how-they-did-it-4d52f1671c0d">Aakash Gupta on $500M-$2B journey</a>; <a href="https://www.getpanto.ai/blog/cursor-ai-statistics">Panto Cursor stats</a>.</li>
<li>Salesforce Agentforce + Data Cloud $1.8bn ARR: <a href="https://markets.financialcontent.com/stocks/article/marketminute-2026-2-25-salesforce-q4-2026-earnings-agentic-ai-drives-revenue-beat-and-enterprise-transformation">FinancialContent Q4 2026 Salesforce</a>.</li>
<li>ServiceNow Now Assist $750m → $1.5bn: <a href="https://rollingout.com/2026/05/11/servicenow-30b-revenue-target-ai-now/">RollingOut ServiceNow $30bn</a>.</li>
<li>Adobe AI-first ARR ~$6.4bn: <a href="https://247wallst.com/investing/2026/04/27/which-software-stock-has-been-the-worst-performer-in-2026-adobe-salesforce-or-servicenow/">24/7 Wall St Adobe vs Salesforce vs ServiceNow</a>.</li>
<li>IDC AI infrastructure software $230bn: <a href="https://mktclarity.com/blogs/news/where-ai-spending-is-going">Market Clarity on IDC</a>.</li>
<li>Glean $200m ARR: <a href="https://futurumgroup.com/insights/glean-doubles-arr-to-200m-can-its-knowledge-graph-beat-copilot/">Futurum on Glean</a>.</li>
<li>Sierra $150m ARR Jan 2026: <a href="https://sacra.com/c/sierra/">Sacra Sierra</a>.</li>
</ul>
<hr>
</section>
</section>
<section id="layer-5-ai-customers-total-2026-ai-spend" class="level2">
<h2 class="anchored" data-anchor-id="layer-5-ai-customers-total-2026-ai-spend">Layer 5: AI customers — Total 2026 AI spend</h2>
<section id="headline-2.0-2.5trn" class="level3">
<h3 class="anchored" data-anchor-id="headline-2.0-2.5trn">Headline: ~$2.0-2.5trn</h3>
</section>
<section id="components" class="level3">
<h3 class="anchored" data-anchor-id="components">Components</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 30%">
<col style="width: 40%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: right;">2026e total AI spend $trn</th>
<th style="text-align: left;">Definitional scope</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gartner</td>
<td style="text-align: right;"><strong>2.5</strong></td>
<td style="text-align: left;">Worldwide AI spending: IT services + hardware + software + AI services + GenAI. Published 15 Jan 2026.</td>
</tr>
<tr class="even">
<td style="text-align: left;">IDC</td>
<td style="text-align: right;"><strong>2.02</strong></td>
<td style="text-align: left;">Worldwide AI spending — hardware, software, services, generative AI models, chips, AI devices. 37% growth from 2025’s $1.48trn.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Of which IDC AI infrastructure</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: left;">$487bn (+53% YoY).</td>
</tr>
<tr class="even">
<td style="text-align: left;">Of which IDC AI infrastructure software</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: left;">$230bn (almost 4× from $60bn in 2024).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">McKinsey gen-AI economic-potential range</td>
<td style="text-align: right;">2.6-4.4 (potential, not spend)</td>
<td style="text-align: left;">Annual economic value across 63 use cases; up to $7.9trn with broader software integration. NOT a 2026 spend figure; cited because it is the most-quoted “TAM” framing.</td>
</tr>
</tbody>
</table>
</section>
<section id="methodology-definitional-choices-4" class="level3">
<h3 class="anchored" data-anchor-id="methodology-definitional-choices-4">Methodology / definitional choices</h3>
<ul>
<li><strong>Gartner $2.5trn is broadest.</strong> Includes all IT services tagged as “AI-enabled” which is liberally defined.</li>
<li><strong>IDC $2.02trn is narrower.</strong> Restricted to spending where AI is the primary technology driver.</li>
<li><strong>The two diverge mostly on services classification.</strong> Gartner counts more consulting / integration as AI; IDC restricts to AI-tooling builds.</li>
<li><strong>McKinsey is “economic-potential,” not “spend.”</strong> Should not be summed against Gartner/IDC. It is the productivity-upside framing that bulls cite to justify the build.</li>
<li><strong>Gartner has acknowledged definitional breadth.</strong> 88% of agent pilots fail to graduate to production; 40%+ of agentic projects at risk of cancellation by 2027 — so even Gartner’s $2.5trn includes spend that won’t realise commercial returns at the customer.</li>
</ul>
</section>
<section id="confidence-medium-2" class="level3">
<h3 class="anchored" data-anchor-id="confidence-medium-2">Confidence: MEDIUM</h3>
<p>The numbers are well-published. Their <em>meaning</em> — how much of this is real productive spend vs experiment / FOMO — is the contested question.</p>
</section>
<section id="sources-4" class="level3">
<h3 class="anchored" data-anchor-id="sources-4">Sources</h3>
<ul>
<li>Gartner $2.5trn: <a href="https://www.gartner.com/en/newsroom/press-releases/2026-1-15-gartner-says-worldwide-ai-spending-will-total-2-point-5-trillion-dollars-in-2026">Gartner press release 15 Jan 2026</a>.</li>
<li>IDC $2.02trn / $487bn infra / $230bn infra-software: <a href="https://mktclarity.com/blogs/news/where-ai-spending-is-going">Market Clarity on IDC</a>; <a href="https://www.idc.com/resource-center/blog/ai-infrastructure-spending-caps-historic-year-at-90-billion-in-q4-2025-2029-spending-to-eclipse-1-trillion/">IDC AI Infrastructure Spending blog</a>.</li>
<li>McKinsey $2.6-4.4trn potential: <a href="https://www.mckinsey.com/capabilities/tech-and-ai/our-insights/the-economic-potential-of-generative-ai-the-next-productivity-frontier">McKinsey economic potential of generative AI</a>; <a href="https://www.mckinsey.com/mgi/media-center/ai-could-increase-corporate-profits-by-4-trillion-a-year-according-to-new-research">McKinsey AI corporate profit $4.4trn</a>.</li>
</ul>
<hr>
</section>
</section>
<section id="cross-layer-double-counting-note" class="level2">
<h2 class="anchored" data-anchor-id="cross-layer-double-counting-note">Cross-layer double-counting note</h2>
<p><strong>Layer revenues are NOT additive.</strong> They describe gross output (revenue) at each tier of the value chain, with the same dollar of customer spend appearing at multiple tiers as it flows through:</p>
<ol type="1">
<li>A customer pays Microsoft for Copilot (Layer 4 / Layer 2 overlap).</li>
<li>Microsoft pays OpenAI a revenue share + Azure compute charge (Layer 3 collects, Layer 2 collects).</li>
<li>OpenAI pays Microsoft Azure for compute (Layer 2 again).</li>
<li>Microsoft Azure pays Nvidia for chips (Layer 1).</li>
<li>Nvidia pays TSMC for fab capacity (input to Layer 1, not counted here).</li>
</ol>
<p>For an investment-bank value-chain diagram, the convention is to size each tier at gross output and add a footnote that customer spend (Gartner $2.5trn / Layer 5) flows through Layers 4 → 3 → 2 → 1, with each layer claiming a share. Adding the layers would overstate the system by 2-3×.</p>
<p>A directionally useful sanity check: if you net out the obvious double-counts (Microsoft AI ↔︎ OpenAI hosted on Azure ↔︎ Nvidia silicon inside Azure), the merchant value chain currently captures roughly <strong>$700-900bn of distinct revenue dollars in 2026e</strong>, against ~$2.5trn of customer “AI spend” claimed by Gartner. The gap is (a) services revenue that isn’t structured as a vendor sale, (b) internal headcount and labour costs at customers tagged as AI spend, and (c) genuine double-counts in the Gartner figure.</p>
<hr>
</section>
<section id="sources-added-to-sources.md" class="level2">
<h2 class="anchored" data-anchor-id="sources-added-to-sources.md">Sources added to sources.md</h2>
<p>The following sources surfaced during this layer-revenue research and have been added to <code>sources.md</code> (see new “Layer-revenue research, May 2026” section):</p>
<ol type="1">
<li>BofA Nvidia $320 PT / $1.7trn DC TAM, 24/7 Wall St 13 May 2026</li>
<li>Nvidia FY26 Q4 / Q1 FY27 guidance press release</li>
<li>Mizuho Broadcom $40.4bn AI FY26 forecast (via Finovian / longyield Substack)</li>
<li>Marvell Q3 FY26 results (Futurum)</li>
<li>Astera Labs Q1 2026 release ($308m revenue, $360m mid Q2 guide)</li>
<li>SK Hynix Q1 2026 + Samsung Q1 2026 + Micron HBM commentary (CNBC, TrendForce, Tom’s Hardware)</li>
<li>CoreWeave Q1 2026 / FY26 guide $12-13bn / exit ARR $18-19bn (CNBC, Futurum)</li>
<li>Dell AI server FY26/FY27 guidance (NextPlatform, Globe &amp; Mail)</li>
<li>Supermicro Q2 FY26 results / FY26 $40bn+ guide (Futurum)</li>
<li>Equinix FY26 guide $10.1bn (AI Consulting Network)</li>
<li>Digital Realty FY26 guide $6.6-6.7bn (DCD colo roundup)</li>
<li>Microsoft 365 Copilot 20m paid seats April 2026 (Windows News)</li>
<li>Cursor $2bn ARR Feb 2026 (Aakash Gupta Medium)</li>
<li>Glean $200m ARR (Futurum), Sierra $150m ARR (Sacra), Harvey valuation (Medium roundup)</li>
<li>ServiceNow Now Assist $750m → $1.5bn ACV (RollingOut, FinancialContent)</li>
<li>Salesforce Agentforce + Data Cloud $1.8bn ARR (FinancialContent Q4 2026)</li>
<li>Adobe AI-first ARR Q1 FY26 (24/7 Wall St roundup)</li>
<li>Mistral $400m ARR Jan 2026 / €1bn FY26 target (Sacra, MLQ, Idlen)</li>
<li>Cohere $150m ARR mid-2026 (AI Funding Tracker)</li>
<li>xAI / Grok 2026e revenue estimates (Sacra, SQ Magazine, Business of Apps)</li>
<li>SemiAnalysis on Anthropic $44bn / “$96m ARR per day” (MindStudio, OfficeChai)</li>
<li>IDC 2026 AI spending $2.02trn / $487bn infra / $230bn infra-software (Market Clarity, IDC blog)</li>
<li>McKinsey AI economic potential update ($2.6-4.4trn; $4.4trn corporate profit framing)</li>
<li>Oracle FY26 OCI $18bn guide / Q3 FY26 results (Futurum, Oracle IR)</li>
<li>Counterpoint / TrendForce custom-ASIC market-share forecasts (60% Broadcom / 25% Marvell by 2027)</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>