<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Leitch">
<meta name="dcterms.date" content="2026-05-13">

<title>Data centre backup diesel gensets: technical specs and unit economics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="backup_gensets_economics_files/libs/clipboard/clipboard.min.js"></script>
<script src="backup_gensets_economics_files/libs/quarto-html/quarto.js"></script>
<script src="backup_gensets_economics_files/libs/quarto-html/popper.min.js"></script>
<script src="backup_gensets_economics_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="backup_gensets_economics_files/libs/quarto-html/anchor.min.js"></script>
<link href="backup_gensets_economics_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="backup_gensets_economics_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="backup_gensets_economics_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="backup_gensets_economics_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="backup_gensets_economics_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<meta name="quarto:status" content="draft">


</head>

<body class="fullcontent"><div id="quarto-draft-alert" class="alert alert-warning"><i class="bi bi-pencil-square"></i>Draft</div>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Data centre backup diesel gensets: technical specs and unit economics</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>David Leitch </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 13, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="why-this-matters" class="level1">
<h1>Why this matters</h1>
<p>The diesel set behind a hyperscale data centre is, for most of its life, an unloved capital asset that runs 50–100 hours a year. But the kit is unusually concentrated, expensive and increasingly capacity-constrained. Caterpillar, Cummins and Rolls-Royce Power Systems (mtu) lead the global market; lead times for 2.5–3 MW class standby sets have stretched to 18–24 months [1]; and the installed fleet of standby capacity attached to data centres globally rose from around 20 GW in 2018 to 55 GW in 2024 [2]. Virginia alone permits more than 27 GW of diesel capacity behind data centres [2].</p>
<p>This note builds up the engineering and the unit economics from the OEM datasheet, through the 96-hour fuel inventory required for ANSI/TIA-942 Rated-4 and NFPA 110 Level 1 design intent, up to the total backup-power capex for a 100 MW IT-load hyperscale build, and then prices the annual operating cost.</p>
<p>The headline result for the 100 MW worked example: the diesel backup system — sets, switchgear, paralleling controls, fuel storage, polishing and ATSs — runs to roughly US$1.0–1.5 million per MW of IT load installed, or US$100–150 million for the facility. That sits inside an overall hyperscale build cost of US$10–13 million per MW IT (US$20m+ per MW for liquid-cooled AI training) [3, 4]. Backup-power kit is therefore 8–12% of total air-cooled hyperscale capex, and a smaller share of an AI build, but it is the longest-lead and most regulated component on the site.</p>
</section>
<section id="the-reference-machines" class="level1">
<h1>1. The reference machines</h1>
<p>Two anchors. The Caterpillar 3516E HD is the workhorse of US hyperscale builds in the 2.5–2.75 MW class. The mtu 20V4000 sits at 2.8–3.25 MW and is the European and APAC reference. Cummins QSK60 is the third option, particularly in markets where Cummins dealer coverage is strong (parts of APAC, the Middle East and Latin America). All three are V-configuration heavy-duty diesels at 1500 rpm (50 Hz) or 1800 rpm (60 Hz).</p>
<p><strong>Table 1 — Reference standby gensets, 2.5–3 MW class</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 35%">
<col style="width: 25%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: right;">Caterpillar 3516E (60 Hz)</th>
<th style="text-align: right;">mtu 20V4000 DS3000</th>
<th style="text-align: right;">Cummins QSK60-G23</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Standby rating (ekW)</td>
<td style="text-align: right;">2,750</td>
<td style="text-align: right;">3,000</td>
<td style="text-align: right;">2,500</td>
</tr>
<tr class="even">
<td style="text-align: left;">Standby rating (kVA)</td>
<td style="text-align: right;">3,438</td>
<td style="text-align: right;">3,750</td>
<td style="text-align: right;">3,125</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Prime / continuous (ekW)</td>
<td style="text-align: right;">2,500</td>
<td style="text-align: right;">2,500</td>
<td style="text-align: right;">2,250</td>
</tr>
<tr class="even">
<td style="text-align: left;">Engine configuration</td>
<td style="text-align: right;">V16, 4-stroke</td>
<td style="text-align: right;">V20, 4-stroke</td>
<td style="text-align: right;">V16, 4-stroke</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bore × stroke (mm)</td>
<td style="text-align: right;">170 × 215</td>
<td style="text-align: right;">170 × 210</td>
<td style="text-align: right;">159 × 190</td>
</tr>
<tr class="even">
<td style="text-align: left;">Displacement (L)</td>
<td style="text-align: right;">78.1</td>
<td style="text-align: right;">95.4</td>
<td style="text-align: right;">60.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Compression ratio</td>
<td style="text-align: right;">14.7:1</td>
<td style="text-align: right;">15.5:1</td>
<td style="text-align: right;">14.5:1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Engine speed (rpm)</td>
<td style="text-align: right;">1,800</td>
<td style="text-align: right;">1,800</td>
<td style="text-align: right;">1,800</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Specific power (kW/L disp.)</td>
<td style="text-align: right;">35.2</td>
<td style="text-align: right;">31.4</td>
<td style="text-align: right;">41.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dry weight, set + radiator (t)</td>
<td style="text-align: right;">~19.8</td>
<td style="text-align: right;">~21.5</td>
<td style="text-align: right;">~23.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Footprint L×W×H (m)</td>
<td style="text-align: right;">7.5 × 2.2 × 3.4</td>
<td style="text-align: right;">7.7 × 2.3 × 3.6</td>
<td style="text-align: right;">8.0 × 2.3 × 3.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">EPA standby tier</td>
<td style="text-align: right;">Tier 2 (stationary emergency)</td>
<td style="text-align: right;">Tier 2</td>
<td style="text-align: right;">Tier 2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aftertreatment (Tier 2 standby)</td>
<td style="text-align: right;">None standard</td>
<td style="text-align: right;">None standard</td>
<td style="text-align: right;">None standard</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tier 4 Final option</td>
<td style="text-align: right;">Yes, w/ SCR + DPF + DEF</td>
<td style="text-align: right;">Yes, w/ SCR + DPF + DEF</td>
<td style="text-align: right;">Yes, w/ SCR + DPF + DEF</td>
</tr>
</tbody>
</table>
<p><em>Source: Caterpillar 3516E (60 Hz) datasheet LEHE1351-09 [5]; mtu Onsite Energy 20V4000 DS3000 G04 spec [6]; Cummins QSK60-G23 standby spec sheet, 2250–2500 kVA, Rev-03, May 2023 [7]. Cummins V16 has the highest specific power but the smallest displacement; the mtu V20 has the largest swept volume but lowest BMEP, reflecting an emphasis on overhaul interval over peak rating.</em></p>
<p>The key point: standby-rated emergency gensets in the United States operate under a regulatory exemption that lets them stay at EPA Tier 2 emissions, avoiding the cost and complexity of SCR + DPF + AdBlue/DEF aftertreatment that Tier 4 Final demands [8]. Most hyperscale builds today specify Tier 2 standby gensets where local air permits allow; Virginia data, however, suggests that more than half of newly permitted capacity is now being installed at Tier 4 standards because of local non-attainment area limits and to preserve the option of running the kit in grid services or peak shaving [2, 9]. The Tier 4 adder runs to roughly US$100–200/kW, plus DEF storage and a substantial increase in footprint and weight.</p>
<section id="fuel-consumption-the-caterpillar-3516e-datasheet" class="level2">
<h2 class="anchored" data-anchor-id="fuel-consumption-the-caterpillar-3516e-datasheet">Fuel consumption — the Caterpillar 3516E datasheet</h2>
<p>This is the load-curve number that matters most for sizing fuel storage and for operating-cost calculations. Caterpillar publishes the following for the 3516E at 2,750 ekW standby (60 Hz, low-fuel-consumption rating, with engine-mounted fan) [5]:</p>
<p><strong>Table 2 — Caterpillar 3516E HD fuel consumption (2,750 ekW standby, 60 Hz)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 22%">
<col style="width: 25%">
<col style="width: 44%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Load</th>
<th style="text-align: right;">Fuel rate (L/hr)</th>
<th style="text-align: right;">Fuel rate (US gph)</th>
<th style="text-align: right;">Specific fuel consumption (g/kWh)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">25% (687 kW)</td>
<td style="text-align: right;">184.4</td>
<td style="text-align: right;">48.7</td>
<td style="text-align: right;">225</td>
</tr>
<tr class="even">
<td style="text-align: left;">50% (1,375 kW)</td>
<td style="text-align: right;">309.0</td>
<td style="text-align: right;">81.6</td>
<td style="text-align: right;">188</td>
</tr>
<tr class="odd">
<td style="text-align: left;">75% (2,063 kW)</td>
<td style="text-align: right;">431.8</td>
<td style="text-align: right;">114.1</td>
<td style="text-align: right;">175</td>
</tr>
<tr class="even">
<td style="text-align: left;">100% (2,750 kW)</td>
<td style="text-align: right;">563.8</td>
<td style="text-align: right;">148.9</td>
<td style="text-align: right;">172</td>
</tr>
</tbody>
</table>
<p><em>Source: Caterpillar 3516E specification sheet LEHE1351-09 [5]. Note: the 3,000 ekW variant lifts 100% consumption to 645.8 L/hr (170.6 gph). Values are at sea level, 25 °C, ISO 3046 reference.</em></p>
<p>The picture sharpens around 0.20 L/kWh at full load and slightly above 0.22 L/kWh at 25% — diesel becomes thermodynamically less efficient at low load, and this is the practical reason for the wet-stacking problem. The Cummins QSK60 at full standby load consumes around 535 L/hr (141 gph) for 2,500 ekW [7]; the mtu 20V4000 DS3000 sits at around 690–720 L/hr at 3,000 ekW from manufacturer data [6]. All three converge to roughly 200–215 g/kWh at full load — better-than-utility-scale diesel reciprocating performance but materially worse than CCGT.</p>
<p>For sizing purposes, the <strong>rule of thumb of 0.22 L/kWh standby at full load is conservative and safe</strong> across the three OEMs. For a 3 MW unit, that is 660 L/hr at full standby load — and that is the number I will use to size the 100 MW facility’s fuel inventory below.</p>
</section>
</section>
<section id="fuel-system-for-96-hour-autonomy" class="level1">
<h1>2. Fuel system for 96-hour autonomy</h1>
<section id="the-96-hour-requirement" class="level2">
<h2 class="anchored" data-anchor-id="the-96-hour-requirement">The 96-hour requirement</h2>
<p>ANSI/TIA-942-C, the data-centre infrastructure standard, sets descending fault-tolerance criteria from Rated-1 to Rated-4. Rated-4 (fault-tolerant) implicitly requires that the site survive any single failure including loss of utility power for an extended period. The standard is paywalled, but design-practice commentary consistently aligns Rated-4 with <strong>96 hours of on-site fuel</strong> at full critical load [10, 11].</p>
<p>NFPA 110, the US emergency power supply standard, expresses the same idea differently: Level 1 systems where loss of power could cause death or serious injury must be designed for 96 hours of operation, though the standard allows an authority having jurisdiction to accept a documented fuel-supply contract instead of full on-site inventory [12]. In practice, hyperscale operators don’t rely on contracts during a 96-hour outage — they build the tanks.</p>
<p>By contrast, the Uptime Institute’s Tier Standard sets only a 12-hour on-site fuel storage minimum for all Tiers including Tier IV [13]. The 96-hour number is therefore a TIA-942/NFPA design choice rather than a Tier number; most US and Australian hyperscale specifications use 72 or 96 hours.</p>
</section>
<section id="tank-sizing-for-a-3-mw-set" class="level2">
<h2 class="anchored" data-anchor-id="tank-sizing-for-a-3-mw-set">Tank sizing for a 3 MW set</h2>
<p>At 660 L/hr (full standby load with margin), one 3 MW class set running for 96 hours needs:</p>
<p>660 L/hr × 96 hr = <strong>63,360 L of usable fuel per genset</strong>.</p>
<p>NFPA 110 requires the main fuel tank to carry 133% of the calculated requirement to allow for unusable volume, expansion ullage and pump cut-out [12]. Applied here:</p>
<p>63,360 × 1.33 = <strong>~84,300 L (22,300 US gal) of nameplate tank capacity per 3 MW set</strong>.</p>
<p>Most builds settle this in a two-tier architecture:</p>
<ul>
<li>A <strong>belly tank or skid sub-base tank</strong> on each genset providing 4–12 hours of run-time autonomy. Cat 3516E factory sub-base tanks are typically 7,000–12,000 L. mtu integrated tanks are typically 4,000 L at the standard package.</li>
<li>A <strong>bulk tank farm</strong> sized for the remaining hours, feeding <strong>day tanks</strong> at each genset via duplex transfer pumps. Day tanks accept the engine-driven return-fuel loop and provide a thermally buffered local supply.</li>
</ul>
</section>
<section id="fuel-polishing-the-silent-reliability-risk" class="level2">
<h2 class="anchored" data-anchor-id="fuel-polishing-the-silent-reliability-risk">Fuel polishing — the silent reliability risk</h2>
<p>Diesel fuel begins to degrade within 28 days of delivery. Standby fuel that sits for months accumulates water (condensation, atmospheric moisture), microbial growth at the fuel/water interface, asphaltene precipitation as the fuel oxidises, and particulate sediment. The ASTM D975 specification covers grade-2 diesel quality at delivery but does not address stored-fuel ageing; that is left to ASTM D6217 (particulate), D2709 (water and sediment), D6469 (microbial) and similar [14].</p>
<p>Best-practice data-centre fuel-quality programs run [14, 15, 16]:</p>
<ul>
<li><strong>Monthly</strong> visual inspections and basic water-detection on day tanks.</li>
<li><strong>Quarterly</strong> microbial monitoring and water-bottom sampling on bulk tanks.</li>
<li><strong>Annual</strong> full ASTM D975 specification testing on each tank.</li>
<li><strong>Continuous or scheduled fuel polishing</strong> — pump fuel through filter/water-separator/coalescer skids — typically rotating the bulk inventory every 4–8 weeks. A 1–2 m³/hr polishing skid handles a 100,000 L tank in 2–4 days; permanent skids cost US$15,000–40,000 each; mobile services cost roughly US$0.05–0.15 per litre per pass [16].</li>
</ul>
<p>Annual testing and polishing service contracts run US$875–1,475 per tank in the US per Bell Performance benchmarks [15]; a hyperscale site with 30–50 bulk and day tanks therefore spends US$30,000–75,000 a year on testing alone, plus polishing skid capex and consumables. Across a hyperscale fleet the total fuel-quality program can run into six figures annually [16].</p>
</section>
<section id="australian-dangerous-goods-thresholds" class="level2">
<h2 class="anchored" data-anchor-id="australian-dangerous-goods-thresholds">Australian dangerous-goods thresholds</h2>
<p>AS 1940:2017 — <em>The storage and handling of flammable and combustible liquids</em> — is the technical standard that state and territory dangerous-goods regulations adopt by reference. Diesel is <strong>Class C1 combustible liquid</strong> (flash point &gt;60 °C and ≤93 °C, or relabelled under recent GHS revisions). The key Australian thresholds [17, 18, 19]:</p>
<p><strong>Table 3 — Australian regulatory thresholds for above-ground diesel storage</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 63%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Threshold</th>
<th style="text-align: right;">Quantity (diesel, C1 combustible)</th>
<th style="text-align: left;">Trigger</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">AS 1940 “minor storage” upper limit</td>
<td style="text-align: right;">10,000 L (in any one location)</td>
<td style="text-align: left;">Above this, full AS 1940 fire-protection, bunding, separation distance rules apply</td>
</tr>
<tr class="even">
<td style="text-align: left;">High-level alarm required</td>
<td style="text-align: right;">25,000 L (above-ground combustible tank)</td>
<td style="text-align: left;">AS 1940:2017 update</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Placard quantity (dangerous-goods placarding)</td>
<td style="text-align: right;">~10,000 L for C1 combustible; varies by jurisdiction</td>
<td style="text-align: left;">Notify dangerous-goods regulator; placards on tanks</td>
</tr>
<tr class="even">
<td style="text-align: left;">Manifest quantity (full notification)</td>
<td style="text-align: right;">100,000 L (C1 combustible, model WHS)</td>
<td style="text-align: left;">Manifest filed with state regulator and fire brigade</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Major hazard facility threshold</td>
<td style="text-align: right;">Schedule 15 quantity tests; for C1 combustibles, generally 5,000 t (~6,000,000 L)</td>
<td style="text-align: left;">Triggers MHF licensing under model WHS regulations</td>
</tr>
</tbody>
</table>
<p><em>Source: AS 1940:2017 [17]; Bulk Fuel Australia 2019 Guide [18]; Safe Work Australia Schedule 15 to model WHS regulations [19]; Viva Energy AS 1940 compliance guide [20].</em></p>
<p>For a hyperscale site with 4–8 million litres of diesel on hand, the placard and manifest quantities are crossed comfortably but the major hazard facility threshold for diesel alone is not. The MHF designation typically only triggers if the site also stores significant LPG, hydrogen or other Schedule 15 chemicals, or if multiple data centres on a single site aggregate above ~6 million litres. Hyperscale operators are therefore well inside heavy dangerous-goods regulatory territory but generally below MHF — they need licensed dangerous-goods premises, full bunding to AS 1940, fire-water capacity sized to NFPA 30, hot-work permits, and full firefighter pre-incident plans, but not the full safety-case regime of an oil terminal.</p>
</section>
<section id="tank-cost-benchmarks-australia" class="level2">
<h2 class="anchored" data-anchor-id="tank-cost-benchmarks-australia">Tank cost benchmarks (Australia)</h2>
<p>Self-bunded above-ground steel tanks dominate the Australian data-centre fuel-storage market. Pricing from suppliers like Fes Tanks, Fuelfix and Durotank, plus several private quotes for hyperscale projects, give the following indicative ranges:</p>
<ul>
<li>30,000 L self-bunded tank: AU$35,000–55,000 (~AU$1.20–1.80 per litre)</li>
<li>68,000 L tank: AU$70,000–95,000 (~AU$1.10–1.40 per litre)</li>
<li>110,000 L tank: AU$110,000–140,000 (~AU$1.00–1.30 per litre)</li>
</ul>
<p>Civils, foundations, bunding upgrades, fire protection, level instrumentation, transfer pumps, day tank skids, polishing skids and 2.4 km equivalent of fuel-oil pipework typically multiply the bare-tank cost by 2.5–3.5×. <strong>All-in installed bulk fuel storage</strong> for hyperscale builds therefore lands at roughly AU$3–5 per litre of capacity (US$2–3.5/L) [21]. For a 100 MW facility that is approximately US$10–17 million on fuel storage alone before fuel inventory itself.</p>
</section>
<section id="refuelling-logistics" class="level2">
<h2 class="anchored" data-anchor-id="refuelling-logistics">Refuelling logistics</h2>
<p>Australian fuel road tankers are typically B-double 50,000–60,000 L payload. Delivering 4 million litres into a hyperscale tank farm during a sustained outage therefore requires roughly 70–80 tanker movements. The standing rate at which a fleet of 5–8 dedicated tankers can resupply a site is around 200,000–400,000 L per day per dedicated route — meaning a fully drained 96-hour inventory takes 10–20 days to refill at a single site. In practice, hyperscale fuel-supply contracts specify a minimum response time (typically 6 hours to first delivery, with priority access during emergencies) and a dedicated routing pool [22]. The Houston flood in 2017 and the Texas grid event in 2021 both saw data centres burn through 24–48 hours of fuel before resupply caught up — leaving the 72–96 hour inventory as the relevant design margin.</p>
</section>
</section>
<section id="backup-power-system-for-a-100-mw-rated-4-facility" class="level1">
<h1>3. Backup power system for a 100 MW Rated-4 facility</h1>
<section id="load-to-back-up" class="level2">
<h2 class="anchored" data-anchor-id="load-to-back-up">Load to back up</h2>
<p>A modern air-cooled hyperscale facility carries an IT load with PUE around 1.3–1.4. For a 100 MW IT design:</p>
<ul>
<li>IT load: 100 MW</li>
<li>Cooling, lighting, controls, transformers: 30–40 MW</li>
<li><strong>Total backed-up load: ~130 MW</strong></li>
</ul>
<p>Liquid-cooled AI training builds achieve PUE 1.1–1.2 and back up roughly 110–120 MW for the same IT load; below I take the 130 MW number as the binding case.</p>
</section>
<section id="generator-count-and-architecture" class="level2">
<h2 class="anchored" data-anchor-id="generator-count-and-architecture">Generator count and architecture</h2>
<p>2N is the binding redundancy choice for Rated-4. Two completely independent A-side and B-side gen-busses, each fully capable of carrying 130 MW. The standard architecture uses standby-rated 2.5–3 MW sets paralleled on a common medium-voltage bus per side.</p>
<p>Taking 2.75 MW per genset (Cat 3516E mission-critical rating) [5]:</p>
<ul>
<li>N per side: 130 / 2.75 = 48 sets (rounding up)</li>
<li>With N+1 redundancy on each side: 49 sets per side</li>
<li><strong>Total facility genset count: 98 sets</strong>, total nameplate 270 MW</li>
<li>Many designs simplify to 50 sets per side at 2.75 MW = 100 sets, 275 MW nameplate</li>
</ul>
<p>Alternative architectures use larger 4 MW class sets (Caterpillar C175-20 or mtu 20V4000 DS4000) to reduce set count, switchgear complexity and footprint. A 4 MW per set 2N+1 design lands at roughly 34 sets per side (68 sets total, 272 MW nameplate). Hyperscale operators have moved toward larger 3–4 MW sets in the past five years for exactly this reason.</p>
</section>
<section id="switchgear-and-paralleling" class="level2">
<h2 class="anchored" data-anchor-id="switchgear-and-paralleling">Switchgear and paralleling</h2>
<p>Each side of a 2N system needs medium-voltage paralleling switchgear capable of synchronising 30–50 sets to a common bus, plus generator breakers, bus-tie breakers, ATSs, distribution switchgear and protective relays. Indicative pricing from contractor quotes and industry benchmarks [1, 23]:</p>
<ul>
<li>Generator breakers and metering per set: US$60,000–120,000</li>
<li>Medium-voltage paralleling switchgear (per side, 50–60 MW bus): US$3–8 million</li>
<li>Automatic transfer switches (one per critical load block, typically 16–32 ATSs per side): US$3–8 million total</li>
<li>Paralleling control system (PLC, EMCP, synchroniser, load-share controls): US$1.5–3 million</li>
</ul>
<p>A complete 100 MW IT facility therefore lands at roughly <strong>US$25–45 million on switchgear and controls alone</strong>.</p>
</section>
<section id="fuel-inventory" class="level2">
<h2 class="anchored" data-anchor-id="fuel-inventory">Fuel inventory</h2>
<p>At 660 L/hr per 3 MW set running at full load, all 50 paralleled sets on one side at full load burn:</p>
<p>50 × 660 L/hr = 33,000 L/hr → 33 m³/hr → <strong>3,168 m³ over 96 hours = ~3.17 million litres per side</strong>.</p>
<p>A 2N design must store enough fuel for the binding scenario. The common interpretation is to size for one side at full load for 96 hours (because if the utility fails, one side is enough to carry the IT load — the other is parallel insurance). Some operators are more conservative and size each side independently for 96 hours.</p>
<p><strong>Practical specification: 4 million litres of total bulk fuel storage</strong>, distributed across 30–50 tanks ranging 50,000–150,000 L each, with day tanks at each genset (typically 2,500–5,000 L) totalling another 200,000 L of distributed inventory. A handful of operators specify 6 million litres for genuine 2N × 96-hour redundancy.</p>
</section>
<section id="capex-build-up-100-mw-it-rated-4-air-cooled" class="level2">
<h2 class="anchored" data-anchor-id="capex-build-up-100-mw-it-rated-4-air-cooled">Capex build-up — 100 MW IT, Rated-4, air-cooled</h2>
<p><strong>Table 4 — Backup power system capex, 100 MW IT facility (Rated-4, 2N)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 16%">
<col style="width: 29%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Component</th>
<th style="text-align: right;">Quantity</th>
<th style="text-align: right;">Unit cost (US$)</th>
<th style="text-align: right;">Total (US$ million)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Gensets (2.75 MW, Tier 2, sound enclosure, sub-base tank)</td>
<td style="text-align: right;">100</td>
<td style="text-align: right;">1.0–1.4 m each</td>
<td style="text-align: right;">100–140</td>
</tr>
<tr class="even">
<td style="text-align: left;">Medium-voltage switchgear, paralleling</td>
<td style="text-align: right;">2 sides</td>
<td style="text-align: right;">5–8 m per side</td>
<td style="text-align: right;">10–16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Automatic transfer switches and distribution</td>
<td style="text-align: right;">~40 ATSs</td>
<td style="text-align: right;">150–250 k each</td>
<td style="text-align: right;">6–10</td>
</tr>
<tr class="even">
<td style="text-align: left;">Paralleling controls, EMCP, synchronisers</td>
<td style="text-align: right;">facility</td>
<td style="text-align: right;">2–4 m</td>
<td style="text-align: right;">2–4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bulk fuel tanks (4 ML capacity, self-bunded steel)</td>
<td style="text-align: right;">30–40 tanks</td>
<td style="text-align: right;">2.5–3.5 $/L installed</td>
<td style="text-align: right;">10–14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Day tanks, transfer pumps, fuel polishing</td>
<td style="text-align: right;">facility</td>
<td style="text-align: right;">2–4 m</td>
<td style="text-align: right;">2–4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fuel-oil piping, valves, leak detection</td>
<td style="text-align: right;">facility</td>
<td style="text-align: right;">2–4 m</td>
<td style="text-align: right;">2–4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Civils, foundations, enclosures, exhaust stacks</td>
<td style="text-align: right;">facility</td>
<td style="text-align: right;">8–14 m</td>
<td style="text-align: right;">8–14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Engineering, commissioning, witness testing</td>
<td style="text-align: right;">facility</td>
<td style="text-align: right;">5–10% of above</td>
<td style="text-align: right;">7–14</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total backup power system</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>147–220</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Per MW IT (US$M/MW)</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>1.5–2.2</strong></td>
</tr>
</tbody>
</table>
<p><em>Source: Author build-up using OEM list prices [1, 5, 6, 7], Cushman &amp; Wakefield Data Center Development Cost Guide 2025 commentary [3], Generator Source benchmarks [23] and Australian self-bunded tank pricing [21].</em></p>
<p>The Cushman &amp; Wakefield 2025 guide notes that generator capital costs alone rose 45% from Q3 2021 to mid-2024, and that data-centre electrical equipment costs across all categories (transformers +44%, UPS +48%, switchgear +31%) have all moved in lockstep [3]. The build-up above reflects 2025 pricing; pre-Covid pricing for the same system would have been roughly 30–35% lower in nominal terms.</p>
<p><strong>The gensets themselves are 65–70% of the backup-power system cost.</strong> Switchgear and paralleling are 10–15%. Fuel storage and distribution is 12–15%. Civils, engineering and commissioning soak up the balance.</p>
</section>
</section>
<section id="operating-costs" class="level1">
<h1>4. Operating costs</h1>
<section id="routine-maintenance" class="level2">
<h2 class="anchored" data-anchor-id="routine-maintenance">Routine maintenance</h2>
<p>Standby gensets at hyperscale data centres run a heavily proceduralised maintenance cycle [24, 25]:</p>
<ul>
<li><strong>Monthly:</strong> No-load black-start test, visual inspection, battery and charger check, day-tank water draining, control-system function check.</li>
<li><strong>Quarterly:</strong> Load-bank test at minimum 30% load for 30 minutes (NFPA 110 wet-stacking prevention), oil and fuel sample analysis, fuel polishing if needed.</li>
<li><strong>Annual:</strong> Stepped 2-hour load-bank test (30% → 50% → 75% for 30/30/60 minutes), oil and filter change, coolant test/change, air filter change, complete control-system inspection, fuel polishing all bulk tanks.</li>
<li><strong>Top-end overhaul at 12,000–18,000 hours</strong> (often never reached on a true standby genset that runs &lt;100 hr/yr — would take 120+ years), or by calendar at 10–15 years for valve adjustment and injector replacement.</li>
<li><strong>Major overhaul at 36,000–60,000 hours</strong> — almost never reached on pure standby duty.</li>
</ul>
</section>
<section id="annual-cost-per-mw" class="level2">
<h2 class="anchored" data-anchor-id="annual-cost-per-mw">Annual cost per MW</h2>
<p>Building it up [24, 25, 26, 16]:</p>
<p><strong>Table 5 — Annual operating cost per MW IT, backup power system (100 MW Rated-4 facility)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 45%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Cost item</th>
<th style="text-align: right;">US$/year (100 MW IT)</th>
<th style="text-align: right;">US$/MW IT/yr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Routine maintenance (monthly + quarterly + annual PMs, parts)</td>
<td style="text-align: right;">1,200,000</td>
<td style="text-align: right;">12,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Annual stepped load-bank testing (rented load banks, labour)</td>
<td style="text-align: right;">250,000</td>
<td style="text-align: right;">2,500</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diesel consumed in load-bank tests (estimate 50 hr × 660 L/hr × 100 sets × AU$1.50/L)</td>
<td style="text-align: right;">500,000</td>
<td style="text-align: right;">5,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Fuel polishing and quality testing</td>
<td style="text-align: right;">200,000</td>
<td style="text-align: right;">2,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fuel inventory turnover (every 18–24 months, ~AU$0.30/L loss to mixing, blending, replacement)</td>
<td style="text-align: right;">600,000</td>
<td style="text-align: right;">6,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lube oil, coolant, filters</td>
<td style="text-align: right;">200,000</td>
<td style="text-align: right;">2,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Major service contract (OEM, 24/7 response)</td>
<td style="text-align: right;">1,500,000</td>
<td style="text-align: right;">15,000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Insurance, dangerous-goods compliance, spill response</td>
<td style="text-align: right;">400,000</td>
<td style="text-align: right;">4,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Operator labour allocation (DC ops team prorata)</td>
<td style="text-align: right;">800,000</td>
<td style="text-align: right;">8,000</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total annual opex, backup power</strong></td>
<td style="text-align: right;"><strong>5,650,000</strong></td>
<td style="text-align: right;"><strong>56,500</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">As % of installed capex</td>
<td style="text-align: right;">~3.4%</td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p><em>Source: Author build-up. Routine maintenance benchmarks from Cummins data-centre genset specification guide [24] and Caterpillar service literature [25]. Fuel polishing pricing from Bell Performance [15] and Mojo Fuel [16]. Diesel pricing per Australian Institute of Petroleum terminal-gate data [27].</em></p>
<p>Two observations. First, <strong>the working-capital cost of holding 4 million litres of diesel</strong> is itself material. At AU$1.80/L wholesale (close to the May 2026 terminal-gate price [27]), the fuel inventory alone represents AU$7.2 million of working capital, or roughly AU$430,000/year at a 6% pre-tax cost of funds — not large, but real. Second, <strong>fuel inventory turnover is a substantive cost</strong>: standby fuel cannot sit for ever. Operators rotate inventory every 18–24 months, either by burning it in extended load-bank tests, blending into commercial diesel supply, or paying for tanker removal and replacement. Each tank-flush event costs around AU$0.20–0.40/L of capacity.</p>
<p>Diesel consumed during the quarterly load-bank tests is the largest single fuel cost. A typical site burns approximately 50 hours × 660 L/hr × 50 sets per year on testing = 1.65 million litres, costing AU$2.5–3 million in fuel alone at 2026 prices.</p>
</section>
</section>
<section id="backup-power-as-a-fraction-of-total-hyperscale-capex" class="level1">
<h1>5. Backup power as a fraction of total hyperscale capex</h1>
<section id="total-hyperscale-capex-per-mw-it" class="level2">
<h2 class="anchored" data-anchor-id="total-hyperscale-capex-per-mw-it">Total hyperscale capex per MW IT</h2>
<p>Multiple independent benchmarks converge on US$10–13 million per MW IT for a current-generation air-cooled hyperscale build [3, 4, 28, 29]:</p>
<ul>
<li>JLL Global Data Center Outlook 2026: US$11.3 million per MW projected average, up from US$10.7m in 2025 and US$7.7m in 2020 [4]</li>
<li>Turner &amp; Townsend Data Centre Construction Cost Index 2025: Tokyo US$15.2/W, Singapore US$14.5/W, Zurich US$14.2/W, Dublin/Madrid US$10.0/W [29]</li>
<li>Cushman &amp; Wakefield 2025 Cost Guide: US Tier-1 markets US$10–13M/MW IT for air-cooled hyperscale [3]</li>
<li>AI/liquid-cooled builds: US$20–25M/MW IT for facility only; US$30–40M/MW including GPU fit-out [4, 28]</li>
</ul>
<p><strong>Anchor: US$11M/MW IT for an air-cooled hyperscale build; US$22M/MW IT for AI-optimised.</strong></p>
</section>
<section id="capex-breakdown" class="level2">
<h2 class="anchored" data-anchor-id="capex-breakdown">Capex breakdown</h2>
<p>Drawing on the Cushman &amp; Wakefield 2025 guide, JLL 2026 and Alpha Matica deconstruction [3, 4, 28, 30]:</p>
<p><strong>Table 6 — Capex breakdown, 100 MW IT hyperscale (US$11M/MW IT baseline)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 26%">
<col style="width: 35%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Category</th>
<th style="text-align: right;">Share of total</th>
<th style="text-align: right;">US$M for 100 MW IT</th>
<th style="text-align: right;">US$M/MW IT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Building shell and core</td>
<td style="text-align: right;">10–15%</td>
<td style="text-align: right;">110–165</td>
<td style="text-align: right;">1.1–1.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Land and site works</td>
<td style="text-align: right;">4–7%</td>
<td style="text-align: right;">44–77</td>
<td style="text-align: right;">0.4–0.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mechanical / cooling</td>
<td style="text-align: right;">15–20%</td>
<td style="text-align: right;">165–220</td>
<td style="text-align: right;">1.6–2.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Electrical distribution, transformers, MV gear</td>
<td style="text-align: right;">15–20%</td>
<td style="text-align: right;">165–220</td>
<td style="text-align: right;">1.6–2.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UPS systems (with batteries)</td>
<td style="text-align: right;">8–12%</td>
<td style="text-align: right;">88–132</td>
<td style="text-align: right;">0.9–1.3</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Backup power (generators + switchgear + fuel)</strong></td>
<td style="text-align: right;"><strong>8–12%</strong></td>
<td style="text-align: right;"><strong>88–132</strong></td>
<td style="text-align: right;"><strong>0.9–1.3</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fire suppression, security, BMS</td>
<td style="text-align: right;">2–4%</td>
<td style="text-align: right;">22–44</td>
<td style="text-align: right;">0.2–0.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Interior fit-out, white space</td>
<td style="text-align: right;">10–15%</td>
<td style="text-align: right;">110–165</td>
<td style="text-align: right;">1.1–1.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Engineering, commissioning, contingency</td>
<td style="text-align: right;">8–12%</td>
<td style="text-align: right;">88–132</td>
<td style="text-align: right;">0.9–1.3</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Total</strong></td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">1,100</td>
<td style="text-align: right;">11.0</td>
</tr>
</tbody>
</table>
<p><em>Source: Cushman &amp; Wakefield Data Center Development Cost Guide 2025 [3]; JLL 2026 Global Data Center Outlook [4]; Alpha Matica deconstruction [28]; author build-up for backup-power line item from Table 4.</em></p>
<p>The backup-power slice — 8–12% of facility capex, roughly US$1.0–1.3 million per MW IT — is the third or fourth largest line item, behind shell, cooling and primary electrical distribution. It is roughly the same size as the UPS-and-battery system. Both are typically built and operated by the same electrical contractor pool, and both have suffered similar 40–50% price rises since 2021 because of identical demand-side pressure on switchgear, transformer and large-format battery supply chains [3].</p>
<p>For an AI-optimised liquid-cooled build at US$22M/MW IT, the backup-power slice is smaller proportionally (4–6%) because cooling and primary electrical kit scale faster. But the absolute size — US$1.0–1.5M/MW — is roughly the same, because what is backed up is roughly the same number of joules.</p>
</section>
<section id="how-the-backup-power-slice-compares" class="level2">
<h2 class="anchored" data-anchor-id="how-the-backup-power-slice-compares">How the backup-power slice compares</h2>
<p>To anchor: a 100 MW IT facility’s backup-power system, at US$1.0–1.5M/MW IT installed, is in the same range as:</p>
<ul>
<li>A modern combined-cycle gas turbine plant (US$1.0–1.5M/MW installed), although a GT delivers continuous power and the genset delivers standby insurance.</li>
<li>The site’s primary HV transformer and switchyard (typically US$0.8–1.2M/MW for a 132/33 kV connection).</li>
<li>The cost of three large lithium-iron-phosphate utility batteries that could in principle replace 5–10 minutes of UPS function but not 96 hours.</li>
</ul>
<p>The reason hyperscalers continue to pay this premium is straightforward: diesel is the only practical technology that delivers 96 hours of guaranteed energy storage at the densities — 35–40 MJ/kg — that a 130 MW load demands. A lithium battery alternative for the same energy stored (130 MW × 96 hr = 12,480 MWh) would cost roughly US$3.5–5 billion at current battery prices, before any consideration of cycling life, footprint or fire risk. The diesel set is, in this narrow sense, irreplaceable.</p>
</section>
</section>
<section id="implications-for-entry" class="level1">
<h1>6. Implications for entry</h1>
<p>For an analyst evaluating the diesel-backup-services market the relevant takeaways:</p>
<ol type="1">
<li><p><strong>The kit market is concentrated.</strong> Caterpillar, mtu (Rolls-Royce Power Systems) and Cummins together hold roughly 80% of the &gt;1 MW data-centre standby market globally. Generac is pushing aggressively into the 2.25–3.25 MW range [1] and Kohler/Rehlko are credible challengers. Entry as an OEM is implausible.</p></li>
<li><p><strong>The integration and service market is fragmented.</strong> A single hyperscale build with 100 sets needs dozens of skids, hundreds of valves, kilometres of fuel-oil pipework, paralleling switchgear, ATSs and a 30–50 tank fuel farm. Generator-package integrators, fuel-system specialists, switchgear builders, polishing-service operators and tank fabricators all compete for fragmented slices. This is where service revenue and capital-light entry sit.</p></li>
<li><p><strong>The opex line is small but sticky.</strong> US$50,000–75,000 per MW IT per year, across a 55 GW global standby fleet, is a US$3–4 billion service-and-fuel market — and growing at 15–20% as the installed base catches up with the build pipeline. Australian hyperscale opex spends are 10–15% above US benchmarks because of higher labour rates and dangerous-goods compliance loads.</p></li>
<li><p><strong>Lead times are the binding constraint.</strong> 18–24 months for a new 3 MW set from order to delivery [1] means that secondhand and refurbished diesel sets are now trading above replacement cost in some markets. Hyperscale buyers will lock in 3–5 year framework supply agreements with Caterpillar and Cummins; the spot market is for the merchant DC operator.</p></li>
<li><p><strong>Tier 4 transition is the regulatory tail risk.</strong> Today, the standby exemption keeps emergency gensets at Tier 2 [8]. Two threats to this: tightening of state-level non-attainment area air permits (already happening in California, Virginia, Texas) and re-classification if the genset participates in demand-response or peak-shaving markets [9]. A Tier-4 retrofit costs roughly US$200/kW and adds DEF storage, weight and footprint.</p></li>
<li><p><strong>The 96-hour fuel inventory is not optional and not cheap.</strong> A 100 MW facility holds roughly 4 million litres of diesel — about the same physical inventory as a regional fuel terminal. The dangerous-goods, fire-protection and refuelling-logistics envelope around that inventory is a meaningful operational discipline and a credible barrier to entry for second-tier operators.</p></li>
</ol>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>[1] <a href="https://www.kairuipower.com/blog/generator-price-trends-implications-for-data-center-and-power-plant-planning">Kairui Power, “Generator Price Trends 2025–2030: Plan Smarter for Data Centers”</a>, 2025.</p>
<p>[2] <a href="https://www.latitudemedia.com/news/the-data-center-boom-is-a-diesel-generator-boom/">Latitude Media, “The data center boom is a diesel generator boom”</a>, 2025.</p>
<p>[3] <a href="https://www.cushmanwakefield.com/en/united-states/insights/data-center-development-cost-guide">Cushman &amp; Wakefield, US Data Center Development Cost Guide 2025</a>.</p>
<p>[4] <a href="https://www.jll.com/en-us/insights/market-outlook/data-center-outlook">JLL, 2026 Global Data Center Outlook</a>.</p>
<p>[5] <a href="https://www.cat.com/en_US/products/new/power-systems/electric-power/diesel-generator-sets/1000033111.html">Caterpillar 3516E (60 Hz) 2500–2750 kW Diesel Generator product page</a>, specification sheet LEHE1351-09 referenced via Western States Cat and Cleveland Brothers dealer pages.</p>
<p>[6] <a href="https://www.mtu-solutions.com/content/dam/mtu/products/power-generation/powergeneration-product-list-latest/231219_PG_Spec_20V4000DS3000G04_3000kW_3D_FC_60Hz_45C.pdf">mtu Onsite Energy 20V4000 DS3000 60 Hz spec sheet</a>; supplementary <a href="https://www.curtispowersolutions.com/specs-mtu-4000-gensets">Curtis Power Solutions 60 Hz MTU 4000 series listings</a>.</p>
<p>[7] <a href="https://www.cummins.com/sites/default/files/2023-05/2250-2500kVA-QSK60_Rev-03.pdf">Cummins QSK60 Series 2250–2500 kVA Standby spec sheet, Rev-03, May 2023</a>.</p>
<p>[8] <a href="https://generatorsource.com/fuel/diesel/the-facility-managers-guide-to-epa-tier-4-final-vs-tier-2-3-standby/">Generator Source, “The Facility Manager’s Guide to EPA Tier 4 Final vs.&nbsp;Tier 2/3 Standby”</a>.</p>
<p>[9] <a href="https://powergenenterprises.com/tier-4-generator-requirements-compliance-guide-2026">Power Generation Enterprises, “Tier 4 Generator Requirements: Compliance Guide 2026”</a>.</p>
<p>[10] <a href="https://tiaonline.org/products-and-services/tia942certification/ansi-tia-942-standard/">TIA Online, “ANSI/TIA-942 Standard”</a>.</p>
<p>[11] <a href="https://www.score-grp.com/en/post/data-center-standards-iso-ansi-tia-942-and-tiers-in-2026-how-to-design-classify-and-operate-re">Score Group, “Data Center Standards (ISO, ANSI/TIA-942 and Tiers) in 2026”</a>.</p>
<p>[12] <a href="https://ckpower.com/wp-content/uploads/2018/04/NFPA-110-Final.pdf">CK Power, “No-Nonsense Guide to NFPA 110 Compliance for Emergency Power Systems”</a>; also <a href="https://www.curtispowersolutions.com/nfpa-110-emergency-power-supply-eps">Curtis Power Solutions “NFPA 110 Emergency Power Supply”</a>.</p>
<p>[13] <a href="https://journal.uptimeinstitute.com/fuel-system-design-reliability/">Uptime Institute Journal, “Fuel system design and reliability”</a>.</p>
<p>[14] <a href="https://fuelcareusa.com/critical-facilities-power-resilience/astm-d975-diesel-fuel-testing-guide/">FuelCare USA, “ASTM D975 Diesel Fuel Testing Guide”</a>.</p>
<p>[15] <a href="https://www.bellperformance.com/bell-performs-blog/data-center-generator-fuel-quality-the-complete-guide-to-preventing-backup-power-failures">Bell Performance, “Data Center Generator Fuel Quality: Complete Guide”</a>.</p>
<p>[16] <a href="https://mojo-fuel.com/commercial-and-industrial">Mojo Fuel Optimization, Commercial &amp; Industrial Fuel Polishing service pricing</a>; <a href="https://precisionfiltration.com/blog/how-fuel-polishing-prevents-data-center-downtime/">Precision Filtration “How Fuel Polishing Prevents Data Center Downtime”</a>.</p>
<p>[17] <a href="https://www.festanks.com.au/blog/as1940-2017-storage-handling-flammable-combustible-liquids/">Fes Tanks summary of AS 1940:2017 changes</a>.</p>
<p>[18] <a href="https://bulkfuel.com.au/index.php?id=106%3Aa-guide-to-flammable-and-combustible-liquids-part-one">Bulk Fuel Australia, “A guide to flammable and combustible liquids (2019 Edition)”</a>.</p>
<p>[19] <a href="https://classic.austlii.edu.au/au//legis/cth/consol_reg/whasr2011327/sch15.html">Safe Work Australia, model WHS Regulations Schedule 15 — Hazardous chemicals at major hazard facilities</a>; <a href="https://www.safeworkaustralia.gov.au/system/files/documents/1702/notification_and_determination.pdf">Safe Work Australia, Major Hazard Facilities Notification and Determination Guide, 2012</a>.</p>
<p>[20] <a href="https://www.vivaenergy.com.au/blog/innovation/complying-with-as1940-the-safe-storage-and-handling-of-fuel">Viva Energy, “Complying with AS1940 — the safe storage and handling of fuel”</a>.</p>
<p>[21] <a href="https://www.festanks.com.au/grande-tanks/68000l-aboveground-fuel-tank/">Fes Tanks</a>, <a href="https://www.fuelfix.com.au/product/30000l-self-bunded-fuel-tank/">Fuelfix</a>, <a href="https://durotank.com.au/product-category/self-bunded-fuel-tanks/">Durotank</a>, <a href="https://www.fuelequipmentspecialists.com.au/p/110-000-litre-self-bunded-tank">Fuel Equipment Specialists</a> — Australian self-bunded tank pricing 2024–2026.</p>
<p>[22] <a href="https://www.earthsafe.com/the-new-logistics-of-data-center-fuel-supply">Earthsafe, “The New Logistics of Data Center Fuel Supply”</a>; <a href="https://mansfield.energy/2025/01/30/powering-data-centers-the-ultimate-guide-to-a-fail-safe-fueling-program/">Mansfield Energy, “Powering Data Centers: The Ultimate Guide to a Fail-Safe Fueling Program”</a>.</p>
<p>[23] <a href="https://generatorsource.com/backup-power/backup-power-for-data-centers/">Generator Source, “Backup Power for Data Centers”</a>; <a href="https://constructandcommission.com/data-center-redundancy-n-n1-n2-2n-2n1-2n1-explained/">Constructandcommission “Data Center Redundancy: N, N+1, N+2, 2N &amp; 2N+1 Explained”</a>.</p>
<p>[24] <a href="https://www.cummins.com/sites/default/files/2023-04/Specifying%20Standby%20Generator%20Set%20Requirements%20for%20Data%20Centers%202022-08-10.pdf">Cummins, “Specifying Standby Generator Set Requirements for Data Centers”</a>.</p>
<p>[25] <a href="https://csdieselgenerators.com/guide-to-data-center-generator-maintenance/">Central States Diesel Generators, “Guide to Data Center Generator Maintenance”</a>; <a href="https://csdieselgenerators.com/nfpa-110-generator-maintenance-requirements-simplified-for-2025/">Central States Diesel Generators, “NFPA 110 Generator Maintenance Requirements Simplified for 2025”</a>.</p>
<p>[26] <a href="https://avtronpower.com/resources/articles/how-can-load-bank-testing-your-genset-reduce-the-cost-of-ownership/">Avtron Power Solutions, “How can load bank testing your genset reduce the cost of ownership?”</a>.</p>
<p>[27] <a href="https://www.aip.com.au/pricing/terminal-gate-prices">Australian Institute of Petroleum, Terminal Gate Prices</a>; <a href="https://www.accc.gov.au/system/files/weekly-fuel-price-monitoring-report-2-april-2026.pdf">ACCC Weekly fuel price monitoring update 2 April 2026</a>.</p>
<p>[28] <a href="https://www.alpha-matica.com/post/deconstructing-the-data-center-a-look-at-the-cost-structure-1">Alpha Matica, “Deconstructing the Data Center: A Look at the Cost Structure Igniting the AI Boom”</a>.</p>
<p>[29] <a href="https://www.turnerandtownsend.com/insights/data-centre-construction-cost-index-2025-2026/">Turner &amp; Townsend, Data Centre Construction Cost Index 2025-2026</a>; <a href="https://reports.turnerandtownsend.com/data-centre-construction-cost-index-2025/">report site 2025</a>.</p>
<p>[30] <a href="https://iot-analytics.com/data-center-infrastructure-market/">IoT Analytics, “Data Center infrastructure market: AI-driven CapEx pushing IT and facility equipment spending toward $1 trillion by 2030”</a>.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>