<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>community_local</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="community_local_files/libs/clipboard/clipboard.min.js"></script>
<script src="community_local_files/libs/quarto-html/quarto.js"></script>
<script src="community_local_files/libs/quarto-html/popper.min.js"></script>
<script src="community_local_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="community_local_files/libs/quarto-html/anchor.min.js"></script>
<link href="community_local_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="community_local_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="community_local_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="community_local_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="community_local_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="local-community-opposition-to-us-data-centres-research-draft" class="level1">
<h1>Local Community Opposition to US Data Centres: Research Draft</h1>
<p><strong>Author:</strong> Research draft for ITK <strong>Date:</strong> May 2026 <strong>Scope:</strong> Site-specific local opposition to US data centre projects, 2024-2026</p>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This draft surveys the wave of locally-organised opposition to US data centre development that has accelerated through 2024, 2025 and into 2026. The focus is deliberately narrow: zoning fights, nuisance complaints, environmental-justice litigation and county-level ordinances. It does <em>not</em> cover statewide rate-impact disputes (which are an electricity-customer issue better handled in a separate political-dimensions draft), nor opposition to AI as a technology in the abstract. Local opposition to a specific data centre site is overwhelmingly about quality-of-life impacts - noise, air, water, traffic, viewshed, lost farmland, fiscal trade-offs - rather than about the underlying compute.</p>
<p>The scale is now material to investment timing. Data Center Watch, an industry-aligned monitoring service operated by 10a Labs, has tallied roughly USD 64 billion in projects “blocked or delayed” by local opposition in the two years to March 2025, with at least 142 organised activist groups active across 24 states; its 2025 update raised the running tally to roughly USD 156 billion across 48 cancelled or delayed projects [Source: https://www.datacenterwatch.org/report; https://thehill.com/policy/technology/5605667-data-center-criticism-study/]. The Hill describes the opposition as bipartisan: Republican-leaning concerns about tax incentives and grid strain sit alongside Democratic concerns about environmental impact and water [Source: https://thehill.com/policy/technology/5605667-data-center-criticism-study/].</p>
<p>Data Center Watch is itself an industry-funded source and its definitions (what counts as “blocked” versus “delayed”) are not externally audited; the figures should be treated as an order-of-magnitude indicator rather than as a formal accounting.</p>
</section>
<section id="summary-table-of-major-case-studies" class="level2">
<h2 class="anchored" data-anchor-id="summary-table-of-major-case-studies">Summary table of major case studies</h2>
<p><strong>Major US data centre community-opposition cases, 2024-2026</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Project</th>
<th style="text-align: left;">Location</th>
<th style="text-align: left;">Lead developer / tenant</th>
<th style="text-align: left;">Primary issues</th>
<th style="text-align: left;">Outcome to date</th>
<th style="text-align: left;">Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">PW Digital Gateway</td>
<td style="text-align: left;">Prince William Co., VA</td>
<td style="text-align: left;">QTS (Blackstone), Compass</td>
<td style="text-align: left;">Heritage (Manassas Battlefield buffer), rural character, noise, scale</td>
<td style="text-align: left;">Rezoning voided by Circuit Court Aug 2025; upheld by VA Court of Appeals 31 Mar 2026; Compass dropped appeal; QTS appeal to VA Supreme Court filed 30 Apr 2026; county withdrew from defence 15 Apr 2026</td>
<td style="text-align: left;"><a href="https://wtop.com/virginia/2026/04/prince-william-co-withdraws-from-digital-gateway-lawsuit-reversing-course-from-2023/">WTOP</a>; <a href="https://www.bisnow.com/national/news/data-center-development/developer-backs-out-of-17-gw-virginia-data-center-plan-134341">Bisnow</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Compass “True North” / Goose Creek</td>
<td style="text-align: left;">Loudoun Co., VA</td>
<td style="text-align: left;">Compass Datacenters</td>
<td style="text-align: left;">Residential-area siting, noise, traffic</td>
<td style="text-align: left;">Approved Dec 2023 over 380 emails of opposition; project advancing</td>
<td style="text-align: left;"><a href="https://www.bisnow.com/washington-dc/news/data-center/loudoun-approves-controversial-data-center-after-initial-opposition-84151">Bisnow</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stargate (Related Digital / Oracle / OpenAI)</td>
<td style="text-align: left;">Saline Township, MI</td>
<td style="text-align: left;">Related Digital, Oracle, OpenAI</td>
<td style="text-align: left;">Farmland loss, scale (1.4 GW), water, noise</td>
<td style="text-align: left;">Township rezoning denied 4-1 March 2025; developer sued under Michigan exclusionary-zoning doctrine; township settled within weeks; construction proceeded; ~USD 14 m community-benefits package; MI PSC approved DTE contract Dec 2025</td>
<td style="text-align: left;"><a href="https://fortune.com/2026/05/06/ai-data-center-michigan-saline-politics-farmland/">Fortune</a>; <a href="https://www.michiganpublic.org/environment-climate-change/2025-12-18/michigan-regulators-approve-saline-twp-data-center-request-with-conditions">Michigan Public</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">xAI Colossus 1 &amp; 2</td>
<td style="text-align: left;">Memphis, TN / Southaven, MS</td>
<td style="text-align: left;">xAI / MZX Tech</td>
<td style="text-align: left;">Air pollution from 35+ unpermitted gas turbines; environmental justice (Boxtown, predominantly Black)</td>
<td style="text-align: left;">NAACP / SELC / Earthjustice 60-day notice Feb 2026; lawsuit filed; preliminary-injunction motion 2026</td>
<td style="text-align: left;"><a href="https://earthjustice.org/case/xai-illegal-gas-power-plant-data-center-colossus">Earthjustice</a>; <a href="https://www.selc.org/news/xai-built-an-illegal-power-plant-to-power-its-data-center/">SELC</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Project Blue (originally AWS)</td>
<td style="text-align: left;">Tucson / Pima Co., AZ</td>
<td style="text-align: left;">Beale Infrastructure (originally Amazon)</td>
<td style="text-align: left;">Water (~2,000 acre-feet/yr proposed), energy, drought</td>
<td style="text-align: left;">Tucson City Council rejected 7-0, Aug 2025; Pima County subsequently approved on county land with closed-loop cooling; Amazon withdrew Dec 2025; AZ Corporation Commission approved power deal Dec 2025</td>
<td style="text-align: left;"><a href="https://www.democracynow.org/2025/8/7/headlines/tucson_city_council_votes_unanimously_to_reject_project_blue_a_proposed_data_center_linked_to_amazon">DemocracyNow</a>; <a href="https://www.kjzz.org/the-show/2025-12-09/rejected-by-tucson-and-abandoned-by-amazon-project-blue-data-center-moves-forward">KJZZ</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Chandler proposal</td>
<td style="text-align: left;">Chandler, AZ</td>
<td style="text-align: left;">Confidential applicant (USD 2.5 bn)</td>
<td style="text-align: left;">Water (initial request &gt;100 m gal/yr), noise, energy</td>
<td style="text-align: left;">Chandler City Council rejected 7-0, Dec 2025</td>
<td style="text-align: left;"><a href="https://www.fox10phoenix.com/news/chandler-data-center-proposal-draws-heavy-opposition-council-meeting">Fox 10 Phoenix</a>; <a href="https://www.phoenixnewtimes.com/news/how-much-water-will-chandlers-data-center-project-use-40627750/">Phoenix New Times</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tract West Valley</td>
<td style="text-align: left;">Buckeye / Goodyear, AZ</td>
<td style="text-align: left;">Tract</td>
<td style="text-align: left;">Building heights, noise, water, infrastructure strain</td>
<td style="text-align: left;">Original USD 14 bn Buckeye-airport rezoning withdrawn May 2024; revised proposal proceeded with broader engagement; Hassayampa Ranch USD 25 bn approved Dec 2024-2025 with wildlife-corridor mitigation</td>
<td style="text-align: left;"><a href="https://www.abc15.com/news/business/14-billion-west-valley-data-center-project-request-withdrawn-after-cities-push-back">ABC15</a>; <a href="https://berryriddell.com/25b-data-center-planned-west-of-phoenix-wins-key-approval-from-county/">Berry Riddell</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Meta El Paso 1 GW campus</td>
<td style="text-align: left;">El Paso, TX</td>
<td style="text-align: left;">Meta / El Paso Electric / Enchanted Rock</td>
<td style="text-align: left;">Air emissions from 813 modular gas units (~366 MW); water; tax breaks</td>
<td style="text-align: left;">El Paso City Council voted unanimously Jan 2026 to intervene at Texas PUC; Sembrando Esperanza Coalition active</td>
<td style="text-align: left;"><a href="https://www.texastribune.org/2026/01/26/texas-el-paso-meta-data-center-natural-gas-power-plant/">Texas Tribune</a>; <a href="https://elpasomatters.org/2026/01/18/el-paso-electric-meta-data-center-new-473-million-natural-gas-power-plant/">El Paso Matters</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Microsoft Palmetto / Douglasville</td>
<td style="text-align: left;">South Fulton / Coweta Co., GA</td>
<td style="text-align: left;">Microsoft</td>
<td style="text-align: left;">Rural-fringe character, water, noise, scale</td>
<td style="text-align: left;">Approved 2024; ground broken July 2024; mayor of Palmetto publicly opposed; opposition organising continues</td>
<td style="text-align: left;"><a href="https://www.wsbtv.com/news/local/atlanta/palmetto-residents-concerned-over-data-center-construction-neighboring-coweta-county/AKZ6W5ZB3JAOFEY7DOLVX7FUGY/">WSB-TV</a>; <a href="https://www.ajc.com/news/business/microsoft-continues-aggressive-metro-atlanta-land-grab-for-data-center-development/2OCAF752OFEUDNJTOJPVWLRDGI/">AJC</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">DeKalb County moratorium</td>
<td style="text-align: left;">DeKalb Co., GA (metro Atlanta)</td>
<td style="text-align: left;">n/a</td>
<td style="text-align: left;">Health, costs, density</td>
<td style="text-align: left;">Moratorium on new applications and expansions extended to 23 June 2026</td>
<td style="text-align: left;"><a href="https://www.cbsnews.com/atlanta/news/dekalb-leaders-extend-data-center-moratorium-to-june-as-residents-raise-health-cost-concerns/">CBS Atlanta</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Stack / Caroline County</td>
<td style="text-align: left;">Caroline Co., VA</td>
<td style="text-align: left;">SAC III (Stack Infrastructure)</td>
<td style="text-align: left;">Power, water, rural character</td>
<td style="text-align: left;">SPEX-08-2025 application active; ordinance amended Dec 2024 to require special exception under PIRT standards</td>
<td style="text-align: left;"><a href="https://co.caroline.va.us/AgendaCenter/ViewFile/Item/7389?fileID=11579">Caroline Co.&nbsp;Planning</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Microsoft / Mount Pleasant</td>
<td style="text-align: left;">Mount Pleasant, WI (Foxconn site)</td>
<td style="text-align: left;">Microsoft</td>
<td style="text-align: left;">Energy demand (~3.9 GW combined with Port Washington)</td>
<td style="text-align: left;">Local support (Foxconn-fatigue dynamic); 15 additional buildings approved Jan 2026; adjacent Caledonia rezoning withdrawn Sept 2025 after opposition</td>
<td style="text-align: left;"><a href="https://www.cnbc.com/2026/01/26/microsoft-wins-approval-for-15-data-centers-at-wisconsin-foxconn-site.html">CNBC</a>; <a href="https://www.theregister.com/2025/11/25/microsoft_caledonia/">The Register</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vantage “Lighthouse” Stargate</td>
<td style="text-align: left;">Port Washington, WI</td>
<td style="text-align: left;">Vantage / Oracle / OpenAI</td>
<td style="text-align: left;">Construction nuisance, energy costs, transparency</td>
<td style="text-align: left;">670-acre campus broke ground 17 Dec 2025; mayoral recall petition Feb 2026 fell ~hundreds of signatures short of 1,600; first US referendum requiring city-vote on large TIF districts passed</td>
<td style="text-align: left;"><a href="https://www.wpr.org/news/port-washington-data-center-campus-openai-oracle-stargate-chatgpt">WPR</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Meta Beaver Dam</td>
<td style="text-align: left;">Beaver Dam, WI</td>
<td style="text-align: left;">Meta (via Alliant)</td>
<td style="text-align: left;">Wells running dry near construction; rate impact</td>
<td style="text-align: left;">Alliant ICR rate filing modified by PSC May 2026 to require data centre to bear full cost; well-failure complaints documented</td>
<td style="text-align: left;"><a href="https://www.wpr.org/news/state-regulators-change-we-energies-data-center-rate-proposal-to-protect-customers">WPR</a>; <a href="https://pbswisconsin.org/news-item/wisconsin-communities-face-scrutiny-over-data-center-secrecy-beyond-use-of-ndas/">PBS Wisconsin</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Newark / U Delaware (“Battle of Data Center Hill” reprise)</td>
<td style="text-align: left;">Newark, DE</td>
<td style="text-align: left;">The Data Centers LLC (2014 vintage); New Castle Co.&nbsp;proposals 2025</td>
<td style="text-align: left;">Cogen power, energy demand, residential proximity</td>
<td style="text-align: left;">Original UDel project killed June 2024; New Castle Co.&nbsp;ordinance Sept 2025 requires 1,000 ft setback from residential, BESS, noise/water/traffic standards</td>
<td style="text-align: left;"><a href="https://www.datacenterknowledge.com/regulations/university-of-delaware-puts-nail-in-coffin-of-data-center-and-power-plant-project">Data Center Knowledge</a>; <a href="https://spotlightdelaware.org/2025/12/16/two-new-castle-county-industrial-projects-may-become-data-centers/">Spotlight Delaware</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Project Delta</td>
<td style="text-align: left;">Stokes Co., NC</td>
<td style="text-align: left;">Engineered Land Solutions</td>
<td style="text-align: left;">Dan River corridor, rural character, scale (1,800 ac)</td>
<td style="text-align: left;">County rezoning approved 12 Jan 2026 voided March 2026 over defective public notice; community lawsuit pending</td>
<td style="text-align: left;"><a href="https://ncnewsline.com/2026/03/13/community-groups-sue-over-planned-data-center-in-stokes-county/">NC Newsline</a>; <a href="https://www.selc.org/news/a-rural-community-steps-up-to-stop-data-centers/">SELC</a></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Microsoft LaPorte</td>
<td style="text-align: left;">LaPorte Co., IN</td>
<td style="text-align: left;">Microsoft</td>
<td style="text-align: left;">Farmland (~1,000 ac annexation), rural character</td>
<td style="text-align: left;">County advanced restrictions late 2025; LaPorte city annexed ~1,000 acres April 2026</td>
<td style="text-align: left;"><a href="https://indianaeconomicdigest.net/Content/Most-Recent/Agriculture/Article/LaPorte-County-backs-limits-on-data-centers-amid-farmland-concerns/31/68/120326">Indiana Economic Digest</a>; <a href="https://www.wndu.com/2026/04/14/city-laporte-votes-annex-roughly-1000-acres-farmland-near-microsoft-data-center-project/">WNDU</a></td>
</tr>
</tbody>
</table>
<p><em>Source: Compiled from sources cited inline; outcomes current to early May 2026.</em></p>
</section>
<section id="recurring-local-issues-with-quantified-examples" class="level2">
<h2 class="anchored" data-anchor-id="recurring-local-issues-with-quantified-examples">Recurring local issues, with quantified examples</h2>
<section id="noise" class="level3">
<h3 class="anchored" data-anchor-id="noise">Noise</h3>
<p>The constant low-frequency hum from chillers, cooling fans and (intermittently) backup generators is the most-cited grievance in densely-developed clusters. The Loudoun County zoning ordinance caps industrial noise at 55 dB at residential property lines; one CloudHQ measurement reached 90 dB at the boundary, and Vantage attracted at least a dozen complaints in 2024 [Source: https://www.wusa9.com/article/news/local/data/loudoun-county-officials-data-center-noise/65-45884219-750f-4d47-a660-71a20d8db001]. In Prince William County residents have complained that levels routinely exceed 60 dB; a NASA acoustician told Bristow-area residents the new builds would be audible inside their homes [Source: https://bristowbeat.com/stories/nasa-scientist-brings-attention-to-data-center-noise-levels,11231]. Supervisor Mike Turner (Loudoun) has publicly questioned whether the dB(A)-only standard captures the “tonal narrow band hum” and low-frequency vibration that residents find most distressing [Source: https://www.wusa9.com/article/news/local/data/loudoun-county-officials-data-center-noise/65-45884219-750f-4d47-a660-71a20d8db001].</p>
<p>The regulatory response has been to tighten setbacks rather than tighten dB limits: Calvert County (MD) requires 400 ft from residential buildings; Linn County (Iowa) imposes 1,000 ft from residentially-zoned property and explicit noise/light caps; LaGrange/Troup (GA) requires 1,500 ft from “sensitive receptors” (homes, schools, daycares, hospitals, parks); New Castle County (DE) requires 1,000 ft from residential for facilities over 20,000 sqft [Source: https://www.lagrangenews.com/news/commissioners-approve-data-center-ordinance-lift-moratorium-2b6e15ed; https://insideclimatenews.org/news/01032026/iowa-county-data-center-ordinance/; https://www.calvertcountymd.gov/3880/Data-Centers; https://spotlightdelaware.org/2025/12/16/two-new-castle-county-industrial-projects-may-become-data-centers/].</p>
</section>
<section id="water" class="level3">
<h3 class="anchored" data-anchor-id="water">Water</h3>
<p>Water has emerged as the single most-cited concern in arid-state and drought-stressed locations. Of 25 data-centre projects cancelled in 2025 owing to local opposition, water use was raised in over 40% of cases [Source: https://commercialobserver.com/2026/02/opposition-data-centers-real-estate-reasons/].</p>
<p>In Tucson, Project Blue would have used roughly 2,000 acre-feet of city water per year, which would have made it the city’s single largest water customer; the council rejected it 7-0 in August 2025 [Source: https://azluminaria.org/2025/08/06/tucson-city-council-rejects-project-blue-amid-intense-community-pressure/]. In Chandler, the rejected USD 2.5 bn project would have drawn up to 48,000 gallons per day per the city’s water resources manager - what Chandler officials called “an absolute maximum” - while the developer’s own filings suggested over 100 million gallons per year [Source: https://www.phoenixnewtimes.com/news/how-much-water-will-chandlers-data-center-project-use-40627750/]. The countervailing data point: in Mesa, where Apple and Meta both operate, industrial water use was about 6% of total potable use in 2024, and Mesa, Avondale and Phoenix all now cap industrial use and require developers to source supplemental supplies above the cap [Source: https://grist.org/technology/arizona-water-data-centers-semiconducters/].</p>
<p>In Beaver Dam, Wisconsin, families near the Meta site have reported wells running dry [Source: https://pbswisconsin.org/news-item/wisconsin-communities-face-scrutiny-over-data-center-secrecy-beyond-use-of-ndas/]. This is a hydrogeological complaint adjacent to the construction-water issue and has not yet been adjudicated by an independent investigation.</p>
</section>
<section id="air-emissions" class="level3">
<h3 class="anchored" data-anchor-id="air-emissions">Air emissions</h3>
<p>The xAI Colossus campus in Memphis is the headline air-emissions case. Aerial imagery and satellite analysis by University of Tennessee researchers documented at least 35 gas turbines on site (xAI’s previously-disclosed count was lower); peak NO2 concentrations rose 79% in immediate-vicinity areas and 9% in adjacent Boxtown [Source: https://capitalbnews.org/musk-xai-memphis-black-neighborhood-pollution/; https://us.boell.org/en/2026/01/28/promise-peace-plenty-how-south-memphis-refusing-ais-big-lies]. xAI subsequently moved 27 turbines across the state line to Southaven, Mississippi - which according to SELC has the potential to make the site the largest single industrial NOx source in the 11-county Memphis metropolitan area [Source: https://earthjustice.org/case/xai-illegal-gas-power-plant-data-center-colossus]. The American Lung Association has graded both Shelby County (TN) and DeSoto County (MS) “F” for ozone [Source: https://earthjustice.org/case/xai-illegal-gas-power-plant-data-center-colossus]. Earthjustice and SELC are both advocacy organisations and their characterisations of the public-health risk should be read accordingly; the underlying turbine count, permit status (none) and emissions inventory are independently documentable from regulatory filings and aerial imagery.</p>
<p>In El Paso, the Meta 1 GW campus would be powered by an 813-unit Enchanted Rock modular-generator stack totalling 366 MW. The PUC application discloses annual emissions of approximately 117 metric tonnes of NOx, 2,700 t of CO and 42 t of particulates [Source: https://www.texastribune.org/2026/01/26/texas-el-paso-meta-data-center-natural-gas-power-plant/]. The El Paso City Council voted unanimously in January 2026 to intervene at the PUC against the project, an unusual move for a Texas city given how rarely municipalities formally intervene in PUC proceedings.</p>
<p>In Loudoun County alone, approximately 4,700 diesel backup generators are now permitted with about 12 GW of nameplate capacity - notionally equivalent to 12 large gas plants or 12 nuclear units, although these run only as backup or for limited testing [Source: https://www.pecva.org/work/energy-work/proposed-increase-to-data-center-diesel-generator-use/]. The Northern Virginia airshed is already in ozone non-attainment. Virginia DEQ in late 2025 began consulting on relaxing the 500-hour annual cap on emergency-engine running, narrowed in early 2026 to a Loudoun-only variance; Piedmont Environmental Council and others have opposed the relaxation [Source: https://virginiamercury.com/2025/12/16/virginia-regulators-weigh-expanded-use-of-data-centers-polluting-generators/].</p>
</section>
<section id="visual-viewshed-heritage" class="level3">
<h3 class="anchored" data-anchor-id="visual-viewshed-heritage">Visual / viewshed / heritage</h3>
<p>The Manassas National Battlefield case is the clearest viewshed-and-heritage flashpoint. The Pageland Lane parcels that QTS and Compass sought to develop sit immediately west of the battlefield boundary, on land long zoned agricultural specifically to provide a buffer; the Park Service superintendent publicly described the proposal as risking “wholesale destruction” of associated historic context [Source: https://www.princewilliamtimes.com/news/park-superintendent-warns-of-data-centers-wholesale-destruction-of-historic-areas-around-the-manassas-battlefield/article_278caca0-37c3-11ee-9f99-abdeeaa89493.html]. Battlefield maps show troop movements east of Pageland Lane; the application area also includes Camp Hardee, where hundreds of Confederate soldiers died in an 1861 measles outbreak and are presumed buried [Source: https://www.battlefields.org/speak-out/digital-gateway-threatens-overwhelm-manassas-battlefield]. The American Battlefield Trust (an advocacy organisation) and the Piedmont Environmental Council have been lead organisers; the Court of Appeals decision turning on procedural notice rather than substantive heritage protection limits the precedent value to other heritage-adjacent sites.</p>
<p>In western Loudoun, the Compass “True North”/Goose Creek proposal drew 380 emails of opposition before the December 2023 vote, primarily about siting a 750,000 sqft industrial use approximately five miles from the main data-centre cluster in a residentially-characterised area [Source: https://www.bisnow.com/washington-dc/news/data-center/loudoun-approves-controversial-data-center-after-initial-opposition-84151]. The broader Bull Run Mountain area opposition is part of the same Western Loudoun resistance documented in Bloomberg’s July 2025 reporting [Source: https://www.bloomberg.com/news/features/2025-07-29/loudon-county-data-center-growth-strains-residents-seeking-ai-regulation].</p>
</section>
<section id="farmland-and-rural-character-loss" class="level3">
<h3 class="anchored" data-anchor-id="farmland-and-rural-character-loss">Farmland and rural character loss</h3>
<p>Saline Township is now the case-study reference point. The township board voted 4-1 in March 2025 to deny rezoning for the Stargate (Related Digital / Oracle / OpenAI) project. Two days later the developer sued under Michigan’s exclusionary-zoning doctrine, arguing that because Saline Township had no industrially-zoned land at all, a “necessary” use could not be excluded altogether. The township settled within weeks; construction began; the Michigan PSC approved the DTE supply contract in December 2025 with conditions; and Fortune’s May 2026 reporting confirms the facility is operational on a path to 1.4 GW [Source: https://fortune.com/2026/05/06/ai-data-center-michigan-saline-politics-farmland/; https://www.michiganpublic.org/environment-climate-change/2025-12-18/michigan-regulators-approve-saline-twp-data-center-request-with-conditions]. Residents secured roughly USD 14 m in community benefits including fire-department funding, farmland preservation and environmental restrictions [Source: https://fortune.com/2026/05/06/ai-data-center-michigan-saline-politics-farmland/]. The case is striking precisely because it shows local opposition can be procedurally overruled where state-law exclusionary-zoning doctrine applies and where the township’s own zoning omissions become the developer’s lever.</p>
<p>In LaPorte County (Indiana), Microsoft is building six initial data-centre buildings on roughly 500 acres with plans for 11 more (17 total); the city of LaPorte annexed ~1,000 acres of additional farmland in April 2026 to facilitate expansion. The county has moved to restrict where data centres can be sited [Source: https://www.wndu.com/2026/04/14/city-laporte-votes-annex-roughly-1000-acres-farmland-near-microsoft-data-center-project/; https://indianaeconomicdigest.net/Content/Most-Recent/Agriculture/Article/LaPorte-County-backs-limits-on-data-centers-amid-farmland-concerns/31/68/120326]. Across Indiana, the majority of the 40+ tracked projects are sited on agricultural land [Source: https://www.latitudemedia.com/news/in-indiana-an-anatomy-of-data-center-opposition/].</p>
<p>In central Wisconsin, opposition organising is now coordinated through cross-community networks. Menomonie defeated a project and now distributes a “toolkit” to other towns [Source: https://reasonstobecheerful.world/menomonie-wisconsin-data-center-toolkit/]. The state’s unique tax instrument (computer-exempt personal property combined with TIF treatment) has been identified by the Wisconsin Examiner as a structural reason data centres concentrate in rural Wisconsin [Source: https://wisconsinexaminer.com/2026/01/22/rural-wisconsin-has-become-a-hotspot-for-data-centers-states-unique-tax-instrument-explains-why/].</p>
</section>
<section id="traffic-and-construction-nuisance" class="level3">
<h3 class="anchored" data-anchor-id="traffic-and-construction-nuisance">Traffic and construction nuisance</h3>
<p>Construction-period nuisance is rarely the lead grievance but tips opinion when sustained. Port Washington residents have publicly complained about around-the-clock construction at the Vantage “Lighthouse” site [Source: https://www.wpr.org/news/port-washington-data-center-campus-openai-oracle-stargate-chatgpt]. Construction-traffic concerns also appear in the Stokes County Project Delta filings and in Caroline County (VA) hearings [Source: https://www.northcarolinahealthnews.org/2026/03/25/nc-communities-push-back-ai-data-centers-project-delta-lawsuit/].</p>
</section>
<section id="fiscal-trade-offs-jobs-versus-exemptions" class="level3">
<h3 class="anchored" data-anchor-id="fiscal-trade-offs-jobs-versus-exemptions">Fiscal trade-offs: jobs versus exemptions</h3>
<p>The job-density argument is now well-documented. JLARC estimates Virginia’s data-centre sector supports 74,000 jobs across the economy, mostly in construction; the operational footprint per facility is much smaller [Source: https://jlarc.virginia.gov/pdfs/presentations/JLARC%20Virginia%20Data%20Center%20Study_FINAL_12-09-2024.pdf]. Industry analyses cite 1-2 permanent staff per MW for the most automated hyperscale campuses (250-2,000 per GW), with specific examples ranging from ~100 estimated permanent positions at the 1 GW Abilene Stargate site to ~1,000 at a 1 GW Wisconsin Stargate site [Source: https://www.latitudemedia.com/news/data-center-jobs-arent-at-servers-theyre-in-energy/; https://www.hjnews.com/tremonton/news/what-is-a-hyperscale-data-center-and-what-does-it-mean-for-utah/article_e37b5c4a-f108-42d3-91c2-1747f2b68d2d.html]. The order-of-magnitude takeaway commonly invoked by opponents - “tens to low hundreds of jobs per gigawatt” - is consistent with the hyperscale end of these ranges.</p>
<p>The opportunity cost of the sales-tax exemption is now substantial:</p>
<ul>
<li><strong>Virginia</strong>: USD 80.6 bn of investment claimed and USD 3.2 bn of sales-tax exemption claimed in FY24-25; FY25 added 1,610 reported jobs against USD 1.9 bn of foregone tax [Source: https://www.vpm.org/generalassembly/2026-03-12/budget-data-center-tax-break-scott-lucas-spanberger-torian-rephann].</li>
<li><strong>Texas</strong>: Comptroller projects roughly USD 1.8 bn annual cost by FY30, up from prior estimates near USD 1.3 bn [Source: https://www.texastribune.org/2026/04/08/texas-data-centers-sales-tax-break-billion-dollars/].</li>
<li><strong>Georgia</strong>: Projected USD 2.5 bn FY26 cost - 664% higher than the previous official estimate of USD 327 m [Source: https://csgsouth.org/policies/take-that-for-data-incentivizing-innovation-or-inefficiency/].</li>
</ul>
<p>A University of Georgia audit found roughly 70% of Georgia’s data-centre construction would have occurred without the exemption, implying the marginal incentive value is well below the headline foregone revenue [Source: https://csgsouth.org/policies/take-that-for-data-incentivizing-innovation-or-inefficiency/]. Virginia’s Rephann (cited in VPM coverage) estimates the exemption is the marginal driver in roughly 50% of cases and that share has been declining [Source: https://www.vpm.org/generalassembly/2026-03-12/budget-data-center-tax-break-scott-lucas-spanberger-torian-rephann].</p>
</section>
<section id="backup-diesel-storage-and-refuelling" class="level3">
<h3 class="anchored" data-anchor-id="backup-diesel-storage-and-refuelling">Backup diesel storage and refuelling</h3>
<p>Beyond the air-emissions inventory captured under “air emissions” above, several jurisdictions have flagged on-site diesel storage volumes (often hundreds of thousands of gallons across a campus) as a fire and groundwater risk. This is most explicit in Virginia DEQ permitting and in the New Castle County (DE) ordinance, which now requires battery energy storage as part of any large facility partly to limit reliance on diesel [Source: https://spotlightdelaware.org/2025/12/16/two-new-castle-county-industrial-projects-may-become-data-centers/].</p>
</section>
</section>
<section id="local-and-state-government-responses" class="level2">
<h2 class="anchored" data-anchor-id="local-and-state-government-responses">Local and state-government responses</h2>
<section id="moratoriums" class="level3">
<h3 class="anchored" data-anchor-id="moratoriums">Moratoriums</h3>
<p>The “moratorium” terminology requires care. Most so-called moratoriums are six- to twelve-month pauses pending an ordinance review, not permanent bans. Documented examples:</p>
<ul>
<li><strong>DeKalb County (GA)</strong>: Moratorium on new applications and expansions, extended to 23 June 2026 [Source: https://www.cbsnews.com/atlanta/news/dekalb-leaders-extend-data-center-moratorium-to-june-as-residents-raise-health-cost-concerns/].</li>
<li><strong>Troup County (GA)</strong>: Moratorium lifted in early 2026 once ordinance with 1,500 ft setback adopted [Source: https://www.lagrangenews.com/news/commissioners-approve-data-center-ordinance-lift-moratorium-2b6e15ed].</li>
<li><strong>Glynn County (GA)</strong>: Rejected a moratorium April 2026 but adopted ordinance with closed-loop water condition; setback at only 50 ft is well below the 200-500 ft generally recommended [Source: https://thecurrentga.org/2026/04/15/glynn-county-to-vote-on-zoning-residents-ask-to-delay-data-center-rule/].</li>
<li><strong>Gates County (NC)</strong>: One-year moratorium passed December 2025 [Source: https://www.northcarolinahealthnews.org/2026/03/25/nc-communities-push-back-ai-data-centers-project-delta-lawsuit/].</li>
<li><strong>North Carolina, broadly</strong>: Approximately a dozen jurisdictions have passed or are considering one-year moratoriums [Source: https://www.northcarolinahealthnews.org/2026/03/25/nc-communities-push-back-ai-data-centers-project-delta-lawsuit/].</li>
<li><strong>Federal</strong>: S.4214 “Artificial Intelligence Data Center Moratorium Act” was introduced in the 119th Congress (text on Congress.gov); the bill has not advanced [Source: https://www.congress.gov/bill/119th-congress/senate-bill/4214/text].</li>
</ul>
<p>A Good Jobs First analysis tracks moratorium <em>bills</em> spreading at state level into 2026, primarily state-rate-impact and tax-incentive legislation rather than outright build bans [Source: https://goodjobsfirst.org/data-center-moratorium-bills-are-spreading-in-2026/].</p>
</section>
<section id="zoning-ordinance-tightening" class="level3">
<h3 class="anchored" data-anchor-id="zoning-ordinance-tightening">Zoning ordinance tightening</h3>
<p>The clearest single jurisdictional change is Loudoun County’s elimination of by-right data-centre zoning. On 18 March 2025 the Board of Supervisors approved Phase 1 of the Data Center Standards and Locations Comprehensive Plan Amendment plus a Zoning Ordinance Amendment, requiring Special Exception (SPEX) approval for data centres in IP, GI and MR-HI zoning districts - meaning all new projects must go through public review [Source: https://www.hklaw.com/en/insights/publications/2025/04/loudoun-county-virginia-eliminates-by-right-data-center-development]. Caroline County (VA) made an analogous change in December 2024, requiring special exception under PIRT standards [Source: https://co.caroline.va.us/AgendaCenter/ViewFile/Item/7389?fileID=11579].</p>
<p>Setback-and-noise tightening (covered above): Calvert (MD) 400 ft, Linn (Iowa) 1,000 ft, LaGrange/Troup (GA) 1,500 ft from sensitive receptors, New Castle (DE) 1,000 ft. Closed-loop cooling requirements: Glynn (GA), New Castle (DE), and de facto in Tucson/Pima Co.&nbsp;after Project Blue’s redesign.</p>
</section>
<section id="tax-break-revisions" class="level3">
<h3 class="anchored" data-anchor-id="tax-break-revisions">Tax-break revisions</h3>
<ul>
<li><strong>Virginia</strong>: General Assembly held a special session in 2026 to weigh phasing out or capping the USD 1.6-1.9 bn annual sales-tax exemption; budget negotiations centred on the issue in March 2026 [Source: https://www.vpm.org/generalassembly/2026-03-12/budget-data-center-tax-break-scott-lucas-spanberger-torian-rephann].</li>
<li><strong>Texas</strong>: Legislators have signalled they will consider limiting or repealing the exemption in the next session [Source: https://www.texastribune.org/2026/04/08/texas-data-centers-sales-tax-break-billion-dollars/].</li>
<li><strong>Wisconsin</strong>: PSC has now ruled (May 2026) that large data centres served by We Energies must pick up the entire cost of new generation needed to serve them; the Alliant Beaver Dam ICR has been modified on the same principle. Commissioner Kristy Nieto called this potentially “fundamentally reshaping the utility system” [Source: https://www.wpr.org/news/state-regulators-change-we-energies-data-center-rate-proposal-to-protect-customers]. (This is a rate-design rather than tax-incentive change, but the fiscal logic is parallel.)</li>
</ul>
</section>
<section id="litigation-outcomes" class="level3">
<h3 class="anchored" data-anchor-id="litigation-outcomes">Litigation outcomes</h3>
<p>The PW Digital Gateway is the leading case. Prince William Circuit Court (Judge Kimberly A. Irving, August 2025) voided the December 2023 rezonings on the procedural ground that the County failed to publish proper legal notice. The Virginia Court of Appeals unanimously upheld this on 31 March 2026. Compass dropped its appeal; Prince William County’s Board of Supervisors voted unanimously on 15 April 2026 to withdraw the County from the lawsuit; QTS filed a Virginia Supreme Court appeal hours before the deadline on 30 April 2026 [Source: https://wtop.com/virginia/2026/04/prince-william-co-withdraws-from-digital-gateway-lawsuit-reversing-course-from-2023/; https://www.bisnow.com/national/news/data-center-development/developer-backs-out-of-17-gw-virginia-data-center-plan-134341]. The Stokes County (NC) Project Delta zoning was similarly voided in March 2026 over defective public notice [Source: https://myfox8.com/news/north-carolina/stokes/stokes-county-board-of-commissioners-speaks-out-after-voting-to-start-proposed-data-center-development-over-again-after-lawsuit/]. The xAI Memphis NAACP/SELC/Earthjustice Clean Air Act suit is at the preliminary-injunction stage in 2026 [Source: https://earthjustice.org/press/2026/naacp-asks-court-for-emergency-action-to-stop-illegal-air-pollution-from-xais-data-center-power-plant].</p>
<p>The procedural theme matters: in two of the highest-profile defeats for developers, the legal hook was inadequate public notice rather than substantive land-use or environmental law. This is a replicable cause of action in any jurisdiction with rigorous notice statutes.</p>
</section>
<section id="projects-substantially-modified-downsized-or-cancelled" class="level3">
<h3 class="anchored" data-anchor-id="projects-substantially-modified-downsized-or-cancelled">Projects substantially modified, downsized or cancelled</h3>
<ul>
<li><strong>Project Blue (Tucson)</strong>: Switched from city water to closed-loop air cooling after city council rejection; Amazon withdrew as anchor tenant [Source: https://www.kjzz.org/the-show/2025-12-09/rejected-by-tucson-and-abandoned-by-amazon-project-blue-data-center-moves-forward].</li>
<li><strong>Tract West Valley (AZ)</strong>: USD 14 bn proposal withdrawn May 2024; replaced with a smaller engagement-led version [Source: https://www.abc15.com/news/business/14-billion-west-valley-data-center-project-request-withdrawn-after-cities-push-back].</li>
<li><strong>Microsoft Caledonia (WI)</strong>: Microsoft ended its rezoning attempt in September 2025 after community opposition [Source: https://www.cnbc.com/2025/11/25/microsoft-ai-data-center-rejection-vs-support.html].</li>
<li><strong>University of Delaware “Data Center Hill”</strong>: Killed June 2024 after extended trades-union and resident opposition [Source: https://www.datacenterknowledge.com/regulations/university-of-delaware-puts-nail-in-coffin-of-data-center-and-power-plant-project].</li>
<li><strong>PW Digital Gateway</strong>: Compass abandoned its share May 2026; QTS continues fighting [Source: https://www.bisnow.com/national/news/data-center-development/developer-backs-out-of-17-gw-virginia-data-center-plan-134341].</li>
</ul>
</section>
</section>
<section id="polling-and-survey-evidence" class="level2">
<h2 class="anchored" data-anchor-id="polling-and-survey-evidence">Polling and survey evidence</h2>
<p>The strongest single dataset is the Washington Post-Schar School (George Mason University) Virginia poll conducted 26-31 March 2026 across 1,101 registered voters. The share of Virginia voters who say they would be “comfortable” with a new data centre going up in their community fell from 69% in 2023 to 35% in 2026 [Source: https://www.washingtonpost.com/business/2026/04/15/data-centers-poll-virginia/; https://www.washingtonpost.com/documents/0eee4c34-9746-492b-babe-116e433209d1.pdf]. Support for tax breaks for data centres creating ≥1,000 jobs fell from 61% to 37% over the same window. A majority (56%) still credit data centres with positive job impact, but fewer than half think they help fund county governments or hold down local property tax rates [Source: https://www.washingtonpost.com/business/2026/04/15/data-centers-poll-virginia/].</p>
<p>The Mason-Dixon December 2024 Virginia poll commissioned by the Virginia Hospital and Healthcare Association captured related but earlier findings; the Wason Center (Christopher Newport University) January 2025 poll noted Spanberger leading and statewide concern about data centres rising, with the exception of Southwest Virginia where employment-creation arguments held more weight [Source: https://vhha.com/wp-content/uploads/2025/01/Mason-Dixon-Poll-December-2024.pdf; https://cardinalnews.org/2025/01/16/cnu-poll-spanberger-up-data-centers-down-except-maybe-in-southwest-virginia/].</p>
<p>The Wisconsin PSC public-comment record in dockets 6630-TE-113 (We Energies) and 6680-TE-115 (Alliant / Beaver Dam) is the strongest formal-comment dataset outside Virginia. Of 2,209 written comments in the WEC tariff docket reviewed by the Sierra Club Wisconsin Chapter, 98.5% disapproved of the proposed structure. In the Alliant docket, all 601 comments were tallied and 93% of verbal and 85% of written comments said data centres should pay 100% of their costs [Source: https://www.sierraclub.org/wisconsin/blog/2026/04/data-widespread-disproval-data-center-costs-wisconsin]. The Sierra Club is an advocacy organisation and conducted the tally itself; the underlying comment text is on the PSC docket and could in principle be independently coded. The PSC’s own subsequent rate ruling in May 2026 (data centres bear full cost of new generation) is the closest thing to an official confirmation that the comment record influenced the outcome [Source: https://www.wpr.org/news/state-regulators-change-we-energies-data-center-rate-proposal-to-protect-customers].</p>
<p>JLARC’s December 2024 Virginia data-centre report drew on stakeholder consultation including residents but did not publish a representative resident-survey instrument; its conclusions on resident impact (noise, viewshed, increasing residential proximity) are qualitatively presented [Source: https://jlarc.virginia.gov/pdfs/presentations/JLARC%20Virginia%20Data%20Center%20Study_FINAL_12-09-2024.pdf].</p>
</section>
<section id="caveats-and-limitations" class="level2">
<h2 class="anchored" data-anchor-id="caveats-and-limitations">Caveats and limitations</h2>
<ol type="1">
<li><strong>Source-tier discipline.</strong> Several of the most-cited campaign organisations - Sierra Club, NAACP, SELC, Earthjustice, Piedmont Environmental Council, American Battlefield Trust, Memphis Community Against Pollution - are advocacy groups with explicit positions. Their press releases describe legitimate facts (turbine counts, court filings, ordinance language) that are independently verifiable, but their characterisations of public-health risk, motive or scale should be cross-checked against primary regulatory dockets where possible. Where this draft cites them, it is with that caveat in mind.</li>
<li><strong>Data Center Watch numbers.</strong> The USD 64-156 bn “blocked or delayed” tally is the most quoted figure in this space. Data Center Watch is funded by 10a Labs (an AI security firm) and has not published audited definitions of “blocked” versus “delayed”. The number should be read as directional rather than precise.</li>
<li><strong>“Moratorium” terminology.</strong> Most jurisdictional pauses are 6-12 month studies pending an ordinance, not permanent prohibitions. Coverage that conflates the two overstates the regulatory wall.</li>
<li><strong>Distinguishing local from rate-impact concerns.</strong> Wisconsin PSC dockets, Virginia rate cases and Texas comptroller fights involve electricity-customer interests across an entire utility footprint. They are politically related to local opposition (the same residents may oppose both) but are analytically distinct. This draft includes them where they are the local response mechanism (e.g.&nbsp;WI PSC), but the rate-impact dimension proper belongs in a separate political-dimensions draft.</li>
<li><strong>Distinguishing local opposition from AI-ethics opposition.</strong> Some opposition material conflates local quality-of-life concerns with national debates about AI safety, content moderation or labour displacement. The case studies in this draft are all rooted in site-specific impacts.</li>
<li><strong>Cases not verified in this pass.</strong> I did not find a credible 2024-2026 source documenting an “Apex / xAI / Hanging Rock NC” project at the level of detail you suggested - the best I located is generalised North Carolina opposition coverage. If a specific Hanging Rock project exists I would need a project name, developer or county-meeting reference to confirm. Similarly, the Newark “Stargate” angle as such did not surface; the Newark case I did verify is the older 2024 University of Delaware project plus 2025 New Castle County ordinance activity.</li>
<li><strong>Outcome volatility.</strong> Several of these cases are still moving as of May 2026 (PW Digital Gateway VA Supreme Court appeal, xAI preliminary-injunction motion, Stokes County re-do, Virginia tax-break special session). Outcomes will need refresh before publication.</li>
</ol>
</section>
<section id="bibliography" class="level2">
<h2 class="anchored" data-anchor-id="bibliography">Bibliography</h2>
<ul>
<li>American Battlefield Trust. “‘Digital Gateway’ Threatens to Overwhelm Manassas Battlefield.” https://www.battlefields.org/speak-out/digital-gateway-threatens-overwhelm-manassas-battlefield</li>
<li>AZ Luminaria. “Tucson City Council rejects Project Blue data center amid intense community pressure.” 6 Aug 2025. https://azluminaria.org/2025/08/06/tucson-city-council-rejects-project-blue-amid-intense-community-pressure/</li>
<li>Bisnow. “Loudoun Approves Controversial Data Center After Initial Opposition.” https://www.bisnow.com/washington-dc/news/data-center/loudoun-approves-controversial-data-center-after-initial-opposition-84151</li>
<li>Bisnow. “Developer Backs Out Of 17-GW Virginia Data Center Plan.” https://www.bisnow.com/national/news/data-center-development/developer-backs-out-of-17-gw-virginia-data-center-plan-134341</li>
<li>Bloomberg. “Loudoun County Data Center Growth Strains Residents Seeking AI Regulation.” 29 July 2025. https://www.bloomberg.com/news/features/2025-07-29/loudon-county-data-center-growth-strains-residents-seeking-ai-regulation</li>
<li>Capital B News. “A Historic Black Community Takes On the World’s Richest Man Over Environmental Racism.” https://capitalbnews.org/musk-xai-memphis-black-neighborhood-pollution/</li>
<li>Cardinal News. “CNU poll: Spanberger up, data centers down (except maybe in Southwest Virginia).” 16 Jan 2025. https://cardinalnews.org/2025/01/16/cnu-poll-spanberger-up-data-centers-down-except-maybe-in-southwest-virginia/</li>
<li>CBS Atlanta. “DeKalb leaders extend data center moratorium to June as residents raise health, cost concerns.” https://www.cbsnews.com/atlanta/news/dekalb-leaders-extend-data-center-moratorium-to-june-as-residents-raise-health-cost-concerns/</li>
<li>CNBC. “Microsoft’s plans for 15 more data centers win approval at former Wisconsin Foxconn site.” 26 Jan 2026. https://www.cnbc.com/2026/01/26/microsoft-wins-approval-for-15-data-centers-at-wisconsin-foxconn-site.html</li>
<li>CNBC. “Microsoft data center rejected in Wisconsin village, AI boom hits snag.” 25 Nov 2025. https://www.cnbc.com/2025/11/25/microsoft-ai-data-center-rejection-vs-support.html</li>
<li>Caroline County (VA) Planning Commission. SPEX-08-2025 packet. https://co.caroline.va.us/AgendaCenter/ViewFile/Item/7389?fileID=11579</li>
<li>Commercial Observer. “Data Center Opposition Has Scrambled the Calculations.” Feb 2026. https://commercialobserver.com/2026/02/opposition-data-centers-real-estate-reasons/</li>
<li>Congress.gov. “S.4214 - Artificial Intelligence Data Center Moratorium Act.” https://www.congress.gov/bill/119th-congress/senate-bill/4214/text</li>
<li>CSG South. “Take That for Data: Incentivizing Innovation or Inefficiency.” https://csgsouth.org/policies/take-that-for-data-incentivizing-innovation-or-inefficiency/</li>
<li>Data Center Dynamics. “Group claims $64bn in US data center projects impacted by local opposition in last two years.” https://www.datacenterdynamics.com/en/news/group-claims-64bn-in-us-data-center-projects-impacted-by-local-opposition-in-last-two-years/</li>
<li>Data Center Knowledge. “University of Delaware Puts Nail in Coffin of Data Center and Power Plant Project.” https://www.datacenterknowledge.com/regulations/university-of-delaware-puts-nail-in-coffin-of-data-center-and-power-plant-project</li>
<li>Data Center Watch. Report. https://www.datacenterwatch.org/report</li>
<li>Democracy Now. “Tucson City Council Votes Unanimously to Reject Project Blue.” 7 Aug 2025. https://www.democracynow.org/2025/8/7/headlines/tucson_city_council_votes_unanimously_to_reject_project_blue_a_proposed_data_center_linked_to_amazon</li>
<li>Earthjustice. “Illegal Pollution from Data Center Power Plants - We’re Suing xAI.” https://earthjustice.org/case/xai-illegal-gas-power-plant-data-center-colossus</li>
<li>Earthjustice. “NAACP Asks Court for Emergency Action to Stop Illegal Air Pollution from xAI.” 2026. https://earthjustice.org/press/2026/naacp-asks-court-for-emergency-action-to-stop-illegal-air-pollution-from-xais-data-center-power-plant</li>
<li>EESI. “Communities Are Raising Noise Pollution Concerns About Data Centers.” https://www.eesi.org/articles/view/communities-are-raising-noise-pollution-concernsabout-data-centers</li>
<li>El Paso Matters. “El Paso Meta data center calls for $473 million gas-powered power plant.” 18 Jan 2026. https://elpasomatters.org/2026/01/18/el-paso-electric-meta-data-center-new-473-million-natural-gas-power-plant/</li>
<li>Fortune. “A Michigan farm town voted down plans for a giant OpenAI-Oracle data center. Weeks later, construction began.” 6 May 2026. https://fortune.com/2026/05/06/ai-data-center-michigan-saline-politics-farmland/</li>
<li>Fox 10 Phoenix. “Chandler City Council unanimously rejects proposed data center.” https://www.fox10phoenix.com/news/chandler-data-center-proposal-draws-heavy-opposition-council-meeting</li>
<li>Good Jobs First. “Data Center Moratorium Bills Are Spreading in 2026.” https://goodjobsfirst.org/data-center-moratorium-bills-are-spreading-in-2026/</li>
<li>Grist. “Arizona’s water is drying up. That won’t stop its data center rush.” https://grist.org/technology/arizona-water-data-centers-semiconducters/</li>
<li>Heinrich Boll Stiftung. “The Promise of ‘The Peace of Plenty:’ How South Memphis Is Refusing AI’s Big Lies.” 28 Jan 2026. https://us.boell.org/en/2026/01/28/promise-peace-plenty-how-south-memphis-refusing-ais-big-lies</li>
<li>Holland &amp; Knight. “Loudoun County, Virginia, Eliminates By-Right Data Center Development.” Apr 2025. https://www.hklaw.com/en/insights/publications/2025/04/loudoun-county-virginia-eliminates-by-right-data-center-development</li>
<li>Indiana Economic Digest. “LaPorte County backs limits on data centers amid farmland concerns.” https://indianaeconomicdigest.net/Content/Most-Recent/Agriculture/Article/LaPorte-County-backs-limits-on-data-centers-amid-farmland-concerns/31/68/120326</li>
<li>Inside Climate News. “Facing Its Third Data Center, an Iowa County Rolls Out Extensive Zoning Rules.” 1 Mar 2026. https://insideclimatenews.org/news/01032026/iowa-county-data-center-ordinance/</li>
<li>JLARC (Virginia). “Data Centers in Virginia.” 9 Dec 2024. https://jlarc.virginia.gov/pdfs/presentations/JLARC%20Virginia%20Data%20Center%20Study_FINAL_12-09-2024.pdf</li>
<li>KJZZ. “Rejected by Tucson and abandoned by Amazon, Project Blue data center moves forward.” 9 Dec 2025. https://www.kjzz.org/the-show/2025-12-09/rejected-by-tucson-and-abandoned-by-amazon-project-blue-data-center-moves-forward</li>
<li>LaGrange News (Troup Co.&nbsp;GA). “Commissioners approve data center ordinance, lift moratorium.” https://www.lagrangenews.com/news/commissioners-approve-data-center-ordinance-lift-moratorium-2b6e15ed</li>
<li>Latitude Media. “In Indiana, an anatomy of data center opposition.” https://www.latitudemedia.com/news/in-indiana-an-anatomy-of-data-center-opposition/</li>
<li>Latitude Media. “Data center jobs aren’t at servers - they’re in energy.” https://www.latitudemedia.com/news/data-center-jobs-arent-at-servers-theyre-in-energy/</li>
<li>Mason-Dixon Polling &amp; Strategy. “December 2024 Virginia poll” (commissioned by VHHA). https://vhha.com/wp-content/uploads/2025/01/Mason-Dixon-Poll-December-2024.pdf</li>
<li>Michigan Public. “Michigan regulators approve Saline Twp data center request with conditions.” 18 Dec 2025. https://www.michiganpublic.org/environment-climate-change/2025-12-18/michigan-regulators-approve-saline-twp-data-center-request-with-conditions</li>
<li>MultiState. “State Data Center Legislation Faces Local Zoning Battles.” 15 Jan 2026. https://www.multistate.us/insider/2026/1/15/state-data-center-legislation-faces-local-zoning-battles</li>
<li>NAACP. “NAACP Sues xAI for Illegal Pollution from Data Center Power Plant.” https://naacp.org/articles/naacp-sues-xai-illegal-pollution-data-center-power-plant</li>
<li>NC Health News. “NC communities push back on AI data centers.” 25 Mar 2026. https://www.northcarolinahealthnews.org/2026/03/25/nc-communities-push-back-ai-data-centers-project-delta-lawsuit/</li>
<li>NC Newsline. “Community groups sue over planned data center in Stokes County.” 13 Mar 2026. https://ncnewsline.com/2026/03/13/community-groups-sue-over-planned-data-center-in-stokes-county/</li>
<li>PEC (Piedmont Environmental Council). “Massive ‘Digital Gateway’ Data Center Project Has Been Halted.” https://www.pecva.org/region/regional-state-national-region/prince-william/massive-digital-gateway-data-center-project-has-been-halted/</li>
<li>PEC. “Proposed Increase to Data Center Diesel Generator Use.” https://www.pecva.org/work/energy-work/proposed-increase-to-data-center-diesel-generator-use/</li>
<li>PBS Wisconsin. “Wisconsin communities face scrutiny over data center secrecy beyond use of NDAs.” https://pbswisconsin.org/news-item/wisconsin-communities-face-scrutiny-over-data-center-secrecy-beyond-use-of-ndas/</li>
<li>Phoenix New Times. “How much water will Chandler’s data center project use?” https://www.phoenixnewtimes.com/news/how-much-water-will-chandlers-data-center-project-use-40627750/</li>
<li>Prince William Times. “Park superintendent warns of data centers’ ‘wholesale destruction’ of historic areas around the Manassas battlefield.” https://www.princewilliamtimes.com/news/park-superintendent-warns-of-data-centers-wholesale-destruction-of-historic-areas-around-the-manassas-battlefield/article_278caca0-37c3-11ee-9f99-abdeeaa89493.html</li>
<li>Reasons to Be Cheerful. “The Small Wisconsin City That Defeated a Giant Data Center.” https://reasonstobecheerful.world/menomonie-wisconsin-data-center-toolkit/</li>
<li>SELC. “xAI built an illegal power plant to power its data center.” https://www.selc.org/news/xai-built-an-illegal-power-plant-to-power-its-data-center/</li>
<li>SELC. “A rural community steps up to stop data centers.” https://www.selc.org/news/a-rural-community-steps-up-to-stop-data-centers/</li>
<li>Sierra Club Wisconsin. “The Data is In: Widespread Disproval for Data Center Costs in Wisconsin.” Apr 2026. https://www.sierraclub.org/wisconsin/blog/2026/04/data-widespread-disproval-data-center-costs-wisconsin</li>
<li>Spotlight Delaware. “Two New Castle County industrial projects may become data centers.” 16 Dec 2025. https://spotlightdelaware.org/2025/12/16/two-new-castle-county-industrial-projects-may-become-data-centers/</li>
<li>Tech-Insider. “U.S. AI Data Center Delays: 7 GW Capacity Crisis.” https://tech-insider.org/us-ai-data-center-delays-cancellations-7gw-capacity-crisis-2026/</li>
<li>Texas Tribune. “Plan to run El Paso data center on natural gas sparks concern.” 26 Jan 2026. https://www.texastribune.org/2026/01/26/texas-el-paso-meta-data-center-natural-gas-power-plant/</li>
<li>Texas Tribune. “Texas losing a billion dollars a year on data center tax break.” 8 Apr 2026. https://www.texastribune.org/2026/04/08/texas-data-centers-sales-tax-break-billion-dollars/</li>
<li>The Current GA. “Glynn County rejects data center moratorium despite community pushback.” 15 Apr 2026. https://thecurrentga.org/2026/04/15/glynn-county-to-vote-on-zoning-residents-ask-to-delay-data-center-rule/</li>
<li>The Hill. “Bipartisan local backlash to data centers halts $64B in development: Study.” https://thehill.com/policy/technology/5605667-data-center-criticism-study/</li>
<li>TIME. “Inside the Memphis Community Battling Elon Musk’s xAI.” https://time.com/7308925/elon-musk-memphis-ai-data-center/</li>
<li>Tom’s Hardware. “Virginia voter support for new data centers collapses from 69% in 2023 to 35%.” https://www.tomshardware.com/tech-industry/virginia-voter-support-for-new-data-centers-collapses-to-35-percent</li>
<li>Virginia DEQ. “Issued Air Permits for Data Centers.” https://www.deq.virginia.gov/news-info/shortcuts/permits/air/issued-air-permits-for-data-centers</li>
<li>Virginia Mercury. “Virginia regulators weigh expanded use of data centers’ polluting generators.” 16 Dec 2025. https://virginiamercury.com/2025/12/16/virginia-regulators-weigh-expanded-use-of-data-centers-polluting-generators/</li>
<li>VPM (Virginia Public Media). “$2B data center tax break fight pushes Virginia budget negotiations.” 12 Mar 2026. https://www.vpm.org/generalassembly/2026-03-12/budget-data-center-tax-break-scott-lucas-spanberger-torian-rephann</li>
<li>VPM. “Data center opposition is ‘catching a fire’ across North Carolina politics.” 5 May 2026. https://www.vpm.org/news/2026-05-05/wunc-data-center-opposition-political-challenges-north-carolina</li>
<li>Washington Post. “Poll finds Virginia voters have turned against data centers.” 15 Apr 2026. https://www.washingtonpost.com/business/2026/04/15/data-centers-poll-virginia/</li>
<li>Washington Post-Schar School. “March 26-31, 2026 Virginia poll.” https://www.washingtonpost.com/documents/0eee4c34-9746-492b-babe-116e433209d1.pdf</li>
<li>Wisconsin Examiner. “Rural Wisconsin has become a hotspot for data centers. State’s unique tax instrument explains why.” 22 Jan 2026. https://wisconsinexaminer.com/2026/01/22/rural-wisconsin-has-become-a-hotspot-for-data-centers-states-unique-tax-instrument-explains-why/</li>
<li>Wisconsin Public Radio (WPR). “State regulators change We Energies’ data center rate proposal to protect customers.” https://www.wpr.org/news/state-regulators-change-we-energies-data-center-rate-proposal-to-protect-customers</li>
<li>Wisconsin Public Radio. “Port Washington data center campus will be $15B hub for OpenAI, Oracle ‘Stargate’ program.” https://www.wpr.org/news/port-washington-data-center-campus-openai-oracle-stargate-chatgpt</li>
<li>WNDU. “LaPorte moves forward with the annexation of 1,000 acres for Microsoft data center expansion.” 14 Apr 2026. https://www.wndu.com/2026/04/14/city-laporte-votes-annex-roughly-1000-acres-farmland-near-microsoft-data-center-project/</li>
<li>WSB-TV Atlanta. “Palmetto residents concerned over data center construction in neighboring Coweta County.” https://www.wsbtv.com/news/local/atlanta/palmetto-residents-concerned-over-data-center-construction-neighboring-coweta-county/AKZ6W5ZB3JAOFEY7DOLVX7FUGY/</li>
<li>WTOP. “Prince William Co.&nbsp;withdraws from Digital Gateway lawsuit.” Apr 2026. https://wtop.com/virginia/2026/04/prince-william-co-withdraws-from-digital-gateway-lawsuit-reversing-course-from-2023/</li>
<li>WUSA9. “As data center noise concerns grow, Loudoun Co.&nbsp;officials discuss possible mitigation efforts.” https://www.wusa9.com/article/news/local/data/loudoun-county-officials-data-center-noise/65-45884219-750f-4d47-a660-71a20d8db001</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>