<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Leitch">
<meta name="dcterms.date" content="2026-05-10">

<title>US Data Centre Electricity Demand: Forecast Reconciliation and Announced Project Pipeline</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="demand_forecasts_files/libs/clipboard/clipboard.min.js"></script>
<script src="demand_forecasts_files/libs/quarto-html/quarto.js"></script>
<script src="demand_forecasts_files/libs/quarto-html/popper.min.js"></script>
<script src="demand_forecasts_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="demand_forecasts_files/libs/quarto-html/anchor.min.js"></script>
<link href="demand_forecasts_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="demand_forecasts_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="demand_forecasts_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="demand_forecasts_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="demand_forecasts_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">US Data Centre Electricity Demand: Forecast Reconciliation and Announced Project Pipeline</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>David Leitch </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="us-data-centre-electricity-demand-forecast-reconciliation-and-announced-project-pipeline" class="level1">
<h1>US data centre electricity demand: forecast reconciliation and announced project pipeline</h1>
<section id="why-this-matters-and-what-is-being-forecast" class="level2">
<h2 class="anchored" data-anchor-id="why-this-matters-and-what-is-being-forecast">1. Why this matters and what is being forecast</h2>
<p>Forecasts of US data centre electricity demand published between mid-2024 and early 2026 differ by more than a factor of three for the same target year. The Lawrence Berkeley National Laboratory (LBNL) base case for 2028 is 325 TWh; Goldman Sachs Research’s most recent number for 2030 is roughly 750 TWh of US-only consumption; Morgan Stanley’s implied number is higher again. EPRI, the IEA, BloombergNEF, NERC and the EIA sit between these poles.</p>
<p>The spread is not all about underlying disagreement on AI workloads. A substantial part of it comes from inconsistent definitions. Three different quantities are routinely conflated:</p>
<ul>
<li><strong>Annual energy consumption (TWh/year)</strong>: what the meter actually records. This is what LBNL, EIA and IEA primarily report.</li>
<li><strong>Coincident peak demand (GW)</strong>: the instantaneous draw the grid must serve at the system peak. This is what NERC, RTOs and utility load forecasts focus on.</li>
<li><strong>Contracted or announced capacity (GW)</strong>: nameplate ratings of facilities that developers have signed agreements for, including duplicated requests across multiple utilities. This is what hyperscaler press releases and interconnection queues report.</li>
</ul>
<p>PG&amp;E published analysis showing data centre peak load runs at about 67% of nameplate, and average load is lower again [Source: https://www.powerpolicy.net/p/the-puzzle-of-low-data-center-utilization]. So a 1 GW “announced campus” might translate to about 670 MW of coincident peak and roughly 5–6 TWh/year of energy at high utilisation — not the 8.76 TWh implied by 1 GW × 8,760 hours.</p>
<p>The “phantom load” problem compounds this. ERCOT’s large-load interconnection queue grew from 63 GW at the end of 2024 to 226 GW by October 2025, but only 1.8% of that queued capacity was actually operational and drawing power [Source: https://www.latitudemedia.com/news/phantom-data-centers-are-flooding-the-load-queue/]. Industry observers estimate speculative interconnection requests outnumber real projects by 5–10x [Source: https://www.utilitydive.com/news/a-fraction-of-proposed-data-centers-will-get-built-utilities-are-wising-up/748214/].</p>
<p>The rest of this note (a) presents the major forecasts on a comparable basis where possible, (b) catalogues the largest announced campuses that are not yet under construction or are in early build, and (c) reconciles the spread.</p>
<hr>
</section>
<section id="forecast-comparison" class="level2">
<h2 class="anchored" data-anchor-id="forecast-comparison">2. Forecast comparison</h2>
<p>The table below presents the headline US data centre demand numbers from each source. Where a source publishes a range, the central or “base” case is shown with the range in parentheses. Definitions vary — see the methodology notes that follow.</p>
<p><strong>Table 1. US data centre electricity demand forecasts (selected sources)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 29%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: left;">Publication date</th>
<th style="text-align: right;">2028 TWh</th>
<th style="text-align: right;">2030 TWh</th>
<th style="text-align: right;">2035 TWh</th>
<th style="text-align: right;">Peak GW addition by 2030</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LBNL (DOE)</td>
<td style="text-align: left;">Dec 2024</td>
<td style="text-align: right;">325 (low) – 580 (high), midpoint ~450</td>
<td style="text-align: right;">n/a (forecast ends 2028)</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: left;">Energy basis; 2023 baseline 176 TWh</td>
</tr>
<tr class="even">
<td style="text-align: left;">EPRI (Powering Intelligence)</td>
<td style="text-align: left;">May 2024; updated Feb 2026</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">380–790 (2026 update)</td>
<td style="text-align: right;">~900 (medium)</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: left;">2026 update is 60% higher than 2024</td>
</tr>
<tr class="odd">
<td style="text-align: left;">IEA (Energy and AI)</td>
<td style="text-align: left;">Apr 2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">~425 (US share)</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: left;">US increase 240 TWh from 185 TWh 2024</td>
</tr>
<tr class="even">
<td style="text-align: left;">EIA (AEO 2025 / 2026)</td>
<td style="text-align: left;">Jan 2026 / Apr 2026</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a explicit</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: left;">Reference case: commercial computing 8% (2024) → 20% (2050) of commercial sector</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Morgan Stanley</td>
<td style="text-align: left;">Aug 2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">implied ~720 (~18% of US)</td>
<td style="text-align: right;">implied ~800+</td>
<td style="text-align: right;">~150 GW new DCs by 2030 (global)</td>
<td style="text-align: left;">18% of US elec by 2030</td>
</tr>
<tr class="even">
<td style="text-align: left;">Goldman Sachs</td>
<td style="text-align: left;">Sep 2025 (revised Apr 2026)</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">~750 (US); 1,350 global</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">US capacity 95 GW by 2030 (+197% from 2025)</td>
<td style="text-align: left;">Lifted 220% global growth</td>
</tr>
<tr class="odd">
<td style="text-align: left;">McKinsey</td>
<td style="text-align: left;">2024–2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">606 (~11.7% of US)</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">80 GW (US, from 25 GW in 2024)</td>
<td style="text-align: left;">Mid scenario; AI workload triples 2025–2030</td>
</tr>
<tr class="even">
<td style="text-align: left;">BloombergNEF</td>
<td style="text-align: left;">Dec 2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">~78 GW implied</td>
<td style="text-align: right;">n/a (energy)</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: left;">106 GW US peak by 2035; 8.6% of US elec</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NERC (LTRA 2025)</td>
<td style="text-align: left;">Jan 2026</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">+224 GW summer peak North America by 2035 (10-yr)</td>
<td style="text-align: left;">65% increase vs LTRA 2024</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grid Strategies</td>
<td style="text-align: left;">Dec 2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">+166 GW US peak by 2030 (~90 GW from DCs)</td>
<td style="text-align: left;">6x revision vs 2022 forecast</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PJM Long-Term Load Forecast</td>
<td style="text-align: left;">Jan 2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">+30 GW peak (2025–2030)</td>
<td style="text-align: right;">1,328 TWh total RTO energy 2035</td>
<td style="text-align: right;">+32 GW peak 2024–2030; 94% from DCs</td>
<td style="text-align: left;">RTO-wide</td>
</tr>
<tr class="even">
<td style="text-align: left;">ERCOT Long-Term Load Forecast</td>
<td style="text-align: left;">Apr 2025; queue update Dec 2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">130–148 GW planning capacity</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">138 GW large loads on grid by 2030</td>
<td style="text-align: left;">226 GW in queue, ~75% data centres</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MISO</td>
<td style="text-align: left;">2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">163 GW peak by 2035 (+35% vs 2025)</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: left;">2.7% CAGR mid case</td>
</tr>
<tr class="even">
<td style="text-align: left;">SPP</td>
<td style="text-align: left;">2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">~90 GW DC-linked of 166 GW total peak growth</td>
<td style="text-align: left;">Among RTOs</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dominion Energy (VA IRP)</td>
<td style="text-align: left;">Dec 2024; updated Oct 2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">~9 GW DC peak in 10 yrs</td>
<td style="text-align: right;">+20,000 MW DC growth in Dominion Zone by 2037</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: left;">47.2 GW contracted DC pipeline</td>
</tr>
<tr class="even">
<td style="text-align: left;">Georgia Power (2025 IRP)</td>
<td style="text-align: left;">Jan 2025; approved Jul 2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">~8,500 MW load growth by 2030</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">6,000–8,500 MW certified production additions</td>
<td style="text-align: left;">2,600 MW above 2023 IRP</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Entergy</td>
<td style="text-align: left;">2025</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">~7 GW Meta Hyperion alone by 2030</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: right;">13% near-term annual industrial sales growth</td>
<td style="text-align: left;">80% CapEx expansion since 2023</td>
</tr>
</tbody>
</table>
<p>Sources are listed individually under §5.</p>
<section id="how-to-read-the-table" class="level3">
<h3 class="anchored" data-anchor-id="how-to-read-the-table">How to read the table</h3>
<ul>
<li><strong>TWh columns</strong>: annual electricity consumption.</li>
<li><strong>Peak GW addition</strong>: incremental coincident peak demand (or equivalent) above 2024 baseline.</li>
<li>“n/a” means the source did not publish a number for that year on the relevant basis. Most do not publish 2035 numbers explicitly; LBNL stops at 2028.</li>
</ul>
<hr>
</section>
</section>
<section id="where-the-forecasts-agree-where-they-diverge-and-why" class="level2">
<h2 class="anchored" data-anchor-id="where-the-forecasts-agree-where-they-diverge-and-why">3. Where the forecasts agree, where they diverge, and why</h2>
<section id="areas-of-broad-agreement" class="level3">
<h3 class="anchored" data-anchor-id="areas-of-broad-agreement">Areas of broad agreement</h3>
<ol type="1">
<li><strong>Direction and magnitude</strong>: every major source projects US data centre electricity consumption at least doubling from the 2023 baseline of 176 TWh by 2030 [Source: https://newscenter.lbl.gov/2025/01/15/berkeley-lab-report-evaluates-increase-in-electricity-demand-from-data-centers/]. The lowest 2030 number (LBNL low case extrapolated) is roughly 350 TWh; the highest (Goldman/Morgan Stanley) is roughly 750 TWh.</li>
<li><strong>AI is the dominant driver post-2024</strong>. EPRI assumes AI queries draw roughly ten times the electricity of a traditional search [Source: https://www.utilitydive.com/news/artificial-intelligence-doubles-data-center-demand-2030-EPRI/717467/]. McKinsey expects AI workloads to more than triple between 2025 and 2030 [Source: https://www.mckinsey.com/industries/private-capital/our-insights/how-data-centers-and-the-energy-sector-can-sate-ais-hunger-for-power].</li>
<li><strong>PJM and ERCOT are the epicentres</strong>. Every source places the largest absolute load growth in those two footprints, with MISO third on the latest data [Source: https://www.utilitydive.com/news/data-centers-miso-ferc-market-report/815831/].</li>
<li><strong>Resource adequacy is at risk in 13 of 23 NERC assessment areas</strong> over the next five years [Source: https://www.nerc.com/globalassets/our-work/assessments/nerc_ltra_2025.pdf].</li>
</ol>
</section>
<section id="where-they-disagree-and-why" class="level3">
<h3 class="anchored" data-anchor-id="where-they-disagree-and-why">Where they disagree, and why</h3>
<p><strong>The Goldman / Morgan Stanley vs LBNL gap (~$2x by 2030)</strong>:</p>
<p>Goldman Sachs Research lifted its global 2030 forecast to 1,350 TWh in September 2025, with the US share at approximately 750 TWh [Source: https://www.goldmansachs.com/insights/articles/ai-to-drive-165-increase-in-data-center-power-demand-by-2030]. That implies 95 GW of US capacity by 2030, up 197% from 2025. Morgan Stanley implies a similar magnitude — 18% of US electricity by 2030, which on EIA’s 2030 generation projection is roughly 720 TWh [Source: https://www.morganstanley.com/insights/podcasts/thoughts-on-the-market/data-center-electricity-consumption-michelle-weaver-david-arcaro].</p>
<p>LBNL’s central 2028 case is 450 TWh, which on the same growth trajectory would reach roughly 550–600 TWh by 2030 — about 20% below Goldman.</p>
<p>The gap is driven by three assumption differences:</p>
<ol type="1">
<li><strong>AI server share and intensity</strong>: investment-bank forecasts assume AI servers reach 27%+ of total data centre power by 2027; LBNL’s mid case assumes a slower diffusion path with significant gains in chip-level efficiency.</li>
<li><strong>Build rate</strong>: Goldman and Morgan Stanley take announced hyperscaler capex commitments largely at face value. LBNL applies historical build-rate constraints and a more cautious view on supply chain bottlenecks (transformers, switchgear, GPU supply).</li>
<li><strong>Cooling and PUE</strong>: LBNL assumes continued PUE improvements, particularly in liquid cooling adoption. The bank forecasts assume more modest efficiency gains because AI training clusters run at sustained high utilisation that limits cooling efficiency headroom.</li>
</ol>
<p><strong>The peak-GW vs annual-TWh translation</strong>:</p>
<p>NERC, Grid Strategies and the RTOs report peak GW. Converting to annual TWh requires a load factor assumption. At a 65% data-centre load factor (consistent with PG&amp;E’s metered evidence), Grid Strategies’ 90 GW of data-centre peak growth by 2030 implies ~510 TWh of new annual energy, on top of the ~150 TWh consumed by data centres in 2023 — a 2030 total of ~660 TWh. That sits between LBNL’s high case and Goldman’s number, and inside EPRI’s 2026 update range of 380–790 TWh [Source: https://restservice.epri.com/publicattachment/97025].</p>
<p><strong>The phantom-load discount</strong>:</p>
<p>Utility and RTO interconnection queues are massively oversubscribed. Three pieces of evidence:</p>
<ul>
<li>ERCOT: 226 GW in the queue, 1.8% operational [Source: https://www.latitudemedia.com/news/ercots-large-load-queue-has-nearly-quadrupled-in-a-single-year/].</li>
<li>Dominion: 47.2 GW contracted, against a forecast peak data-centre demand of 9 GW in 10 years [Source: https://virginiabusiness.com/dominion-data-center-power-demand-virginia-scc/].</li>
<li>Industry estimates: speculative interconnection requests run at 5–10x the number of projects actually built [Source: https://www.utilitydive.com/news/a-fraction-of-proposed-data-centers-will-get-built-utilities-are-wising-up/748214/].</li>
</ul>
<p>This is partly developers genuinely shopping the same load to multiple utilities, and partly a rational response to long interconnection queues — a developer who only puts a single application in cannot be sure of getting served. Texas passed legislation in 2025 requiring large-load customers to disclose duplicate filings [Source: https://www.utilitydive.com/news/ercots-large-load-queue-jumped-almost-300-last-year-official/808820/].</p>
<p>If utility forecasts are taken at face value, the US will need 166 GW of additional peak capacity by 2030 [Source: https://gridstrategiesllc.com/wp-content/uploads/Grid-Strategies-National-Load-Growth-Report-2025.pdf]. If 30–50% of that is phantom (a defensible estimate given the ratios above), the build requirement is 80–115 GW, much closer to BloombergNEF’s bottom-up 2035 number of 106 GW [Source: https://www.utilitydive.com/news/us-data-center-power-demand-could-reach-106-gw-by-2035-bloombergnef/806972/].</p>
</section>
<section id="my-read-on-the-spread" class="level3">
<h3 class="anchored" data-anchor-id="my-read-on-the-spread">My read on the spread</h3>
<p>The most defensible 2030 US data centre energy consumption range is <strong>500–700 TWh</strong> (12–17% of US electricity). The investment-bank top end (~750 TWh) requires both rapid AI build-out and resolution of supply chain bottlenecks; the LBNL low case (~350 TWh) requires AI training to plateau or efficiency gains to outrun workload growth, which the 2024–2026 trajectory does not support. EPRI’s mid scenario, BloombergNEF’s bottom-up, and the discounted Grid Strategies number all cluster in the 500–650 TWh band.</p>
<p>For 2035 the range widens because few primary sources publish that far ahead. BloombergNEF’s 106 GW peak implies roughly 600–750 TWh at typical load factors — broadly consistent with EPRI’s “around 900 TWh by 2050” central case [Source: https://restservice.epri.com/publicattachment/97025].</p>
<hr>
</section>
</section>
<section id="largest-announced-us-data-centre-projects-not-yet-operational" class="level2">
<h2 class="anchored" data-anchor-id="largest-announced-us-data-centre-projects-not-yet-operational">4. Largest announced US data centre projects not yet operational</h2>
<p>The table below covers campuses of 500 MW or larger that have been publicly announced for commercial operation in 2027 or later. Some have early phases already energised; the “expected MW” column refers to full build-out.</p>
<p><strong>Table 2. Largest announced US data centre campuses (500 MW+, full COD 2027+)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 18%">
<col style="width: 19%">
<col style="width: 24%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Owner / partners</th>
<th style="text-align: left;">Location</th>
<th style="text-align: right;">Expected full MW</th>
<th style="text-align: left;">Expected full COD</th>
<th style="text-align: left;">Power source / utility</th>
<th style="text-align: left;">Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Meta (Hyperion)</td>
<td style="text-align: left;">Richland Parish, LA</td>
<td style="text-align: right;">5,000 (ultimate); 1,500 by end-2027</td>
<td style="text-align: left;">2030 (full); summer 2028 (initial ops)</td>
<td style="text-align: left;">Entergy Louisiana — 10 gas plants, ~7.2 GW, plus 1.5 GW solar</td>
<td style="text-align: left;">Site work since Dec 2024; financing closed Oct 2025</td>
</tr>
<tr class="even">
<td style="text-align: left;">Amazon / Anthropic (Project Rainier Phase 2)</td>
<td style="text-align: left;">NW Indiana (NIPSCO)</td>
<td style="text-align: right;">2,400 (Phase 2 expansion)</td>
<td style="text-align: left;">2027–2028</td>
<td style="text-align: left;">NIPSCO — gas + renewables</td>
<td style="text-align: left;">Phase 1 (2.2 GW, New Carlisle) operational Oct 2025; Phase 2 announced Nov 2025</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OpenAI / Oracle / Crusoe (Stargate Abilene)</td>
<td style="text-align: left;">Abilene, TX</td>
<td style="text-align: right;">1,200</td>
<td style="text-align: left;">Q4 2026 (full); 0.6 GW mid-2026</td>
<td style="text-align: left;">Crusoe-procured gas + renewables; ERCOT</td>
<td style="text-align: left;">Two of eight buildings live Sep 2025</td>
</tr>
<tr class="even">
<td style="text-align: left;">OpenAI / Oracle / SB Energy (Stargate Milam County)</td>
<td style="text-align: left;">Milam County, TX</td>
<td style="text-align: right;">1,200</td>
<td style="text-align: left;">Initial 2026; full 2027</td>
<td style="text-align: left;">ERCOT</td>
<td style="text-align: left;">Site work underway</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OpenAI / Oracle / STACK (Stargate New Mexico, “Project Jupiter”)</td>
<td style="text-align: left;">Doña Ana County, NM</td>
<td style="text-align: right;">1,000+ (ultimate up to 1.5 GW)</td>
<td style="text-align: left;">Initial 2027</td>
<td style="text-align: left;">El Paso Electric / SPS</td>
<td style="text-align: left;">Foundation work underway</td>
</tr>
<tr class="even">
<td style="text-align: left;">OpenAI / Related Digital / Oracle (Stargate Michigan)</td>
<td style="text-align: left;">Saline Township, MI</td>
<td style="text-align: right;">1,000</td>
<td style="text-align: left;">2027</td>
<td style="text-align: left;">DTE / METC</td>
<td style="text-align: left;">Announced Sep 2025</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OpenAI / Oracle / Vantage (Stargate Wisconsin)</td>
<td style="text-align: left;">Port Washington, WI</td>
<td style="text-align: right;">1,300 by end-2027; 3,500 long-term</td>
<td style="text-align: left;">End-2027</td>
<td style="text-align: left;">We Energies</td>
<td style="text-align: left;">Site work underway</td>
</tr>
<tr class="even">
<td style="text-align: left;">OpenAI / SoftBank (Stargate Lordstown)</td>
<td style="text-align: left;">Lordstown, OH</td>
<td style="text-align: right;">up to 1,500 (with Milam)</td>
<td style="text-align: left;">2026–2027</td>
<td style="text-align: left;">AEP Ohio</td>
<td style="text-align: left;">Ground broken Sep 2025</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Microsoft (Fairwater Mount Pleasant)</td>
<td style="text-align: left;">Mount Pleasant, WI</td>
<td style="text-align: right;">~3,300 (4-building build-out)</td>
<td style="text-align: left;">Late 2027</td>
<td style="text-align: left;">We Energies</td>
<td style="text-align: left;">Phase 1 live; investment $7.3B</td>
</tr>
<tr class="even">
<td style="text-align: left;">Microsoft (Fairwater Atlanta — East US 3)</td>
<td style="text-align: left;">Fulton / Douglas counties, GA</td>
<td style="text-align: right;">~2,000 (multi-site)</td>
<td style="text-align: left;">Phase 1 by 2026; full by 2027</td>
<td style="text-align: left;">Georgia Power</td>
<td style="text-align: left;">Under construction</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Meta (Lebanon, Ohio)</td>
<td style="text-align: left;">Lebanon, OH (LEAP District)</td>
<td style="text-align: right;">1,000</td>
<td style="text-align: left;">Late 2027 / early 2028</td>
<td style="text-align: left;">AEP Ohio</td>
<td style="text-align: left;">Construction Feb 2026</td>
</tr>
<tr class="even">
<td style="text-align: left;">AWS (Salem Township)</td>
<td style="text-align: left;">Luzerne County, PA</td>
<td style="text-align: right;">up to 960 (initial); expansion via grid-connected PPA up to 1,920</td>
<td style="text-align: left;">Phased through 2028+</td>
<td style="text-align: left;">Talen / Susquehanna nuclear (1.92 GW PPA via FERC-approved retail structure)</td>
<td style="text-align: left;">Operating; expansion subject to FERC outcome</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AWS (Mississippi — Madison County)</td>
<td style="text-align: left;">Madison County, MS</td>
<td style="text-align: right;">Multi-GW (within $25B commitment)</td>
<td style="text-align: left;">2027+</td>
<td style="text-align: left;">Entergy Mississippi (Vicksburg + Traceview gas plants)</td>
<td style="text-align: left;">Construction underway</td>
</tr>
<tr class="even">
<td style="text-align: left;">AWS (NC, Sherwood Smith complex)</td>
<td style="text-align: left;">North Carolina</td>
<td style="text-align: right;">2,240</td>
<td style="text-align: left;">Full by 2027–2028</td>
<td style="text-align: left;">Duke Energy</td>
<td style="text-align: left;">Ground Oct 2025</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hut 8 (Beacon Point)</td>
<td style="text-align: left;">Texas (AEP Texas)</td>
<td style="text-align: right;">1,000</td>
<td style="text-align: left;">Q1 2027 initial energization</td>
<td style="text-align: left;">AEP Texas — interconnection agreement signed</td>
<td style="text-align: left;">First 352 MW IT lease signed</td>
</tr>
<tr class="even">
<td style="text-align: left;">CleanArc</td>
<td style="text-align: left;">Virginia</td>
<td style="text-align: right;">900</td>
<td style="text-align: left;">Initial 300 MW early 2027</td>
<td style="text-align: left;">Dominion / PJM</td>
<td style="text-align: left;">Under development</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amazon / X-energy SMR fleet</td>
<td style="text-align: left;">Multiple US sites</td>
<td style="text-align: right;">5,000+ (by 2039)</td>
<td style="text-align: left;">First units mid-2030s</td>
<td style="text-align: left;">X-energy Xe-100 SMRs</td>
<td style="text-align: left;">$500M Series C-1; KHNP/Doosan partnership 2026</td>
</tr>
<tr class="even">
<td style="text-align: left;">Google / Kairos Power SMRs</td>
<td style="text-align: left;">Multiple US sites</td>
<td style="text-align: right;">500 (7 SMRs)</td>
<td style="text-align: left;">First unit 2030; complete by 2035</td>
<td style="text-align: left;">Kairos KP-FHR</td>
<td style="text-align: left;">Agreement Oct 2024</td>
</tr>
</tbody>
</table>
<p>Sources for project entries are listed in §5.</p>
<section id="key-observations-on-the-announced-pipeline" class="level3">
<h3 class="anchored" data-anchor-id="key-observations-on-the-announced-pipeline">Key observations on the announced pipeline</h3>
<ul>
<li><strong>Phase delivery vs full COD</strong>: most “gigawatt campuses” deliver in 100–300 MW phases over 3–5 years. The full nameplate is rarely energised before 2028.</li>
<li><strong>Power source skew</strong>: of the 18 listed, 9 are anchored by new gas-fired generation (overwhelmingly Entergy and Georgia Power footprints). Only the AWS-Talen Susquehanna deal and the SMR programmes are anchored on nuclear, and the SMR units do not arrive at scale until the early-to-mid 2030s.</li>
<li><strong>Stargate alone</strong> (Abilene + 5 new sites + Michigan + ongoing development) is on track to add about 7 GW by 2027 [Source: https://openai.com/index/five-new-stargate-sites/] — a single programme equal to roughly 6% of BloombergNEF’s entire 2035 US data centre forecast.</li>
<li><strong>The Susquehanna case</strong> illustrates the regulatory friction: FERC rejected the original behind-the-meter co-location structure in November 2024, forcing a restructure to a grid-connected PPA with retail provision [Source: https://www.utilitydive.com/news/talen-amazon-aws-susquehanna-nuclear-data-centert/750440/]. FERC subsequently directed PJM to write new co-location rules in late 2025 [Source: https://www.ferc.gov/news-events/news/fact-sheet-ferc-directs-nations-largest-grid-operator-create-new-rules-embrace].</li>
</ul>
<hr>
</section>
</section>
<section id="sources" class="level2">
<h2 class="anchored" data-anchor-id="sources">5. Sources</h2>
<section id="primary-forecasts" class="level3">
<h3 class="anchored" data-anchor-id="primary-forecasts">Primary forecasts</h3>
<ul>
<li><strong>LBNL (2024 United States Data Center Energy Usage Report)</strong>, December 2024. Lead author Arman Shehabi. Key finding: 176 TWh in 2023 (4.4% of US electricity), 325–580 TWh by 2028 (6.7–12%). https://eta-publications.lbl.gov/sites/default/files/2024-12/lbnl-2024-united-states-data-center-energy-usage-report_1.pdf and https://newscenter.lbl.gov/2025/01/15/berkeley-lab-report-evaluates-increase-in-electricity-demand-from-data-centers/</li>
<li><strong>EPRI Powering Intelligence (2024)</strong>, May 2024. Four scenarios with 3.7–15% CAGR; 9% of US electricity by 2030 base case. https://www.epri.com/about/media-resources/press-release/q5vu86fr8tkxatfx8ihf1u48vw4r1dzf</li>
<li><strong>EPRI Powering Intelligence 2026 update</strong>, February 2026. Revised range 380–790 TWh by 2030 (60% above 2024 numbers), 9–17% of US electricity by 2030, 10–20% by 2035, ~900 TWh by 2050 medium scenario. https://restservice.epri.com/publicattachment/97025 and https://powering-intelligence.epri.com/</li>
<li><strong>IEA Energy and AI</strong>, April 2025. Global 945 TWh by 2030 (up from 485 TWh in 2025); US increase ~240 TWh (130% rise from ~185 TWh 2024 baseline). https://www.iea.org/reports/energy-and-ai and https://iea.blob.core.windows.net/assets/de9dea13-b07d-42c5-a398-d1b3ae17d866/EnergyandAI.pdf</li>
<li><strong>EIA AEO 2025</strong>, March 2025. Reference case: commercial computing 8% of commercial sector electricity in 2024 → 20% by 2050. https://www.eia.gov/todayinenergy/detail.php?id=65564</li>
<li><strong>EIA AEO 2026</strong>, April 2026. Reference case projects total US generation grows 25–50% through 2050; data centres dominant driver; high case 818 TWh of server consumption by 2050. https://www.eia.gov/pressroom/releases/press587.php and https://www.eia.gov/outlooks/aeo/pdf/AEO2026_Release_Presentation.pdf</li>
<li><strong>EIA Press Release 13 Jan 2026</strong>: strongest four-year electricity demand growth since 2000. https://www.eia.gov/pressroom/releases/press582.php</li>
<li><strong>NERC 2025 Long-Term Reliability Assessment</strong>, December 2025 / January 2026. Summer peak +224 GW over 10 years (vs +132 GW in LTRA 2024); winter +245 GW. https://www.nerc.com/globalassets/our-work/assessments/nerc_ltra_2025.pdf and infographic https://www.nerc.com/globalassets/our-work/assessments/ltra_infographic_2025.pdf</li>
<li><strong>NERC 2024 LTRA (corrected July 2025)</strong>. https://www.nerc.com/globalassets/our-work/assessments/2024-ltra_corrected_july_2025.pdf</li>
<li><strong>Goldman Sachs Research</strong>, September 2025 update (revised April 2026). Global 1,350 TWh by 2030 (220% increase); US ~750 TWh / 95 GW capacity. https://www.goldmansachs.com/insights/articles/ai-to-drive-165-increase-in-data-center-power-demand-by-2030 and https://www.goldmansachs.com/insights/goldman-sachs-research/data-center-power-demand-the-6-ps-driving-growth-and-constraints</li>
<li><strong>Morgan Stanley</strong>, 2025. 18% of US electricity by 2030, 20% by early 2030s; ~150 GW new global data centres by 2030. https://www.morganstanley.com/insights/podcasts/thoughts-on-the-market/data-center-electricity-consumption-michelle-weaver-david-arcaro</li>
<li><strong>McKinsey &amp; Company</strong>, October 2024 / 2025 updates. US 25 GW (2024) → 80+ GW (2030); 606 TWh in 2030 (11.7% of US). https://www.mckinsey.com/industries/private-capital/our-insights/how-data-centers-and-the-energy-sector-can-sate-ais-hunger-for-power and https://www.mckinsey.com/industries/technology-media-and-telecommunications/our-insights/ai-power-expanding-data-center-capacity-to-meet-growing-demand</li>
<li><strong>BloombergNEF</strong>, December 2025. US 106 GW by 2035 (36% above April 2025 number); 8.6% of US electricity. Press summary at https://www.utilitydive.com/news/us-data-center-power-demand-could-reach-106-gw-by-2035-bloombergnef/806972/ — primary BNEF report paywalled.</li>
<li><strong>Grid Strategies National Load Growth Report</strong>, December 2025. Aggregate US 2030 peak forecast +166 GW (vs +30 GW forecast in 2022); ~90 GW from data centres. https://gridstrategiesllc.com/wp-content/uploads/Grid-Strategies-National-Load-Growth-Report-2025.pdf</li>
</ul>
</section>
<section id="rto-and-utility-forecasts" class="level3">
<h3 class="anchored" data-anchor-id="rto-and-utility-forecasts">RTO and utility forecasts</h3>
<ul>
<li><strong>PJM 2025 Long-Term Load Forecast Report</strong>, January 2025. +32 GW peak 2024–2030 (94% data centres); 2035 RTO energy 1,328 TWh. https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/2025-load-report.pdf and summary https://insidelines.pjm.com/2025-long-term-load-forecast-report-predicts-significant-increase-in-electricity-demand/</li>
<li><strong>ERCOT Long-Term Load Forecast Update 2025–2031</strong>, April 2025. https://www.ercot.com/files/docs/2025/04/07/8.1-Long-Term-Load-Forecast-Update-2025-2031-and-Methodology-Changes.pdf</li>
<li><strong>ERCOT 2025 Report on Existing and Potential Electric System Constraints and Needs</strong>, December 2025. 226 GW large-load queue, ~75% data centres. https://www.ercot.com/files/docs/2025/12/23/2025-Report-on-Existing-and-Potential-Electric-System-Constraints-and-Needs.pdf</li>
<li><strong>MISO MTEP25 Report</strong>, 2025. Peak load to 163 GW by 2035 (+35% vs 2025 baseline of 121 GW); 2.7% CAGR mid case. https://cdn.misoenergy.org/MTEP25%20Report731648.pdf</li>
<li><strong>MISO Long-Term Resource Adequacy Update</strong>, September 2025. https://cdn.misoenergy.org/06_2025-09-16_SPC_Open_Long%20Term%20Resource%20Adequacy%20%20Interconnection%20Queue%20Update_FINAL717559.pdf</li>
<li><strong>Dominion Energy 2024 Virginia IRP</strong>, December 2024. https://www.dominionenergy.com/-/media/content/about/our-company/irp/pdfs/2024-irp-w_o-appendices.pdf</li>
<li><strong>Dominion Long-Range Projections</strong>, October 2025. 47.2 GW DC contracted; +7 GW since Dec 2024 IRP; 9 GW DC peak by ~2034. https://virginiabusiness.com/dominion-data-center-power-demand-virginia-scc/</li>
<li><strong>JLARC Virginia Data Center Study</strong>, December 2024. https://jlarc.virginia.gov/pdfs/presentations/JLARC%20Virginia%20Data%20Center%20Study_FINAL_12-09-2024.pdf</li>
<li><strong>Georgia Power 2025 IRP</strong>, January 2025 (PSC approval July 2025). 8,500 MW load growth by 2030; 9,885 MW new resources approved. https://www.georgiapower.com/content/dam/georgia-power/pdfs/company-pdfs/2025-Integrated-Resource-Plan.pdf and PSC fact sheet https://psc.ga.gov/site/downloads/datacenterfactsheet.pdf</li>
<li><strong>Entergy data centre announcements</strong>, 2025. https://www.entergy.com/datacenters and https://www.utilitydive.com/news/gas-continues-to-dominate-entergy-plans-as-data-center-pipeline-grows/804521/</li>
</ul>
</section>
<section id="phantom-load-and-queue-dynamics" class="level3">
<h3 class="anchored" data-anchor-id="phantom-load-and-queue-dynamics">Phantom load and queue dynamics</h3>
<ul>
<li>“Load queue flooded by phantom data centers”, Latitude Media, 2025. https://www.latitudemedia.com/news/phantom-data-centers-are-flooding-the-load-queue/</li>
<li>“ERCOT’s large load queue has nearly quadrupled in a single year”, Latitude Media. https://www.latitudemedia.com/news/ercots-large-load-queue-has-nearly-quadrupled-in-a-single-year/</li>
<li>“ERCOT’s large load queue jumped almost 300% last year”, Utility Dive. https://www.utilitydive.com/news/ercots-large-load-queue-jumped-almost-300-last-year-official/808820/</li>
<li>“A fraction of proposed data centers will get built”, Utility Dive. https://www.utilitydive.com/news/a-fraction-of-proposed-data-centers-will-get-built-utilities-are-wising-up/748214/</li>
<li>“The Puzzle of Low Data Center Utilization Rates” (PG&amp;E metering analysis). https://www.powerpolicy.net/p/the-puzzle-of-low-data-center-utilization</li>
<li>E3, “Forecasting Large Loads in the Age of AI and Data Centers”, December 2025. https://www.ethree.com/wp-content/uploads/2025/12/E3Whitepaper_DataCenterForecasting.pdf</li>
</ul>
</section>
<section id="project-announcements-table-2-sources" class="level3">
<h3 class="anchored" data-anchor-id="project-announcements-table-2-sources">Project announcements (Table 2 sources)</h3>
<ul>
<li><strong>Meta Hyperion</strong>: https://www.datacenterdynamics.com/en/news/meta-purchases-additional-1400-acres-for-hyperion-mega-data-center-expansion/ and https://fortune.com/2026/03/27/meta-hyperion-10-gas-power-plants-louisiana-entergy/ and https://www.entergy.com/news/entergy-louisiana-announces-a-new-agreement-with-meta-that-will-deliver-an-additional-2b-in-customer-savings</li>
<li><strong>AWS Project Rainier</strong>: https://www.cnbc.com/2025/10/29/amazon-opens-11-billion-ai-data-center-project-rainier-in-indiana.html and https://www.datacenterfrontier.com/hyperscale/article/55295967/amazon-doubles-down-on-ai-infrastructure-with-30b-in-new-us-data-center-investments</li>
<li><strong>AWS Mississippi</strong>: https://www.datacenterdynamics.com/en/news/aws-scales-up-investment-commitment-for-mississippi-data-centers-to-25bn/</li>
<li><strong>AWS Salem Township PA / Talen Susquehanna</strong>: https://www.utilitydive.com/news/talen-amazon-aws-susquehanna-nuclear-data-centert/750440/ and https://www.datacenterdynamics.com/en/news/aws-talen-sign-ppa-for-192gw-of-power-from-pennsylvania-nuclear-plant/</li>
<li><strong>FERC Susquehanna ruling</strong>: https://www.utilitydive.com/news/ferc-interconnection-isa-talen-amazon-data-center-susquehanna-exelon/731841/ and https://www.ans.org/news/2025-04-16/article-6937/</li>
<li><strong>FERC PJM colocation order Dec 2025</strong>: https://www.ferc.gov/news-events/news/fact-sheet-ferc-directs-nations-largest-grid-operator-create-new-rules-embrace and https://www.bakerbotts.com/thought-leadership/publications/2025/december/ferc-issues-order-providing-guidance-for-co-locating-power-plants-with-data-centers-within-pjm</li>
<li><strong>Stargate / OpenAI five new sites</strong>: https://openai.com/index/five-new-stargate-sites/ and https://group.softbank/en/news/press/20250924 and https://www.datacenterfrontier.com/machine-learning/article/55319132/scaling-stargate-openais-five-new-us-data-centers-push-toward-10-gw-ai-infrastructure</li>
<li><strong>Stargate Abilene operational</strong>: https://www.datacenterdynamics.com/en/news/crusoes-abilene-data-center-officially-live-serving-oracle-and-openais-stargate/ and https://www.crusoe.ai/resources/newsroom/crusoe-announces-flagship-abilene-data-center-is-live</li>
<li><strong>Stargate Michigan</strong>: https://www.datacenterdynamics.com/en/news/related-digitals-michigan-1gw-data-center-project-to-serve-openai-oracle/</li>
<li><strong>Stargate Wisconsin (Port Washington)</strong>: https://www.datacenterdynamics.com/en/news/openai-announces-five-more-us-stargate-data-centers-with-oracle-and-softbank/</li>
<li><strong>Microsoft Fairwater Mount Pleasant</strong>: https://local.microsoft.com/blog/mount-pleasant-datacenter-project-update/ and https://www.datacenterdynamics.com/en/news/microsoft-ceo-says-fairwater-data-center-site-is-going-live-ahead-of-schedule/ and https://epoch.ai/data-insights/fairwater-power-usage</li>
<li><strong>Microsoft Atlanta (East US 3)</strong>: https://www.datacenterdynamics.com/en/news/microsoft-to-launch-new-cloud-region-in-atlanta-georgia-in-2027/ and https://www.datacenterfrontier.com/hyperscale/article/55126626/details-emerge-on-microsofts-18-billion-investment-in-atlanta-data-centers-amid-tax-development-wrangles</li>
<li><strong>Meta Lebanon, Ohio</strong>: https://www.blackridgeresearch.com/blog/upcoming-largest-data-center-projects-in-united-states-usa</li>
<li><strong>Hut 8 Beacon Point</strong>: https://www.prnewswire.com/news-releases/hut-8-commercializes-first-phase-of-1-gw-beacon-point-ai-data-center-campus-with-15-year-352-mw-it-lease-with-base-term-contract-value-of-9-8-billion-302763484.html</li>
<li><strong>Amazon-X-energy SMR</strong>: https://www.datacenterdynamics.com/en/news/amazon-x-energy-partner-with-south-korean-consortium-to-advance-smr-development-across-us/ and https://www.theregister.com/2025/11/24/x_energy_700m_smr/</li>
<li><strong>Google-Kairos SMR</strong>: https://www.datacenterfrontier.com/energy/article/55235902/google-and-amazon-make-major-inroads-with-smrs-to-bring-nuclear-energy-to-data-centers and https://spectrum.ieee.org/nuclear-powered-data-center</li>
</ul>
<hr>
</section>
</section>
<section id="methodology-and-definitional-notes" class="level2">
<h2 class="anchored" data-anchor-id="methodology-and-definitional-notes">6. Methodology and definitional notes</h2>
<p><strong>Geographic scope</strong>: figures are US-only unless explicitly noted as “global”. Goldman Sachs and IEA publish global numbers and a US share; the US share is reported here.</p>
<p><strong>Energy vs power</strong>: TWh is annual energy consumption from the meter. GW is instantaneous power draw. Converting between them requires a load factor (annual average / peak). Hyperscale data centres typically run at 60–75% load factor; AI training clusters can reach 80%+ when continuously loaded.</p>
<p><strong>Nameplate vs metered</strong>: announcement press releases give nameplate / contracted capacity. Actual peak draw is typically 60–75% of nameplate (PG&amp;E evidence). Forecasters that aggregate announced campuses without applying a discount over-state the grid impact.</p>
<p><strong>Phantom load adjustment</strong>: there is no industry-standard discount factor. Texas’s 1.8% operational ratio is an extreme. A more defensible adjustment for forward forecasting is to take 30–50% of utility-stated demand as duplicative or speculative, based on the 5–10x ratio of requests to actual builds.</p>
<p><strong>What’s not in this note</strong>: residential AI inference at the edge, crypto mining (which the EIA tracks separately and which has been absorbed by AI compute capacity in some cases), and demand response / load flexibility programmes that could shave coincident peak. Industrial decarbonisation electrification (EVs, heat pumps, electrolyser hydrogen) is the other major source of US load growth — Grid Strategies attributes ~45% of its 166 GW number to non-data-centre sources.</p>
<p><strong>What I would not extrapolate</strong>: most sources do not publish 2035 numbers explicitly. EPRI’s medium 900 TWh by 2050 and BloombergNEF’s 106 GW by 2035 are the only direct mid-2030s primary numbers I located. Anything else for 2035 is either implied or back-cast.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>