<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>operating_fleet</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="operating_fleet_files/libs/clipboard/clipboard.min.js"></script>
<script src="operating_fleet_files/libs/quarto-html/quarto.js"></script>
<script src="operating_fleet_files/libs/quarto-html/popper.min.js"></script>
<script src="operating_fleet_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="operating_fleet_files/libs/quarto-html/anchor.min.js"></script>
<link href="operating_fleet_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="operating_fleet_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="operating_fleet_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="operating_fleet_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="operating_fleet_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="us-operating-data-centre-fleet-research-note" class="level1">
<h1>US Operating Data Centre Fleet — Research Note</h1>
<p><strong>Date prepared:</strong> 10 May 2026 <strong>Prepared for:</strong> ITK research note on US data centre fleet <strong>Scope:</strong> Operating (commissioned) US data centres only — pipeline and announced projects are flagged separately</p>
<hr>
<section id="headline-numbers-and-the-definition-trap" class="level2">
<h2 class="anchored" data-anchor-id="headline-numbers-and-the-definition-trap">1. Headline numbers and the definition trap</h2>
<p>The “number of US data centres” varies by an order of magnitude depending on what is counted. The following figures all describe the <strong>2024–2025 US fleet</strong> but use very different definitions:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: left;">Definition / Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">All facilities (including small enterprise sites)</td>
<td style="text-align: right;">~5,427</td>
<td style="text-align: left;">Cloudscene database, Nov 2025 [Source: https://www.cargoson.com/en/blog/number-of-data-centers-by-country]</td>
</tr>
<tr class="even">
<td style="text-align: left;">All facilities tracked by Baxtel</td>
<td style="text-align: right;">~4,720</td>
<td style="text-align: left;">Baxtel directory, May 2026 snapshot [Source: https://baxtel.com/data-center/united-states]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hyperscale-owned facilities (US only)</td>
<td style="text-align: right;">580</td>
<td style="text-align: left;">Synergy Research, end-2025 [Source: https://www.srgresearch.com/articles/hyperscale-data-center-count-hits-1136-average-size-increases-us-accounts-for-54-of-total-capacity]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hyperscale-owned facilities (US only)</td>
<td style="text-align: right;">504</td>
<td style="text-align: left;">Synergy Research, end-Q4 2024 [Source: https://www.srgresearch.com/articles/hyperscale-data-center-count-hits-1136-average-size-increases-us-accounts-for-54-of-total-capacity]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Operating IT load — all US data centres</td>
<td style="text-align: right;">~50 GW</td>
<td style="text-align: left;">FERC 2025 State of the Markets, year-end 2025 [Source: https://www.utilitydive.com/news/data-centers-miso-ferc-market-report/815831/]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Operating power demand (implied from energy use)</td>
<td style="text-align: right;">74–132 GW</td>
<td style="text-align: left;">LBNL 2024 report, derived from 176 TWh in 2023 at 50% utilisation [Source: https://eta-publications.lbl.gov/sites/default/files/2024-12/lbnl-2024-united-states-data-center-energy-usage-report_1.pdf]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Operating IT load — colocation primary markets</td>
<td style="text-align: right;">9,432 MW</td>
<td style="text-align: left;">CBRE H2 2025, year-end 2025, 8 primary markets only [Source: https://www.cbre.com/insights/books/north-america-data-center-trends-h2-2025]</td>
</tr>
</tbody>
</table>
<p><em>Source: ITK compilation from sources listed in column 3.</em></p>
<section id="reconciling-the-numbers" class="level3">
<h3 class="anchored" data-anchor-id="reconciling-the-numbers">Reconciling the numbers</h3>
<ul>
<li>The <strong>FERC 50 GW</strong> figure (year-end 2025) is the most authoritative single number for <strong>operating</strong> facilities and is grounded in interconnection data. FERC’s 2025 State of the Markets report (released 19 March 2026) describes 24% compound annual growth in data centre interconnected load since 2020, with the average new facility entering service in 2025 at nearly 80 MW (vs ~25 MW in 2020) [Source: https://www.utilitydive.com/news/data-centers-miso-ferc-market-report/815831/].</li>
<li>The <strong>LBNL 74–132 GW</strong> range is <em>power demand</em> derived from measured 2023 electricity use of 176 TWh (4.4% of US electricity). Because data centres are not at 100% utilisation, the underlying installed IT plus cooling capacity is somewhat lower than this range; the 50 GW IT-load figure from FERC is consistent with the lower bound once cooling and other overheads are stripped out [Source: https://eta-publications.lbl.gov/sites/default/files/2024-12/lbnl-2024-united-states-data-center-energy-usage-report_1.pdf].</li>
<li><strong>CBRE’s 9,432 MW</strong> is a <strong>subset</strong>: it counts only multi-tenant (third-party colocation and wholesale) inventory in the eight “primary” North American markets (Northern Virginia, Dallas-Ft. Worth, Silicon Valley, Chicago, Phoenix, New York Tri-State, Atlanta, Hillsboro). It excludes hyperscaler-owned facilities and all secondary markets [Source: https://www.cbre.com/insights/books/north-america-data-center-trends-h2-2025]. Bloom Energy and Synergy estimate hyperscalers own ~50–55% of US capacity, and that share is growing [Source: https://www.srgresearch.com/articles/hyperscale-data-center-count-hits-1136-average-size-increases-us-accounts-for-54-of-total-capacity].</li>
</ul>
<p><strong>Best single-source point estimate for operating US IT load (year-end 2025): ~50 GW</strong> (FERC). For comparison and <strong>colocation only</strong> in primary markets: 9.4 GW (CBRE). Synergy reports the US holds ~55% of global hyperscale capacity.</p>
<hr>
</section>
</section>
<section id="top-15-currently-operating-us-data-centre-campuses" class="level2">
<h2 class="anchored" data-anchor-id="top-15-currently-operating-us-data-centre-campuses">2. Top 15 currently operating US data centre campuses</h2>
<p>The list below is restricted to <strong>operating</strong> sites (or sites where at least one phase is operating) as of early 2026. Where a campus is multi-phase, the IT-load figure is the <strong>currently energised</strong> load, with planned full build flagged. “Gross site MW” (which includes cooling, lighting and step-down losses) can be 30–40% above IT load and is noted where sources conflate the two.</p>
<p><strong>Table 1: Largest operating US data centre campuses, ~2025–early 2026</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">#</th>
<th style="text-align: left;">Campus</th>
<th style="text-align: left;">Operator</th>
<th style="text-align: left;">Location</th>
<th style="text-align: right;">Operating IT load (MW)</th>
<th style="text-align: left;">Power source</th>
<th style="text-align: left;">First online</th>
<th style="text-align: left;">Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;">Altoona Campus</td>
<td style="text-align: left;">Meta</td>
<td style="text-align: left;">Altoona, IA</td>
<td style="text-align: right;">~1,400 (campus IT load, multi-building)</td>
<td style="text-align: left;">MidAmerican grid + Meta wind/solar PPAs (100% renewable matched)</td>
<td style="text-align: left;">2014</td>
<td style="text-align: left;">[Source: https://datacenters.atmeta.com/us-locations/]</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;">Prineville Campus</td>
<td style="text-align: left;">Meta</td>
<td style="text-align: left;">Prineville, OR</td>
<td style="text-align: right;">~1,290 (multi-building)</td>
<td style="text-align: left;">PacifiCorp grid + on-site solar; renewable-matched</td>
<td style="text-align: left;">2011</td>
<td style="text-align: left;">[Source: https://datacenters.atmeta.com/us-locations/]</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;">Stargate / Lancium Clean Campus</td>
<td style="text-align: left;">Crusoe / Oracle (for OpenAI)</td>
<td style="text-align: left;">Abilene, TX</td>
<td style="text-align: right;">~300 MW operating; 1,200 MW full build by Q4 2026</td>
<td style="text-align: left;">ERCOT grid + 360 MW on-site gas turbines + on-site solar/storage</td>
<td style="text-align: left;">First building 2025</td>
<td style="text-align: left;">[Source: https://epoch.ai/blog/openai-stargate-where-the-us-sites-stand]; [Source: https://www.tomshardware.com/tech-industry/oracle-and-openai-scrap-planned-600mw-abilene-expansion]</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: left;">Fort Worth Campus</td>
<td style="text-align: left;">Meta</td>
<td style="text-align: left;">Fort Worth, TX</td>
<td style="text-align: right;">~730</td>
<td style="text-align: left;">ERCOT grid; 100% renewable matched via Meta PPAs</td>
<td style="text-align: left;">2017</td>
<td style="text-align: left;">[Source: https://datacenters.atmeta.com/us-locations/]</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: left;">Switch Citadel — TAHOE RENO 1</td>
<td style="text-align: left;">Switch</td>
<td style="text-align: left;">Tahoe Reno, NV</td>
<td style="text-align: right;">~130 operating (campus master-planned to 650 MW; 179 MW behind-the-meter solar added)</td>
<td style="text-align: left;">NV Energy + on-site BTM solar; “100% renewable” claim</td>
<td style="text-align: left;">2017</td>
<td style="text-align: left;">[Source: https://www.switch.com/switch-tahoe-reno-data-center-now-open/]</td>
</tr>
<tr class="even">
<td style="text-align: center;">6</td>
<td style="text-align: left;">Quincy Campus (MWH cluster)</td>
<td style="text-align: left;">Microsoft</td>
<td style="text-align: left;">Quincy, WA</td>
<td style="text-align: right;">~622 (gens 2–4; gen 5 in build)</td>
<td style="text-align: left;">BPA / Grant PUD — Grand Coulee hydro line</td>
<td style="text-align: left;">2007 (gen 1)</td>
<td style="text-align: left;">[Source: https://baxtel.com/data-center/microsoft-quincy-mwh]</td>
</tr>
<tr class="odd">
<td style="text-align: center;">7</td>
<td style="text-align: left;">Council Bluffs Campus</td>
<td style="text-align: left;">Google</td>
<td style="text-align: left;">Council Bluffs, IA</td>
<td style="text-align: right;">Estimated 600+ (Google does not publish IT load; Google’s largest worldwide)</td>
<td style="text-align: left;">MidAmerican grid + Google wind PPAs</td>
<td style="text-align: left;">2009</td>
<td style="text-align: left;">[Source: https://www.datacenterknowledge.com/hyperscalers/google-to-double-size-of-oklahoma-data-center]</td>
</tr>
<tr class="even">
<td style="text-align: center;">8</td>
<td style="text-align: left;">Pryor (Mayes County) Campus</td>
<td style="text-align: left;">Google</td>
<td style="text-align: left;">Pryor, OK</td>
<td style="text-align: right;">Not published; Google’s #2 globally; 600 MW new clean energy PPAs signed 2025</td>
<td style="text-align: left;">OG&amp;E + Google solar PPAs (Mayes County 372 MW solar adjacent)</td>
<td style="text-align: left;">2011</td>
<td style="text-align: left;">[Source: https://www.datacenterdynamics.com/en/news/google-signs-ppa-with-leeward-to-power-oklahoma-data-center-operations/]</td>
</tr>
<tr class="odd">
<td style="text-align: center;">9</td>
<td style="text-align: left;">Colossus 1 (xAI)</td>
<td style="text-align: left;">xAI</td>
<td style="text-align: left;">Memphis, TN</td>
<td style="text-align: right;">250–420 (estimates vary; 200,000 GPUs)</td>
<td style="text-align: left;">TVA + MLGW grid + on-site Solar Group gas turbines (controversial)</td>
<td style="text-align: left;">Sept 2024</td>
<td style="text-align: left;">[Source: https://en.wikipedia.org/wiki/Colossus_(supercomputer)]; [Source: https://www.hpcwire.com/2025/05/13/colossus-ai-hits-200000-gpus-as-musk-ramps-up-ai-ambitions/]</td>
</tr>
<tr class="even">
<td style="text-align: center;">10</td>
<td style="text-align: left;">Switch Core Campus</td>
<td style="text-align: left;">Switch</td>
<td style="text-align: left;">Las Vegas, NV</td>
<td style="text-align: right;">~495</td>
<td style="text-align: left;">NV Energy; renewable PPAs</td>
<td style="text-align: left;">2008 (phased)</td>
<td style="text-align: left;">[Source: https://www.blackridgeresearch.com/blog/largest-top-biggest-data-centers-in-united-states-list]</td>
</tr>
<tr class="odd">
<td style="text-align: center;">11</td>
<td style="text-align: left;">QTS Atlanta-Metro (DC1+expansion)</td>
<td style="text-align: left;">QTS / Blackstone</td>
<td style="text-align: left;">Atlanta, GA</td>
<td style="text-align: right;">~278</td>
<td style="text-align: left;">Georgia Power on-site substation</td>
<td style="text-align: left;">2007 (former Sears facility); QTS 2009</td>
<td style="text-align: left;">[Source: https://q.com/data-centers/atlanta-1/]</td>
</tr>
<tr class="even">
<td style="text-align: center;">12</td>
<td style="text-align: left;">New Albany / Columbus campus (multiple sites)</td>
<td style="text-align: left;">Meta + AWS + Google</td>
<td style="text-align: left;">New Albany, OH</td>
<td style="text-align: right;">500+ across multiple operators (composite, not single campus)</td>
<td style="text-align: left;">AEP Ohio</td>
<td style="text-align: left;">2017 onward</td>
<td style="text-align: left;">[Source: https://www.datacenterfrontier.com/site-selection/article/33035576/data-centers-are-booming-in-ohios-digital-heartland]</td>
</tr>
<tr class="odd">
<td style="text-align: center;">13</td>
<td style="text-align: left;">Talen / AWS Cumulus campus</td>
<td style="text-align: left;">AWS (acquired from Talen)</td>
<td style="text-align: left;">Salem Township, PA</td>
<td style="text-align: right;">300 operating, 960 MW PPA full build (Susquehanna nuclear)</td>
<td style="text-align: left;">Susquehanna nuclear plant — direct ISO-bypass interconnection</td>
<td style="text-align: left;">Acquired 2024; ramp 2024–2032</td>
<td style="text-align: left;">[Source: https://www.esgdive.com/news/amazon-talen-energy-ink-nuclear-ppa-to-power-data-centers-pennsylvania/750950/]</td>
</tr>
<tr class="even">
<td style="text-align: center;">14</td>
<td style="text-align: left;">Lakeside Technology Center</td>
<td style="text-align: left;">Digital Realty</td>
<td style="text-align: left;">Chicago, IL</td>
<td style="text-align: right;">100+ (~1.1 M sq ft)</td>
<td style="text-align: left;">ComEd grid</td>
<td style="text-align: left;">1999</td>
<td style="text-align: left;">[Source: https://www.blackridgeresearch.com/blog/largest-top-biggest-data-centers-in-united-states-list]</td>
</tr>
<tr class="odd">
<td style="text-align: center;">15</td>
<td style="text-align: left;">AWS US-East-1 Ashburn cluster</td>
<td style="text-align: left;">AWS</td>
<td style="text-align: left;">Ashburn / Loudoun, VA</td>
<td style="text-align: right;">~1,500+ aggregate across many buildings (not a single campus; largest single building ~60 MW Cosner)</td>
<td style="text-align: left;">Dominion Energy + AWS solar/wind PPAs</td>
<td style="text-align: left;">2006 onward</td>
<td style="text-align: left;">[Source: https://baxtel.com/data-center/aws-us-east-n-virginia]</td>
</tr>
</tbody>
</table>
<p><em>Source: ITK compilation. Capacity figures cross-checked across operator press releases, Baxtel, BlackRidge Research and Data Center Frontier. Where operators do not publish IT load (Google in particular), figures are external estimates and flagged.</em></p>
<section id="important-caveats-on-the-table" class="level3">
<h3 class="anchored" data-anchor-id="important-caveats-on-the-table">Important caveats on the table</h3>
<ul>
<li><strong>Meta’s Altoona and Prineville sites</strong> are routinely cited as the largest single-operator US campuses by gross IT load. The 1,400 MW and 1,290 MW figures circulate widely (e.g.&nbsp;BlackRidge Research, Data Center Magazine) but Meta does not publish an authoritative IT-load number — these are aggregated from individual building permits over 10+ years. They should be treated as <strong>upper-bound estimates</strong>.</li>
<li><strong>Stargate Abilene</strong> is operational but only at ~300 MW of an eventual 1,200 MW (capped after the 600 MW expansion was scrapped in March 2026 due to grid delivery delays) [Source: https://www.tomshardware.com/tech-industry/oracle-and-openai-scrap-planned-600mw-abilene-expansion].</li>
<li><strong>xAI Colossus</strong> is unusual — power capacity reports range from 150 MW (initial), to 250 MW (mid-2025), to 420 MW (late 2025), with much of the additional supply from on-site portable gas turbines that the Shelby County Health Department ruled were operating without permits.</li>
<li>The <strong>AWS Ashburn cluster</strong> is a network of dozens of buildings rather than a single campus; the ~1.5 GW aggregate is a market estimate (Dgtl Infra; AI Data Center Index), not a published AWS figure [Source: https://aidatacenterindex.com/datacenters/amazon-ec2-virginia-hyperscale-campus.html].</li>
<li>“100% renewable” claims by hyperscalers are typically <strong>annual matched via PPAs and RECs</strong>, not 24/7 carbon-free. Actual instantaneous grid mix follows the host utility.</li>
</ul>
<hr>
</section>
</section>
<section id="geographic-concentration" class="level2">
<h2 class="anchored" data-anchor-id="geographic-concentration">3. Geographic concentration</h2>
<section id="northern-virginia-dominates" class="level3">
<h3 class="anchored" data-anchor-id="northern-virginia-dominates">Northern Virginia dominates</h3>
<p>CBRE H2 2025 (year-end 2025 data, published 25 February 2026) puts Northern Virginia colocation inventory at <strong>4,039.6 MW</strong> of operating commissioned multi-tenant power [Source: https://www.cbre.com/insights/books/north-america-data-center-trends-h2-2025]. This excludes hyperscaler-owned, behind-the-fence facilities (which collectively are larger again in the region — local press cite ~4,900 MW total in mid-2025 and ~5,300–6,000 MW for Loudoun County alone if hyperscaler-owned sites are included [Source: https://wtop.com/business-finance/2025/06/northern-virginia-data-centers-have-topped-4900-megawatts-what-does-that-mean/]).</p>
<p>Northern Virginia is <strong>~43% of the 9,432 MW US primary-market colocation inventory</strong> and roughly <strong>8–12% of the 50 GW national operating IT load</strong> depending on how hyperscaler facilities are attributed.</p>
</section>
<section id="top-us-markets-operating-colocation-inventory-year-end-2025" class="level3">
<h3 class="anchored" data-anchor-id="top-us-markets-operating-colocation-inventory-year-end-2025">Top US markets — operating colocation inventory, year-end 2025</h3>
<p><strong>Table 2: US/North America primary data centre markets — colocation operating inventory</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Market</th>
<th style="text-align: right;">Operating IT load (MW)</th>
<th style="text-align: right;">Vacancy</th>
<th style="text-align: right;">YoY growth</th>
<th style="text-align: left;">Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Northern Virginia</td>
<td style="text-align: right;">4,039.6</td>
<td style="text-align: right;">0.5%</td>
<td style="text-align: right;">+37%</td>
<td style="text-align: left;">Largest in the world; +1,102 MW absorption in 2025</td>
</tr>
<tr class="even">
<td style="text-align: left;">Atlanta</td>
<td style="text-align: right;">1,459.2</td>
<td style="text-align: right;">2.0%</td>
<td style="text-align: right;">+46%</td>
<td style="text-align: left;">Now #2; +458.8 MW YoY; +456 MW absorbed</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dallas-Ft. Worth</td>
<td style="text-align: right;">~1,500</td>
<td style="text-align: right;">low</td>
<td style="text-align: right;">n/a</td>
<td style="text-align: left;">Crossed 1 GW in 2025; +470.8 MW absorption</td>
</tr>
<tr class="even">
<td style="text-align: left;">Phoenix</td>
<td style="text-align: right;">~603 (2024 base)</td>
<td style="text-align: right;">1.7%</td>
<td style="text-align: right;">+67% (2024)</td>
<td style="text-align: left;">Strong further 2025 growth not yet itemised</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chicago</td>
<td style="text-align: right;">n/a separate; ~1,000 inferred</td>
<td style="text-align: right;">3.1%</td>
<td style="text-align: right;">modest</td>
<td style="text-align: left;">Vacancy ticked up</td>
</tr>
<tr class="even">
<td style="text-align: left;">Silicon Valley</td>
<td style="text-align: right;">n/a separate; ~500 inferred</td>
<td style="text-align: right;">low</td>
<td style="text-align: right;">low</td>
<td style="text-align: left;">Power constrained; rents +19%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hillsboro (Portland)</td>
<td style="text-align: right;">~430 (across operators)</td>
<td style="text-align: right;">low</td>
<td style="text-align: right;">rising</td>
<td style="text-align: left;">NTT 354 MW alone; QTS 180 MW</td>
</tr>
<tr class="even">
<td style="text-align: left;">New York Tri-State</td>
<td style="text-align: right;">n/a separate; ~300 inferred</td>
<td style="text-align: right;">low</td>
<td style="text-align: right;">low</td>
<td style="text-align: left;">Power constrained</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Primary markets total</strong></td>
<td style="text-align: right;"><strong>9,432</strong></td>
<td style="text-align: right;">1.4%</td>
<td style="text-align: right;">+36%</td>
<td style="text-align: left;">CBRE H2 2025</td>
</tr>
</tbody>
</table>
<p><em>Source: CBRE North America Data Center Trends H2 2025; Phoenix and Hillsboro figures from CBRE H1 2025 market profiles. Inferred values are derived by subtracting itemised markets from the 9,432 MW total and apportioning by historical share — flagged where exact figures were not located in publicly available CBRE summaries.</em></p>
</section>
<section id="notes-on-selected-secondary-clusters" class="level3">
<h3 class="anchored" data-anchor-id="notes-on-selected-secondary-clusters">Notes on selected secondary clusters</h3>
<ul>
<li><strong>Columbus / New Albany, OH:</strong> AEP Ohio’s load forecasts identify ~5 GW of contracted hyperscaler load in central Ohio (Meta, AWS, Google, QTS) by 2030, with current operating IT load lower [Source: https://www.datacenterfrontier.com/site-selection/article/33035576/data-centers-are-booming-in-ohios-digital-heartland].</li>
<li><strong>Tahoe-Reno (Switch + Apple + Vantage):</strong> ~1 GW master-planned, lower currently energised.</li>
<li><strong>Memphis:</strong> Effectively created by xAI in 2024 — 250–420 MW operating.</li>
<li><strong>Iowa (Council Bluffs, Altoona, Des Moines):</strong> Google + Meta + Microsoft cluster — combined ~3 GW operating estimate.</li>
<li><strong>Pacific Northwest</strong> (Quincy WA + Hillsboro OR + The Dalles): Baxtel reports 5,488 MW across the Pacific Northwest region (operator-published nameplate, includes some non-operating phases) [Source: https://baxtel.com/data-center/united-states].</li>
</ul>
<hr>
</section>
</section>
<section id="power-source-observations" class="level2">
<h2 class="anchored" data-anchor-id="power-source-observations">4. Power source observations</h2>
<p>The shift in 2024–2025 is towards <strong>dedicated firm generation</strong> rather than relying on incremental utility-grid expansion:</p>
<ul>
<li><strong>Nuclear restarts and direct PPAs</strong>: Microsoft’s 835 MW 20-year PPA with Constellation for the restart of Three Mile Island Unit 1 (now “Crane Clean Energy Center”), expected back online 2027 [Source: https://www.datacenterdynamics.com/en/news/three-mile-island-nuclear-power-plant-to-return-as-microsoft-signs-20-year-835mw-ai-data-center-ppa/]. AWS purchased the Cumulus campus from Talen for $650 m and signed a 17-year, 1.92 GW PPA from Susquehanna nuclear [Source: https://www.esgdive.com/news/amazon-talen-energy-ink-nuclear-ppa-to-power-data-centers-pennsylvania/750950/].</li>
<li><strong>Behind-the-meter gas turbines</strong>: Stargate Abilene has 360 MW of on-site gas turbines as primary/back-up [Source: https://energynewsbeat.co/an-on-site-natural-gas-plant-will-help-power-stargates-first-data-center-public-filings-show/]; xAI Memphis is using ~30 portable Solar Group gas turbines on site, drawing regulatory complaints.</li>
<li><strong>Behind-the-meter solar + storage</strong>: Switch Tahoe Reno added 179 MW BTM solar; Meta and Google sign large utility-scale solar/wind PPAs.</li>
<li><strong>Dedicated hydro lines</strong>: Microsoft Quincy uses dedicated lines from Grand Coulee.</li>
</ul>
<p>The Bloom Energy 2025 report frames an aggregate ~35 GW “energy gap” by 2030 between data centre demand growth and grid delivery, driving the on-site generation trend [Source: https://www.bloomenergy.com/news/data-centers-are-turning-to-onsite-power-sources-to-address-35-gw-energy-gap-by-2030/].</p>
<hr>
</section>
<section id="uncertainties-and-caveats" class="level2">
<h2 class="anchored" data-anchor-id="uncertainties-and-caveats">5. Uncertainties and caveats</h2>
<ol type="1">
<li><strong>No single authoritative count of operating US data centres exists.</strong> The 5,427 (Cloudscene) and 4,720 (Baxtel) figures are directory-derived and use different inclusion thresholds. They likely both undercount small enterprise server rooms and, as both are continuously updated, the underlying date is fuzzy.</li>
<li><strong>“Operating MW” definitions are inconsistent.</strong> Operators, brokers and utilities variously cite IT load (servers only), critical/UPS load (IT plus N+1 redundancy), commissioned MW (energised by utility), gross site MW (including cooling and BTM losses), or contracted/announced MW (much of which never builds out at announced size). The largest-campus rankings are particularly sensitive to this — the same site can be reported at IT-load values that differ by 40%+.</li>
<li><strong>Hyperscaler facilities are opaque.</strong> Meta, Google, AWS and Microsoft do not publish per-site IT load; figures circulating in trade press are derived from utility filings, building permits and aerial-image analysis. Meta is the most transparent (publishes campus square-footage and renewable PPAs).</li>
<li><strong>The Synergy Research and CBRE samples do not overlap cleanly.</strong> Synergy counts hyperscaler-owned facilities globally (1,360 in Q4 2025; 580 in US). CBRE counts colocation/wholesale in 8 US primary markets (~9.4 GW). FERC counts everything that interconnects to a covered market. Adding these without care produces double-counting.</li>
<li><strong>The LBNL 74–132 GW power-demand range</strong> is <em>not</em> a count of installed capacity but a back-derivation from 2023 electricity use at assumed 50% utilisation. The wide range reflects genuine uncertainty in capacity utilisation across the fleet.</li>
<li><strong>2025 was a step-change year</strong>. The CBRE primary-market inventory grew 36% YoY (the fastest on record), so any figure more than 6 months old is materially out of date.</li>
<li><strong>Several listed largest-campus figures should be cross-checked against utility interconnection filings</strong> before publication. Meta Altoona (1,400 MW) and Prineville (1,290 MW) in particular are at the upper end of plausible IT-load ranges; some sources interpret the same numbers as gross site MW.</li>
</ol>
<hr>
</section>
<section id="bibliography" class="level2">
<h2 class="anchored" data-anchor-id="bibliography">6. Bibliography</h2>
<section id="tier-1-government-and-laboratory-sources" class="level3">
<h3 class="anchored" data-anchor-id="tier-1-government-and-laboratory-sources">Tier 1: Government and laboratory sources</h3>
<ul>
<li>Lawrence Berkeley National Laboratory, <em>2024 United States Data Center Energy Usage Report</em> (December 2024). https://eta.lbl.gov/publications/2024-lbnl-data-center-energy-usage-report ; full PDF: https://eta-publications.lbl.gov/sites/default/files/2024-12/lbnl-2024-united-states-data-center-energy-usage-report_1.pdf</li>
<li>US Department of Energy, “DOE Releases New Report Evaluating Increase in Electricity Demand from Data Centers” (20 December 2024). https://www.energy.gov/articles/doe-releases-new-report-evaluating-increase-electricity-demand-data-centers</li>
<li>Berkeley Lab News Center, “Berkeley Lab Report Evaluates Increase in Electricity Demand from Data Centers” (15 January 2025). https://newscenter.lbl.gov/2025/01/15/berkeley-lab-report-evaluates-increase-in-electricity-demand-from-data-centers/</li>
<li>Federal Energy Regulatory Commission, <em>2025 State of the Markets Report</em> (released 19 March 2026), as summarised in Utility Dive, “50 GW of data centers online at end of 2025…” https://www.utilitydive.com/news/data-centers-miso-ferc-market-report/815831/</li>
<li>US Energy Information Administration, “Data center owners turn to nuclear as potential electricity source” https://www.eia.gov/todayinenergy/detail.php?id=63304</li>
<li>Joint Legislative Audit and Review Commission of Virginia, <em>Data Centers in Virginia</em> (December 2024). https://jlarc.virginia.gov/pdfs/reports/Rpt598-2.pdf</li>
</ul>
</section>
<section id="tier-2-industry-analysts-public-methodology" class="level3">
<h3 class="anchored" data-anchor-id="tier-2-industry-analysts-public-methodology">Tier 2: Industry analysts (public methodology)</h3>
<ul>
<li>Synergy Research Group, “Hyperscale Data Center Count Hits 1,136; Average Size Increases; US Accounts for 54% of Total Capacity” (March 2025). https://www.srgresearch.com/articles/hyperscale-data-center-count-hits-1136-average-size-increases-us-accounts-for-54-of-total-capacity</li>
<li>CBRE, <em>North America Data Center Trends H2 2025</em> (25 February 2026). https://www.cbre.com/insights/books/north-america-data-center-trends-h2-2025</li>
<li>CBRE, <em>North America Data Center Trends H1 2025</em> (8 September 2025). https://www.cbre.com/insights/reports/north-america-data-center-trends-h1-2025</li>
<li>CBRE, “Fast-Growing North American Data Center Market Set Records in 2025” press release. https://www.cbre.com/press-releases/fast-growing-north-american-data-center-market-set-records-in-2025</li>
<li>JLL, <em>2026 Global Data Center Outlook</em>. https://www.jll.com/en-us/insights/market-outlook/data-center-outlook</li>
<li>JLL, <em>North America Data Center Report Year-end 2025</em>. https://www.jll.com/en-us/insights/market-dynamics/north-america-data-centers</li>
<li>Bloom Energy, <em>2025 Data Center Power Report</em> (January 2026). https://www.bloomenergy.com/news/data-centers-are-turning-to-onsite-power-sources-to-address-35-gw-energy-gap-by-2030/</li>
<li>Dgtl Infra, “United States Data Centers: Top 10 Locations in the USA”. https://dgtlinfra.com/united-states-data-centers/</li>
<li>Baxtel, “United States Data Centers &amp; Colocation”. https://baxtel.com/data-center/united-states</li>
<li>Baxtel, “Northern Virginia Data Center Market”. https://baxtel.com/data-center/northern-virginia</li>
<li>Cloudscene database via Cargoson, “Number of Data Centers by Country” (November 2025). https://www.cargoson.com/en/blog/number-of-data-centers-by-country</li>
<li>AI Data Center Index — AWS Northern Virginia. https://aidatacenterindex.com/datacenters/amazon-ec2-virginia-hyperscale-campus.html</li>
<li>Epoch AI, “OpenAI Stargate: where the US sites stand”. https://epoch.ai/blog/openai-stargate-where-the-us-sites-stand</li>
</ul>
</section>
<section id="tier-3-trade-press-project-level-facts" class="level3">
<h3 class="anchored" data-anchor-id="tier-3-trade-press-project-level-facts">Tier 3: Trade press (project-level facts)</h3>
<ul>
<li>BlackRidge Research, “Top 10 Largest Data Centers In The US (2026)” (6 February 2026). https://www.blackridgeresearch.com/blog/largest-top-biggest-data-centers-in-united-states-list</li>
<li>Data Center Frontier, “Comparing Highlights from the Latest CBRE, JLL ‘State of the Market’ Reports”. https://www.datacenterfrontier.com/colocation/article/55137045/comparing-highlights-from-the-latest-cbre-jll-state-of-the-market-reports-for-us-data-centers</li>
<li>Data Center Frontier, “Data Centers Are Booming In Ohio’s Digital Heartland”. https://www.datacenterfrontier.com/site-selection/article/33035576/data-centers-are-booming-in-ohios-digital-heartland</li>
<li>Data Center Frontier, “Data Center Nuclear Power Update: Microsoft, Constellation, AWS, Talen, Meta”. https://www.datacenterfrontier.com/energy/article/55239739/data-center-nuclear-power-update-microsoft-constellation-aws-talen-meta</li>
<li>Data Center Dynamics, “Three Mile Island nuclear power plant to return as Microsoft signs 20-year, 835MW AI data center PPA”. https://www.datacenterdynamics.com/en/news/three-mile-island-nuclear-power-plant-to-return-as-microsoft-signs-20-year-835mw-ai-data-center-ppa/</li>
<li>Data Center Dynamics, “Oracle/OpenAI drop plans to expand flagship Abilene Stargate site”. https://www.datacenterdynamics.com/en/news/oracleopenai-drop-plans-to-expand-flagship-abilene-stargate-site-meta-in-talks-to-pick-up-crusoe-capacity-with-nvidias-help/</li>
<li>Tom’s Hardware, “Oracle and OpenAI’s Abilene expansion saga detailed” (March 2026). https://www.tomshardware.com/tech-industry/oracle-and-openai-scrap-planned-600mw-abilene-expansion</li>
<li>WTOP News, “Northern Virginia data centers have topped 4,900 megawatts. What does that mean?” (June 2025). https://wtop.com/business-finance/2025/06/northern-virginia-data-centers-have-topped-4900-megawatts-what-does-that-mean/</li>
<li>Meta Data Centers, US locations summary. https://datacenters.atmeta.com/us-locations/</li>
<li>Microsoft Quincy MWH (Baxtel listing). https://baxtel.com/data-center/microsoft-quincy-mwh</li>
<li>Switch press release, “Switch TAHOE RENO Now Open”. https://www.switch.com/switch-tahoe-reno-data-center-now-open/</li>
<li>QTS Atlanta-Metro DC1 (q.com). https://q.com/data-centers/atlanta-1/</li>
<li>HPCwire, “Colossus AI Hits 200,000 GPUs as Musk Ramps Up AI Ambitions” (13 May 2025). https://www.hpcwire.com/2025/05/13/colossus-ai-hits-200000-gpus-as-musk-ramps-up-ai-ambitions/</li>
<li>Wikipedia, “Colossus (supercomputer)”. https://en.wikipedia.org/wiki/Colossus_(supercomputer)</li>
<li>ESG Dive, “Amazon, Talen Energy ink nuclear PPA”. https://www.esgdive.com/news/amazon-talen-energy-ink-nuclear-ppa-to-power-data-centers-pennsylvania/750950/</li>
<li>Energy News Beat, “An on-site natural gas plant will help power Stargate’s first data center”. https://energynewsbeat.co/an-on-site-natural-gas-plant-will-help-power-stargates-first-data-center-public-filings-show/</li>
</ul>
<hr>
<p><em>End of research note. The CBRE H1 2025 and H2 2025 PDFs and the LBNL 2024 report PDF should be obtained directly for any figures intended for publication, since secondary summaries differ in detail.</em></p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>