<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Leitch">
<meta name="dcterms.date" content="2026-05-10">

<title>US Data Centre Pipeline Under Construction — May 2026 Snapshot</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="under_construction_files/libs/clipboard/clipboard.min.js"></script>
<script src="under_construction_files/libs/quarto-html/quarto.js"></script>
<script src="under_construction_files/libs/quarto-html/popper.min.js"></script>
<script src="under_construction_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="under_construction_files/libs/quarto-html/anchor.min.js"></script>
<link href="under_construction_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="under_construction_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="under_construction_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="under_construction_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="under_construction_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">US Data Centre Pipeline Under Construction — May 2026 Snapshot</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>David Leitch </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 10, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="methodology-note-what-counts-as-under-construction" class="level2">
<h2 class="anchored" data-anchor-id="methodology-note-what-counts-as-under-construction">Methodology note: what counts as “under construction”</h2>
<p>The figure most often quoted in the trade press for US data centre construction in early 2026 is roughly <strong>25 GW</strong> of IT/critical load. That number — used by Cushman &amp; Wakefield, datacenterHawk and broadly consistent with JLL — includes any project where vertical construction (steel, foundations or shell) is in progress in primary, secondary and tertiary North American markets. By contrast, <strong>CBRE’s H2 2025 report cites 5,994 MW under construction</strong> at the end of 2025, down from 6,350 MW a year earlier [Source: https://www.cbre.com/insights/books/north-america-data-center-trends-h2-2025, 25 Feb 2026]. The difference is definitional: CBRE’s tracked universe is wholesale colocation in eight primary markets (Northern Virginia, Dallas-Ft Worth, Atlanta, Phoenix, Chicago, Silicon Valley, Hillsboro, New York Tri-State), excluding hyperscaler-owned/built campuses, behind-the-meter “AI factories” outside those metros (Abilene, Shackelford County, Richland Parish, etc.) and tertiary markets such as West Texas, central Wisconsin and rural Indiana.</p>
<p>For this note “under construction” means <strong>physical construction underway</strong> (foundation work, steel, shell, mechanical/electrical fit-out) as of approximately May 2026 — distinct from “planned/announced” (zoning, land option, MOU). I exclude projects whose only public milestone to date is an interconnection request, a land option or a press release. Several mega-campus announcements (Crusoe Project Jade in Wyoming, Sailfish Comanche Circle in Hood County TX, Anthropic-Fluidstack Mitchell County TX) have site approvals but limited evidence of vertical construction, so I flag them as “early-stage”.</p>
<p>A critical pitfall: a “$25 billion data centre” press release frequently bundles a 10-year campus build-out into a single announcement. The numbers below distinguish <strong>first-phase under construction</strong> from <strong>full campus build-out</strong>.</p>
</section>
<section id="pipeline-aggregates-reconciling-the-trackers" class="level2">
<h2 class="anchored" data-anchor-id="pipeline-aggregates-reconciling-the-trackers">Pipeline aggregates: reconciling the trackers</h2>
<p><strong>Table 1 — Major tracker estimates of US/Americas under-construction capacity, late 2025 / early 2026</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 13%">
<col style="width: 28%">
<col style="width: 18%">
<col style="width: 10%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Source</th>
<th style="text-align: left;">Headline figure</th>
<th style="text-align: left;">Geography</th>
<th style="text-align: left;">Date</th>
<th style="text-align: left;">Definition notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Cushman &amp; Wakefield H2 2025</td>
<td style="text-align: left;"><strong>25.3 GW</strong> under construction; 89% pre-committed</td>
<td style="text-align: left;">Americas</td>
<td style="text-align: left;">Feb 2026</td>
<td style="text-align: left;">All asset types; Virginia 6.3 GW (~25%), West Texas 2.9 GW</td>
</tr>
<tr class="even">
<td style="text-align: left;">datacenterHawk</td>
<td style="text-align: left;"><strong>25.3 GW</strong> under construction; 89% pre-leased</td>
<td style="text-align: left;">North America</td>
<td style="text-align: left;">Q1 2026</td>
<td style="text-align: left;">Methodology aligns with C&amp;W</td>
</tr>
<tr class="odd">
<td style="text-align: left;">JLL 2026 Global Outlook</td>
<td style="text-align: left;"><strong>35 GW</strong> total US construction pipeline; 92% pre-committed; <strong>&gt;10 sites ≥1 GW</strong> under construction; Texas 6.5 GW alone</td>
<td style="text-align: left;">US</td>
<td style="text-align: left;">Jan 2026</td>
<td style="text-align: left;">Includes near-term (≤24 mo) plus active sitework</td>
</tr>
<tr class="even">
<td style="text-align: left;">CBRE H2 2025</td>
<td style="text-align: left;"><strong>5,994 MW</strong> under construction</td>
<td style="text-align: left;">North America primary markets</td>
<td style="text-align: left;">Feb 2026</td>
<td style="text-align: left;">Wholesale colocation only, 8 primary metros</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Newmark 2025 Outlook</td>
<td style="text-align: left;">$31.5 bn annualised data centre construction spend</td>
<td style="text-align: left;">US</td>
<td style="text-align: left;">Feb 2025</td>
<td style="text-align: left;">Capex-based, not MW-based</td>
</tr>
<tr class="even">
<td style="text-align: left;">Synergy Research</td>
<td style="text-align: left;">Hyperscale capex $142 bn in Q3 2025 (+180% YoY); ~800 hyperscale facilities in pipeline globally</td>
<td style="text-align: left;">Global</td>
<td style="text-align: left;">Q4 2025</td>
<td style="text-align: left;">Hyperscale only</td>
</tr>
</tbody>
</table>
<p><em>Sources: <a href="https://www.cushmanwakefield.com/en/united-states/news/2026/02/americas-data-center-market-shifts-to-managed-growth">Cushman &amp; Wakefield</a>; <a href="https://www.jll.com/en-us/insights/market-outlook/data-center-outlook">JLL 2026 Global Data Center Outlook</a>; <a href="https://www.cbre.com/insights/books/north-america-data-center-trends-h2-2025">CBRE H2 2025</a>; <a href="https://www.nmrk.com/insights/market-report/2025-us-data-center-market-outlook">Newmark 2025 US Data Center Outlook</a>; <a href="https://www.srgresearch.com/articles/hyperscale-spending-spree-is-driving-dramatic-growth-in-data-center-capacity">Synergy Research</a>.</em></p>
<p><strong>Reconciliation.</strong> The CBRE 6 GW and the C&amp;W/Hawk 25 GW figures are not contradictory — they describe different universes. The CBRE number is the most defensible “wholesale colo space being built in the eight legacy hubs”; the 25 GW figure adds hyperscaler-owned campuses (Meta Hyperion, Amazon Project Rainier, Microsoft Mt Pleasant, xAI Colossus, all the Stargate sites) and emerging power-advantaged regions (Abilene, Shackelford County, Richland Parish, southern Wyoming, Mt Pleasant WI, New Carlisle IN). JLL’s 35 GW is the broadest, including projects where construction begins in 2026 H1.</p>
<p>For an “actually-under-construction in mid-2026” working number, <strong>22–28 GW of IT/critical load in the United States</strong> is a reasonable range, with the central estimate around <strong>24–26 GW</strong>.</p>
</section>
<section id="top-under-construction-projects-top-20" class="level2">
<h2 class="anchored" data-anchor-id="top-under-construction-projects-top-20">Top under-construction projects (top 20)</h2>
<p>The table below catalogues the largest individual projects with verifiable construction underway. Capacity refers to first-phase IT/critical load under construction unless noted; full campus build-out is in the notes column where larger.</p>
<p><strong>Table 2 — Top US data centre projects under physical construction, May 2026</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">#</th>
<th style="text-align: left;">Project / Campus</th>
<th style="text-align: left;">Owner-Developer / Anchor</th>
<th style="text-align: left;">Location (Utility / ISO)</th>
<th style="text-align: right;">UC capacity (MW)</th>
<th style="text-align: left;">First power / COD</th>
<th style="text-align: left;">Power source</th>
<th style="text-align: left;">Source</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Stargate Abilene (Lancium Clean Campus)</td>
<td style="text-align: left;">Crusoe / Oracle / OpenAI</td>
<td style="text-align: left;">Abilene, TX (Oncor / ERCOT)</td>
<td style="text-align: right;">1,200 (8 buildings; 4 live, 4 finishing)</td>
<td style="text-align: left;">4 buildings live Sep 2025; balance mid-2026</td>
<td style="text-align: left;">On-site natural gas + ERCOT grid (some local wind)</td>
<td style="text-align: left;"><a href="https://www.datacenterdynamics.com/en/news/crusoe-tops-out-final-building-at-openai-stargate-data-center-campus-in-abilene-texas/">DCD</a>; <a href="https://www.cnbc.com/2025/09/23/openai-first-data-center-in-500-billion-stargate-project-up-in-texas.html">CNBC</a></td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Hyperion (Richland Parish)</td>
<td style="text-align: left;">Meta / own use</td>
<td style="text-align: left;">Richland Parish, LA (Entergy / MISO South)</td>
<td style="text-align: right;">2,000 first phase (campus scales to 5 GW)</td>
<td style="text-align: left;">Phase 1 partial energisation 2027; full first-phase 2028</td>
<td style="text-align: left;">3 new Entergy CCGTs totalling ~2.3 GW + 240 mi 500-kV line; Meta-funded utility-scale renewables; LOI for nuclear</td>
<td style="text-align: left;"><a href="https://www.datacenterdynamics.com/en/news/entergy-obtains-approval-to-construct-three-gas-facilities-to-serve-metas-2gw-data-center-in-louisiana/">Entergy/DCD</a>; <a href="https://datacenters.atmeta.com/richland-parish-data-center/">Meta</a>; <a href="https://www.enr.com/articles/62766-27b-meta-data-center-pushes-louisiana-toward-massive-power-expansion">ENR</a></td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Project Rainier</td>
<td style="text-align: left;">AWS / Anthropic</td>
<td style="text-align: left;">New Carlisle, IN (AEP / I&amp;M / MISO Indiana)</td>
<td style="text-align: right;">2,200+ campus; 7 of 30 buildings already live (~500 MW operational)</td>
<td style="text-align: left;">Operational since Oct 2025; balance through 2026-27</td>
<td style="text-align: left;">AEP grid; AWS PPAs incl.&nbsp;nuclear (Susquehanna), wind, solar</td>
<td style="text-align: left;"><a href="https://www.cnbc.com/2025/10/29/amazon-opens-11-billion-ai-data-center-project-rainier-in-indiana">CNBC</a>; <a href="https://convergedigest.com/aws-activates-project-rainier-data-center-campus/">AWS</a></td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Frontier (Shackelford County)</td>
<td style="text-align: left;">Vantage Data Centers / Oracle / OpenAI (Stargate)</td>
<td style="text-align: left;">Shackelford County, TX (Oncor / ERCOT)</td>
<td style="text-align: right;">1,400 (10 buildings, 3.7 M sqft)</td>
<td style="text-align: left;">First building H2 2026</td>
<td style="text-align: left;">700 MW behind-the-meter natural gas microgrid (Voltagrid) — off-grid initially</td>
<td style="text-align: left;"><a href="https://www.datacenterdynamics.com/en/news/vantage-breaks-ground-on-texas-gigawatt-data-center-campus-for-openai/">DCD</a>; <a href="https://www.constructionowners.com/news/oracle-and-openai-to-power-new-texas-data-center-off-the-grid">Construction Owners</a></td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">Saline Township (Stargate Michigan)</td>
<td style="text-align: left;">Related Digital / Oracle / OpenAI</td>
<td style="text-align: left;">Saline Township, MI (DTE / MISO)</td>
<td style="text-align: right;">1,400 (3 buildings)</td>
<td style="text-align: left;">Construction started early 2026; first power 2027–28</td>
<td style="text-align: left;">DTE grid + battery storage</td>
<td style="text-align: left;"><a href="https://www.related.com/press-releases/2025-10-30/openai-oracle-and-related-digital-announce-stargate-data-center-site">Related</a>; <a href="https://fortune.com/2026/05/06/ai-data-center-michigan-saline-politics-farmland/">Fortune</a></td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">Project Jupiter (Stargate New Mexico)</td>
<td style="text-align: left;">STACK Infrastructure / BorderPlex / Oracle / OpenAI</td>
<td style="text-align: left;">Doña Ana County (Santa Teresa), NM (El Paso Electric / WECC)</td>
<td style="text-align: right;">2,200 planned, 4 buildings phase 1</td>
<td style="text-align: left;">Late 2026 first energisation</td>
<td style="text-align: left;">Bloom Energy solid-oxide fuel-cell microgrid (revised Apr 2026 from gas turbines)</td>
<td style="text-align: left;"><a href="https://www.datacenterdynamics.com/en/news/stack-joins-multi-billion-dollar-data-center-microgrid-project-in-new-mexico/">DCD</a>; <a href="https://sourcenm.com/2026/04/27/nm-project-jupiter-data-center-developers-announce-new-plans-for-generating-power/">Source NM</a></td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Stargate Milam County</td>
<td style="text-align: left;">SB Energy / SoftBank / OpenAI / Oracle</td>
<td style="text-align: left;">Milam County, TX (Oncor / ERCOT)</td>
<td style="text-align: right;">1,200</td>
<td style="text-align: left;">First building Oct 2026</td>
<td style="text-align: left;">On-site generation (type undisclosed); ERCOT grid</td>
<td style="text-align: left;"><a href="https://epoch.ai/blog/openai-stargate-where-the-us-sites-stand">Epoch AI</a>; <a href="https://www.datacenterdynamics.com/en/news/openai-announces-five-more-us-stargate-data-centers-with-oracle-and-softbank/">DCD</a></td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">Stargate Port Washington</td>
<td style="text-align: left;">Vantage Data Centers / Oracle / OpenAI</td>
<td style="text-align: left;">Port Washington, WI (We Energies / MISO)</td>
<td style="text-align: right;">1,300</td>
<td style="text-align: left;">First power 2027</td>
<td style="text-align: left;">Grid + ~70% solar/wind/battery PPAs</td>
<td style="text-align: left;"><a href="https://epoch.ai/blog/openai-stargate-where-the-us-sites-stand">Epoch AI</a>; <a href="https://www.datacenterfrontier.com/hyperscale/article/55326357/vantage-data-centers-pours-15b-into-wisconsin-ai-campus-as-it-builds-global-giga-scale-footprint">Data Center Frontier</a></td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">Microsoft Mt Pleasant (former Foxconn site)</td>
<td style="text-align: left;">Microsoft / own use</td>
<td style="text-align: left;">Mount Pleasant, WI (We Energies / MISO)</td>
<td style="text-align: right;">First DC online; 15 more buildings approved Jan 2026 (~9 M sqft)</td>
<td style="text-align: left;">First DC late 2025; phase 2 ground 2026</td>
<td style="text-align: left;">We Energies grid (incl.&nbsp;unused legacy Foxconn capacity), Microsoft renewable PPAs</td>
<td style="text-align: left;"><a href="https://www.cnbc.com/2026/01/26/microsoft-wins-approval-for-15-data-centers-at-wisconsin-foxconn-site.html">CNBC</a>; <a href="https://www.datacenterdynamics.com/en/news/microsoft-given-greenlight-for-15-more-data-center-buildings-in-mount-pleasant-wisconsin/">DCD</a></td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">Cumulus / Susquehanna Campus</td>
<td style="text-align: left;">AWS (acquired from Talen 2024) / Talen Energy</td>
<td style="text-align: left;">Berwick (Salem Twp), PA (PPL / PJM)</td>
<td style="text-align: right;">960 currently sited; PPA scales to 1,920 by 2032</td>
<td style="text-align: left;">Front-of-meter transition Spring 2026</td>
<td style="text-align: left;">Susquehanna nuclear (PPA), then PJM-delivered via PPL</td>
<td style="text-align: left;"><a href="https://www.utilitydive.com/news/talen-amazon-aws-susquehanna-nuclear-data-centert/750440/">Utility Dive</a>; <a href="https://ir.talenenergy.com/news-releases/news-release-details/talen-energy-expands-nuclear-energy-relationship-amazon">Talen IR</a></td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: left;">xAI Colossus 1 + Colossus 2</td>
<td style="text-align: left;">xAI (Musk) / own use</td>
<td style="text-align: left;">South Memphis, TN (TVA / MLGW) and Southaven, MS</td>
<td style="text-align: right;">~750 operational; permit for 1,200 self-gen approved</td>
<td style="text-align: left;">Colossus 1 live; Colossus 2 came online late 2025 / Jan 2026</td>
<td style="text-align: left;">18+ on-site Solar Turbines/Mitsubishi gas turbines (495 MW operating; 41 more permitted in MS); some TVA/MLGW grid; planned 168 MWh Megapack BESS</td>
<td style="text-align: left;"><a href="https://newsletter.semianalysis.com/p/xais-colossus-2-first-gigawatt-datacenter">SemiAnalysis</a>; <a href="https://www.datacenterdynamics.com/en/news/musks-xai-gets-go-ahead-for-41-natural-gas-turbines-in-mississippi-to-power-colossus-data-centers/">DCD</a>; <a href="https://www.selc.org/news/xai-built-an-illegal-power-plant-to-power-its-data-center/">SELC</a></td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: left;">Meta El Paso (Project Ranger)</td>
<td style="text-align: left;">Meta / own use</td>
<td style="text-align: left;">El Paso, TX (El Paso Electric / WECC; not ERCOT)</td>
<td style="text-align: right;">1,000 (12 buildings, ~1.2 M sqft)</td>
<td style="text-align: left;">Phase 1 by 2028; ground broken Oct 2025</td>
<td style="text-align: left;">813 modular gas-fired generators (~366 MW) on-site; El Paso Electric grid; matching renewables</td>
<td style="text-align: left;"><a href="https://datacenters.atmeta.com/2025/10/hello-el-paso/">Meta</a>; <a href="https://www.cnbc.com/2026/03/26/meta-to-spend-10-billion-on-ai-data-center-in-el-paso-1gw-by-2028.html">CNBC</a>; <a href="https://www.texastribune.org/2026/01/26/texas-el-paso-meta-data-center-natural-gas-power-plant/">Texas Tribune</a></td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: left;">Microsoft Palmetto / Atlanta Cluster</td>
<td style="text-align: left;">Microsoft / own use</td>
<td style="text-align: left;">Palmetto / Douglasville / East Point, GA (Georgia Power / SERC)</td>
<td style="text-align: right;">$1.8 bn invested; Palmetto ~116 acres + multiple sub-campuses</td>
<td style="text-align: left;">Palmetto in active construction since Apr 2024; finishes by 2028</td>
<td style="text-align: left;">Georgia Power grid (heavy gas + nuclear Vogtle); Microsoft renewable PPAs</td>
<td style="text-align: left;"><a href="https://www.datacenterfrontier.com/hyperscale/article/55126626/details-emerge-on-microsofts-18-billion-investment-in-atlanta-data-centers-amid-tax-development-wrangles">Data Center Frontier</a>; <a href="https://local.microsoft.com/blog/palmetto-datacenter-construction-update/">Microsoft Local</a></td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: left;">Microsoft Quincy WA expansion</td>
<td style="text-align: left;">Microsoft / own use</td>
<td style="text-align: left;">Quincy, Malaga, East Wenatchee, WA (Grant PUD / Chelan PUD / WECC)</td>
<td style="text-align: right;">622 MW existing; further expansion permitted Jan 2026</td>
<td style="text-align: left;">Continuous build-out</td>
<td style="text-align: left;">Grand Coulee hydro via Grant PUD; new closed-loop cooling</td>
<td style="text-align: left;"><a href="https://www.opb.org/article/2026/01/17/quincy-washington-microsoft-data-center/">OPB</a>; <a href="https://www.datacenterdynamics.com/en/analysis/inside-microsofts-quincy-data-center/">DCD</a></td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: left;">Crane Clean Energy Center (TMI Unit 1)</td>
<td style="text-align: left;">Constellation / Microsoft (PPA)</td>
<td style="text-align: left;">Londonderry Twp, PA (PJM / PPL)</td>
<td style="text-align: right;">835 MW reactor restart (entirely PPA-dedicated to MS data centres)</td>
<td style="text-align: left;">Restart targeted 2027</td>
<td style="text-align: left;">Restarted nuclear (PPA, 20-yr)</td>
<td style="text-align: left;"><a href="https://www.constellationenergy.com/newsroom/2025/09/one-year-later-crane-clean-energy-center-still-in-the-spotlight-and-ahead-of-schedule.html">Constellation</a>; <a href="https://www.world-nuclear-news.org/articles/constellation-seeks-regulators-help-for-2027-plant-restart">World Nuclear News</a></td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: left;">Duane Arnold restart</td>
<td style="text-align: left;">NextEra / Google (PPA)</td>
<td style="text-align: left;">Palo, IA (MISO / Alliant)</td>
<td style="text-align: right;">600 MW reactor restart</td>
<td style="text-align: left;">Targeted Q1 2029</td>
<td style="text-align: left;">Restarted nuclear (Google PPA, 25-yr)</td>
<td style="text-align: left;"><a href="https://www.ans.org/news/article-7501/nextera-and-google-ink-a-deal-to-restart-duane-arnold/">ANS</a>; <a href="https://www.iowapublicradio.org/ipr-news/2026-04-29/what-restarting-the-duane-arnold-power-plant-tells-us-about-nuclear-energy-under-the-trump-administration">Iowa PR</a></td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: left;">Palisades restart</td>
<td style="text-align: left;">Holtec / unsigned offtake</td>
<td style="text-align: left;">Covert Twp, MI (MISO / Consumers)</td>
<td style="text-align: right;">800 MW PWR restart</td>
<td style="text-align: left;">Restart slipped from late 2025 to Q1/Q2 2026; SMR-300 twin units early 2030s</td>
<td style="text-align: left;">Restarted nuclear; SMR phase under licensing</td>
<td style="text-align: left;"><a href="https://www.powermag.com/palisades-nuclear-plant-moved-to-operations-status-ready-to-receive-fuel/">Power Magazine</a>; <a href="https://neutronbytes.com/2026/01/11/holtec-submits-license-application-to-nrc-for-the-palisades-twin-smr-300s/">Neutron Bytes</a></td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: left;">QTS PW Digital Gateway</td>
<td style="text-align: left;">QTS (Blackstone)</td>
<td style="text-align: left;">Prince William County, VA (Dominion / PJM)</td>
<td style="text-align: right;">Up to 800 acres planned; rezoning blocked Mar 2026, appeal pending</td>
<td style="text-align: left;">Stalled by court ruling</td>
<td style="text-align: left;">Dominion (PJM)</td>
<td style="text-align: left;"><a href="https://www.bisnow.com/washington-dc/news/data-center-development/blackstones-qts-appeals-court-decision-blocking-huge-virginia-project-134390">Bisnow</a></td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: left;">Equinix Loudoun expansion (LD-15-class)</td>
<td style="text-align: left;">Equinix / colocation</td>
<td style="text-align: left;">Ashburn, VA (Dominion / PJM)</td>
<td style="text-align: right;">1.1 M sqft, 6 new buildings filed late 2025</td>
<td style="text-align: left;">Permitting / early site works</td>
<td style="text-align: left;">Dominion grid</td>
<td style="text-align: left;"><a href="http://www.virginiabusiness.com/news/article/equinix-wants-to-build-another-large-data-center-in-loudoun-county">Virginia Business</a></td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: left;">EdgeConneX New Albany OH</td>
<td style="text-align: left;">EdgeConneX / hyperscaler tenant</td>
<td style="text-align: left;">New Albany, OH (AEP Ohio / PJM)</td>
<td style="text-align: right;">700,000 sqft, MW undisclosed (likely 100–250 MW)</td>
<td style="text-align: left;">Construction Q4 2025; live Q1 2026</td>
<td style="text-align: left;">AEP Ohio grid</td>
<td style="text-align: left;"><a href="https://www.datacenterdynamics.com/en/news/edgeconnex-files-to-convert-warehouse-and-build-new-700000-sq-ft-data-center-in-new-albany-ohio/">DCD</a></td>
</tr>
</tbody>
</table>
<p><em>Notes: “UC capacity” is what is currently under construction (i.e.&nbsp;shell or fit-out in progress as of May 2026), not the full multi-decade campus envelope. Several projects (Hyperion, Project Rainier, Mt Pleasant, Quincy) sit on land approved for far larger build-outs that should not be conflated with what is being built today.</em></p>
<section id="items-i-could-not-verify-as-physically-under-construction-in-may-2026" class="level3">
<h3 class="anchored" data-anchor-id="items-i-could-not-verify-as-physically-under-construction-in-may-2026">Items I could not verify as physically under construction in May 2026</h3>
<ul>
<li><strong>Crusoe Project Jade (southeast Wyoming)</strong> — county approval and 2.7 GW gas plant approved January 2026; first buildings expected 2027. Listed by Crusoe and Tallgrass as advancing but no public evidence of vertical construction yet [Source: https://www.datacenterdynamics.com/en/news/crusoe-gets-go-ahead-for-18gw-data-center-campus-and-power-plant-in-cheyenne-wyoming/].</li>
<li><strong>Sailfish Comanche Circle (Hood County, TX)</strong> — 5 GW master-planned; first 600 MW behind-the-meter envisaged in 24 months but ground-up status not confirmed in public reporting [Source: https://www.datacenterdynamics.com/en/news/sailfish-plans-multi-gigawatt-data-center-park-outside-dfw-texas/].</li>
<li><strong>Anthropic-Fluidstack (Mitchell County TX, Niagara County NY, southeast LA, Haskell County TX)</strong> — announced Nov 2025; sites coming online “throughout 2026” but only some are confirmed as under construction. Google’s $5 bn financing of a Texas Anthropic site (Nexus operator) was reported in late March 2026 [Source: https://www.cnbc.com/2025/11/12/anthropic-ai-data-centers-texas-new-york.html; https://www.anthropic.com/news/anthropic-invests-50-billion-in-american-ai-infrastructure].</li>
<li><strong>Stargate Lordstown OH</strong> — SoftBank claims groundbreaking but DCD/Epoch reporting indicates land clearance only, not data centre construction [Source: https://epoch.ai/blog/openai-stargate-where-the-us-sites-stand].</li>
<li><strong>Meta-Oklo Pike County OH (1.2 GW SMR campus)</strong> — first reactors not expected until 2030; classify as planned [Source: https://carboncredits.com/meta-signs-three-nuclear-deals-of-up-to-6-6-gw-to-fuel-ai-data-center-growth/].</li>
</ul>
</section>
</section>
<section id="geographic-and-utility-concentration" class="level2">
<h2 class="anchored" data-anchor-id="geographic-and-utility-concentration">Geographic and utility concentration</h2>
<p><strong>Top markets by under-construction MW (combining trackers, May 2026):</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 46%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: right;">UC capacity (MW)</th>
<th style="text-align: left;">Primary utility / ISO</th>
<th style="text-align: left;">Stress notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Northern Virginia (Loudoun + PW)</td>
<td style="text-align: right;">~6,300</td>
<td style="text-align: left;">Dominion / PJM</td>
<td style="text-align: left;">PJM Dominion zone forecast +20 GW data centre load by 2037 [Source: PJM 2025 LTLF]; capacity auction cleared $14.7 bn for 2025-26, ~63% attributed to data centre demand [Source: IEEFA]</td>
</tr>
<tr class="even">
<td style="text-align: left;">West Texas (Abilene, Shackelford, Milam)</td>
<td style="text-align: right;">~2,900–3,500</td>
<td style="text-align: left;">Oncor / ERCOT</td>
<td style="text-align: left;">ERCOT large-load queue 233 GW, +269% YoY; ~77% data centre [Source: https://www.utilitydive.com/news/ercots-large-load-queue-jumped-almost-300-last-year-official/808820/]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Central Texas / DFW</td>
<td style="text-align: right;">~1,000–1,500 colo + Sailfish/PowerHouse adds</td>
<td style="text-align: left;">Oncor / ERCOT</td>
<td style="text-align: left;">Same large-load queue dynamics; gas turbine supply-chain backlog</td>
</tr>
<tr class="even">
<td style="text-align: left;">Atlanta / Georgia</td>
<td style="text-align: right;">~2,076 (CBRE)</td>
<td style="text-align: left;">Georgia Power / SERC</td>
<td style="text-align: left;">Georgia Power asking for 9 GW more capacity; Vogtle 3/4 already commissioned</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Phoenix</td>
<td style="text-align: right;">~1,000–1,500</td>
<td style="text-align: left;">APS / SRP / WECC</td>
<td style="text-align: left;">Water and transmission constraints</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hillsboro / Portland</td>
<td style="text-align: right;">~600</td>
<td style="text-align: left;">PGE / Bonneville / WECC</td>
<td style="text-align: left;">Constrained by Bonneville interconnection queue</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chicago / NW Indiana</td>
<td style="text-align: right;">~1,500 (incl.&nbsp;Project Rainier)</td>
<td style="text-align: left;">AEP / NIPSCO / Commonwealth Edison / MISO/PJM</td>
<td style="text-align: left;">Indiana load growth pushing AEP/I&amp;M into emergency capacity contracts</td>
</tr>
<tr class="even">
<td style="text-align: left;">Louisiana (Richland Parish + DeSoto Parish)</td>
<td style="text-align: right;">~2,000 (Hyperion phase 1)</td>
<td style="text-align: left;">Entergy / MISO South</td>
<td style="text-align: left;">Entergy data-centre customer pipeline 7–12 GW; PSC approved 2.3 GW new gas</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wisconsin (Mt Pleasant + Port Washington)</td>
<td style="text-align: right;">~2,500–3,000</td>
<td style="text-align: left;">We Energies / MISO</td>
<td style="text-align: left;">Microsoft + Vantage stacking on adjacent counties</td>
</tr>
<tr class="even">
<td style="text-align: left;">Memphis MSA</td>
<td style="text-align: right;">~750–1,200 (xAI)</td>
<td style="text-align: left;">TVA / MLGW + on-site</td>
<td style="text-align: left;">Air-quality and unpermitted-turbine litigation (Earthjustice/SELC)</td>
</tr>
</tbody>
</table>
<p><strong>Headline grid-stress takeaway.</strong> PJM (Dominion zone), ERCOT (Oncor west Texas), MISO (Entergy Louisiana, Indiana, Wisconsin) and the Georgia Power service area are the four most acute concentrations. PJM’s 2025 Long-Term Load Forecast attributes 94% of the projected 32 GW of incremental peak load from 2024-2030 to data centres [Source: https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/2025-load-report.pdf]. ERCOT begins 2026 with 233 GW in its large-load interconnection queue, of which ~77% (~180 GW) is data centre [Source: https://www.utilitydive.com/news/ercots-large-load-queue-jumped-almost-300-last-year-official/808820/]. MISO utilities collectively forecast 61 GW of new demand, more than half of MISO’s 2025 peak [Source: https://southernrenewable.org/news-updates/what-miso-souths-grid-markets-transmission-buildout-mean-for-ersc-in-2026].</p>
</section>
<section id="notable-behind-the-meter-off-grid-power-deals" class="level2">
<h2 class="anchored" data-anchor-id="notable-behind-the-meter-off-grid-power-deals">Notable behind-the-meter / off-grid power deals</h2>
<p>A pronounced shift in 2025-26 is the move to <strong>on-site / behind-the-meter generation</strong> to escape multi-year interconnection queues:</p>
<ul>
<li><strong>Vantage Frontier (Shackelford TX)</strong>: 700 MW Voltagrid natural-gas microgrid, off-grid initially [Source: https://www.constructionowners.com/news/oracle-and-openai-to-power-new-texas-data-center-off-the-grid].</li>
<li><strong>xAI Colossus 1+2 (Memphis/Southaven)</strong>: 18+ on-site gas turbines (~495 MW) operational; 41 more permitted in Mississippi; Earthjustice/SELC filed suit over unpermitted air emissions [Source: https://earthjustice.org/case/xai-illegal-gas-power-plant-data-center-colossus].</li>
<li><strong>Meta El Paso</strong>: 813 modular Caterpillar/Cummins-class gensets totalling 366 MW on-site [Source: https://www.texastribune.org/2026/01/26/texas-el-paso-meta-data-center-natural-gas-power-plant/].</li>
<li><strong>Project Jupiter (Doña Ana NM)</strong>: Bloom Energy solid-oxide fuel cells (April 2026 redesign replacing original gas turbines) [Source: https://sourcenm.com/2026/04/27/nm-project-jupiter-data-center-developers-announce-new-plans-for-generating-power/].</li>
<li><strong>Crusoe Abilene</strong>: hybrid on-site gas + Oncor grid + local wind [Source: https://www.datacenterdynamics.com/en/news/crusoe-tops-out-final-building-at-openai-stargate-data-center-campus-in-abilene-texas/].</li>
<li><strong>Crusoe-Tallgrass Cheyenne (Project Jade)</strong>: 2.7 GW dedicated gas plant approved Jan 2026 (planned, not yet built) [Source: https://www.powermag.com/wyoming-approves-data-center-campus-that-includes-2-7-gw-of-new-natural-gas-fired-generation/].</li>
</ul>
</section>
<section id="notable-nuclear-ppa-deals-most-are-restarts-or-new-build-not-under-physical-construction-at-the-data-centre-level" class="level2">
<h2 class="anchored" data-anchor-id="notable-nuclear-ppa-deals-most-are-restarts-or-new-build-not-under-physical-construction-at-the-data-centre-level">Notable nuclear-PPA deals (most are restarts or new-build, not under physical construction at the data centre level)</h2>
<ul>
<li><strong>Crane Clean Energy Center / Three Mile Island Unit 1</strong> — Constellation / Microsoft 20-yr PPA, restart targeted 2027 (accelerated from 2028); 835 MW [Source: https://www.constellationenergy.com/newsroom/2025/09/one-year-later-crane-clean-energy-center-still-in-the-spotlight-and-ahead-of-schedule.html].</li>
<li><strong>Susquehanna / Cumulus</strong> — Amazon/Talen 1,920 MW PPA through 2042; transitions to front-of-meter Spring 2026 [Source: https://www.utilitydive.com/news/talen-amazon-aws-susquehanna-nuclear-data-centert/750440/].</li>
<li><strong>Duane Arnold</strong> — Google / NextEra 25-yr PPA; restart Q1 2029; 600 MW [Source: https://www.ans.org/news/2025-10-28/article-7501/nextera-and-google-ink-a-deal-to-restart-duane-arnold/].</li>
<li><strong>Palisades</strong> — Holtec restart slipped to Q1/Q2 2026; no signed data centre offtake confirmed publicly. Twin SMR-300 application filed Jan 2026, in service early 2030s [Source: https://neutronbytes.com/2026/01/11/holtec-submits-license-application-to-nrc-for-the-palisades-twin-smr-300s/].</li>
<li><strong>Energy Northwest / X-energy / Amazon</strong> — 320 MW Phase 1 (option to 960 MW), in service late 2030s [Source: https://www.aboutamazon.com/news/sustainability/amazon-nuclear-small-modular-reactor-net-carbon-zero].</li>
<li><strong>Meta-Oklo Pike County, OH</strong> — 1.2 GW (16 × 75 MW Aurora units), Phase 1 150 MW by 2030 [Source: https://carboncredits.com/meta-signs-three-nuclear-deals-of-up-to-6-6-gw-to-fuel-ai-data-center-growth/].</li>
</ul>
<p><strong>Important interpretive caveat:</strong> none of the SMR or restart projects above are themselves “under construction” in the conventional sense, except for Palisades (refurbishment) and the Crane Clean Energy Center (refurbishment + grid reconfiguration). The SMR pipeline is at licensing/early-engineering stage; first commercial NRC SMR construction permits are expected in calendar 2026 [Source: https://www.eia.gov/todayinenergy/detail.php?id=67584].</p>
</section>
<section id="reconciliation-summary-and-confidence-ranking" class="level2">
<h2 class="anchored" data-anchor-id="reconciliation-summary-and-confidence-ranking">Reconciliation summary and confidence ranking</h2>
<ol type="1">
<li><strong>Highest confidence</strong> (verifiably steel/concrete in ground in May 2026): Stargate Abilene, Project Rainier, Hyperion, Microsoft Mt Pleasant phase 1, Microsoft Palmetto, xAI Colossus 1, Microsoft Quincy expansion, Frontier (Shackelford) site preparation, Crane CEC restart works, Susquehanna transmission reconfiguration, EdgeConneX New Albany, Equinix Ashburn (existing buildings).</li>
<li><strong>Medium confidence</strong> (announced ground-breaking, partial verification): Stargate Saline Township, Stargate Doña Ana (foundation work confirmed Mar 2026), Stargate Milam County (steel framing per March 2026 satellite imagery), Meta El Paso, xAI Colossus 2 third building, Vantage Frontier vertical construction.</li>
<li><strong>Lower confidence — early stage / pre-construction</strong>: Crusoe Project Jade Wyoming, Sailfish Comanche Circle, Anthropic-Fluidstack sites beyond first lease, Stargate Lordstown OH, QTS PW Digital Gateway (court-blocked), Meta-Oklo Pike County (planning).</li>
</ol>
<p>The <strong>best central estimate</strong> for US data centre IT/critical load physically under construction in May 2026 is <strong>22–26 GW</strong>, spread across approximately 35–50 individual campuses, of which <strong>at least 10 individual sites are 1 GW or larger</strong> (consistent with JLL’s count of “more than 10 ≥1 GW projects under construction”). Roughly <strong>89–92% is pre-committed</strong> (preleased or owner-occupied), so this is a supply pipeline aimed at known customers, not speculative capacity.</p>
</section>
<section id="bibliography" class="level2">
<h2 class="anchored" data-anchor-id="bibliography">Bibliography</h2>
<section id="tier-1-government-iso-regulator-filings" class="level3">
<h3 class="anchored" data-anchor-id="tier-1-government-iso-regulator-filings">Tier 1 — Government, ISO, regulator filings</h3>
<ul>
<li>PJM Interconnection. (2025). <em>2025 Long-Term Load Forecast Report</em>. https://www.pjm.com/-/media/DotCom/library/reports-notices/load-forecast/2025-load-report.pdf</li>
<li>PJM Inside Lines. (2025). <em>2025 Long-Term Load Forecast Report Predicts Significant Increase in Electricity Demand</em>. https://insidelines.pjm.com/2025-long-term-load-forecast-report-predicts-significant-increase-in-electricity-demand/</li>
<li>ERCOT. (2026, April). <em>Public ERCOT Update — Senate Committee on Business &amp; Commerce</em>. https://www.ercot.com/files/docs/2026/04/01/ERCOT_LargeLoad_Update_April2026_B-C_-Hearing.pdf</li>
<li>ERCOT. (2026, April 15). <em>ERCOT Releases Preliminary Long-Term Load Forecast for Years 2026-2032</em>. https://www.ercot.com/news/release/04152026-ercot-releases-preliminary</li>
<li>US EIA. (2025). <em>Small modular reactors and microreactors under development in the United States</em>. https://www.eia.gov/todayinenergy/detail.php?id=67584</li>
<li>US EIA. (2025). <em>We expect rapid electricity demand growth in Texas and the mid-Atlantic</em>. https://www.eia.gov/todayinenergy/detail.php?id=65844</li>
<li>Virginia JLARC. (2024, December). <em>Virginia Data Center Study</em>. https://jlarc.virginia.gov/pdfs/presentations/JLARC%20Virginia%20Data%20Center%20Study_FINAL_12-09-2024.pdf</li>
<li>Grid Strategies LLC. (2025). <em>Power Demand Forecasts Revised Up for Third Year Running</em>. https://gridstrategiesllc.com/wp-content/uploads/Grid-Strategies-National-Load-Growth-Report-2025.pdf</li>
</ul>
</section>
<section id="tier-2-real-estate-industry-trackers" class="level3">
<h3 class="anchored" data-anchor-id="tier-2-real-estate-industry-trackers">Tier 2 — Real-estate / industry trackers</h3>
<ul>
<li>CBRE. (2026, February 25). <em>North America Data Center Trends H2 2025</em>. https://www.cbre.com/insights/books/north-america-data-center-trends-h2-2025</li>
<li>CBRE. (2025, October). <em>North America Data Center Trends H1 2025</em>. https://www.cbre.com/insights/reports/north-america-data-center-trends-h1-2025</li>
<li>Cushman &amp; Wakefield. (2026, February). <em>Americas Data Center Market Shifts to “Managed Growth” — H2 2025 Update</em>. https://www.cushmanwakefield.com/en/united-states/news/2026/02/americas-data-center-market-shifts-to-managed-growth</li>
<li>Cushman &amp; Wakefield. (2026). <em>Americas Data Center Update H2 2025</em>. https://www.cushmanwakefield.com/en/insights/americas-data-center-update</li>
<li>JLL. (2026, January). <em>2026 Global Data Center Outlook</em>. https://www.jll.com/en-us/insights/market-outlook/data-center-outlook</li>
<li>JLL. (2026). <em>North America Data Center Report Year-end 2025: Texas prepares to dethrone Virginia</em>. https://www.jll.com/en-us/newsroom/jll-north-america-data-center-report-year-end-2025</li>
<li>Newmark. (2025, February). <em>2025 U.S. Data Center Market Outlook</em>. https://www.nmrk.com/insights/market-report/2025-us-data-center-market-outlook</li>
<li>Synergy Research Group. (2025). <em>Hyperscale Data Center Count Hits 1,136</em>. https://www.srgresearch.com/articles/hyperscale-data-center-count-hits-1136-average-size-increases-us-accounts-for-54-of-total-capacity</li>
<li>Synergy Research Group. (2026). <em>Hyperscale Operators to Account for 67% of all Data Center Capacity by 2031</em>. https://www.srgresearch.com/articles/hyperscale-operators-to-account-for-67-of-all-data-center-capacity-by-2031</li>
<li>DC Byte. (2025). <em>2025 Global Data Centre Index</em>. https://www.dcbyte.com/global-data-centre-index/2025-global-data-centre-index/</li>
<li>DC Byte. (2026). <em>2026 Data Centre Outlook: The Top Five Trends</em>. https://www.dcbyte.com/news-blogs/2026-data-centre-outlook-top-five-trends/</li>
<li>datacenterHawk. (2025). <em>3Q 2025 Data Center Market Recap</em>. https://datacenterhawk.com/resources/market-insights/3q-2025-data-center-market-recap</li>
<li>datacenterHawk. (2026). <em>Behind-the-Meter Power Solutions: The Data Center Industry’s New Reality</em>. https://datacenterhawk.com/resources/market-insights/behind-the-meter-power-solutions-the-data-center-industry-s-new-reality</li>
<li>Avison Young. (2025). <em>US Data Center Update Q2 2025</em>. https://www.avisonyoung.us/documents/d/us/q2-2025-us-data-center-update</li>
<li>IEEFA. (2025). <em>Projected data center growth spurs PJM capacity prices by factor of 10</em>. https://ieefa.org/resources/projected-data-center-growth-spurs-pjm-capacity-prices-factor-10</li>
<li>Wood Mackenzie. (2026). <em>Reality bytes: the US data centre pipeline additions halved in Q4 2025</em>. https://www.woodmac.com/news/opinion/reality-bytes-the-us-data-centre-pipeline-additions-halved-in-q4-2025-compared-to-the-previous-quarter/</li>
</ul>
</section>
<section id="tier-3-project-level-reporting" class="level3">
<h3 class="anchored" data-anchor-id="tier-3-project-level-reporting">Tier 3 — Project-level reporting</h3>
<ul>
<li>Crusoe. (2025, September 30). <em>Crusoe announces flagship Abilene data center is live</em>. https://www.crusoe.ai/resources/newsroom/crusoe-announces-flagship-abilene-data-center-is-live</li>
<li>Data Center Dynamics. (2026). <em>Crusoe tops out final building at OpenAI Stargate data center campus in Abilene, Texas</em>. https://www.datacenterdynamics.com/en/news/crusoe-tops-out-final-building-at-openai-stargate-data-center-campus-in-abilene-texas/</li>
<li>CNBC. (2025, September 23). <em>OpenAI’s first data center in $500 billion Stargate project is open in Texas</em>. https://www.cnbc.com/2025/09/23/openai-first-data-center-in-500-billion-stargate-project-up-in-texas.html</li>
<li>Epoch AI. (2026, April 17). <em>OpenAI Stargate: where the US sites stand</em>. https://epoch.ai/blog/openai-stargate-where-the-us-sites-stand</li>
<li>OpenAI. (2025, September). <em>OpenAI, Oracle, and SoftBank expand Stargate with five new AI data center sites</em>. https://openai.com/index/five-new-stargate-sites/</li>
<li>Meta. (n.d.). <em>Richland Parish Data Center</em>. https://datacenters.atmeta.com/richland-parish-data-center/</li>
<li>Meta. (2025, October). <em>Hello, El Paso!</em>. https://datacenters.atmeta.com/2025/10/hello-el-paso/</li>
<li>Meta. (2025, December). <em>One Year In: Meta’s Richland Parish Data Center Supports Louisiana Economy With $875M In Contracts</em>. https://about.fb.com/news/2025/12/metas-richland-parish-data-center-supports-louisiana-economy-875-million-in-contracts/</li>
<li>Engineering News-Record. (2026). <em>$27B Meta Data Center Pushes Louisiana Toward Massive Power Expansion</em>. https://www.enr.com/articles/62766-27b-meta-data-center-pushes-louisiana-toward-massive-power-expansion</li>
<li>Data Center Dynamics. (2026). <em>Entergy obtains approval to construct three gas facilities to serve Meta’s 2GW data center in Louisiana</em>. https://www.datacenterdynamics.com/en/news/entergy-obtains-approval-to-construct-three-gas-facilities-to-serve-metas-2gw-data-center-in-louisiana/</li>
<li>Data Center Dynamics. (2026). <em>Entergy to build $1.2bn 500kV transmission line to serve Meta mega data center</em>. https://www.datacenterdynamics.com/en/news/entergy-to-build-12bn-500kv-transmission-line-to-serve-meta-mega-data-center-in-louisiana/</li>
<li>CNBC. (2025, October 29). <em>Amazon opens $11 billion AI data center Project Rainier in Indiana</em>. https://www.cnbc.com/2025/10/29/amazon-opens-11-billion-ai-data-center-project-rainier-in-indiana.html</li>
<li>Converge Digest. (2025). <em>AWS Activates Project Rainier Data Center Campus</em>. https://convergedigest.com/aws-activates-project-rainier-data-center-campus/</li>
<li>Utility Dive. (2024). <em>Talen to sell Amazon 1.9 GW from Susquehanna nuclear plant</em>. https://www.utilitydive.com/news/talen-amazon-aws-susquehanna-nuclear-data-centert/750440/</li>
<li>Talen Energy. (2025, June 11). <em>Talen Energy Expands Nuclear Energy Relationship with Amazon</em>. https://ir.talenenergy.com/news-releases/news-release-details/talen-energy-expands-nuclear-energy-relationship-amazon</li>
<li>World Nuclear News. (2025). <em>New supply agreement expands Talen-Amazon partnership</em>. https://www.world-nuclear-news.org/articles/new-supply-agreement-expands-talen-amazon-partnership</li>
<li>Constellation Energy. (2025, September). <em>One Year Later: Crane Clean Energy Center Still in the Spotlight and Ahead of Schedule</em>. https://www.constellationenergy.com/newsroom/2025/09/one-year-later-crane-clean-energy-center-still-in-the-spotlight-and-ahead-of-schedule.html</li>
<li>World Nuclear News. (2025). <em>Constellation seeks regulator’s help for 2027 plant restart</em>. https://www.world-nuclear-news.org/articles/constellation-seeks-regulators-help-for-2027-plant-restart</li>
<li>ANS. (2025, October 28). <em>NextEra and Google ink a deal to restart Duane Arnold</em>. https://www.ans.org/news/2025-10-28/article-7501/nextera-and-google-ink-a-deal-to-restart-duane-arnold/</li>
<li>Power Magazine. (2025). <em>Palisades Nuclear Plant Moved to Operations Status, Ready to Receive Fuel</em>. https://www.powermag.com/palisades-nuclear-plant-moved-to-operations-status-ready-to-receive-fuel/</li>
<li>Neutron Bytes. (2026, January 11). <em>Holtec Submits License Application to NRC for the Palisades Twin SMR-300s</em>. https://neutronbytes.com/2026/01/11/holtec-submits-license-application-to-nrc-for-the-palisades-twin-smr-300s/</li>
<li>SemiAnalysis. (2025). <em>xAI’s Colossus 2 — First Gigawatt Datacenter In The World</em>. https://newsletter.semianalysis.com/p/xais-colossus-2-first-gigawatt-datacenter</li>
<li>Data Center Dynamics. (2026). <em>Elon Musk’s xAI gets go-ahead for 41 natural gas turbines in Mississippi</em>. https://www.datacenterdynamics.com/en/news/musks-xai-gets-go-ahead-for-41-natural-gas-turbines-in-mississippi-to-power-colossus-data-centers/</li>
<li>Earthjustice. (2025). <em>Illegal Pollution from Data Center Power Plants Shouldn’t Harm Our Communities. We’re Suing xAI</em>. https://earthjustice.org/case/xai-illegal-gas-power-plant-data-center-colossus</li>
<li>SELC. (2025). <em>xAI built an illegal power plant to power its data center</em>. https://www.selc.org/news/xai-built-an-illegal-power-plant-to-power-its-data-center/</li>
<li>Data Center Dynamics. (2025). <em>Vantage breaks ground on Texas gigawatt data center campus for OpenAI</em>. https://www.datacenterdynamics.com/en/news/vantage-breaks-ground-on-texas-gigawatt-data-center-campus-for-openai/</li>
<li>Vantage Data Centers. (2025). <em>Vantage Data Centers Unveils Plans for “Frontier”</em>. https://vantage-dc.com/news/vantage-data-centers-unveils-plans-for-frontier-a-25b-mega-campus-in-texas-to-meet-unprecedented-ai-demand/</li>
<li>Construction Owners. (2025). <em>Oracle and OpenAI’s New Off-Grid Data Center in Texas to Run on 700MW Natural Gas Microgrid</em>. https://www.constructionowners.com/news/oracle-and-openai-to-power-new-texas-data-center-off-the-grid</li>
<li>Data Center Frontier. (2025). <em>Vantage Data Centers Pours $15B Into Wisconsin AI Campus</em>. https://www.datacenterfrontier.com/hyperscale/article/55326357/vantage-data-centers-pours-15b-into-wisconsin-ai-campus-as-it-builds-global-giga-scale-footprint</li>
<li>CNBC. (2026, January 26). <em>Microsoft’s plans for 15 more data centers win approval at former Wisconsin Foxconn site</em>. https://www.cnbc.com/2026/01/26/microsoft-wins-approval-for-15-data-centers-at-wisconsin-foxconn-site.html</li>
<li>Data Center Dynamics. (2026). <em>Microsoft given greenlight for 15 more data center buildings in Mount Pleasant, Wisconsin</em>. https://www.datacenterdynamics.com/en/news/microsoft-given-greenlight-for-15-more-data-center-buildings-in-mount-pleasant-wisconsin/</li>
<li>OPB. (2026, January 17). <em>A small town in Central Washington is Microsoft’s answer to the data center backlash</em>. https://www.opb.org/article/2026/01/17/quincy-washington-microsoft-data-center/</li>
<li>Data Center Frontier. (2025). <em>Details Emerge On Microsoft’s $1.8 Billion Investment In Atlanta Data Centers</em>. https://www.datacenterfrontier.com/hyperscale/article/55126626/details-emerge-on-microsofts-18-billion-investment-in-atlanta-data-centers-amid-tax-development-wrangles</li>
<li>Data Center Dynamics. (2026). <em>Sailfish plans multi-gigawatt data center park outside DFW, Texas</em>. https://www.datacenterdynamics.com/en/news/sailfish-plans-multi-gigawatt-data-center-park-outside-dfw-texas/</li>
<li>Data Center Dynamics. (2026). <em>Crusoe gets go-ahead for 1.8GW data center campus and power plant in Cheyenne, Wyoming</em>. https://www.datacenterdynamics.com/en/news/crusoe-gets-go-ahead-for-18gw-data-center-campus-and-power-plant-in-cheyenne-wyoming/</li>
<li>Power Magazine. (2026). <em>Wyoming Approves Data Center Campus That Includes 2.7 GW of New Natural Gas-Fired Generation</em>. https://www.powermag.com/wyoming-approves-data-center-campus-that-includes-2-7-gw-of-new-natural-gas-fired-generation/</li>
<li>Data Center Dynamics. (2025). <em>Stack joins multi-billion-dollar data center &amp; microgrid project in New Mexico</em>. https://www.datacenterdynamics.com/en/news/stack-joins-multi-billion-dollar-data-center-microgrid-project-in-new-mexico/</li>
<li>Source NM. (2026, April 27). <em>NM Project Jupiter data center developers announce new plans for generating power</em>. https://sourcenm.com/2026/04/27/nm-project-jupiter-data-center-developers-announce-new-plans-for-generating-power/</li>
<li>Anthropic. (2025, November 12). <em>Anthropic invests $50 billion in American AI infrastructure</em>. https://www.anthropic.com/news/anthropic-invests-50-billion-in-american-ai-infrastructure</li>
<li>CNBC. (2025, November 12). <em>Anthropic to spend $50 billion on U.S. AI infrastructure</em>. https://www.cnbc.com/2025/11/12/anthropic-ai-data-centers-texas-new-york.html</li>
<li>Texas Tribune. (2026, January 26). <em>Plan to run El Paso data center on natural gas sparks concern</em>. https://www.texastribune.org/2026/01/26/texas-el-paso-meta-data-center-natural-gas-power-plant/</li>
<li>Bisnow. (2025). <em>Blackstone’s QTS Files Appeal To Save Massive Virginia Data Center Campus</em>. https://www.bisnow.com/washington-dc/news/data-center-development/blackstones-qts-appeals-court-decision-blocking-huge-virginia-project-134390</li>
<li>Data Center Dynamics. (2026). <em>EdgeConneX files to convert warehouse and build new 700,000 sq ft data center in New Albany, Ohio</em>. https://www.datacenterdynamics.com/en/news/edgeconnex-files-to-convert-warehouse-and-build-new-700000-sq-ft-data-center-in-new-albany-ohio/</li>
<li>Utility Dive. (2026). <em>ERCOT’s large load queue jumped almost 300% last year</em>. https://www.utilitydive.com/news/ercots-large-load-queue-jumped-almost-300-last-year-official/808820/</li>
<li>Utility Dive. (2025). <em>Gas continues to dominate Entergy plans as data center pipeline grows</em>. https://www.utilitydive.com/news/gas-continues-to-dominate-entergy-plans-as-data-center-pipeline-grows/804521/</li>
<li>The Center Square. (2026). <em>Entergy seeks more big projects in 2026 as Louisiana load surges</em>. https://www.thecentersquare.com/louisiana/article_7675e48d-c161-49a6-9e42-0f18ed188cc6.html</li>
<li>Carbon Credits. (2026). <em>Meta Signs Three Nuclear Deals of Up to 6.6 GW to Fuel AI Data Center Growth</em>. https://carboncredits.com/meta-signs-three-nuclear-deals-of-up-to-6-6-gw-to-fuel-ai-data-center-growth/</li>
<li>Amazon. (2024). <em>Amazon signs agreements for innovative nuclear energy projects</em>. https://www.aboutamazon.com/news/sustainability/amazon-nuclear-small-modular-reactor-net-carbon-zero</li>
<li>Virginia Business. (2025). <em>Equinix wants to build another large data center in Loudoun County</em>. http://www.virginiabusiness.com/news/article/equinix-wants-to-build-another-large-data-center-in-loudoun-county</li>
<li>Fortune. (2026, May 6). <em>A Michigan farm town voted down plans for a giant OpenAI-Oracle data center. Weeks later, construction began</em>. https://fortune.com/2026/05/06/ai-data-center-michigan-saline-politics-farmland/</li>
<li>Related Companies. (2025, October 30). <em>OpenAI, Oracle and Related Digital announce Stargate data center site in Michigan</em>. https://www.related.com/press-releases/2025-10-30/openai-oracle-and-related-digital-announce-stargate-data-center-site</li>
<li>Microsoft Local. (n.d.). <em>Palmetto datacenter construction update</em>. https://local.microsoft.com/blog/palmetto-datacenter-construction-update/</li>
</ul>
</section>
<section id="limitations-and-caveats" class="level3">
<h3 class="anchored" data-anchor-id="limitations-and-caveats">Limitations and caveats</h3>
<ul>
<li>CBRE, Cushman &amp; Wakefield, JLL and Newmark publications are partly paywalled or aggregated; numerical extracts above are taken from publicly summarised press releases, secondary news coverage, and the publicly accessible chapter pages.</li>
<li>DC Byte and datacenterHawk full datasets are subscription-only; their headline figures here come from publicly issued summary reports and trade press citation.</li>
<li>Several “MW” figures for hyperscaler-owned campuses (xAI, Meta, AWS, Microsoft) are estimates from satellite imagery, county filings, generator permits and gas-turbine permits because the operators do not publish IT load directly.</li>
<li>For projects where construction was confirmed via single-source reporting, I have flagged “medium” or “low” confidence above; do not cite a single trade-press item as evidence of vertical construction without corroboration.</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>