<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ITK - Claude assisted Research">
<meta name="dcterms.date" content="2026-06-23">

<title>Energy Production of the Dunhuang–Turpan–Urumqi Corridor – ITK Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../ITK_logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-d96a739641c07e2640703e5ad7a4e5f4.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-86c03801c75847bd115b064e8b296803.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script defer="" data-domain="itkservices3.com" src="https://plausible.io/js/script.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function() {
  document.querySelectorAll('.navbar a[href^="https://"]').forEach(function(a) {
    a.setAttribute('target', '_blank');
    a.setAttribute('rel', 'noopener');
  });
});
</script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Energy Production of the Dunhuang–Turpan–Urumqi Corridor – ITK Research">
<meta property="og:description" content="Electricity markets analysis">
<meta property="og:site_name" content="ITK Research">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../ITK_logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ITK Research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dashboards-(load-slow" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Dashboards (load slow)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dashboards-(load-slow">    
        <li>
    <a class="dropdown-item" href="../IEA.html">
 <span class="dropdown-text">IEA-electricity</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://nemgen.itkservices2.com">
 <span class="dropdown-text">NEM-ITK ↗</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../forecast.html">
 <span class="dropdown-text">AEMO demand fcst</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../posts.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">more</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more">    
        <li>
    <a class="dropdown-item" href="../windy.html">
 <span class="dropdown-text">Temperature Forecast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../green_iron/index.html">
 <span class="dropdown-text">Green Iron</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentations.html">
 <span class="dropdown-text">Presentations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../background.html">
 <span class="dropdown-text">Background notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../energyinsiders.html">
 <span class="dropdown-text">Energy Insiders</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../posts.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../mailchimp.html"> 
<span class="menu-text">Signup</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#coal-mining" id="toc-coal-mining" class="nav-link" data-scroll-target="#coal-mining">Coal Mining</a>
  <ul class="collapse">
  <li><a href="#electric-and-autonomous-haul-trucks" id="toc-electric-and-autonomous-haul-trucks" class="nav-link" data-scroll-target="#electric-and-autonomous-haul-trucks">Electric and autonomous haul trucks</a></li>
  </ul></li>
  <li><a href="#oil" id="toc-oil" class="nav-link" data-scroll-target="#oil">Oil</a></li>
  <li><a href="#natural-gas" id="toc-natural-gas" class="nav-link" data-scroll-target="#natural-gas">Natural Gas</a></li>
  <li><a href="#electricity-coal-fired-generation" id="toc-electricity-coal-fired-generation" class="nav-link" data-scroll-target="#electricity-coal-fired-generation">Electricity: Coal-Fired Generation</a></li>
  <li><a href="#wind" id="toc-wind" class="nav-link" data-scroll-target="#wind">Wind</a></li>
  <li><a href="#solar-pv" id="toc-solar-pv" class="nav-link" data-scroll-target="#solar-pv">Solar PV</a></li>
  <li><a href="#concentrating-solar-power-csp" id="toc-concentrating-solar-power-csp" class="nav-link" data-scroll-target="#concentrating-solar-power-csp">Concentrating Solar Power (CSP)</a></li>
  <li><a href="#transmission-and-transmission-capacity" id="toc-transmission-and-transmission-capacity" class="nav-link" data-scroll-target="#transmission-and-transmission-capacity">Transmission and Transmission Capacity</a>
  <ul class="collapse">
  <li><a href="#major-uhv-lines" id="toc-major-uhv-lines" class="nav-link" data-scroll-target="#major-uhv-lines">Major UHV lines</a></li>
  <li><a href="#outbound-capacity-and-exported-energy" id="toc-outbound-capacity-and-exported-energy" class="nav-link" data-scroll-target="#outbound-capacity-and-exported-energy">Outbound capacity and exported energy</a></li>
  <li><a href="#intra-regional-grid" id="toc-intra-regional-grid" class="nav-link" data-scroll-target="#intra-regional-grid">Intra-regional grid</a></li>
  <li><a href="#transmission-as-the-binding-constraint" id="toc-transmission-as-the-binding-constraint" class="nav-link" data-scroll-target="#transmission-as-the-binding-constraint">Transmission as the binding constraint</a></li>
  </ul></li>
  <li><a href="#synthesis" id="toc-synthesis" class="nav-link" data-scroll-target="#synthesis">Synthesis</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Energy Production of the Dunhuang–Turpan–Urumqi Corridor</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Global</div>
    <div class="quarto-category">Generation</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>ITK - Claude assisted Research </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 23, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="summary" class="level1">
<h1>Summary</h1>
<p>The Dunhuang–Turpan–Urumqi corridor straddles two provinces. <strong>Dunhuang</strong> sits in the Hexi Corridor of far-western <strong>Gansu</strong>; <strong>Turpan, Hami (Kumul) and Urumqi</strong> lie in eastern and central <strong>Xinjiang</strong>. Together this stretch of land leads China in coal reserves, leads in oil-and-gas output, and adds wind and solar capacity faster than any other province. It is the western anchor of the ultra-high-voltage (UHV) lines that carry electricity 2,000–3,300 km to the eastern seaboard.</p>
<p>One mechanism runs through every sub-sector below. Because the region lies ~3,000 km from China’s demand centres, the strategy is to convert primary energy to electricity locally and move the electrons east (“coal-by-wire”, renewable mega-bases feeding UHV lines) rather than rail coal and pipe gas the full distance.</p>
<p><strong>Table 1: Energy production of the corridor at a glance (2024 unless noted)</strong></p>
<table class="table">
<colgroup>
<col style="width: 17%">
<col style="width: 24%">
<col style="width: 30%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Sub-sector</th>
<th style="text-align: left;">Headline figure</th>
<th style="text-align: left;">Key assets / region</th>
<th style="text-align: left;">National position</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Coal mining</td>
<td style="text-align: left;">540 Mt, +17.5% y/y</td>
<td style="text-align: left;">Zhundong, Hami, Turpan open-pits</td>
<td style="text-align: left;">~11% of national output; largest reserves</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oil</td>
<td style="text-align: left;">~33 Mt crude (66.6 Mt oil+gas equiv.)</td>
<td style="text-align: left;">Karamay/Junggar, Tarim, Tuha</td>
<td style="text-align: left;">Top oil-and-gas province, 4 years running</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Natural gas</td>
<td style="text-align: left;">~42 bcm</td>
<td style="text-align: left;">Tarim Basin; West–East Pipeline</td>
<td style="text-align: left;">Largest gas province (~17% of output)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Coal-fired power</td>
<td style="text-align: left;">~90 GW thermal (est.)</td>
<td style="text-align: left;">Mine-mouth Zhundong, Hami, Changji</td>
<td style="text-align: left;">Leads China in new-coal approvals</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wind</td>
<td style="text-align: left;">~30 GW (Xinjiang, end-2025)</td>
<td style="text-align: left;">Dabancheng, Hami, Jiuquan/Guazhou</td>
<td style="text-align: left;">2nd-largest wind resource nationally</td>
</tr>
<tr class="even">
<td style="text-align: left;">Solar PV</td>
<td style="text-align: left;">56.7 GW (Xinjiang, end-2024)</td>
<td style="text-align: left;">Midong 3.5 GW, Ruoqiang 4 GW</td>
<td style="text-align: left;">1st for new additions in 2024</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Concentrating solar (CSP)</td>
<td style="text-align: left;">~450 MW operating (Xinjiang) + 621 MW (Gansu)</td>
<td style="text-align: left;">Dunhuang &amp; Hami molten-salt towers</td>
<td style="text-align: left;">China’s largest CSP cluster</td>
</tr>
<tr class="even">
<td style="text-align: left;">Transmission</td>
<td style="text-align: left;">~33 GW outbound capacity</td>
<td style="text-align: left;">Four UHV DC channels</td>
<td style="text-align: left;">126 TWh exported in 2024</td>
</tr>
</tbody>
</table>
<p><em>Source: Author compilation from sources cited in the relevant sections below. Figures are rounded; “Mt” = million tonnes, “bcm” = billion cubic metres, “GW” = gigawatts, “TWh” = terawatt-hours.</em></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Units and conventions
</div>
</div>
<div class="callout-body-container callout-body">
<p>Oil-and-gas output is reported by Chinese operators as a blended “equivalent” (oil tonnes plus gas converted to tonnes), so pure-crude splits are approximate. Several 2025–26 figures are forward-looking and flagged where the underlying source is a forecast or a single secondary report.</p>
</div>
</div>
<hr>
</section>
<section id="coal-mining" class="level1">
<h1>Coal Mining</h1>
<p>Xinjiang holds China’s largest coal endowment. Estimated resources are put at ~2.19 trillion tonnes (about 41% of the national total, first nationally) and proven reserves at ~450 billion tonnes, second only to Inner Mongolia <span class="citation" data-cites="chinadaily-xinjiang-coal-2023">(<a href="#ref-chinadaily-xinjiang-coal-2023" role="doc-biblioref">China Daily, 2023</a>)</span>. The bulk sits along this corridor. The largest single deposit is the <strong>Zhundong (Junggar Basin) coalfield</strong>, with reserves cited at over 300 billion tonnes <span class="citation" data-cites="seetao-zhundong-2025">(<a href="#ref-seetao-zhundong-2025" role="doc-biblioref">Seetao, 2025</a>)</span>; other major fields lie at <strong>Hami/Kumul</strong>, <strong>Turpan–Shanshan</strong>, and the <strong>Sha’er Lake</strong> deposit, an 89.2-billion-tonne reserve described as Asia’s largest of its kind <span class="citation" data-cites="smm-shaerhu-coal">(<a href="#ref-smm-shaerhu-coal" role="doc-biblioref">Shanghai Metals Market, 2024</a>)</span>.</p>
<p>Production is growing faster here than anywhere else in China. Xinjiang output reached <strong>540 Mt in 2024, up 17.5% year-on-year</strong> — the largest increment and fastest growth rate of any province — lifting its national share from ~7% in 2020 to ~11% <span class="citation" data-cites="xinhua-xinjiang-coal-2024">(<a href="#ref-xinhua-xinjiang-coal-2024" role="doc-biblioref">Xinhua, 2024</a>)</span>. New open-pit capacity continues to come online, such as the Yankuang Qineng No.&nbsp;4 open-pit in Zhundong (23 Mt/yr design capacity), in trial operation from July 2025 <span class="citation" data-cites="seetao-zhundong-2025">(<a href="#ref-seetao-zhundong-2025" role="doc-biblioref">Seetao, 2025</a>)</span>.</p>
<p>Operators include CHN Energy (Shenhua group), which runs the Zhundong open-pit and in October 2024 launched a ¥170-billion coal-to-liquids and clean-coal base at Hami anchored by the Chahaquan No.&nbsp;1 open-pit <span class="citation" data-cites="chinadaily-chnenergy-base-2024">(<a href="#ref-chinadaily-chnenergy-base-2024" role="doc-biblioref">China Daily, 2024a</a>)</span>; Xinjiang Energy Group; and Yankuang/Shandong Energy. The outbound rail artery is the Lanzhou–Xinjiang railway plus newer Hami lines, but the ~3,000 km distance to eastern markets makes rail costly, so the region increasingly exports electricity rather than coal (see Transmission) <span class="citation" data-cites="yicai-xinjiang-rail-coal scmp-xinjiang-railway-2022">(<a href="#ref-scmp-xinjiang-railway-2022" role="doc-biblioref">South China Morning Post, 2022</a>; <a href="#ref-yicai-xinjiang-rail-coal" role="doc-biblioref">Yicai Global, 2024a</a>)</span>.</p>
<section id="electric-and-autonomous-haul-trucks" class="level2">
<h2 class="anchored" data-anchor-id="electric-and-autonomous-haul-trucks">Electric and autonomous haul trucks</h2>
<p>The corridor’s open-pits run some of the world’s largest battery-electric, driverless haul fleets:</p>
<ul>
<li><strong>Zhundong open-pit (CHN Energy):</strong> 120 Tonly TLE138 battery-electric wide-body trucks (90 t payload) on EACON’s ORCASTRA autonomy system — among the world’s largest single-site battery-electric haulage fleets, with over 7 million km logged <span class="citation" data-cites="im-mining-eacon-2026">(<a href="#ref-im-mining-eacon-2026" role="doc-biblioref">International Mining, 2026b</a>)</span>.</li>
<li><strong>Zhundong (separate fleet):</strong> Boonray ~145 t-class autonomous trucks set a record of 200 battery swaps in a single day; BYD invested over US$14.4 million in Boonray in January 2026 <span class="citation" data-cites="im-mining-boonray-2026">(<a href="#ref-im-mining-boonray-2026" role="doc-biblioref">International Mining, 2026a</a>)</span>.</li>
<li><strong>Shitoumei No.&nbsp;1, Hami (Santanghu Energy):</strong> 91 domestically built autonomous trucks (70–100 t each) reached full unmanned operation by May 2025 using BeiDou positioning and 5G, cutting the haulage workforce from about 200 to 2 supervisors <span class="citation" data-cites="globaltimes-trucks-2025">(<a href="#ref-globaltimes-trucks-2025" role="doc-biblioref">Global Times, 2025a</a>)</span>.</li>
</ul>
<p>For context, the same manufacturers (XCMG, Tonly, Boonray, Waytous/EACON) are scaling these fleets across China’s western coal bases — XCMG delivered 100 cabless all-electric ZNK95 autonomous trucks to the Huaneng Yimin pit in Inner Mongolia in May 2025 <span class="citation" data-cites="electrive-xcmg-2025">(<a href="#ref-electrive-xcmg-2025" role="doc-biblioref">electrive, 2025</a>)</span>.</p>
<p>The Zhundong reserve magnitude varies between sources (a Wikipedia stub lists ~10 Bt against Chinese sources’ 300+ Bt), and the truck-fleet counts expand month to month; both are flagged as moving figures.</p>
<hr>
</section>
</section>
<section id="oil" class="level1">
<h1>Oil</h1>
<p>The corridor is the centre of China’s onshore oil frontier. Xinjiang has been China’s top oil-and-gas producing province for four consecutive years, reaching ~66.6 Mt of oil-and-gas equivalent in 2024, of which crude was about 33 Mt <span class="citation" data-cites="tianshannet-xinjiang-2025">(<a href="#ref-tianshannet-xinjiang-2025" role="doc-biblioref">Tianshannet, 2025</a>)</span>. Three basins anchor it:</p>
<ul>
<li><strong>Junggar Basin / Karamay</strong> (PetroChina Xinjiang Oilfield), north of the corridor — China’s first large oilfield (1955). The 2024 targets were ~14.8 Mt crude plus 4.5 bcm gas <span class="citation" data-cites="chinadaily-xinjiang-oilfield-2022">(<a href="#ref-chinadaily-xinjiang-oilfield-2022" role="doc-biblioref">China Daily, 2022b</a>)</span>. The Jimsar shale-oil zone, China’s first national shale-oil demonstration base, passed 1 Mt/yr in 2024 <span class="citation" data-cites="globaltimes-jimsar-2025">(<a href="#ref-globaltimes-jimsar-2025" role="doc-biblioref">Global Times, 2025c</a>)</span>.</li>
<li><strong>Turpan-Hami Basin / Tuha oilfield (吐哈)</strong> — sits under Turpan; mature and declining, about 1.58 Mt oil-and-gas equivalent in 2024 (crude 1.42 Mt plus 1.99 bcm gas) <span class="citation" data-cites="tianshannet-xinjiang-2025">(<a href="#ref-tianshannet-xinjiang-2025" role="doc-biblioref">Tianshannet, 2025</a>)</span>.</li>
<li><strong>Tarim Basin</strong> (PetroChina Tarim), to the south and west — China’s main ultra-deep base. Output exceeded ~33 Mt oil-and-gas equivalent in 2024, of which 20.5 Mt came from below 6,000 m (~37% of China’s ultra-deep output) <span class="citation" data-cites="cgtn-tarim-2025">(<a href="#ref-cgtn-tarim-2025" role="doc-biblioref">CGTN, 2025a</a>)</span>. The record well Shenditake-1 reached 10,910 m in February 2025, Asia’s deepest <span class="citation" data-cites="xinhua-deepest-well-2025">(<a href="#ref-xinhua-deepest-well-2025" role="doc-biblioref">Xinhua, 2025a</a>)</span>.</li>
</ul>
<p>Refining is concentrated in three PetroChina bases: Dushanzi (15 Mt/yr crude, 1.22 Mt/yr ethylene, expanding toward 3 Mt under a ~US$3 billion project), Karamay (6 Mt/yr, specialty naphthenic lubricants and asphalt), and Urumqi Petrochemical <span class="citation" data-cites="baike-dushanzi baike-karamay">(<a href="#ref-baike-dushanzi" role="doc-biblioref">Baidu Baike, 2024a</a>, <a href="#ref-baike-karamay" role="doc-biblioref">2024b</a>)</span>.</p>
<p>The Tarim total and Tuha figures rest on secondary Chinese compilations; CNPC’s own headline emphasises the 20.5 Mt Tarim ultra-deep number.</p>
<hr>
</section>
<section id="natural-gas" class="level1">
<h1>Natural Gas</h1>
<p>Xinjiang is China’s largest gas-producing province, with output of ~42 bcm in 2024 — about 17% of national production <span class="citation" data-cites="ceic-xinjiang-gas-2025 aa-china-gas-2025">(<a href="#ref-aa-china-gas-2025" role="doc-biblioref">Anadolu Agency, 2025</a>; <a href="#ref-ceic-xinjiang-gas-2025" role="doc-biblioref">CEIC, 2025</a>)</span>. The <strong>Tarim Basin</strong> is the anchor, sustaining more than 31 bcm/yr for six consecutive years and supplying a record 7.35 bcm to southern Xinjiang in 2024 <span class="citation" data-cites="xinhua-tarim-gas-2025">(<a href="#ref-xinhua-tarim-gas-2025" role="doc-biblioref">Xinhua, 2025b</a>)</span>. The Junggar and Tuha basins add tight and declining volumes.</p>
<p>The corridor is China’s gas-export artery via the <strong>West–East Gas Pipeline (西气东输)</strong>. Line 1 originates at the Lunnan field in the Tarim Basin (4,380 km to Shanghai); Lines 2–4 carry a blend of Tarim, Junggar and Tuha gas with Central Asian imports eastward. Tarim alone had cumulatively delivered over 366 bcm via this system by end-2024 <span class="citation" data-cites="xinhua-tarim-gas-2025 wikipedia-west-east">(<a href="#ref-wikipedia-west-east" role="doc-biblioref">Wikipedia, 2024b</a>; <a href="#ref-xinhua-tarim-gas-2025" role="doc-biblioref">Xinhua, 2025b</a>)</span>. The Hutubi underground gas storage near Urumqi is China’s largest, at 10.7 bcm design capacity <span class="citation" data-cites="chinadaily-hutubi-2022">(<a href="#ref-chinadaily-hutubi-2022" role="doc-biblioref">China Daily, 2022a</a>)</span>.</p>
<p>Xinjiang is also China’s coal-to-gas (SNG) hub, with about 10 projects (~40 bcm/yr planned) anchored by the 2 bcm/yr Zhundong plant <span class="citation" data-cites="seetao-coal-gas-2024">(<a href="#ref-seetao-coal-gas-2024" role="doc-biblioref">Seetao, 2024b</a>)</span>. The 42 bcm provincial total and the ~8.4 tcm Tarim resource figure could not be confirmed against a primary source; the 17% national share is derived.</p>
<hr>
</section>
<section id="electricity-coal-fired-generation" class="level1">
<h1>Electricity: Coal-Fired Generation</h1>
<p>Xinjiang remains one of China’s largest and fastest-growing coal-power frontiers. By mid-2025 the regional grid reached ~219 GW of installed capacity, ~60% of it renewable, implying roughly <strong>90 GW of thermal/coal capacity</strong> (a derived figure — official releases report total and renewable capacity, not coal alone) <span class="citation" data-cites="people-daily-grid-2025">(<a href="#ref-people-daily-grid-2025" role="doc-biblioref">People’s Daily, 2025</a>)</span>. Xinjiang has led China for new coal-plant approvals: the highest newly permitted coal capacity of any province at 11.65 GW across 2024 to Q3 2025 <span class="citation" data-cites="greenpeace-coal-2025">(<a href="#ref-greenpeace-coal-2025" role="doc-biblioref">Greenpeace East Asia, 2025</a>)</span>. National coal-plant construction starts hit a 10-year high of ~94.5 GW in 2024, with Xinjiang among the top builders <span class="citation" data-cites="carbonbrief-coal-2025">(<a href="#ref-carbonbrief-coal-2025" role="doc-biblioref">Carbon Brief, 2025</a>)</span>. Mine-mouth plants cluster at Zhundong, Hami and Changji/Urumqi.</p>
<p>The defining feature is <strong>coal-by-wire</strong> — exporting electricity rather than coal. Coal increasingly plays a firming and peak-shaping role behind the renewable build-out: the Hami–Chongqing base pairs a 4 GW (4×1,000 MW) ultra-supercritical coal plant with 10.2 GW of wind, solar and CSP <span class="citation" data-cites="cgtn-hami-chongqing-2025">(<a href="#ref-cgtn-hami-chongqing-2025" role="doc-biblioref">CGTN, 2025b</a>)</span>. CHN Energy launched a ¥170-billion Hami integrated energy base in October 2024 on the same multi-energy template <span class="citation" data-cites="chinadaily-chnenergy-base-2024">(<a href="#ref-chinadaily-chnenergy-base-2024" role="doc-biblioref">China Daily, 2024a</a>)</span>.</p>
<p>Xinjiang’s outbound electricity set a record 126.4 TWh in 2024 (more than 30% from renewables), with cumulative cross-provincial transmission exceeding 860 TWh <span class="citation" data-cites="globaltimes-export-2025 people-daily-grid-2025">(<a href="#ref-globaltimes-export-2025" role="doc-biblioref">Global Times, 2025d</a>; <a href="#ref-people-daily-grid-2025" role="doc-biblioref">People’s Daily, 2025</a>)</span>. UHV-line throughput remains coal-dominated despite official emphasis on rising renewable shares; per-line coal-vs-renewable splits are not consistently published.</p>
<hr>
</section>
<section id="wind" class="level1">
<h1>Wind</h1>
<p>The corridor is one of China’s leading wind regions, built on natural wind gaps and Gobi terrain.</p>
<ul>
<li><strong>Dabancheng (达坂城), near Urumqi</strong> — in the wind gap between Urumqi and Turpan, China’s oldest large wind site (first turbines 1986–88). It now holds over 6.6 GW across ~59 farms and 1,000+ turbines, with 200+ days a year of force-6 winds <span class="citation" data-cites="xinhua-dabancheng-2026">(<a href="#ref-xinhua-dabancheng-2026" role="doc-biblioref">Xinhua, 2026a</a>)</span>.</li>
<li><strong>Hami/Kumul base</strong> — a designated national 10-GW-class base spanning the Santanghu and Xiaocaohu wind zones, exporting via the Hami UHV lines <span class="citation" data-cites="gem-hami-wind bolandnewenergy-hami">(<a href="#ref-bolandnewenergy-hami" role="doc-biblioref">Boland New Energy, 2024</a>; <a href="#ref-gem-hami-wind" role="doc-biblioref">Global Energy Monitor, 2024</a>)</span>.</li>
<li><strong>Gansu Jiuquan/Guazhou (“Three Gorges on Land”), near Dunhuang</strong> — China’s first approved 10-GW wind base (2008). Grid-connected wind at Jiuquan reached ~10.45 GW (~72% of Gansu’s fleet), exporting on the Jiuquan–Hunan ±800 kV line <span class="citation" data-cites="seetao-jiuquan-wind yicai-jiuquan-2024">(<a href="#ref-seetao-jiuquan-wind" role="doc-biblioref">Seetao, 2024a</a>; <a href="#ref-yicai-jiuquan-2024" role="doc-biblioref">Yicai Global, 2024b</a>)</span>.</li>
</ul>
<p>Xinjiang’s total wind capacity reached ~30 GW by end-2025; the province holds ~780 GW of technically exploitable wind resource, second nationally <span class="citation" data-cites="xinhua-xinjiang-export-2026">(<a href="#ref-xinhua-xinjiang-export-2026" role="doc-biblioref">Xinhua, 2026b</a>)</span>. These corridors fall under China’s “large wind-and-solar bases in desert and Gobi areas” programme <span class="citation" data-cites="globaltimes-desert-bases-2025">(<a href="#ref-globaltimes-desert-bases-2025" role="doc-biblioref">Global Times, 2025b</a>)</span>. Curtailment, once ~40% in 2016, fell to single digits by 2020 but has crept up again in 2024–25 as record additions outpace grid integration <span class="citation" data-cites="ember-2025">(<a href="#ref-ember-2025" role="doc-biblioref">Ember, 2025</a>)</span>. The Hami output and capacity-factor figures circulating from industry aggregators are not official and are flagged as indicative.</p>
<hr>
</section>
<section id="solar-pv" class="level1">
<h1>Solar PV</h1>
<p>The corridor sits in one of China’s best solar belts — Hami records 3,100–3,300 sunshine hours a year, and Xinjiang holds about 40% of China’s technically exploitable solar potential <span class="citation" data-cites="cgtn-hami-base-2023 baogaobox-solar-2025">(<a href="#ref-baogaobox-solar-2025" role="doc-biblioref">Baogaobox, 2025</a>; <a href="#ref-cgtn-hami-base-2023" role="doc-biblioref">CGTN, 2023</a>)</span>. Development concentrates in 10-GW-class bases at Urumqi, Changji and Hami, plus the early Dunhuang park in Gansu.</p>
<p>Xinjiang solar PV reached <strong>56.7 GW at end-2024</strong>, about 55% of the region’s power capacity and its single largest source <span class="citation" data-cites="baogaobox-solar-2025 chinadaily-xinjiang-solar-2024">(<a href="#ref-baogaobox-solar-2025" role="doc-biblioref">Baogaobox, 2025</a>; <a href="#ref-chinadaily-xinjiang-solar-2024" role="doc-biblioref">China Daily, 2024b</a>)</span>. Combined wind and solar passed 100 GW at end-2024 — the first north-west China province to do so — with 40.4 GW added in 2024 alone, ranking first nationally for additions <span class="citation" data-cites="bastillepost-100gw-2024">(<a href="#ref-bastillepost-100gw-2024" role="doc-biblioref">Bastille Post, 2024</a>)</span>.</p>
<p>Flagship desert/Gobi (沙戈荒) projects include:</p>
<ul>
<li><strong>Midong (Urumqi) 3.5 GW</strong> — among the world’s largest single-site PV plants, grid-connected mid-2024 (~6.1 TWh/yr) <span class="citation" data-cites="cdssolar-midong-2024 eia-midong-2024">(<a href="#ref-cdssolar-midong-2024" role="doc-biblioref">CDS Solar, 2024</a>; <a href="#ref-eia-midong-2024" role="doc-biblioref">U.S. Energy Information Administration, 2024</a>)</span>.</li>
<li><strong>Ruoqiang 4 GW</strong> (Taklamakan south-east edge) — connected December 2024, full operation May 2025 (~6.9 TWh/yr) <span class="citation" data-cites="tianshannet-ruoqiang-2024">(<a href="#ref-tianshannet-ruoqiang-2024" role="doc-biblioref">Tianshan Net, 2024</a>)</span>.</li>
<li><strong>Hami Tianshan North Slope</strong> — a ~14.2 GW base, over 70% renewable, anchoring the Xinjiang–Chongqing UHV line <span class="citation" data-cites="cgtn-hami-base-2023">(<a href="#ref-cgtn-hami-base-2023" role="doc-biblioref">CGTN, 2023</a>)</span>.</li>
</ul>
<p>The corridor also hosts Sinopec’s Kuqa green-hydrogen project — a 300 MW PV plant feeding 20,000 t/yr of electrolytic hydrogen, the world’s largest PV-to-hydrogen facility <span class="citation" data-cites="nsenergy-kuqa-2021">(<a href="#ref-nsenergy-kuqa-2021" role="doc-biblioref">NS Energy, 2021</a>)</span>. Both Midong (3.5 GW) and Ruoqiang (4 GW) are marketed as “world’s largest single PV plant”; provincial rank varies by data series.</p>
<hr>
</section>
<section id="concentrating-solar-power-csp" class="level1">
<h1>Concentrating Solar Power (CSP)</h1>
<p>The Dunhuang–Hami–Turpan corridor is China’s largest CSP cluster. High direct-normal irradiance plus the molten-salt thermal storage these plants carry (10–13+ hours) make them dispatchable, baseload-like anchors for the surrounding PV and wind bases.</p>
<ul>
<li><strong>Dunhuang (Gansu)</strong> — Shouhang’s molten-salt power towers: a 10 MW pilot (2016, Asia’s first molten-salt tower able to generate 24 hours, ~15 h storage) and the 100 MW Dunhuang tower (2018, 11 h storage, ~11,900 heliostats, ~390 GWh/yr) <span class="citation" data-cites="cnste-dunhuang-2016 heliocon-dunhuang-2018">(<a href="#ref-cnste-dunhuang-2016" role="doc-biblioref">China Solar Thermal Alliance (CNSTE), 2016</a>; <a href="#ref-heliocon-dunhuang-2018" role="doc-biblioref">HelioCon, 2018</a>)</span>.</li>
<li><strong>Hami 50 MW molten-salt tower</strong> (Xinjiang) — commercial operation September 2021, 13 h storage, ~200 GWh/yr <span class="citation" data-cites="solarpaces-hami-2021">(<a href="#ref-solarpaces-hami-2021" role="doc-biblioref">SolarPACES, 2021</a>)</span>.</li>
<li><strong>CSP+PV+wind hybrids:</strong> a CEEC Hami 1,500 MW project (150 MW tower plus 1,350 MW PV, targeting 2026) and a Turpan 1 GW CSP+PV at Toksun (100 MW tower, 12 h storage) — both billed among the world’s largest PV-CSP plants under construction <span class="citation" data-cites="pvmag-ceec-2026 solarpaces-turpan-2025">(<a href="#ref-pvmag-ceec-2026" role="doc-biblioref">pv magazine, 2026</a>; <a href="#ref-solarpaces-turpan-2025" role="doc-biblioref">SolarPACES, 2025b</a>)</span>.</li>
</ul>
<p>By end-2025, Gansu led China’s operating CSP at ~621 MW, ahead of Qinghai (~510 MW) and Xinjiang (~450 MW), within a national pipeline above 8 GW and a 2030 target of ~15 GW <span class="citation" data-cites="solarpaces-china-2025">(<a href="#ref-solarpaces-china-2025" role="doc-biblioref">SolarPACES, 2025a</a>)</span>. The role of CSP here is less standalone generation than providing the dispatchable, after-sunset core that firms the desert renewable bases. The Hami storage figure is cited as both 13 h and “22 h of supply”; 13 h is the design storage value.</p>
<hr>
</section>
<section id="transmission-and-transmission-capacity" class="level1">
<h1>Transmission and Transmission Capacity</h1>
<p>The corridor is the western anchor of China’s “West–East Power Transmission” (西电东送) system. Power leaves through long-distance UHV DC lines, while a 750 kV AC backbone ties Xinjiang into the Northwest Grid.</p>
<section id="major-uhv-lines" class="level2">
<h2 class="anchored" data-anchor-id="major-uhv-lines">Major UHV lines</h2>
<p><strong>Table 2: UHV transmission channels from the corridor</strong></p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 22%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 16%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Line</th>
<th style="text-align: left;">Voltage / type</th>
<th style="text-align: left;">Route</th>
<th style="text-align: right;">Length</th>
<th style="text-align: right;">Capacity</th>
<th style="text-align: center;">In service</th>
<th style="text-align: left;">Mix carried</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Hami–Zhengzhou</td>
<td style="text-align: left;">±800 kV HVDC</td>
<td style="text-align: left;">Hami → Zhengzhou (Henan)</td>
<td style="text-align: right;">2,190 km</td>
<td style="text-align: right;">8 GW</td>
<td style="text-align: center;">2014</td>
<td style="text-align: left;">Coal-dominant + wind/PV</td>
</tr>
<tr class="even">
<td style="text-align: left;">Changji (Zhundong)–Guquan</td>
<td style="text-align: left;">±1,100 kV UHVDC</td>
<td style="text-align: left;">Zhundong → Wannan (Anhui)</td>
<td style="text-align: right;">3,324 km</td>
<td style="text-align: right;">12 GW</td>
<td style="text-align: center;">2019</td>
<td style="text-align: left;">Coal-heavy + wind/solar</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jiuquan–Hunan</td>
<td style="text-align: left;">±800 kV HVDC</td>
<td style="text-align: left;">Jiuquan (Gansu) → Xiangtan (Hunan)</td>
<td style="text-align: right;">~2,383 km</td>
<td style="text-align: right;">8 GW</td>
<td style="text-align: center;">2017</td>
<td style="text-align: left;">Wind + solar + thermal</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hami–Chongqing</td>
<td style="text-align: left;">±800 kV UHVDC</td>
<td style="text-align: left;">Hami → Chongqing</td>
<td style="text-align: right;">~2,260 km</td>
<td style="text-align: right;">8 GW</td>
<td style="text-align: center;">2025</td>
<td style="text-align: left;">&gt;70% wind/PV/CSP + 4 GW coal</td>
</tr>
</tbody>
</table>
<p><em>Source: <span class="citation" data-cites="wikipedia-hami-zhengzhou nsenergy-changji-2019 powertech-jiuquan-2017 cgtn-hami-chongqing-2025">(<a href="#ref-cgtn-hami-chongqing-2025" role="doc-biblioref">CGTN, 2025b</a>; <a href="#ref-nsenergy-changji-2019" role="doc-biblioref">NS Energy, 2019</a>; <a href="#ref-powertech-jiuquan-2017" role="doc-biblioref">Power Technology, 2017</a>; <a href="#ref-wikipedia-hami-zhengzhou" role="doc-biblioref">Wikipedia, 2024a</a>)</span>. The Changji–Guquan line is the world’s highest-voltage transmission link and had delivered ~300 TWh cumulatively by mid-2025 <span class="citation" data-cites="globaltransmission-changji-2024">(<a href="#ref-globaltransmission-changji-2024" role="doc-biblioref">Global Transmission Report, 2024</a>)</span>.</em></p>
<p>Gansu adds further channels beyond the four above: a Longdong–Shandong ±800 kV line that delivered 28.8 TWh in its first year, and a Gansu–Zhejiang ±800 kV line under construction (&gt;36 TWh/yr, more than half renewable) <span class="citation" data-cites="chinadaily-gansu-shandong-2026 enerdata-gansu-zhejiang">(<a href="#ref-chinadaily-gansu-shandong-2026" role="doc-biblioref">China Daily, 2026</a>; <a href="#ref-enerdata-gansu-zhejiang" role="doc-biblioref">Enerdata, 2025</a>)</span>.</p>
</section>
<section id="outbound-capacity-and-exported-energy" class="level2">
<h2 class="anchored" data-anchor-id="outbound-capacity-and-exported-energy">Outbound capacity and exported energy</h2>
<p>Xinjiang exported a record <strong>126.4 TWh in 2024</strong> (more than 30%, or 39.2 TWh, from renewables); cumulative transmission since 2010 exceeds 860 TWh <span class="citation" data-cites="globaltimes-export-2025">(<a href="#ref-globaltimes-export-2025" role="doc-biblioref">Global Times, 2025d</a>)</span>. With the Hami–Chongqing line completing at end-2025, total outbound capacity rises to <strong>~33 GW</strong>, and the renewable share of exports is targeted to climb from ~30% toward ~50% <span class="citation" data-cites="govcn-export-2025">(<a href="#ref-govcn-export-2025" role="doc-biblioref">The State Council of China, 2025</a>)</span>. Gansu transmitted 33.15 TWh in the first half of 2025, up 34.6% year-on-year <span class="citation" data-cites="cri-gansu-2025">(<a href="#ref-cri-gansu-2025" role="doc-biblioref">China Radio International, 2025</a>)</span>.</p>
</section>
<section id="intra-regional-grid" class="level2">
<h2 class="anchored" data-anchor-id="intra-regional-grid">Intra-regional grid</h2>
<p>The Xinjiang grid was historically islanded. It now connects to the Northwest Grid and Gansu via the Lanzhou–Urumqi 750 kV AC backbone, and reached full 750 kV prefecture coverage in 2020 after a ¥136.8 billion State Grid programme centred on Urumqi and reaching Hami, Ili, Kashgar, Hotan and Altay <span class="citation" data-cites="govcn-xinjiang-grid-2020 sasac-xinjiang-2020">(<a href="#ref-sasac-xinjiang-2020" role="doc-biblioref">SASAC, 2020</a>; <a href="#ref-govcn-xinjiang-grid-2020" role="doc-biblioref">The State Council of China, 2021</a>)</span>. The grid now forms a “four-ring internal supply, four outbound channels” pattern, with reinforcement continuing — for example a Kashgar 750 kV double-ring and Xinjiang’s first 10 GW PV base at Kashgar <span class="citation" data-cites="prnewswire-kashgar-2025">(<a href="#ref-prnewswire-kashgar-2025" role="doc-biblioref">PR Newswire, 2025</a>)</span>.</p>
</section>
<section id="transmission-as-the-binding-constraint" class="level2">
<h2 class="anchored" data-anchor-id="transmission-as-the-binding-constraint">Transmission as the binding constraint</h2>
<p>These lines anchor the desert/Gobi renewable mega-bases, but transmission capacity also limits how fast they can be built. Xinjiang curtailment reached 29.3% in 2017; recent additions have re-tightened constraints. Nationally, H1 2025 solar curtailment rose to 6.6% (from 3.9%) and wind to 5.7% (from 3%), with western provinces disproportionately affected by inadequate inter-regional transmission. China has relaxed its curtailment cap from 5% to 10% and is fast-tracking new lines <span class="citation" data-cites="powertech-curtailment-2025 ember-2025">(<a href="#ref-ember-2025" role="doc-biblioref">Ember, 2025</a>; <a href="#ref-powertech-curtailment-2025" role="doc-biblioref">Power Technology, 2025</a>)</span>.</p>
<p>A planned “fourth Xinjiang channel” is referenced in State Grid’s 2026–2030 programme but has no confirmed route, capacity or commissioning date, and is flagged as planned-not-built. The three confirmed Xinjiang UHVDC channels are Hami–Zhengzhou, Zhundong–Wannan and Hami–Chongqing.</p>
<hr>
</section>
</section>
<section id="synthesis" class="level1">
<h1>Synthesis</h1>
<p>The corridor is a single integrated energy machine. Coal, oil and gas extraction at world scale (Zhundong, Karamay/Junggar, Tarim, Tuha) sits alongside the fastest renewable build in China — 40 GW of wind and solar added in 2024 alone. Coal power and CSP thermal storage increasingly exist to firm the variable renewables rather than to serve local load. And the combined output — coal-fired, wind and solar blended together — is railed, piped and, above all, wired east through the densest concentration of UHV transmission infrastructure on earth. The Dabancheng turbines between Urumqi and Turpan, the Gobi solar fields, the Dunhuang molten-salt towers and the open-pit coal mines are the visible nodes of China’s primary west-to-east energy supply line.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-aa-china-gas-2025" class="csl-entry" role="listitem">
Anadolu Agency. (2025). <em>China’s natural gas consumption to increase by 6.5% in 2025</em>. <a href="https://www.aa.com.tr/en/energy/natural-gas/chinas-natural-gas-consumption-to-increase-by-65-in-2025/47087">https://www.aa.com.tr/en/energy/natural-gas/chinas-natural-gas-consumption-to-increase-by-65-in-2025/47087</a>
</div>
<div id="ref-baike-dushanzi" class="csl-entry" role="listitem">
Baidu Baike. (2024a). <em>Dushanzi petrochemical company of PetroChina</em>. <a href="https://baike.baidu.com/en/item/Dushanzi%20Petrochemical%20Company%20of%20PetroChina%20Company%20Limited/940653">https://baike.baidu.com/en/item/Dushanzi%20Petrochemical%20Company%20of%20PetroChina%20Company%20Limited/940653</a>
</div>
<div id="ref-baike-karamay" class="csl-entry" role="listitem">
Baidu Baike. (2024b). <em>Karamay petrochemical company</em>. <a href="https://baike.baidu.com/en/item/Karamay%20Petrochemical%20Company/65768">https://baike.baidu.com/en/item/Karamay%20Petrochemical%20Company/65768</a>
</div>
<div id="ref-baogaobox-solar-2025" class="csl-entry" role="listitem">
Baogaobox. (2025). <em>Xinjiang solar PV capacity reaches 56.66 GW at end-2024</em>. <a href="https://www.baogaobox.com/insights/250618000012133.html">https://www.baogaobox.com/insights/250618000012133.html</a>
</div>
<div id="ref-bastillepost-100gw-2024" class="csl-entry" role="listitem">
Bastille Post. (2024). <em>Xinjiang’s new-energy installed capacity hits 100 million kW</em>. <a href="https://www.bastillepost.com/global/article/4444459-xinjiangs-new-energy-installed-capacity-hits-100-million-kw">https://www.bastillepost.com/global/article/4444459-xinjiangs-new-energy-installed-capacity-hits-100-million-kw</a>
</div>
<div id="ref-bolandnewenergy-hami" class="csl-entry" role="listitem">
Boland New Energy. (2024). <em>China wind farms: Xinjiang hami wind power base</em>. <a href="https://bolandnewenergy.com/china-wind-farms-xinjiang-hami-wind-power-base/">https://bolandnewenergy.com/china-wind-farms-xinjiang-hami-wind-power-base/</a>
</div>
<div id="ref-carbonbrief-coal-2025" class="csl-entry" role="listitem">
Carbon Brief. (2025). <em>China’s construction of new coal power plants reached 10-year high in 2024</em>. <a href="https://www.carbonbrief.org/chinas-construction-of-new-coal-power-plants-reached-10-year-high-in-2024/">https://www.carbonbrief.org/chinas-construction-of-new-coal-power-plants-reached-10-year-high-in-2024/</a>
</div>
<div id="ref-cdssolar-midong-2024" class="csl-entry" role="listitem">
CDS Solar. (2024). <em>Record-breaking solar power station connected to grid: Xinjiang’s 3.5 GW midong plant</em>. <a href="https://cdssolar.com/record-breaking-solar-power-station-connected-to-grid-xinjiang-s-3-5-gw-solar-plant/">https://cdssolar.com/record-breaking-solar-power-station-connected-to-grid-xinjiang-s-3-5-gw-solar-plant/</a>
</div>
<div id="ref-ceic-xinjiang-gas-2025" class="csl-entry" role="listitem">
CEIC. (2025). <em>China natural gas production: xinjiang</em>. <a href="https://www.ceicdata.com/en/china/energy-production-natural-gas/cn-natural-gas-production-xinjiang">https://www.ceicdata.com/en/china/energy-production-natural-gas/cn-natural-gas-production-xinjiang</a>
</div>
<div id="ref-cgtn-hami-base-2023" class="csl-entry" role="listitem">
CGTN. (2023). <em>Wind-solar project turns gobi desert into oasis of green energy (hami base)</em>. <a href="https://news.cgtn.com/news/2023-12-29/Wind-solar-power-project-turns-Gobi-Desert-into-oasis-of-green-energy-1pVvpBImVgc/p.html">https://news.cgtn.com/news/2023-12-29/Wind-solar-power-project-turns-Gobi-Desert-into-oasis-of-green-energy-1pVvpBImVgc/p.html</a>
</div>
<div id="ref-cgtn-tarim-2025" class="csl-entry" role="listitem">
CGTN. (2025a). <em>Tarim oilfield surpasses 20 million tonnes of ultra-deep output in 2024</em>. <a href="https://news.cgtn.com/news/2025-01-20/Tarim-Oilfield-surpasses-20-million-tonnes-in-2024-1AjmfaVGARq/p.html">https://news.cgtn.com/news/2025-01-20/Tarim-Oilfield-surpasses-20-million-tonnes-in-2024-1AjmfaVGARq/p.html</a>
</div>
<div id="ref-cgtn-hami-chongqing-2025" class="csl-entry" role="listitem">
CGTN. (2025b). <em>UHV project launched sending power from xinjiang to chongqing</em>. <a href="https://news.cgtn.com/news/2025-06-10/UHV-project-launched-sending-power-from-Xinjiang-to-Chongqing-1E63wLpb9Be/p.html">https://news.cgtn.com/news/2025-06-10/UHV-project-launched-sending-power-from-Xinjiang-to-Chongqing-1E63wLpb9Be/p.html</a>
</div>
<div id="ref-chinadaily-hutubi-2022" class="csl-entry" role="listitem">
China Daily. (2022a). <em>Hutubi underground gas storage, china’s largest</em>. <a href="https://www.chinadaily.com.cn/a/202211/20/WS6379c6eca31049175432acb4.html">https://www.chinadaily.com.cn/a/202211/20/WS6379c6eca31049175432acb4.html</a>
</div>
<div id="ref-chinadaily-xinjiang-oilfield-2022" class="csl-entry" role="listitem">
China Daily. (2022b). <em>PetroChina xinjiang oilfield production targets</em>. <a href="https://global.chinadaily.com.cn/a/202212/23/WS63a54073a31057c47eba5e11.html">https://global.chinadaily.com.cn/a/202212/23/WS63a54073a31057c47eba5e11.html</a>
</div>
<div id="ref-chinadaily-xinjiang-coal-2023" class="csl-entry" role="listitem">
China Daily. (2023). <em>Xinjiang’s coal resources estimated at 2.19 trillion tonnes</em>. <a href="https://www.chinadaily.com.cn/a/202301/28/WS63d4912fa31057c47ebab82b.html">https://www.chinadaily.com.cn/a/202301/28/WS63d4912fa31057c47ebab82b.html</a>
</div>
<div id="ref-chinadaily-chnenergy-base-2024" class="csl-entry" role="listitem">
China Daily. (2024a). <em>CHN energy launches 170-billion-yuan integrated energy base in hami</em>. <a href="https://global.chinadaily.com.cn/a/202410/10/WS67073092a310f1265a1c6d37.html">https://global.chinadaily.com.cn/a/202410/10/WS67073092a310f1265a1c6d37.html</a>
</div>
<div id="ref-chinadaily-xinjiang-solar-2024" class="csl-entry" role="listitem">
China Daily. (2024b). <em>Xinjiang solar capacity becomes its largest power source</em>. <a href="https://xj.chinadaily.com.cn/a/202412/30/WS67725ecda310b59111dab9d3.html">https://xj.chinadaily.com.cn/a/202412/30/WS67725ecda310b59111dab9d3.html</a>
</div>
<div id="ref-chinadaily-gansu-shandong-2026" class="csl-entry" role="listitem">
China Daily. (2026). <em>Gansu–shandong UHV line delivers 28.8 TWh in first year</em>. <a href="https://www.chinadaily.com.cn/a/202605/08/WS69fd9c2aa310d6866eb478c9.html">https://www.chinadaily.com.cn/a/202605/08/WS69fd9c2aa310d6866eb478c9.html</a>
</div>
<div id="ref-cri-gansu-2025" class="csl-entry" role="listitem">
China Radio International. (2025). <em>Gansu transmits 33.15 TWh in first half of 2025, up 34.6 percent</em>. <a href="https://news.cri.cn/2025-07-16/1e019059-2f53-3288-2244-7ed4be43c4f8.html">https://news.cri.cn/2025-07-16/1e019059-2f53-3288-2244-7ed4be43c4f8.html</a>
</div>
<div id="ref-cnste-dunhuang-2016" class="csl-entry" role="listitem">
China Solar Thermal Alliance (CNSTE). (2016). <em>Dunhuang 10 MW molten-salt tower grid-connected</em>. <a href="http://en.cnste.org/html/news/2016/1230/96.html">http://en.cnste.org/html/news/2016/1230/96.html</a>
</div>
<div id="ref-electrive-xcmg-2025" class="csl-entry" role="listitem">
electrive. (2025). <em>China launches world’s largest fleet of autonomous electric mining trucks</em>. <a href="https://www.electrive.com/2025/05/20/china-launches-worlds-largest-fleet-of-autonomous-electric-mining-trucks/">https://www.electrive.com/2025/05/20/china-launches-worlds-largest-fleet-of-autonomous-electric-mining-trucks/</a>
</div>
<div id="ref-ember-2025" class="csl-entry" role="listitem">
Ember. (2025). <em>China energy transition review 2025</em>. <a href="https://ember-energy.org/latest-insights/china-energy-transition-review-2025/">https://ember-energy.org/latest-insights/china-energy-transition-review-2025/</a>
</div>
<div id="ref-enerdata-gansu-zhejiang" class="csl-entry" role="listitem">
Enerdata. (2025). <em>China starts work on 800 kV transmission project linking gansu and zhejiang</em>. <a href="https://www.enerdata.net/publications/daily-energy-news/china-starts-work-800-kv-transmission-project-linking-gansu-and-zhejiang.html">https://www.enerdata.net/publications/daily-energy-news/china-starts-work-800-kv-transmission-project-linking-gansu-and-zhejiang.html</a>
</div>
<div id="ref-gem-hami-wind" class="csl-entry" role="listitem">
Global Energy Monitor. (2024). <em>Xinjiang hami china coal comprehensive energy base wind farm</em>. <a href="https://www.gem.wiki/Xinjiang_Hami_China_Coal_Comprehensive_Energy_Base_wind_farm">https://www.gem.wiki/Xinjiang_Hami_China_Coal_Comprehensive_Energy_Base_wind_farm</a>
</div>
<div id="ref-globaltimes-trucks-2025" class="csl-entry" role="listitem">
Global Times. (2025a). <em>91 autonomous trucks achieve full unmanned operation at shitoumei no. 1 mine, hami</em>. <a href="https://www.globaltimes.cn/page/202505/1334403.shtml">https://www.globaltimes.cn/page/202505/1334403.shtml</a>
</div>
<div id="ref-globaltimes-desert-bases-2025" class="csl-entry" role="listitem">
Global Times. (2025b). <em>China’s desert and gobi renewable mega-bases</em>. <a href="https://www.globaltimes.cn/page/202505/1334578.shtml">https://www.globaltimes.cn/page/202505/1334578.shtml</a>
</div>
<div id="ref-globaltimes-jimsar-2025" class="csl-entry" role="listitem">
Global Times. (2025c). <em>Jimsar shale oil demonstration base exceeds one million tonnes</em>. <a href="https://www.globaltimes.cn/page/202510/1346831.shtml">https://www.globaltimes.cn/page/202510/1346831.shtml</a>
</div>
<div id="ref-globaltimes-export-2025" class="csl-entry" role="listitem">
Global Times. (2025d). <em>Xinjiang outbound electricity sets record 126.4 TWh in 2024</em>. <a href="https://www.globaltimes.cn/page/202501/1327375.shtml">https://www.globaltimes.cn/page/202501/1327375.shtml</a>
</div>
<div id="ref-globaltransmission-changji-2024" class="csl-entry" role="listitem">
Global Transmission Report. (2024). <em>China’s +/-1100 kV changji–guquan UHVDC project delivers 300 TWh power</em>. <a href="https://globaltransmission.info/chinas-1100-kv-changji-guquan-uhvdc-project-delivers-300-twh-power/">https://globaltransmission.info/chinas-1100-kv-changji-guquan-uhvdc-project-delivers-300-twh-power/</a>
</div>
<div id="ref-greenpeace-coal-2025" class="csl-entry" role="listitem">
Greenpeace East Asia. (2025). <em>Xinjiang leads china in newly permitted coal power capacity</em>. <a href="https://www.greenpeace.org/eastasia/press/68510/">https://www.greenpeace.org/eastasia/press/68510/</a>
</div>
<div id="ref-heliocon-dunhuang-2018" class="csl-entry" role="listitem">
HelioCon. (2018). <em>Shouhang dunhuang 100 MW phase II molten-salt tower</em>. <a href="https://heliocon.org/plants/Shouhang_Dunhuang_Phase_II.html">https://heliocon.org/plants/Shouhang_Dunhuang_Phase_II.html</a>
</div>
<div id="ref-im-mining-boonray-2026" class="csl-entry" role="listitem">
International Mining. (2026a). <em>BYD invests over US$144 million in electric and autonomous mining truck company boonray</em>. <a href="https://im-mining.com/2026/01/29/byd-invests-over-us144-million-in-electric-and-autonomous-mining-truck-company-boonray/">https://im-mining.com/2026/01/29/byd-invests-over-us144-million-in-electric-and-autonomous-mining-truck-company-boonray/</a>
</div>
<div id="ref-im-mining-eacon-2026" class="csl-entry" role="listitem">
International Mining. (2026b). <em>EACON’s autonomy deployed on 120 battery-electric trucks at zhundong mine</em>. <a href="https://im-mining.com/2026/03/27/eacons-autonomy-deployed-on-120-battery-electric-trucks-at-zhundong-mine/">https://im-mining.com/2026/03/27/eacons-autonomy-deployed-on-120-battery-electric-trucks-at-zhundong-mine/</a>
</div>
<div id="ref-nsenergy-changji-2019" class="csl-entry" role="listitem">
NS Energy. (2019). <em>Changji–guquan UHVDC transmission project</em>. <a href="https://www.nsenergybusiness.com/projects/changji-guquan-uhvdc-transmission-project/">https://www.nsenergybusiness.com/projects/changji-guquan-uhvdc-transmission-project/</a>
</div>
<div id="ref-nsenergy-kuqa-2021" class="csl-entry" role="listitem">
NS Energy. (2021). <em>Sinopec PV green hydrogen production project, kuqa</em>. <a href="https://www.nsenergybusiness.com/news/sinopec-pv-green-hydrogen-production-project-kuqa/">https://www.nsenergybusiness.com/news/sinopec-pv-green-hydrogen-production-project-kuqa/</a>
</div>
<div id="ref-people-daily-grid-2025" class="csl-entry" role="listitem">
People’s Daily. (2025). <em>Xinjiang grid capacity reaches 219 GW with renewables near 60 percent</em>. <a href="https://en.people.cn/n3/2025/0530/c90000-20321552.html">https://en.people.cn/n3/2025/0530/c90000-20321552.html</a>
</div>
<div id="ref-powertech-jiuquan-2017" class="csl-entry" role="listitem">
Power Technology. (2017). <em>Jiuquan–hunan HVDC line, china</em>. <a href="https://www.power-technology.com/marketdata/jiuquan-hunan-hvdc-line-china/">https://www.power-technology.com/marketdata/jiuquan-hunan-hvdc-line-china/</a>
</div>
<div id="ref-powertech-curtailment-2025" class="csl-entry" role="listitem">
Power Technology. (2025). <em>China renewable energy curtailment rises in 2025</em>. <a href="https://www.power-technology.com/news/china-renewable-energy-curtailment/">https://www.power-technology.com/news/china-renewable-energy-curtailment/</a>
</div>
<div id="ref-prnewswire-kashgar-2025" class="csl-entry" role="listitem">
PR Newswire. (2025). <em>Kashgar completes xinjiang’s first 10 GW photovoltaic base</em>. <a href="https://www.prnewswire.com/apac/news-releases/kashgar-completes-xinjiangs-first-10-gw-photovoltaic-base-302478602.html">https://www.prnewswire.com/apac/news-releases/kashgar-completes-xinjiangs-first-10-gw-photovoltaic-base-302478602.html</a>
</div>
<div id="ref-pvmag-ceec-2026" class="csl-entry" role="listitem">
pv magazine. (2026). <em>World’s largest PV-CSP plant under construction in china (CEEC hami 1,500 MW)</em>. <a href="https://www.pv-magazine-india.com/2026/04/14/worlds-largest-pv-csp-plant-under-construction-in-china/">https://www.pv-magazine-india.com/2026/04/14/worlds-largest-pv-csp-plant-under-construction-in-china/</a>
</div>
<div id="ref-sasac-xinjiang-2020" class="csl-entry" role="listitem">
SASAC. (2020). <em>State grid 750 kV network investment in xinjiang</em>. <a href="http://en.sasac.gov.cn/2020/10/26/c_5864.htm">http://en.sasac.gov.cn/2020/10/26/c_5864.htm</a>
</div>
<div id="ref-seetao-jiuquan-wind" class="csl-entry" role="listitem">
Seetao. (2024a). <em>Jiuquan wind base grid-connected capacity reaches 10.45 GW</em>. <a href="https://www.seetao.com/details/123992.html">https://www.seetao.com/details/123992.html</a>
</div>
<div id="ref-seetao-coal-gas-2024" class="csl-entry" role="listitem">
Seetao. (2024b). <em>Xinjiang coal-to-gas projects and the zhundong SNG plant</em>. <a href="https://www.seetaoe.com/details/262462.html">https://www.seetaoe.com/details/262462.html</a>
</div>
<div id="ref-seetao-zhundong-2025" class="csl-entry" role="listitem">
Seetao. (2025). <em>Yankuang qineng no. 4 open-pit coal mine enters trial operation in zhundong</em>. <a href="https://www.seetaoe.com/details/247146.html">https://www.seetaoe.com/details/247146.html</a>
</div>
<div id="ref-smm-shaerhu-coal" class="csl-entry" role="listitem">
Shanghai Metals Market. (2024). <em>Asia’s largest coal reserve discovered in xinjiang (sha’er lake, 89.2 bt)</em>. <a href="https://news.metal.com/newscontent/100027837/Asias-Largest-Coal-Reserve-Discovered-in-Xinjiang-">https://news.metal.com/newscontent/100027837/Asias-Largest-Coal-Reserve-Discovered-in-Xinjiang-</a>
</div>
<div id="ref-solarpaces-hami-2021" class="csl-entry" role="listitem">
SolarPACES. (2021). <em>50 MW hami tower CSP project with stellio heliostats commissioned in china</em>. <a href="https://www.solarpaces.org/50-mw-hami-tower-csp-project-with-novel-stellio-heliostats-commissioned-in-china/">https://www.solarpaces.org/50-mw-hami-tower-csp-project-with-novel-stellio-heliostats-commissioned-in-china/</a>
</div>
<div id="ref-solarpaces-china-2025" class="csl-entry" role="listitem">
SolarPACES. (2025a). <em>China connects 9 more CSP projects in 2025 for 27 total</em>. <a href="https://www.solarpaces.org/china-connects-9-more-csp-projects-in-2025-for-27-total/">https://www.solarpaces.org/china-connects-9-more-csp-projects-in-2025-for-27-total/</a>
</div>
<div id="ref-solarpaces-turpan-2025" class="csl-entry" role="listitem">
SolarPACES. (2025b). <em>Xinjiang’s turpan wustong 1 GW CSP-PV expected completion in 2026</em>. <a href="https://www.solarpaces.org/xinjiangs-turpan-wustong-1gw-csp-pv-expected-completion-in-2026/">https://www.solarpaces.org/xinjiangs-turpan-wustong-1gw-csp-pv-expected-completion-in-2026/</a>
</div>
<div id="ref-scmp-xinjiang-railway-2022" class="csl-entry" role="listitem">
South China Morning Post. (2022). <em>China doubles down on coal with rapid roll-out of new railway track to xinjiang</em>. <a href="https://www.scmp.com/news/china/science/article/3189191/china-doubles-down-coal-rapid-roll-out-new-railway-track-worlds">https://www.scmp.com/news/china/science/article/3189191/china-doubles-down-coal-rapid-roll-out-new-railway-track-worlds</a>
</div>
<div id="ref-govcn-xinjiang-grid-2020" class="csl-entry" role="listitem">
The State Council of China. (2021). <em>Xinjiang completes 750 kV grid coverage of all prefectures</em>. <a href="http://english.www.gov.cn/news/topnews/202112/12/content_WS61b58b0fc6d09c94e48a21da.html">http://english.www.gov.cn/news/topnews/202112/12/content_WS61b58b0fc6d09c94e48a21da.html</a>
</div>
<div id="ref-govcn-export-2025" class="csl-entry" role="listitem">
The State Council of China. (2025). <em>Xinjiang outbound transmission capacity and renewable export share</em>. <a href="https://english.www.gov.cn/archive/statistics/202501/22/content_WS6790949fc6d0868f4e8ef0f2.html">https://english.www.gov.cn/archive/statistics/202501/22/content_WS6790949fc6d0868f4e8ef0f2.html</a>
</div>
<div id="ref-tianshannet-ruoqiang-2024" class="csl-entry" role="listitem">
Tianshan Net. (2024). <em>Ruoqiang 4 GW desert PV base grid-connected</em>. <a href="https://www.ts.cn/xwzx/jjxw/202412/t20241218_25640990.shtml">https://www.ts.cn/xwzx/jjxw/202412/t20241218_25640990.shtml</a>
</div>
<div id="ref-tianshannet-xinjiang-2025" class="csl-entry" role="listitem">
Tianshannet. (2025). <em>Xinjiang leads china in oil and gas output for fourth consecutive year</em>. <a href="https://english.ts.cn/system/2025/02/24/036951331.shtml">https://english.ts.cn/system/2025/02/24/036951331.shtml</a>
</div>
<div id="ref-eia-midong-2024" class="csl-entry" role="listitem">
U.S. Energy Information Administration. (2024). <em>Today in energy: World’s largest solar plant in xinjiang</em>. <a href="https://www.eia.gov/todayinenergy/detail.php?id=65064">https://www.eia.gov/todayinenergy/detail.php?id=65064</a>
</div>
<div id="ref-wikipedia-hami-zhengzhou" class="csl-entry" role="listitem">
Wikipedia. (2024a). <em>Southern hami–zhengzhou UHVDC</em>. <a href="https://en.wikipedia.org/wiki/Southern_Hami%E2%80%93Zhengzhou_UHVDC">https://en.wikipedia.org/wiki/Southern_Hami%E2%80%93Zhengzhou_UHVDC</a>
</div>
<div id="ref-wikipedia-west-east" class="csl-entry" role="listitem">
Wikipedia. (2024b). <em>West–east gas pipeline</em>. <a href="https://en.wikipedia.org/wiki/West%E2%80%93East_Gas_Pipeline">https://en.wikipedia.org/wiki/West%E2%80%93East_Gas_Pipeline</a>
</div>
<div id="ref-xinhua-xinjiang-coal-2024" class="csl-entry" role="listitem">
Xinhua. (2024). <em>Xinjiang coal output reaches 540 million tonnes, up 17.5 percent</em>. <a href="http://english.news.cn/20240930/b4b0fe4148b64fc597a472f3ebf1df2c/c.html">http://english.news.cn/20240930/b4b0fe4148b64fc597a472f3ebf1df2c/c.html</a>
</div>
<div id="ref-xinhua-deepest-well-2025" class="csl-entry" role="listitem">
Xinhua. (2025a). <em>Shenditake-1 reaches 10,910 metres, asia’s deepest well</em>. <a href="https://english.news.cn/20250220/e60a3888cf2744e4b10f73ff81477171/c.html">https://english.news.cn/20250220/e60a3888cf2744e4b10f73ff81477171/c.html</a>
</div>
<div id="ref-xinhua-tarim-gas-2025" class="csl-entry" role="listitem">
Xinhua. (2025b). <em>Tarim oilfield delivers record gas to southern xinjiang and the west-east pipeline</em>. <a href="https://english.news.cn/20250108/f16ae075bd0240c79d730f5f4fc88ec5/c.html">https://english.news.cn/20250108/f16ae075bd0240c79d730f5f4fc88ec5/c.html</a>
</div>
<div id="ref-xinhua-dabancheng-2026" class="csl-entry" role="listitem">
Xinhua. (2026a). <em>Dabancheng, china’s wind valley, near urumqi</em>. <a href="https://english.news.cn/20260127/86ae6f86f3254256b1d6c14a211458e7/c.html">https://english.news.cn/20260127/86ae6f86f3254256b1d6c14a211458e7/c.html</a>
</div>
<div id="ref-xinhua-xinjiang-export-2026" class="csl-entry" role="listitem">
Xinhua. (2026b). <em>Xinjiang power exports and wind capacity, 2025</em>. <a href="https://english.news.cn/20260127/1345f3a81b45409e985c5862a9412679/c.html">https://english.news.cn/20260127/1345f3a81b45409e985c5862a9412679/c.html</a>
</div>
<div id="ref-yicai-xinjiang-rail-coal" class="csl-entry" role="listitem">
Yicai Global. (2024a). <em>China’s fastest-growing coal region xinjiang boosted train transport by 49%</em>. <a href="https://www.yicaiglobal.com/news/chinas-fastest-growing-coal-region-xinjiang-boosted-train-transport-by-49-jan-may">https://www.yicaiglobal.com/news/chinas-fastest-growing-coal-region-xinjiang-boosted-train-transport-by-49-jan-may</a>
</div>
<div id="ref-yicai-jiuquan-2024" class="csl-entry" role="listitem">
Yicai Global. (2024b). <em>Jiuquan, gansu province’s key new-energy industrial hub</em>. <a href="https://www.yicaiglobal.com/news/jiuquan-gansu-provinces-key-new-energy-industrial-hub">https://www.yicaiglobal.com/news/jiuquan-gansu-provinces-key-new-energy-industrial-hub</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/itkservices3\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024 ITK admin@itkservices.com.au</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>