<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Leitch">
<meta name="dcterms.date" content="2026-01-21">

<title>Australian Electric Vehicle Policy Reviews - 2026 – ITK Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../ITK_logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-d96a739641c07e2640703e5ad7a4e5f4.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-86c03801c75847bd115b064e8b296803.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script defer="" data-domain="itkservices3.com" src="https://plausible.io/js/script.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Australian Electric Vehicle Policy Reviews - 2026 – ITK Research">
<meta property="og:description" content="Electricity markets analysis">
<meta property="og:image" content="https://itkservices3.com/media/image-20260121091748742.png">
<meta property="og:site_name" content="ITK Research">
<meta property="og:image:height" content="2362">
<meta property="og:image:width" content="4224">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../ITK_logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ITK Research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dashboards-(load-slow" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Dashboards (load slow)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dashboards-(load-slow">    
        <li>
    <a class="dropdown-item" href="../IEA.html">
 <span class="dropdown-text">IEA-electricity</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../nemgen.html">
 <span class="dropdown-text">NEM-ITK</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../forecast.html">
 <span class="dropdown-text">AEMO demand fcst</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../posts.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">more</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more">    
        <li>
    <a class="dropdown-item" href="../windy.html">
 <span class="dropdown-text">Temperature Forecast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../green_iron/index.html">
 <span class="dropdown-text">Green Iron</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentations.html">
 <span class="dropdown-text">Presentations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../background.html">
 <span class="dropdown-text">Background notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../energyinsiders.html">
 <span class="dropdown-text">Energy Insiders</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../posts.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../mailchimp.html"> 
<span class="menu-text">Signup</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Australian Electric Vehicle Policy Reviews - 2026</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">EVs</div>
                <div class="quarto-category">Policy</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>David Leitch </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 21, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#its-replacing-40-bn-of-annual-oil-imports-stupid" id="toc-its-replacing-40-bn-of-annual-oil-imports-stupid" class="nav-link active" data-scroll-target="#its-replacing-40-bn-of-annual-oil-imports-stupid">It’s replacing $40 bn of annual oil imports stupid</a>
  <ul class="collapse">
  <li><a href="#no-carbon-price-but-lots-of-federal-policy" id="toc-no-carbon-price-but-lots-of-federal-policy" class="nav-link" data-scroll-target="#no-carbon-price-but-lots-of-federal-policy">No carbon price but lots of Federal Policy</a></li>
  <li><a href="#carbon-scoreboard" id="toc-carbon-scoreboard" class="nav-link" data-scroll-target="#carbon-scoreboard">Carbon scoreboard</a></li>
  <li><a href="#oil-imports-are-a-net-40bn-say-6-of-all-imports" id="toc-oil-imports-are-a-net-40bn-say-6-of-all-imports" class="nav-link" data-scroll-target="#oil-imports-are-a-net-40bn-say-6-of-all-imports">Oil imports are a net $40bn say 6% of all imports</a></li>
  <li><a href="#we-are-falling-behind-asia-never-mind-europe" id="toc-we-are-falling-behind-asia-never-mind-europe" class="nav-link" data-scroll-target="#we-are-falling-behind-asia-never-mind-europe">We are falling behind Asia! Never mind Europe</a>
  <ul class="collapse">
  <li><a href="#global-ev-market-share-rankings-2025" id="toc-global-ev-market-share-rankings-2025" class="nav-link" data-scroll-target="#global-ev-market-share-rankings-2025">Global EV Market Share Rankings (2025)</a></li>
  <li><a href="#policy-configuration-by-market" id="toc-policy-configuration-by-market" class="nav-link" data-scroll-target="#policy-configuration-by-market">Policy Configuration by Market</a></li>
  <li><a href="#consumer-incentive-values-by-market" id="toc-consumer-incentive-values-by-market" class="nav-link" data-scroll-target="#consumer-incentive-values-by-market">Consumer Incentive Values by Market</a></li>
  <li><a href="#key-research-conclusions" id="toc-key-research-conclusions" class="nav-link" data-scroll-target="#key-research-conclusions">Key Research Conclusions</a></li>
  </ul></li>
  <li><a href="#what-works-country-insights" id="toc-what-works-country-insights" class="nav-link" data-scroll-target="#what-works-country-insights">What Works: Country Insights</a>
  <ul class="collapse">
  <li><a href="#the-key-lesson" id="toc-the-key-lesson" class="nav-link" data-scroll-target="#the-key-lesson">The Key Lesson</a></li>
  <li><a href="#country-by-country-insights" id="toc-country-by-country-insights" class="nav-link" data-scroll-target="#country-by-country-insights">Country-by-Country Insights</a></li>
  </ul></li>
  <li><a href="#chinas-dual-credit-system-a-model-for-mandates" id="toc-chinas-dual-credit-system-a-model-for-mandates" class="nav-link" data-scroll-target="#chinas-dual-credit-system-a-model-for-mandates">China’s Dual Credit System: A Model for Mandates</a>
  <ul class="collapse">
  <li><a href="#how-it-works" id="toc-how-it-works" class="nav-link" data-scroll-target="#how-it-works">How It Works</a></li>
  <li><a href="#why-it-works" id="toc-why-it-works" class="nav-link" data-scroll-target="#why-it-works">Why It Works</a></li>
  <li><a href="#government-investment-scale" id="toc-government-investment-scale" class="nav-link" data-scroll-target="#government-investment-scale">Government Investment Scale</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="ev_policy_map.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="its-replacing-40-bn-of-annual-oil-imports-stupid" class="level1">
<h1>It’s replacing $40 bn of annual oil imports stupid</h1>
<p>There are lots of sound reasons for Australia to go hard on EVs, much harder than it currently does. But the number one reason that should appeal to Treasury is we get the equivalent of a new export industry. Replacing oil imports is pretty much the same as increasing exports. Why go through all the pain of having new LNG facilities and new coal mines when we can just kill oil imports and get a lot of votes in the process? Of the three main policy reviews this year—(i) safeguards, (ii) EV FBT concession and (iii) EV strategy—it’s the third that provides the biggest opportunity to improve Australia, to win votes, to increase the average Australian’s wealth via a stronger $, to decarbonise a significant sector, to reduce strategic risk and to increase public health.</p>
<p>In this note we cover what policy works and the sequencing that Australia’s EV strategy review of the 2023 policy should implement. It requires going much harder on charging infrastructure, and building future proof infrastructure, ie over powering, then providing consumer incentives, like the FBT but available to all, to close the price gap. Home batteries showed how this can take off. State driven cheap incentive like bus lanes and rego can further drive consumer demand but provide sunset clauses. As consumer demand grows force a supply response via a mandate. In Asia, countries have seen it as in their national interest to promote EV manufacturing as a way to grow a new industry at the expense of traditional manufacturers like Japan. China, Vietnam and via partnerships Thailand have gone this way.</p>
<p>China has provided arguably between US$200 bn and US$300 bn of subsidies to its EV car manufacturers. The ethics of this are one thing but Australia should take advantage of those subsidies to accelerate EV adoption in Australia. Effectively, China pays for our cars. We shouldn’t look this gift horse in the mouth—just use Australian policy to accelerate adoption.</p>
<p>One policy option that emerges from this research is to exempt EVs from GST.</p>
<div id="fig-oil-imports" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-oil-imports-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../media/image-20260121091748742.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Oil imports value"><img src="../media/image-20260121091748742.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-oil-imports-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Oil imports value
</figcaption>
</figure>
</div>
<section id="no-carbon-price-but-lots-of-federal-policy" class="level2">
<h2 class="anchored" data-anchor-id="no-carbon-price-but-lots-of-federal-policy">No carbon price but lots of Federal Policy</h2>
<p>In 2026 there are three known official Federal Government policy reviews for which the outcome is uncertain. One, the EV FBT exemption review is “live” whereas the Safeguard Mechanism and the National EV strategy reviews are yet to formally commence. I expect there are also ongoing informal reviews, particularly of the effectiveness of the CIS in actually inducing new supply, then there is the Tomago-Snowy “back channel” policy.</p>
<p>On top of what the Federal Government is officially and even unofficially, there are also significant AEMC reviews and of course all the States have a bunch of policies and reviews. Overview of Federal Review</p>
<p><strong>Summary of Federal Energy Policy Reviews</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Review</th>
<th>Status</th>
<th>Submissions</th>
<th style="text-align: center;">Published</th>
<th>Agency</th>
<th>Key Focus</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="#gas-market">Gas Market</a></td>
<td>Implementation</td>
<td>Not open</td>
<td style="text-align: center;">✗</td>
<td>DCCEEW/DISR/ACCC</td>
<td>Domestic reservation scheme (15-25%); LNG netback methodology</td>
</tr>
<tr class="even">
<td><a href="#default-market-offer-dmo-implementation">DMO Framework</a></td>
<td>Implementation</td>
<td>Closed</td>
<td style="text-align: center;">✓</td>
<td>AER</td>
<td>Electricity price caps; tariff caps; embedded networks; Solar Sharer Offer</td>
</tr>
<tr class="odd">
<td><a href="#nem-wholesale-market-settings-review">NEM Wholesale Market</a></td>
<td>Implementation</td>
<td>Closed</td>
<td style="text-align: center;">✓</td>
<td>Energy Ministers</td>
<td>Market liquidity; Market-Making Obligation; ESEM</td>
</tr>
<tr class="even">
<td><a href="#cheaper-home-batteries-program">Cheaper Home Batteries</a></td>
<td>Active</td>
<td>N/A</td>
<td style="text-align: center;">—</td>
<td>DCCEEW</td>
<td>~200k installations; $7.2B program; 2M batteries by 2030</td>
</tr>
<tr class="odd">
<td><a href="#electric-car-discount-review">Electric Car Discount</a></td>
<td>Review</td>
<td>Open</td>
<td style="text-align: center;">✗</td>
<td>Treasury/DCCEEW</td>
<td>FBT exemption effectiveness; $1.35B cost; PHEV eligibility</td>
</tr>
<tr class="even">
<td><a href="#national-electric-vehicle-strategy-review">National EV Strategy</a></td>
<td>Pending</td>
<td>Not open</td>
<td style="text-align: center;">✗</td>
<td>DCCEEW</td>
<td>Uptake progress; charging infrastructure; regional equity</td>
</tr>
<tr class="odd">
<td><a href="#safeguard-mechanism-review">Safeguard Mechanism</a></td>
<td>Pending</td>
<td>Not open</td>
<td style="text-align: center;">✗</td>
<td>DCCEEW</td>
<td>Post-2030 decline rates; offset limits; 2035 NDC alignment</td>
</tr>
</tbody>
</table>
<p><em>Source: Author compilation from government announcements</em></p>
<p>Much of this policy could have been minimised if Australia had stuck with the carbon tax. Abolishing the tax has in the end achieved little, coal generators are still going to close, EVs are still slowly gaining market share, renewable generation has grown steadily and it’s likely the seeds for further growth, in the form of FID for several GW of renewables, will be planted this year. The required transmission upgrades are mostly proceeding.</p>
<p>If we had done some of this work back when the carbon tax was in place and stayed ahead of the rest of the world it would have been a lot cheaper but to be fair the delay has enabled technology solutions like inverter based grids to move out of the lab into the actual grid.</p>
</section>
<section id="carbon-scoreboard" class="level2">
<h2 class="anchored" data-anchor-id="carbon-scoreboard">Carbon scoreboard</h2>
<p>Although you can make excuses about carbon by relating emissions to population and/or GDP, in the end the physics of carbon are driven entirely by the longer wave infrared absorption and rejection of the carbon in the atmosphere. More carbon more global warming, population and GDP be damned.</p>
<p>Equally I have excluded land use and forestry from the Australian scorecard because I think they are used to make it seem that Australia is making more progress than it actually is.</p>
<div id="fig-carbon-scorecard" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-carbon-scorecard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../media/image-20260120205448751.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: Australian emissions by sector"><img src="../media/image-20260120205448751.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-carbon-scorecard-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Australian emissions by sector
</figcaption>
</figure>
</div>
<p>Essentially there is progress in electricity but almost nowhere else. As electricity emissions come down the relative importance of Transport, stationary energy and agriculture will increase.</p>
<p>In general the accepted policy for decarbonisation in Australia is the same as for every other country. Decarbonise electricity, then electrify everything. National EV strategy is the economic opportunity.</p>
<p>This note focuses on the EV-related reviews. There are two separate reviews. In essence the FBT is a subset of the EV strategy. I write from the point of view of a household with two EVs and regular long distance trips, not just to capital cities but to regional NSW and Victoria, over 80,000 EV km so far.</p>
<p>In my view over and beyond pollution a higher EV share should be on the priority list for Australia because: (1) Our climate, generally temperate, and terrain, mostly flat, are ideal for EVs. (2) We have no domestic car industry so there is no manufacturing industry to protect, (3) Australia has lots of oil imports which are both a strategic risk in the time of conflict and hurt our trade balance, (4) China has a surplus of EVs and wants to sell them to us, we should strike while the iron is hot.</p>
<p>Like everyone else who looks at decarbonisation seriously you would conclude that from an economics and efficiency point of view a carbon price or carbon tax is clearly the correct choice. But as ever politics have degraded us to the point where second best policies are the tools available.</p>
</section>
<section id="oil-imports-are-a-net-40bn-say-6-of-all-imports" class="level2">
<h2 class="anchored" data-anchor-id="oil-imports-are-a-net-40bn-say-6-of-all-imports">Oil imports are a net $40bn say 6% of all imports</h2>
<p>Let’s forget about climate and look at Australia’s trade balance. As everyone knows our main exports are iron ore, coal, LNG and tourism. We are the world’s top 3 thermal energy exporters, maybe 4 these days. It’s proving difficult to find industries that can replace thermal energy exports but another alternative is to reduce imports and oil is the main target. Importing EVs doesn’t do anything to the trade balance because we already import all the cars we sell. So we get to reduce imports by around $40 bn per year, let’s say $500 bn of net present value at zero cost. Our trade surplus would increase substantially.</p>
<div id="fig-trade-balance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-trade-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../media/image-20260120212141077.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;3: Australia trade balance"><img src="../media/image-20260120212141077.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-trade-balance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Australia trade balance
</figcaption>
</figure>
</div>
<p>You almost can’t say this enough: reducing imports is just as beneficial to Australia as increasing exports.</p>
</section>
<section id="we-are-falling-behind-asia-never-mind-europe" class="level2">
<h2 class="anchored" data-anchor-id="we-are-falling-behind-asia-never-mind-europe">We are falling behind Asia! Never mind Europe</h2>
<p>It’s easy to look at the global car market and think we are doing OK on EV adoption. Even so look at the hit the ICE car industry has already taken over the past decade. In 2018 sales were 94 million, now down to 78 million, that’s a really big drop. But looking at the global market completely misses the point. We aren’t competing with the USA or Japan. Japan is stuck in incumbent mode and the USA is run by a cognitively challenged leader.</p>
<p>We need to compare ourselves with the EV leaders, not the incumbents. France, Italy, Germany, Japan, USA all have to protect their domestic industries, just like we subsidise outdated smelters. We don’t need to subsidise Japanese and German carmakers in Australia.</p>
<div id="fig-global-ev-market" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-global-ev-market-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../media/image-20260121095015968.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;4: Global EV market trends"><img src="../media/image-20260121095015968.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-global-ev-market-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Global EV market trends
</figcaption>
</figure>
</div>
<section id="global-ev-market-share-rankings-2025" class="level3">
<h3 class="anchored" data-anchor-id="global-ev-market-share-rankings-2025">Global EV Market Share Rankings (2025)</h3>
<p><strong>Top 10 Countries by EV Market Share (2025)</strong></p>
<table class="table">
<colgroup>
<col style="width: 4%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Rank</th>
<th>Country</th>
<th style="text-align: right;">BEV+PHEV Share</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td>Norway</td>
<td style="text-align: right;">92%</td>
<td>Target: 100% ZEV sales by 2025</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td>Denmark</td>
<td style="text-align: right;">67%</td>
<td>Up from 56% in 2024</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td>Sweden</td>
<td style="text-align: right;">61%</td>
<td>Strong fleet incentives</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td>Netherlands</td>
<td style="text-align: right;">55%</td>
<td>Highest charging density in Europe</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td>China</td>
<td style="text-align: right;">~50%</td>
<td>Largest market by volume (11M+ sales of pure electric)</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td>Finland</td>
<td style="text-align: right;">50%</td>
<td>-</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td>Vietnam</td>
<td style="text-align: right;">~40%</td>
<td>Driven by domestic manufacturer VinFast</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td>Iceland</td>
<td style="text-align: right;">29%</td>
<td>Small market, strong growth</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td>EU average</td>
<td style="text-align: right;">~25%</td>
<td>~4 million sales expected in 2025</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td>Thailand</td>
<td style="text-align: right;">20%</td>
<td>Up from 1% in 2019</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-</td>
<td><strong>Australia</strong></td>
<td style="text-align: right;"><strong>12.6%</strong></td>
<td>BEV only: 8.3%</td>
</tr>
<tr class="even">
<td style="text-align: right;">-</td>
<td>United States</td>
<td style="text-align: right;">~11%</td>
<td>Growth stalled at 2024 levels</td>
</tr>
<tr class="odd">
<td style="text-align: right;">-</td>
<td>India</td>
<td style="text-align: right;">~5%</td>
<td>Rapid growth from low base</td>
</tr>
</tbody>
</table>
<p><em>Source: IEA Global EV Outlook 2025; ICCT European Market Monitor</em></p>
<p><strong>Key observations:</strong></p>
<ul>
<li>Australia’s 12.6% (BEV+PHEV) places it below the EU average but above the US</li>
<li>The gap between leaders (Norway 92%) and laggards reflects policy intensity</li>
<li>Emerging markets (Vietnam, Thailand, India) are growing faster than mature markets</li>
</ul>
<p>Looking at the TV you might think the USA is the only country in the world, but in fact what mainly comes out of the USA these days is propaganda and like Odysseus with the Sirens, we need to block our ears to the USA and focus on keeping up in our own backyard.</p>
</section>
<section id="policy-configuration-by-market" class="level3">
<h3 class="anchored" data-anchor-id="policy-configuration-by-market">Policy Configuration by Market</h3>
<p><strong>EV Market Share and Policy Configuration</strong></p>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 20%">
<col style="width: 23%">
<col style="width: 13%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Market</th>
<th>EV Share</th>
<th>Supply Mandate</th>
<th>Tax Differential</th>
<th>Infrastructure</th>
<th>Driving Privileges</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Norway</td>
<td>92%</td>
<td>No (incentives-led)</td>
<td>70%+ ICE premium</td>
<td>High</td>
<td>Bus lanes, tolls, parking</td>
</tr>
<tr class="even">
<td>China</td>
<td>51%</td>
<td>Yes (NEV credits)</td>
<td>Moderate</td>
<td>Very high</td>
<td>License plates, driving bans</td>
</tr>
<tr class="odd">
<td>Netherlands</td>
<td>55%</td>
<td>EU CO₂ std</td>
<td>High (BPM tax)</td>
<td>Highest in EU</td>
<td>LEZ/ZEZ, parking priority</td>
</tr>
<tr class="even">
<td>Denmark</td>
<td>67%</td>
<td>EU CO₂ std</td>
<td>Very high (150%+ tax)</td>
<td>High</td>
<td>—</td>
</tr>
<tr class="odd">
<td>Thailand</td>
<td>20%</td>
<td>Production requirement</td>
<td>Excise differential</td>
<td>Growing</td>
<td>None</td>
</tr>
<tr class="even">
<td>Vietnam</td>
<td>40%</td>
<td>No (VinFast-led)</td>
<td>Consumption tax diff</td>
<td>VinFast network</td>
<td>Planned</td>
</tr>
<tr class="odd">
<td>Australia</td>
<td>12.6%</td>
<td>NVES (CO₂ only)</td>
<td>None</td>
<td>Lagging</td>
<td><strong>None</strong></td>
</tr>
<tr class="even">
<td>USA</td>
<td>9%</td>
<td>CA ZEV (some states)</td>
<td>Federal credit (uncertain)</td>
<td>Growing</td>
<td>HOV (some states)</td>
</tr>
</tbody>
</table>
<p><em>Source: IEA Global EV Outlook 2025; ICCT; author compilation</em></p>
</section>
<section id="consumer-incentive-values-by-market" class="level3">
<h3 class="anchored" data-anchor-id="consumer-incentive-values-by-market">Consumer Incentive Values by Market</h3>
<p><strong>Estimated Total Consumer Benefit (AUD equivalent)</strong></p>
<table class="table">
<colgroup>
<col style="width: 10%">
<col style="width: 20%">
<col style="width: 31%">
<col style="width: 20%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Market</th>
<th style="text-align: right;">Direct Subsidy</th>
<th style="text-align: right;">Tax/Registration Saving</th>
<th style="text-align: right;">Other Benefits</th>
<th style="text-align: right;">Total Benefit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Norway</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">~$50,000 (purchase tax exemption)</td>
<td style="text-align: right;">VAT ~$5,000; tolls, parking</td>
<td style="text-align: right;"><strong>~$55,000+</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Denmark</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">~$40,000 (150%+ registration tax avoided)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;"><strong>~$40,000</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: right;">~$6,000</td>
<td style="text-align: right;">Varies by city</td>
<td style="text-align: right;">License plate ~$20,000 (Shanghai)</td>
<td style="text-align: right;"><strong>$6,000–26,000</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Vietnam</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">~$4,000 (consumption tax diff)</td>
<td style="text-align: right;">Registration ~$6,000</td>
<td style="text-align: right;"><strong>~$10,000</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Thailand</td>
<td style="text-align: right;">~$4,000</td>
<td style="text-align: right;">~$2,000 (excise differential)</td>
<td style="text-align: right;">Import duty reduction</td>
<td style="text-align: right;"><strong>~$6,000</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Netherlands</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">High (BPM tax differential)</td>
<td style="text-align: right;">LEZ access, parking</td>
<td style="text-align: right;"><strong>~$15,000+</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Australia</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">~$9,000 (FBT, if eligible)</td>
<td style="text-align: right;">No GST or rego exemption</td>
<td style="text-align: right;"><strong>$0–9,000</strong></td>
</tr>
</tbody>
</table>
<p><em>Source: Author compilation from country sources. Values are indicative and vary by vehicle price and buyer circumstances.</em></p>
<p><strong>Note on Australia</strong>: Unlike Norway (25% VAT exemption) and Denmark (registration tax exemption), Australia offers no exemption from GST (10%) or registration fees for EVs. A GST exemption would save ~$4,500 on a $50,000 EV and align with the tax-exemption approach that has driven high adoption elsewhere.</p>
</section>
<section id="key-research-conclusions" class="level3">
<h3 class="anchored" data-anchor-id="key-research-conclusions">Key Research Conclusions</h3>
<ol type="1">
<li><p><strong>Infrastructure investment is 4-7x more cost-effective than purchase subsidies</strong> - redirecting subsidy spending to charging networks yields higher adoption rates <span class="citation" data-cites="world-bank-ev-2022 cmu-ev-infrastructure-2025">(<a href="#ref-cmu-ev-infrastructure-2025" role="doc-biblioref">Michalek et al., 2025</a>; <a href="#ref-world-bank-ev-2022" role="doc-biblioref">World Bank, 2022</a>)</span></p></li>
<li><p><strong>ZEV mandates provide certainty that subsidies cannot</strong> - manufacturers respond to binding requirements; subsidy-only approaches require unsustainably high levels ($40,000/vehicle) to achieve equivalent outcomes <span class="citation" data-cites="acs-zev-subsidies-2025">(<a href="#ref-acs-zev-subsidies-2025" role="doc-biblioref">American Chemical Society, 2025</a>)</span></p></li>
<li><p><strong>Policy complementarity matters</strong> - subsidies and infrastructure reinforce each other; weakening one policy reduces effectiveness of others <span class="citation" data-cites="rff-ev-investments-2025">(<a href="#ref-rff-ev-investments-2025" role="doc-biblioref">Resources for the Future, 2025</a>)</span></p></li>
<li><p><strong>Tax differentials outperform direct subsidies</strong> - Norway’s tax exemptions (worth 70% of ICE price) and Denmark’s registration tax system create sustained price signals without ongoing fiscal cost <span class="citation" data-cites="norwegian-ev-association oecd-norway-2021">(<a href="#ref-norwegian-ev-association" role="doc-biblioref">Norwegian EV Association, 2025</a>; <a href="#ref-oecd-norway-2021" role="doc-biblioref">OECD, 2021</a>)</span></p></li>
<li><p><strong>Driving privileges provide additional adoption incentive</strong> - license plate priority (China), bus lane access (Norway), and LEZ exemptions (EU) reduce ownership friction, with measurable adoption effects <span class="citation" data-cites="icct-china-city-2023 jenn-hov-2018">(<a href="#ref-icct-china-city-2023" role="doc-biblioref">International Council on Clean Transportation, 2023</a>; <a href="#ref-jenn-hov-2018" role="doc-biblioref">Jenn et al., 2018</a>)</span></p></li>
<li><p><strong>Australia’s policy mix is suboptimal</strong> - demand-side only (FBT exemption benefiting high earners), no binding supply mandate, no ICE tax differential, no driving privileges, lagging infrastructure. This configuration is <strong>least cost-effective</strong> among comparable markets.</p></li>
</ol>
<hr>
</section>
</section>
<section id="what-works-country-insights" class="level2">
<h2 class="anchored" data-anchor-id="what-works-country-insights">What Works: Country Insights</h2>
<section id="the-key-lesson" class="level3">
<h3 class="anchored" data-anchor-id="the-key-lesson">The Key Lesson</h3>
<p>The high-adoption markets share a common feature: <strong>they exempted EVs from pre-existing high taxes on vehicles</strong>. Norway’s 25% VAT and 45% registration tax, Denmark’s 150%+ registration tax, and China’s license plate restrictions all predated EV policy—some by decades. Norway taxed cars as “luxury goods” from the 1960s; Denmark’s registration tax dates to 1924. These countries didn’t introduce new punitive taxes on ICE vehicles—they leveraged existing ones by exempting EVs.</p>
<p>This distinction matters for Australia. Behavioural research shows punishments have 2-3x the impact of rewards, but political research shows the opposite for acceptability: subsidies are seen as “giving money” while taxes are seen as “taking money.” Australia’s carbon tax experience confirms this asymmetry. The politically feasible path is exemption from existing taxes, not new taxes on ICE.</p>
<p><strong>Australia’s opportunity</strong>: A GST exemption for EVs would mirror the VAT exemptions that drove adoption in Norway and the EU. At 10%, it’s smaller than Norway’s 25% VAT, but on a $50,000 EV it would save ~$4,500—a meaningful incentive.</p>
</section>
<section id="country-by-country-insights" class="level3">
<h3 class="anchored" data-anchor-id="country-by-country-insights">Country-by-Country Insights</h3>
<p><strong>Norway (92%)</strong> — Thirty years of policy consistency with no domestic car industry to protect. The key is exemption from <em>pre-existing high taxes</em> (25% VAT + 45% registration tax dating from the 1960s). Removing tax exemptions would drop EV share from 66% to 25%. Bus lane access and toll exemptions provide daily reinforcement.</p>
<p><strong>Denmark/Netherlands (55-67%)</strong> — Tax differential through exemption: EVs avoid registration taxes that have applied to vehicles since 1924 (Denmark) and high BPM taxes (Netherlands). No direct subsidies required—exemption from pre-existing taxes does the work. Netherlands has Europe’s highest charging density.</p>
<p><strong>China (51%)</strong> — Scale plus mandate. The Dual Credit System forces manufacturers to produce EVs or buy credits from competitors—they cannot simply pay a fine. License plate restrictions in major cities (Shanghai plate costs ~$20,000 at auction, NEV plates are free) provide powerful city-level incentives. Per-vehicle subsidies have <em>declined</em> from $13,860 (2018) to under $4,600 (2023) as the market matured.</p>
<p><strong>Vietnam (~40%)</strong> — The VinFast effect: a single dominant domestic manufacturer can drive adoption faster than policy alone. Registration fee exemption saves buyers ~$6,000 per vehicle. Aggressive targets (all new buses electric from 2025, all new taxis from 2030) signal government commitment.</p>
<p><strong>Thailand (1% → 20%)</strong> — Manufacturing-linked incentives work. Companies must offset imported vehicles with local production at 1:2 ratio by 2026 and 1:3 by 2027. This attracted Chinese manufacturers to build factories in Thailand rather than simply export. The 30@30 target (30% BEV production by 2030) signals long-term commitment.</p>
<hr>
</section>
</section>
<section id="chinas-dual-credit-system-a-model-for-mandates" class="level2">
<h2 class="anchored" data-anchor-id="chinas-dual-credit-system-a-model-for-mandates">China’s Dual Credit System: A Model for Mandates</h2>
<p>China’s policy is worth examining in detail because it demonstrates how supply-side mandates can complement demand-side incentives.</p>
<section id="how-it-works" class="level3">
<h3 class="anchored" data-anchor-id="how-it-works">How It Works</h3>
<p>The “Dual Credit” system combines two requirements <span class="citation" data-cites="icct-china-2022">(<a href="#ref-icct-china-2022" role="doc-biblioref">International Council on Clean Transportation, 2022</a>)</span>:</p>
<p><strong>Component 1: Corporate Average Fuel Consumption (CAFC) Credits</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Year</th>
<th style="text-align: right;">Target (L/100km)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2020</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="even">
<td>2025</td>
<td style="text-align: right;">4.0</td>
</tr>
</tbody>
</table>
<p><em>Source: ICCT</em></p>
<p>NEVs count as zero fuel consumption, helping manufacturers meet CAFC targets.</p>
<p><strong>Component 2: NEV Credit Mandate</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Year</th>
<th style="text-align: right;">NEV Credit Requirement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2023</td>
<td style="text-align: right;">18%</td>
</tr>
<tr class="even">
<td>2024</td>
<td style="text-align: right;">28%</td>
</tr>
<tr class="odd">
<td>2025</td>
<td style="text-align: right;">38%</td>
</tr>
<tr class="even">
<td>2026</td>
<td style="text-align: right;">48%</td>
</tr>
<tr class="odd">
<td>2027</td>
<td style="text-align: right;">58%</td>
</tr>
</tbody>
</table>
<p><em>Source: ICCT; Ministry of Industry and Information Technology</em></p>
</section>
<section id="why-it-works" class="level3">
<h3 class="anchored" data-anchor-id="why-it-works">Why It Works</h3>
<ul>
<li>Manufacturers <strong>cannot simply pay a fine</strong>—they must produce NEVs or buy credits from competitors</li>
<li>Links fuel economy compliance to NEV production (surplus NEV credits can offset CAFC deficits)</li>
<li>Creates technology competition (credits tied to performance metrics, not just sales)</li>
<li>Ratchets up annually, forcing continuous improvement</li>
<li>Credits can be traded—creating a market where EV-focused companies (like BYD) can sell credits to laggards</li>
</ul>
</section>
<section id="government-investment-scale" class="level3">
<h3 class="anchored" data-anchor-id="government-investment-scale">Government Investment Scale</h3>
<p><strong>China Government Support for NEV Industry</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Period</th>
<th style="text-align: right;">Estimated Support</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2009-2022 (subsidies + tax breaks)</td>
<td style="text-align: right;">$40-60 billion AUD</td>
</tr>
<tr class="even">
<td>2009-2023 (all support types)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></td>
<td style="text-align: right;">$230 billion USD</td>
</tr>
<tr class="odd">
<td>2024-2027 (tax incentive package)</td>
<td style="text-align: right;">$105 billion AUD</td>
</tr>
</tbody>
</table>
<p><em>Source: CSIS; Ministry of Industry and Information Technology</em></p>
<hr>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li><p><a href="https://blogs.worldbank.org/en/transport/if-you-build-it-they-will-come-lessons-first-decade-electric-vehicles">If You Build It, They Will Come: Lessons from the First Decade of Electric Vehicles</a> — Rode et al., World Bank, 2022. Analysis finding charging infrastructure explains 69% of cross-country EV share variance vs 17% for subsidies; infrastructure investment is 4-7x more cost-effective than subsidies.</p></li>
<li><p><a href="https://www.cmu.edu/tepper/news/stories/2025/0522-should-government-incentivize-ev-adoption-through-consumer-tax-credits-or-infrastructure">Should Government Incentivize EV Adoption Through Consumer Tax Credits or Infrastructure?</a> — Carnegie Mellon University Tepper School of Business, 2025. Research finding redirecting funds from tax credits to charging infrastructure could increase EV adoption by 26% and reduce emissions by 51%.</p></li>
<li><p><a href="https://pubs.acs.org/doi/10.1021/acs.est.4c11772">Subsidies, Standards, or Both? Trade-Offs among Policies for 100% Zero-Emissions Vehicle Sales</a> — Axsen &amp; Bhardwaj, Environmental Science &amp; Technology, 2025. Finding ZEV mandates cost $50-150/tonne CO2e abated vs $450-820/tonne for subsidy-only approaches; subsidies require $40,000/vehicle to achieve 100% ZEV sales.</p></li>
<li><p><a href="https://www.rff.org/publications/working-papers/a-tale-of-two-investments-charging-stations-and-purchase-subsidies-for-ev-adoption/">A Tale of Two Investments: Charging Stations and Purchase Subsidies for EV Adoption</a> — Resources for the Future, 2025. Research demonstrating policy complementarity: charging station density positively influences how important consumers consider purchase subsidies.</p></li>
<li><p><a href="https://elbil.no/english/norwegian-ev-policy/">Norwegian EV Policy</a> — Norwegian EV Association (Norsk elbilforening), 2025. Overview of Norway’s EV incentive package including VAT exemption, registration tax exemption, reduced tolls, and bus lane access.</p></li>
<li><p><a href="https://www.oecd.org/en/publications/ipac-policies-in-practice_22632907-en/norway-s-evolving-incentives-for-zero-emission-vehicles_22d2485b-en.html">Norway’s Evolving Incentives for Zero-Emission Vehicles</a> — OECD, 2021. Analysis of Norway’s fiscal incentives including exemption from registration tax, VAT, and motor fuel taxes; tax expenditure reached NOK 11.3 billion (USD 1.3 billion) in 2021.</p></li>
<li><p><a href="https://theicct.org/publication/pv-chinese-cities-nev-policies-feb23/">Accelerating New Energy Vehicle Uptake in Chinese Cities</a> — International Council on Clean Transportation, 2023. Assessment of city-level policies including preferential license plate access, traffic restriction exemptions, and use-phase incentives.</p></li>
<li><p><a href="https://www.sciencedirect.com/science/article/abs/pii/S0301421518302891">Effectiveness of electric vehicle incentives in the United States</a> — Jenn, Springel &amp; Gopal, Energy Policy, 2018. Research finding HOV lane access increases EV adoption by 4.7% per unit of lane density; every $1,000 rebate increases EV sales by 2.6%.</p></li>
<li><p><a href="https://theicct.org/china-dual-credit-policy-feb22/">How Will the Dual-Credit Policy Help China Boost New Energy Vehicle Growth?</a> — International Council on Clean Transportation, 2022. Explanation of China’s dual credit system where NEV credits can offset fuel consumption deficits but not vice versa, forcing manufacturers to produce EVs.</p></li>
</ol>



</section>
</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-acs-zev-subsidies-2025" class="csl-entry" role="listitem">
American Chemical Society. (2025). <em>Zero emission vehicle subsidies and market transformation</em>. ACS Publications. <a href="https://pubs.acs.org/">https://pubs.acs.org/</a>
</div>
<div id="ref-icct-china-2022" class="csl-entry" role="listitem">
International Council on Clean Transportation. (2022). <em>China’s new energy vehicle industrial development plan</em>. ICCT. <a href="https://theicct.org/">https://theicct.org/</a>
</div>
<div id="ref-icct-china-city-2023" class="csl-entry" role="listitem">
International Council on Clean Transportation. (2023). <em>China city-level electric vehicle policies</em>. ICCT. <a href="https://theicct.org/">https://theicct.org/</a>
</div>
<div id="ref-jenn-hov-2018" class="csl-entry" role="listitem">
Jenn, A., Springel, K., &amp; Gopal, A. R. (2018). Effectiveness of electric vehicle incentives in the united states. <em>Energy Policy</em>, <em>119</em>, 349–356. <a href="https://doi.org/10.1016/j.enpol.2018.04.065">https://doi.org/10.1016/j.enpol.2018.04.065</a>
</div>
<div id="ref-cmu-ev-infrastructure-2025" class="csl-entry" role="listitem">
Michalek, J. et al. (2025). <em>EV charging infrastructure cost-effectiveness analysis</em>. Carnegie Mellon University. <a href="https://www.cmu.edu/">https://www.cmu.edu/</a>
</div>
<div id="ref-norwegian-ev-association" class="csl-entry" role="listitem">
Norwegian EV Association. (2025). <em>Norwegian EV policy</em>. <a href="https://elbil.no/english/">https://elbil.no/english/</a>
</div>
<div id="ref-oecd-norway-2021" class="csl-entry" role="listitem">
OECD. (2021). <em>Norway’s electric vehicle policy review</em>. OECD Publishing. <a href="https://www.oecd.org/">https://www.oecd.org/</a>
</div>
<div id="ref-rff-ev-investments-2025" class="csl-entry" role="listitem">
Resources for the Future. (2025). <em>Electric vehicle investment complementarities</em>. Resources for the Future. <a href="https://www.rff.org/">https://www.rff.org/</a>
</div>
<div id="ref-world-bank-ev-2022" class="csl-entry" role="listitem">
World Bank. (2022). <em>Electric vehicle infrastructure: A guide for cities</em>. World Bank Group. <a href="https://www.worldbank.org/">https://www.worldbank.org/</a>
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>CSIS estimate includes direct subsidies, tax exemptions, government procurement, R&amp;D funding, and infrastructure investment.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script data-isso="//comentario3.itkservices2.com/" data-isso-css="true" data-isso-css-url="null" data-isso-lang="en" data-isso-max-comments-top="10" data-isso-max-comments-nested="5" data-isso-reveal-on-click="5" data-isso-avatar="false" data-isso-avatar-bg="#f0f0f0" data-isso-avatar-fg="#9abf88 #5698c4 #e279a3 #9163b6 ..." data-isso-vote="true" data-isso-vote-levels="" data-isso-page-author-hashes="f124cf6b2f01,7831fe17a8cd" data-isso-reply-notifications-default-enabled="false" src="https://comentario3.itkservices2.com/js/embed.min.js"></script>
        <section id="isso-thread" data-title="Test tag"></section>
   
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/itkservices3\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024 ITK admin@itkservices.com.au</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>