<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Leitch">
<meta name="dcterms.date" content="2026-03-06">

<title>Electrifying all road freight between Sydney and Melbourne is a no brainer - payback 2-4 years – ITK Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../ITK_logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-d96a739641c07e2640703e5ad7a4e5f4.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-86c03801c75847bd115b064e8b296803.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script defer="" data-domain="itkservices3.com" src="https://plausible.io/js/script.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Electrifying all road freight between Sydney and Melbourne is a no brainer - payback 2-4 years – ITK Research">
<meta property="og:description" content="Electricity markets analysis">
<meta property="og:image" content="https://itkservices3.com/media/bdouble_front_trailer_outline-2670384.jpg">
<meta property="og:site_name" content="ITK Research">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../ITK_logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ITK Research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dashboards-(load-slow" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Dashboards (load slow)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dashboards-(load-slow">    
        <li>
    <a class="dropdown-item" href="../IEA.html">
 <span class="dropdown-text">IEA-electricity</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../nemgen.html">
 <span class="dropdown-text">NEM-ITK</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../forecast.html">
 <span class="dropdown-text">AEMO demand fcst</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../posts.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">more</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more">    
        <li>
    <a class="dropdown-item" href="../windy.html">
 <span class="dropdown-text">Temperature Forecast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../green_iron/index.html">
 <span class="dropdown-text">Green Iron</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentations.html">
 <span class="dropdown-text">Presentations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../background.html">
 <span class="dropdown-text">Background notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../energyinsiders.html">
 <span class="dropdown-text">Energy Insiders</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../posts.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../mailchimp.html"> 
<span class="menu-text">Signup</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Electrifying all road freight between Sydney and Melbourne is a no brainer - payback 2-4 years</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">EVs</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>David Leitch </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">March 6, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#electrifying-all-road-freight-between-sydney-and-melbourne-is-a-no-brainer---payback-2-4-years" id="toc-electrifying-all-road-freight-between-sydney-and-melbourne-is-a-no-brainer---payback-2-4-years" class="nav-link active" data-scroll-target="#electrifying-all-road-freight-between-sydney-and-melbourne-is-a-no-brainer---payback-2-4-years">Electrifying all road freight between Sydney and Melbourne is a no brainer - payback 2-4 years</a>
  <ul class="collapse">
  <li><a href="#private-sector-or-policy" id="toc-private-sector-or-policy" class="nav-link" data-scroll-target="#private-sector-or-policy">Private sector or policy?</a></li>
  <li><a href="#the-tech-now-exists-to-electrify-60-tonne-double-bs" id="toc-the-tech-now-exists-to-electrify-60-tonne-double-bs" class="nav-link" data-scroll-target="#the-tech-now-exists-to-electrify-60-tonne-double-bs">The tech now exists to electrify 60 tonne double Bs</a></li>
  <li><a href="#really-exciting-economics-plus-the-other-benefits" id="toc-really-exciting-economics-plus-the-other-benefits" class="nav-link" data-scroll-target="#really-exciting-economics-plus-the-other-benefits">Really exciting economics plus the other benefits</a></li>
  <li><a href="#chinas-already-doing-it-and-they-will-get-better-fast." id="toc-chinas-already-doing-it-and-they-will-get-better-fast." class="nav-link" data-scroll-target="#chinas-already-doing-it-and-they-will-get-better-fast.">China’s already doing it and they will get better fast.</a>
  <ul class="collapse">
  <li><a href="#electric-energy-is-about-13-the-cost-of-diesel" id="toc-electric-energy-is-about-13-the-cost-of-diesel" class="nav-link" data-scroll-target="#electric-energy-is-about-13-the-cost-of-diesel">Electric energy is about 1/3 the cost of diesel</a></li>
  </ul></li>
  <li><a href="#electric-truck-capex-is-about-double-the-capital-cost-of-diesel-trucks." id="toc-electric-truck-capex-is-about-double-the-capital-cost-of-diesel-trucks." class="nav-link" data-scroll-target="#electric-truck-capex-is-about-double-the-capital-cost-of-diesel-trucks.">Electric truck capex is about double the capital cost of diesel trucks.</a></li>
  <li><a href="#the-megawatt-charging-standard-mcs" id="toc-the-megawatt-charging-standard-mcs" class="nav-link" data-scroll-target="#the-megawatt-charging-standard-mcs">The Megawatt Charging Standard (MCS)</a></li>
  <li><a href="#other-benefits" id="toc-other-benefits" class="nav-link" data-scroll-target="#other-benefits">Other benefits</a></li>
  <li><a href="#double-bs" id="toc-double-bs" class="nav-link" data-scroll-target="#double-bs">Double Bs</a></li>
  <li><a href="#tonnes-and-cubic-volume" id="toc-tonnes-and-cubic-volume" class="nav-link" data-scroll-target="#tonnes-and-cubic-volume">Tonnes and cubic volume</a>
  <ul class="collapse">
  <li><a href="#battery-weight" id="toc-battery-weight" class="nav-link" data-scroll-target="#battery-weight">Battery weight</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Longhaul.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="electrifying-all-road-freight-between-sydney-and-melbourne-is-a-no-brainer---payback-2-4-years" class="level1">
<h1>Electrifying all road freight between Sydney and Melbourne is a no brainer - payback 2-4 years</h1>
<p>Australia has a productivity opportunity by electrifying road freight on major corridors. The economic case has become outstandingly clear over the past couple of years and there are essentially no barriers. The payback period is 2-4 years depending on whether you’re replacing diesel trucks at end-of-life (2 years) or building the fleet from scratch (4 years).</p>
<ul>
<li>Battery powered trucks exist that can carry 60 tonnes, purpose designed with 450 km plus of range and capable of being recharged in an hour. They are better than diesel trucks in every way: quieter, much less polluting, faster, with fuel costs one-third of diesel, better equipped inside, and less maintenance required. Drivers love them.</li>
<li>An International Megawatt Charging Standard exists. That is you charge your 700 kWh battery at 1 MW, so 1 hour to charge.</li>
<li>Charging stations are emerging that take up to 50 or more trucks at a time. The biggest of these by Huawei has an input power capacity of 100 MW.</li>
</ul>
<p>About 22 mt per year of freight travels the 900 km between Sydney and Melbourne. It works to about 1.2 billion freight kilometres. When you work the fuel saving maths through, this means that if fully electrified, the industry would save about $0.9 bn per year in fuel costs plus the balance of trade , time savings, energy security and other benefits.</p>
<p>I estimate the capital costs to fully electrify at about $4 bn so a payback of under 5 years. But if you only count the incremental costs — that is, the charging stations and the extra cost of buying an electric semi over a diesel one — then the total incremental capex is about $2.5 bn and that’s a payback of less than 3 years.</p>
<p>In China about 200,000 electric semis are sold every year. It’s proven technology available pretty much off the shelf.</p>
<p>In other industries, eg electricity transmission, Australia has followed other countries and as a result we get caught up in the global rush when the whole world wants to do the same thing at one time. That pushes costs up, see eg transmission lines and transformers.</p>
<p>Australia has a very long freight distribution system, fully vulnerable to an oil supply disruption. Going early and committing fully to electrifying heavy transport and using the Sydney to Melbourne corridor as the proof of concept is a no brainer. An absolute no brainer. The economics are outstanding, the need is obvious.</p>
<p>If I have the sums wrong, or have missed something important I’m more than happy to have it pointed out.</p>
<div id="fig-syd-mel" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-syd-mel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../media/syd_mel_electrification-2748515-2748517.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Electric freight cost comparison: Sydney-Melbourne corridor"><img src="../media/syd_mel_electrification-2748515-2748517.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-syd-mel-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Electric freight cost comparison: Sydney-Melbourne corridor
</figcaption>
</figure>
</div>
<p>Three key technological developments have made this possible.</p>
<section id="private-sector-or-policy" class="level2">
<h2 class="anchored" data-anchor-id="private-sector-or-policy">Private sector or policy?</h2>
<p>If the economics are as good as they seem the private sector will get there off its own bat. An opportunity to undercut the existing players by a significant amount will surely be picked up. Think Uber, think AirBnB.</p>
<p>However the market for the product is not consumers, it’s for those businesses like Coles and Woolworths that are major consumers of freight. There may be many reasons why a small group of large businesses are slow to embrace change.</p>
<p>The role of policy could possibly be a nudge. In the end it is going to take $bns of capex. Not that many $bns but capital that has to be raised. For the private sector to invest its not only the economics that have to be attractive, it helps if policy is supportive, but most of all it will come down to the business seeking to raise capital and their credibility.</p>
<p>What I do know is that productivity is stalling in Australia, that our goods distribution system is ridiculously over dependent on diesel and transport costs are way higher than they need to be.</p>
</section>
<section id="the-tech-now-exists-to-electrify-60-tonne-double-bs" class="level2">
<h2 class="anchored" data-anchor-id="the-tech-now-exists-to-electrify-60-tonne-double-bs">The tech now exists to electrify 60 tonne double Bs</h2>
<p>Only a few years ago the accepted wisdom was that hydrogen would be needed to decarbonise semi trailers. Since hydrogen was expensive and dangerous, the only action required was further research.</p>
<p>However the improving technology and plunging cost of batteries has turned that discussion on its head.</p>
<ul>
<li>CATL now offers a truck battery with a 1.5 million kilometre warranty.</li>
<li>Windrose trucks as purpose built electrics have much lower drag coefficients 0.28, less than half a conventional semi. Windrose have just released V2 of their E700, capable of MW charging, a warranty of 600,000 km, 20% trade in , cost around Euro 250,000 and a claimed 650 km range. There are a whole bunch of innovative features in this truck and you can see a video “review” at <a href="https://youtu.be/Y0VlpCukR4U?si=g2grsb6CGd9DjYPW">Fullycharged</a>. If you watch an earlier interview with Wen Han, CEO of Windrose you will see that the driver was at the centre of the design. There is a lot more to say about this 4 year old company but it’s another story. Windrose is not the only vehicle choice in this space.</li>
<li>Purpose built charging stations and a settled fleet will allow for efficient charging. MW charging is the key to the success of this strategy. A 700-800 kWh battery can be recharged in an hour if the charger is fast enough. Truck drivers have to take rest breaks, mandatory rest on Sydney Melbourne is 30-60 minutes. At 60 minutes your truck is fully charged.</li>
</ul>
</section>
<section id="really-exciting-economics-plus-the-other-benefits" class="level2">
<h2 class="anchored" data-anchor-id="really-exciting-economics-plus-the-other-benefits">Really exciting economics plus the other benefits</h2>
<p>The basic concept is that a 60 tonne truck fully charged at the outset can get to Melbourne with just one charging stop, and the charge takes an hour. Every electric km costs 1/3 the diesel cost. To do this requires the right trucks and the right charging stations. Then depending on how you count the payback is either 4 years (starting from scratch) or 2 years (replacing diesel trucks at the end of their life).</p>
<p>The ideas are coupled together. Because of the range only a few dedicated recharging stations are needed. These are purpose built designed to handle 50-100 MW loads running 20 hours a day. With 100 x 1 MW bays, each doing 20 charges daily, one station can charge 2,000 trucks per day. With 100 drivers on site at any time, the station can support amenities like kitchens and showers. Along the highway you could probably build a 100 MW solar farm and batteries but of course you want a 100 MW grid connection. And even 2,000 charges a day is only good for say 100,000 tonnes of freight a day. You really need about 12x 50 bay stations or 6 x 100 Bay stations. But that’s still no problem spread out over 900 km right next to Humelink.</p>
<p>From a big picture point of view, if this is a good idea then so is Sydney to Brisbane, Sydney to Newcastle is a doddle.</p>
<p>Avoiding the imported fuel cost immediately improves the balance of trade and improves our energy security.</p>
</section>
<section id="chinas-already-doing-it-and-they-will-get-better-fast." class="level2">
<h2 class="anchored" data-anchor-id="chinas-already-doing-it-and-they-will-get-better-fast.">China’s already doing it and they will get better fast.</h2>
<p>Instead of China copying the West, it’s now time for us to copy China. China’s investment and subsidies can benefit Australia as much as they benefit China. In effect, we benefit from Chinese subsidies when purchasing their EVs. If China wants to subsidize Australians buying EVs I say go for it. But in this discussion what we are buying is China’s investment in heavy electric vehicle know how. They have proved the technology up.</p>
<p>China now has more than 9,000 public charging stations dedicated to heavy-duty electric trucks, covering major logistics corridors, industrial clusters, ports, and mining zones <span class="citation" data-cites="china-9000-stations-2025">(<a href="#ref-china-9000-stations-2025" role="doc-biblioref">Anengjie Energy, 2025</a>)</span>. This is an order of magnitude ahead of either the US or Europe.</p>
<p>You can see from the CREF visualisation below that China is now selling about 200,000 electric semi trailers a year, 1 million trucks and more than a few buses. China’s electric semitrailer share is about 33% below cars but on the rise.</p>
<div id="fig-china-transport" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-china-transport-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../media/image-20260227113010480.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: China transport, Source: Carbon Brief/CREF"><img src="../media/image-20260227113010480.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-china-transport-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: China transport, Source: Carbon Brief/CREF
</figcaption>
</figure>
</div>
<section id="electric-energy-is-about-13-the-cost-of-diesel" class="level3">
<h3 class="anchored" data-anchor-id="electric-energy-is-about-13-the-cost-of-diesel">Electric energy is about 1/3 the cost of diesel</h3>
<p>Fuel represents a major operating cost for diesel trucks.</p>
<p>Cost per km comparison</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Electric <span class="citation" data-cites="1.9">(<a href="#ref-1.9" role="doc-biblioref"><strong>1.9?</strong></a>)</span> kWh/km</th>
<th>Diesel <span class="citation" data-cites="50">(<a href="#ref-50" role="doc-biblioref"><strong>50?</strong></a>)</span> L/100km</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Energy rate</td>
<td>$0.15/kWh</td>
<td>$2.00/L</td>
</tr>
<tr class="even">
<td>Energy cost/km</td>
<td>$0.285</td>
<td>$1.00</td>
</tr>
<tr class="odd">
<td>Service cost/km</td>
<td>$0.014</td>
<td>$0.031</td>
</tr>
<tr class="even">
<td>Running cost/km</td>
<td>$0.30</td>
<td>$1.03</td>
</tr>
</tbody>
</table>
<p>Can you get electricity at $150/MWh? I think the answer is clearly yes, if you buy enough of it and you are close enough to transmission.</p>
<p>So every KM an electric semi travels is $0.70 cheaper than diesel.</p>
</section>
</section>
<section id="electric-truck-capex-is-about-double-the-capital-cost-of-diesel-trucks." class="level2">
<h2 class="anchored" data-anchor-id="electric-truck-capex-is-about-double-the-capital-cost-of-diesel-trucks.">Electric truck capex is about double the capital cost of diesel trucks.</h2>
<p>We are roughly talking $0.5 million v $0.25 million. If we assume the electrics are replacing diesels as they retire then its only the difference that is relevant.</p>
</section>
<section id="the-megawatt-charging-standard-mcs" class="level2">
<h2 class="anchored" data-anchor-id="the-megawatt-charging-standard-mcs">The Megawatt Charging Standard (MCS)</h2>
<p>Think I must have been asleep for the past couple of years. It turns out there is a heavy vehicle charging standard (Megawatt Charging Standard), first announced in 2018 the specification document was completed about 2024.</p>
<p>Unsurprisingly it turns out China is far ahead of the rest of the world but even in the USA there are 2 MW truck charging stations.</p>
<p><strong>Estimated Purpose-Built Truck Charging Facility Costs</strong></p>
<table class="table">
<colgroup>
<col style="width: 6%">
<col style="width: 25%">
<col style="width: 36%">
<col style="width: 12%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Region</th>
<th style="text-align: left;">Facility</th>
<th style="text-align: left;">Scale</th>
<th style="text-align: left;">Cost (US$M)</th>
<th style="text-align: left;">Cost per Bay (US$k)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">USA</td>
<td style="text-align: left;">Kettleman City (CA)</td>
<td style="text-align: left;">56 chargers, 1 MW BESS, 3.9 MW solar</td>
<td style="text-align: left;">58</td>
<td style="text-align: left;">~1,040</td>
</tr>
<tr class="even">
<td style="text-align: left;">USA</td>
<td style="text-align: left;">Generic 100-truck depot</td>
<td style="text-align: left;">100 chargers (hardware only)</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">~210</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Europe</td>
<td style="text-align: left;">Milence network (implied)</td>
<td style="text-align: left;">1,700 points across 30+ hubs</td>
<td style="text-align: left;">500 (EUR)</td>
<td style="text-align: left;">~294 (EUR)</td>
</tr>
<tr class="even">
<td style="text-align: left;">China</td>
<td style="text-align: left;">Huawei 100 MW hub</td>
<td style="text-align: left;">126 bays (18x1.44MW + 108x600kW)</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">~166</td>
</tr>
<tr class="odd">
<td style="text-align: left;">China</td>
<td style="text-align: left;">BYD charger unit only</td>
<td style="text-align: left;">Per liquid-cooled unit</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">11-14</td>
</tr>
</tbody>
</table>
<p>The range is wide. The Kettleman City project at US$58 million includes substantial on-site generation and storage, land acquisition on an interstate corridor, and California construction costs. The Huawei facility at US$21 million is a much larger installation by bay count but benefits from Chinese cost structures and an existing industrial site. The University of Chicago’s US$21 million estimate for a 100-truck depot covers hardware and electrical infrastructure only, excluding land, buildings, and on-site generation.</p>
<p>Across the globe an estimate for a <strong>purpose-built, grid-connected truck charging hub</strong> with 20–50 high-power (1+ MW) charging bays is:</p>
<ul>
<li><strong>USA:</strong> US$25–60 million (depending on grid works, on-site generation, and state)</li>
<li><strong>Europe:</strong> EUR 15–40 million (similar drivers, plus higher labour costs in some markets)</li>
<li><strong>China:</strong> US$10–25 million (lower construction and equipment costs, state grid support)</li>
</ul>
<p>The single largest variable is <strong>grid connection cost</strong>. A 20 MW grid connection can require transformer and switchgear upgrades costing US$3–8 million, with lead times of 12–24 months for electrical equipment <span class="citation" data-cites="nrel-hpc-trucking-2025 terawatt-buy-build-2025">(<a href="#ref-nrel-hpc-trucking-2025" role="doc-biblioref">National Renewable Energy Laboratory, 2025</a>; <a href="#ref-terawatt-buy-build-2025" role="doc-biblioref">TeraWatt Infrastructure, 2025</a>)</span>. Sites with existing heavy industrial grid connections (ports, mining sites, former factories) have a major cost advantage.</p>
<p><strong>Peak Charge Rates by System (2025–2026) (source:Internet research</strong></p>
<table class="table">
<colgroup>
<col style="width: 42%">
<col style="width: 19%">
<col style="width: 29%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">System</th>
<th style="text-align: left;">Max Power (MW)</th>
<th style="text-align: left;">Status</th>
<th style="text-align: left;">Region</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">MCS standard (theoretical max)</td>
<td style="text-align: left;">3.75</td>
<td style="text-align: left;">Standard published</td>
<td style="text-align: left;">Global</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huawei supercharger</td>
<td style="text-align: left;">1.44</td>
<td style="text-align: left;">Deployed</td>
<td style="text-align: left;">China</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tesla Megacharger</td>
<td style="text-align: left;">1.20</td>
<td style="text-align: left;">Operational (2 sites)</td>
<td style="text-align: left;">USA</td>
</tr>
<tr class="even">
<td style="text-align: left;">ABB MCS charger</td>
<td style="text-align: left;">1.20</td>
<td style="text-align: left;">Shipping</td>
<td style="text-align: left;">Global</td>
</tr>
<tr class="odd">
<td style="text-align: left;">BYD Flash Charging</td>
<td style="text-align: left;">1.00–1.50</td>
<td style="text-align: left;">Deploying</td>
<td style="text-align: left;">China</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kempower MCS</td>
<td style="text-align: left;">1.00+</td>
<td style="text-align: left;">Available</td>
<td style="text-align: left;">Europe</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Scania MCS (Gen 1)</td>
<td style="text-align: left;">0.75</td>
<td style="text-align: left;">Trucks from mid-2026</td>
<td style="text-align: left;">Europe</td>
</tr>
</tbody>
</table>
<p>The practical ceiling for deployed truck chargers in early 2026 is <strong>1.44 MW</strong> (Huawei), with the MCS standard allowing headroom to 3.75 MW as battery technology and grid infrastructure mature. Most OEMs are targeting 1.0–1.2 MW as the initial commercial sweet spot, which delivers a 20–80% charge in under 30 minutes for current battery capacities (typically 600–900 kWh for a Class 8 truck).</p>
<section id="the-huawei-100-mw-hub" class="level4">
<h4 class="anchored" data-anchor-id="the-huawei-100-mw-hub">The Huawei 100 MW Hub</h4>
<p>The most impressive single facility is the “Sichuan Yuanqi Xingguang Heavy-Duty Truck Megawatt Supercharging Station” in Beichuan, Sichuan Province, which commenced operations in August 2025 <span class="citation" data-cites="huawei-100mw-2025 huawei-electrive-2025">(<a href="#ref-huawei-electrive-2025" role="doc-biblioref">Electrive, 2025</a>; <a href="#ref-huawei-100mw-2025" role="doc-biblioref">Interesting Engineering, 2025</a>)</span>.</p>
<p><strong>Huawei 100 MW Facility Specifications</strong></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Total designed capacity</td>
<td style="text-align: left;">100 MW</td>
</tr>
<tr class="even">
<td style="text-align: left;">Supercharging bays</td>
<td style="text-align: left;">18 at 1.44 MW each</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fast charging bays</td>
<td style="text-align: left;">108 at 600 kW each</td>
</tr>
<tr class="even">
<td style="text-align: left;">Site area</td>
<td style="text-align: left;">11.5 acres (4.7 hectares)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Construction cost</td>
<td style="text-align: left;">US$20.9 million</td>
</tr>
<tr class="even">
<td style="text-align: left;">Daily throughput</td>
<td style="text-align: left;">700 trucks / 300,000+ kWh</td>
</tr>
<tr class="odd">
<td style="text-align: left;">On-site solar</td>
<td style="text-align: left;">~1 MW photovoltaic canopy</td>
</tr>
<tr class="even">
<td style="text-align: left;">Charge speed (3.5C trucks)</td>
<td style="text-align: left;">~100 km range in 5 minutes</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="other-benefits" class="level2">
<h2 class="anchored" data-anchor-id="other-benefits">Other benefits</h2>
<p>To that we can add:</p>
<ul>
<li>Carbon benefit: A one way trip in a B Double Sydney to Melbourne is about 1.4 kg of CO2 per km. For 1.2 bn tonne km required to transport the 22 million tonnes of road freight between Melbourne and Sydney per year thats about 1.7 million tonnes of CO2.</li>
<li>Driver benefit: Drivers can suffer hearing loss and are exposed to diesel health issues.</li>
<li>Time savings: Because of the extra power going up hills you will likely save 30-60 minutes each way. If we value driver time at about $100/hour with on costs the actual wages savings per year are quite material.</li>
<li>Other travellers avoid being stuck behind semis because now everyone is travelling at the speed limit.</li>
<li>Noise is hugely reduced: If you’ve ever been in a motorway tunnel with a semi you know how noisy they are.</li>
</ul>
</section>
<section id="double-bs" class="level2">
<h2 class="anchored" data-anchor-id="double-bs">Double Bs</h2>
<p>The Double B configuration is common. Of course, there are many different semi configurations doing Sydney to Melbourne.</p>
<div id="fig-double-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-double-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../media/bdouble_front_trailer_outline-2670384.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;3: Double B, original Getty"><img src="../media/bdouble_front_trailer_outline-2670384.jpg" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-double-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Double B, original Getty
</figcaption>
</figure>
</div>
</section>
<section id="tonnes-and-cubic-volume" class="level2">
<h2 class="anchored" data-anchor-id="tonnes-and-cubic-volume">Tonnes and cubic volume</h2>
<p>Transport like any topic has its own traps for space cadets. I was thinking about the maybe 24 mt of Melbourne to Sydney freight and how many trucks and truck km are really needed. Probably a better way to think about it is 20 ft containers. A B double takes 2. A 20 ft container can carry around 24 t of payload but it’s really the cubic volume that drives it. If you think about groceries with beverages, canned goods, packaged dry food and so on it averages about 300 kg/cubic metre and a 20 ft container has a volume of about 33 cubic metres. So the typical payload is more like 10 t than 24 t.</p>
<section id="battery-weight" class="level3">
<h3 class="anchored" data-anchor-id="battery-weight">Battery weight</h3>
<p>A 700 kWh battery adds about 4 t to the tare weight of a semi compared to a diesel. Much better to spread that weight over a B double.</p>



</section>
</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-china-9000-stations-2025" class="csl-entry" role="listitem">
Anengjie Energy. (2025). <em>China reaches 9,000 heavy-duty truck charging stations as megawatt-scale charging accelerates nationwide</em>. <a href="https://anengjienergy.com/china-reaches-9000-heavy-duty-truck-charging-stations-as-megawatt-scale-charging-accelerates-nationwide/">https://anengjienergy.com/china-reaches-9000-heavy-duty-truck-charging-stations-as-megawatt-scale-charging-accelerates-nationwide/</a>
</div>
<div id="ref-huawei-electrive-2025" class="csl-entry" role="listitem">
Electrive. (2025). <em>Huawei opens truck charging park in china</em>. <a href="https://www.electrive.com/2025/08/25/huawei-opens-truck-charging-park-in-china/">https://www.electrive.com/2025/08/25/huawei-opens-truck-charging-park-in-china/</a>
</div>
<div id="ref-huawei-100mw-2025" class="csl-entry" role="listitem">
Interesting Engineering. (2025). <em>China’s huawei unveils world’s first 100MW charging hub to power trucks</em>. <a href="https://interestingengineering.com/energy/china-huawei-worlds-first-100mw-charging">https://interestingengineering.com/energy/china-huawei-worlds-first-100mw-charging</a>
</div>
<div id="ref-nrel-hpc-trucking-2025" class="csl-entry" role="listitem">
National Renewable Energy Laboratory. (2025). <em>The dawn of electric trucking calls for high-power charging</em>. <a href="https://www.nrel.gov/news/features/2025/the-dawn-of-electric-trucking-calls-for-high-power-charging.html">https://www.nrel.gov/news/features/2025/the-dawn-of-electric-trucking-calls-for-high-power-charging.html</a>
</div>
<div id="ref-terawatt-buy-build-2025" class="csl-entry" role="listitem">
TeraWatt Infrastructure. (2025). <em>Buy vs build: How heavy-duty fleet operators should weigh their EV charging infrastructure options</em>. <a href="https://www.terawattinfrastructure.com/blog/buy-vs-build-how-heavy-duty-fleet-operators-should-weigh-their-ev-charging-infrastructure-options">https://www.terawattinfrastructure.com/blog/buy-vs-build-how-heavy-duty-fleet-operators-should-weigh-their-ev-charging-infrastructure-options</a>
</div>
</div></section></div></main> <!-- /main -->
<script data-isso="//comentario3.itkservices2.com/" data-isso-css="true" data-isso-css-url="null" data-isso-lang="en" data-isso-max-comments-top="10" data-isso-max-comments-nested="5" data-isso-reveal-on-click="5" data-isso-avatar="false" data-isso-avatar-bg="#f0f0f0" data-isso-avatar-fg="#9abf88 #5698c4 #e279a3 #9163b6 ..." data-isso-vote="true" data-isso-vote-levels="" data-isso-page-author-hashes="f124cf6b2f01,7831fe17a8cd" data-isso-reply-notifications-default-enabled="false" src="https://comentario3.itkservices2.com/js/embed.min.js"></script>
        <section id="isso-thread" data-title="Test tag"></section>
   
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/itkservices3\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024 ITK admin@itkservices.com.au</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>