<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Leitch">
<meta name="dcterms.date" content="2026-01-19">

<title>Australian Safeguard Mechanism – ITK Research</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../ITK_logo.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-d96a739641c07e2640703e5ad7a4e5f4.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-86c03801c75847bd115b064e8b296803.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script defer="" data-domain="itkservices3.com" src="https://plausible.io/js/script.js"></script>


<link rel="stylesheet" href="../styles.css">
<meta property="og:title" content="Australian Safeguard Mechanism – ITK Research">
<meta property="og:image" content="https://itkservices3.com/media/image-20260119183822680.png">
<meta property="og:site_name" content="ITK Research">
<meta property="og:image:height" content="2356">
<meta property="og:image:width" content="4118">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../ITK_logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">ITK Research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-dashboards-(load-slow" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Dashboards (load slow)</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-dashboards-(load-slow">    
        <li>
    <a class="dropdown-item" href="../IEA.html">
 <span class="dropdown-text">IEA-electricity</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../nemgen.html">
 <span class="dropdown-text">NEM-ITK</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../forecast.html">
 <span class="dropdown-text">AEMO demand fcst</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../posts.html"> 
<span class="menu-text">Articles</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-more" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">more</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-more">    
        <li>
    <a class="dropdown-item" href="../windy.html">
 <span class="dropdown-text">Temperature Forecast</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../green_iron/index.html">
 <span class="dropdown-text">Green Iron</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../presentations.html">
 <span class="dropdown-text">Presentations</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../background.html">
 <span class="dropdown-text">Background notes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../energyinsiders.html">
 <span class="dropdown-text">Energy Insiders</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../posts.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../mailchimp.html"> 
<span class="menu-text">Signup</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Australian Safeguard Mechanism</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Policy</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>David Leitch </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">January 19, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#mainly-safeguarding-coal-oil-and-gas-emissions" id="toc-mainly-safeguarding-coal-oil-and-gas-emissions" class="nav-link active" data-scroll-target="#mainly-safeguarding-coal-oil-and-gas-emissions">Mainly safeguarding coal, oil and gas emissions</a>
  <ul class="collapse">
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#how-the-scheme-is-supposed-to-work" id="toc-how-the-scheme-is-supposed-to-work" class="nav-link" data-scroll-target="#how-the-scheme-is-supposed-to-work">How the scheme is supposed to work</a>
  <ul class="collapse">
  <li><a href="#baselines" id="toc-baselines" class="nav-link" data-scroll-target="#baselines">Baselines</a></li>
  <li><a href="#compliance-options" id="toc-compliance-options" class="nav-link" data-scroll-target="#compliance-options">Compliance Options</a></li>
  <li><a href="#cost-containment" id="toc-cost-containment" class="nav-link" data-scroll-target="#cost-containment">Cost Containment</a></li>
  <li><a href="#accu-disclosure-rule" id="toc-accu-disclosure-rule" class="nav-link" data-scroll-target="#accu-disclosure-rule">30% ACCU Disclosure Rule</a></li>
  </ul></li>
  <li><a href="#targets" id="toc-targets" class="nav-link" data-scroll-target="#targets">Targets</a></li>
  <li><a href="#emissions-performance-data" id="toc-emissions-performance-data" class="nav-link" data-scroll-target="#emissions-performance-data">Emissions Performance Data</a>
  <ul class="collapse">
  <li><a href="#projected-trajectory" id="toc-projected-trajectory" class="nav-link" data-scroll-target="#projected-trajectory">Projected Trajectory</a></li>
  </ul></li>
  <li><a href="#key-questions-for-2026-27-statutory-review" id="toc-key-questions-for-2026-27-statutory-review" class="nav-link" data-scroll-target="#key-questions-for-2026-27-statutory-review">Key Questions for 2026-27 Statutory Review</a>
  <ul class="collapse">
  <li><a href="#is-the-4.9-decline-rate-appropriate-for-post-2030" id="toc-is-the-4.9-decline-rate-appropriate-for-post-2030" class="nav-link" data-scroll-target="#is-the-4.9-decline-rate-appropriate-for-post-2030">Is the 4.9% decline rate appropriate for post-2030?</a></li>
  <li><a href="#should-the-threshold-be-lowered-from-100000-tonnes" id="toc-should-the-threshold-be-lowered-from-100000-tonnes" class="nav-link" data-scroll-target="#should-the-threshold-be-lowered-from-100000-tonnes">Should the threshold be lowered from 100,000 tonnes?</a></li>
  <li><a href="#are-offset-arrangements-accussmcs-appropriate-in-a-word-no" id="toc-are-offset-arrangements-accussmcs-appropriate-in-a-word-no" class="nav-link" data-scroll-target="#are-offset-arrangements-accussmcs-appropriate-in-a-word-no">Are offset arrangements (ACCUs/SMCs) appropriate? (in a word: NO)</a></li>
  <li><a href="#how-should-new-entrant-fossil-fuel-projects-be-treated" id="toc-how-should-new-entrant-fossil-fuel-projects-be-treated" class="nav-link" data-scroll-target="#how-should-new-entrant-fossil-fuel-projects-be-treated">How should new entrant fossil fuel projects be treated?</a></li>
  <li><a href="#what-is-the-pathway-to-net-zero-by-2049-50" id="toc-what-is-the-pathway-to-net-zero-by-2049-50" class="nav-link" data-scroll-target="#what-is-the-pathway-to-net-zero-by-2049-50">What is the pathway to net zero by 2049-50?</a></li>
  <li><a href="#how-does-the-scheme-interact-with-the-2035-ndc-62-70" id="toc-how-does-the-scheme-interact-with-the-2035-ndc-62-70" class="nav-link" data-scroll-target="#how-does-the-scheme-interact-with-the-2035-ndc-62-70">How does the scheme interact with the 2035 NDC (62-70%)?</a></li>
  <li><a href="#are-teba-provisions-working-effectively" id="toc-are-teba-provisions-working-effectively" class="nav-link" data-scroll-target="#are-teba-provisions-working-effectively">Are TEBA provisions working effectively?</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="safeguards  review.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="mainly-safeguarding-coal-oil-and-gas-emissions" class="level1">
<h1>Mainly safeguarding coal, oil and gas emissions</h1>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>Australia’s Safeguard Mechanism covers ~215 facilities emitting over 100,000 tonnes CO2-e annually, representing 28% of national emissions. Reformed in 2023, the scheme requires baselines to decline 4.9% per year through 2030. However, early data shows facilities are not decarbonising fast enough: covered emissions fell only 4.3% over two years while exceedance volumes surged 52%. ACCU surrenders have increased six-fold, indicating heavy reliance on offsets rather than on-site abatement. The 2026-27 statutory review will be critical, particularly given the gap between the indicative post-2030 decline rate (3.285%) and rates required to meet the 2035 NDC target (4.82-6.85%).</p>
<p><strong>Conclusion:</strong> The scheme’s fundamental tension is that it “safeguards” industries via being insufficiently tough—coal, oil and gas—that are themselves the primary contributors to global warming via scope 3 combustion. New LNG projects (Pluto, Barossa, Browse) risk consuming a substantial share of remaining emissions budget. I expect global economics will ultimately constrain new fossil fuel developments, making generous baseline provisions for new entrants unnecessary. ACCU use should be strictly limited; genuine ACCU abatement projects deserve support through separate mechanisms perhaps with price reflecting quality. The trade-exposed sector will eventually have to adjust as Australia transitions from being a top-3 thermal energy exporter so Safeguards shouldn’t make it easy for them. Policy will follow the money, and the money is increasingly moving toward electrification. Not in a straight line, but over time.</p>
</section>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>The Safeguard Mechanism is Australia’s principal policy for reducing greenhouse gas emissions from the nation’s largest industrial facilities. Reformed in July 2023, it operates as a baseline-and-credit scheme requiring covered facilities to progressively reduce their emissions in line with national targets.</p>
<p><strong>Legislative basis:</strong> National Greenhouse and Energy Reporting Act 2007 (Cth), administered under the Safeguard Mechanism Rules</p>
<p><strong>Administering bodies:</strong></p>
<ul>
<li>Department of Climate Change, Energy, the Environment and Water (DCCEEW) - policy</li>
<li>Clean Energy Regulator (CER) - compliance and administration</li>
</ul>
<p>Facilities emitting more than <strong>100,000 tonnes CO2-e per year</strong> (scope 1 emissions) are covered.</p>
<p>The following visualisation shows the top emitters and the industries. I’ve included electricity in the industry overview although it’s excluded from the Safeguards scheme.</p>
<div id="fig-corporate-emissions" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-corporate-emissions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../media/image-20260119183245174.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Corporate emissions"><img src="../media/image-20260119183245174.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-corporate-emissions-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Corporate emissions
</figcaption>
</figure>
</div>
<p>The main growth in industry emissions has been in gas, no doubt from the QLD LNG facilities but other expansions as well. Coal growth has slowed in recent years, I have previously noted that in thermal coal Australia has become uncompetitive with Indonesia.</p>
<p>Those industries are also the largest contributors outside electricity to corporate emissions, which when you think about it is kind of a cosmic joke. We have a scheme designed to “safeguard” industries which are in fact the main contributors to global warming via their scope 3 combustion.</p>
<p>Think about shipping. About 40% of global shipping by weight represents the transport of oil, coal and gas. Think about primary energy: an electrified world would consume about 40% less energy than today. That is the world we are moving to.</p>
<div id="fig-emissions-trends" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-emissions-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="../media/image-20260119183822680.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: Corporate emissions trends"><img src="../media/image-20260119183822680.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-emissions-trends-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Corporate emissions trends
</figcaption>
</figure>
</div>
</section>
<section id="how-the-scheme-is-supposed-to-work" class="level2">
<h2 class="anchored" data-anchor-id="how-the-scheme-is-supposed-to-work">How the scheme is supposed to work</h2>
<section id="baselines" class="level3">
<h3 class="anchored" data-anchor-id="baselines">Baselines</h3>
<p>Each facility receives an <strong>emissions intensity baseline</strong> - a limit on emissions relative to production output. Baselines decline annually to drive emissions reductions.</p>
<p><strong>Decline rate:</strong> 4.9% per year (to 2030)</p>
<p>This rate is designed to deliver a proportional share of Australia’s 2030 target (43% below 2005 levels).</p>
</section>
<section id="compliance-options" class="level3">
<h3 class="anchored" data-anchor-id="compliance-options">Compliance Options</h3>
<p>Facilities exceeding their baseline must manage excess emissions through:</p>
<ol type="1">
<li><p><strong>Surrender Australian Carbon Credit Units (ACCUs)</strong> - Offsets representing emissions reduced/removed elsewhere (e.g., reforestation, landfill gas capture)</p></li>
<li><p><strong>Surrender Safeguard Mechanism Credits (SMCs)</strong> - Credits issued to facilities that beat their baseline, tradeable within the scheme</p></li>
<li><p><strong>Flexibility measures:</strong></p>
<ul>
<li>Multi-year monitoring periods (averaging emissions over 2-3 years)</li>
<li>Borrowing from future baselines</li>
<li>Trade-exposed baseline-adjusted (TEBA) facility provisions (reduced decline rate for internationally competitive industries)</li>
</ul></li>
</ol>
</section>
<section id="cost-containment" class="level3">
<h3 class="anchored" data-anchor-id="cost-containment">Cost Containment</h3>
<p><strong>Cost Containment Settings</strong></p>
<table class="table">
<colgroup>
<col style="width: 56%">
<col style="width: 43%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Setting</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Government ACCU price cap</td>
<td style="text-align: left;">$75/tonne (FY2024), indexed to CPI + 2% annually</td>
</tr>
<tr class="even">
<td style="text-align: left;">Default prescribed unit price (FY2024-25)</td>
<td style="text-align: left;">$36.05</td>
</tr>
</tbody>
</table>
<p><em>Source: Clean Energy Regulator</em></p>
</section>
<section id="accu-disclosure-rule" class="level3">
<h3 class="anchored" data-anchor-id="accu-disclosure-rule">30% ACCU Disclosure Rule</h3>
<p>Facilities surrendering ACCUs equal to or exceeding 30% of their baseline must publicly explain why on-site abatement wasn’t undertaken.</p>
</section>
</section>
<section id="targets" class="level2">
<h2 class="anchored" data-anchor-id="targets">Targets</h2>
<p><strong>Emissions Targets</strong></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Milestone</th>
<th style="text-align: left;">Target</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">FY2029-30</td>
<td style="text-align: left;">Net emissions ≤100 Mt CO2-e</td>
</tr>
<tr class="even">
<td style="text-align: left;">FY2049-50</td>
<td style="text-align: left;">Net zero emissions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cumulative budget (FY2020-30)</td>
<td style="text-align: left;">≤1,233 Mt CO2-e</td>
</tr>
</tbody>
</table>
<p><em>Source: DCCEEW</em></p>
</section>
<section id="emissions-performance-data" class="level2">
<h2 class="anchored" data-anchor-id="emissions-performance-data">Emissions Performance Data</h2>
<p><strong>Performance Summary</strong></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Metric</th>
<th style="text-align: right;">FY2022-23</th>
<th style="text-align: right;">FY2023-24</th>
<th style="text-align: right;">FY2024-25<sup>p</sup></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Covered facilities</td>
<td style="text-align: right;">218</td>
<td style="text-align: right;">219</td>
<td style="text-align: right;">~215</td>
</tr>
<tr class="even">
<td style="text-align: left;">Covered emissions (Mt)</td>
<td style="text-align: right;">139</td>
<td style="text-align: right;">136</td>
<td style="text-align: right;">133</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Facilities in exceedance</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">143</td>
</tr>
<tr class="even">
<td style="text-align: left;">Exceedance volume (Mt)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">9.2</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SMCs issued (million)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">8.3</td>
<td style="text-align: right;">~7</td>
</tr>
<tr class="even">
<td style="text-align: left;">ACCUs surrendered (million)</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">7.1</td>
<td style="text-align: right;">~14<sup>e</sup></td>
</tr>
<tr class="odd">
<td style="text-align: left;">SMCs surrendered (million)</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">1.4</td>
<td style="text-align: right;">TBD</td>
</tr>
</tbody>
</table>
<p><em>Source: Clean Energy Regulator. <sup>p</sup>Preliminary. <sup>e</sup>Estimate based on exceedance volume.</em></p>
<p><strong>Key observations:</strong></p>
<ul>
<li><strong>Emissions declining but slower than baselines:</strong> Covered emissions fell 4.3% over two years (139→133 Mt), but baselines declined 7.3% in FY2024-25 alone — facilities are not decarbonising fast enough</li>
<li><strong>Exceedances surging:</strong> Facilities in exceedance rose from 142 to 143, but exceedance volume jumped from 9.2 Mt to 14 Mt — a 52% increase in compliance liability</li>
<li><strong>ACCU reliance growing:</strong> Surrenders increased six-fold from 1.2 million (pre-reform) to 7.1 million in the first reformed year, indicating heavy offset reliance rather than on-site abatement</li>
<li><strong>SMC supply tightening:</strong> Fewer facilities earning SMCs (62→59) means reduced credit supply as demand increases</li>
</ul>
<section id="projected-trajectory" class="level3">
<h3 class="anchored" data-anchor-id="projected-trajectory">Projected Trajectory</h3>
<p>Government projections (DCCEEW):</p>
<ul>
<li>FY2029-30: 121 Mt</li>
<li>FY2034-35: 97 Mt</li>
</ul>
<p>Independent analysis (Climate Analytics) suggests LNG and coal emissions could exceed these projections, potentially reaching 83-112 Mt from fossil fuel projects alone by 2030 (Climate Analytics).</p>
</section>
</section>
<section id="key-questions-for-2026-27-statutory-review" class="level2">
<h2 class="anchored" data-anchor-id="key-questions-for-2026-27-statutory-review">Key Questions for 2026-27 Statutory Review</h2>
<p><strong>Review status:</strong> The formal consultation has not yet opened. The review is scheduled for FY2026-27 (commencing July 2026), once two full years of post-reform compliance data are available.</p>
<section id="is-the-4.9-decline-rate-appropriate-for-post-2030" class="level3">
<h3 class="anchored" data-anchor-id="is-the-4.9-decline-rate-appropriate-for-post-2030">Is the 4.9% decline rate appropriate for post-2030?</h3>
<p><strong>Current settings:</strong> The 4.9% annual decline rate applies only through 2030. For 2030-31 to 2049-50, an indicative rate of <strong>3.285%</strong> is set in the Safeguard Rules. However, actual post-2030 rates will be determined through the 5-year baseline setting process.</p>
<p><strong>2035 NDC implications:</strong> The Climate Change Authority’s analysis indicates that meeting the 2035 NDC target range (62-70% below 2005 levels) requires higher decline rates:</p>
<p><strong>Implied Baseline Decline Rates for 2035 NDC Targets</strong></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">2035 Target</th>
<th style="text-align: right;">Implied Annual Decline Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">62% (minimum)</td>
<td style="text-align: right;">4.82%</td>
</tr>
<tr class="even">
<td style="text-align: left;">65% (middle)</td>
<td style="text-align: right;">5.50%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">70% (ambitious)</td>
<td style="text-align: right;">6.85%</td>
</tr>
</tbody>
</table>
<p><em>Source: CORE Markets analysis</em></p>
<p><strong>Key finding:</strong> The indicative 3.285% post-2030 rate is inconsistent with even the minimum 2035 target. The 2026-27 review will need to set rates for 2030-35 by July 2027, incorporating advice from the Climate Change Authority and the government’s final position on 2035 ambition level.</p>
</section>
<section id="should-the-threshold-be-lowered-from-100000-tonnes" class="level3">
<h3 class="anchored" data-anchor-id="should-the-threshold-be-lowered-from-100000-tonnes">Should the threshold be lowered from 100,000 tonnes?</h3>
<p><strong>Current coverage:</strong> The 100,000 tonne CO2-e threshold captures approximately 215-220 facilities representing about 28% of Australia’s total emissions (ICAP).</p>
<p><strong>Modelling findings:</strong> Carbon Market Institute research (modelling by CORE Markets) found that lowering the facility threshold could bring an additional <strong>8% of emissions</strong> under the scheme (Carbon Market Institute/CORE Markets). This would extend coverage to medium-sized emitters in manufacturing, commercial buildings, and other sectors.</p>
<p><strong>Considerations:</strong></p>
<ul>
<li>Administrative complexity: More covered facilities means greater compliance burden for regulators and businesses</li>
<li>Proportionality: Smaller emitters have less capacity to invest in abatement technologies</li>
<li>Comparable schemes: The EU ETS and other carbon pricing mechanisms typically have lower thresholds or economy-wide coverage</li>
</ul>
<p><strong>Status:</strong> No government proposal to lower the threshold has been announced. The 2026-27 review may examine threshold adjustment as one option for broadening scheme coverage.</p>
</section>
<section id="are-offset-arrangements-accussmcs-appropriate-in-a-word-no" class="level3">
<h3 class="anchored" data-anchor-id="are-offset-arrangements-accussmcs-appropriate-in-a-word-no">Are offset arrangements (ACCUs/SMCs) appropriate? (in a word: NO)</h3>
<p><strong>Current reliance on offsets:</strong> In FY2023-24, facilities surrendered 7.1 million ACCUs - up from 1.2 million in FY2022-23 (CER). This indicates substantial reliance on offsets rather than on-site abatement.</p>
<p><strong>ACCU integrity concerns:</strong> Academic research has raised significant concerns about offset quality. Analysis of the 137 million ACCUs issued since 2011 found that approximately three-quarters came from three project types (avoided deforestation, landfill methane combustion, human-induced regeneration) with questionable integrity - described as “a form of Gresham’s Law, where bad projects drive out the good” (Macintosh et al.&nbsp;2022).</p>
<p><strong>Fossil fuel sector offset usage:</strong> Data from FY2023-24 shows that fossil fuel companies (representing 54% of covered emissions) earned 74% of all Safeguard Mechanism Credits issued (Australia Institute). This raises questions about whether the scheme is driving real abatement.</p>
<p><strong>Policy options under consideration:</strong></p>
<ul>
<li><strong>Discount on ACCU value:</strong> Applying a percentage reduction when offsets are used for more than a certain proportion of compliance</li>
<li><strong>Limits on ACCU use:</strong> Capping the percentage of compliance that can be met through offsets</li>
<li><strong>Restrictions by project type:</strong> Limiting use of ACCUs from project types with integrity concerns</li>
</ul>
<p><strong>Parallel reviews:</strong> The 2026-27 Safeguard review will coincide with the Climate Change Authority’s review of the ACCU Scheme, which will assess whether Australia’s carbon credit supply can meet demands of a tightening compliance market (CORE Markets).</p>
</section>
<section id="how-should-new-entrant-fossil-fuel-projects-be-treated" class="level3">
<h3 class="anchored" data-anchor-id="how-should-new-entrant-fossil-fuel-projects-be-treated">How should new entrant fossil fuel projects be treated?</h3>
<p><strong>Current treatment:</strong> New facilities entering the scheme receive baselines based on industry benchmarks. New extraction facilities are assumed to enter as “new entrants” with associated baseline entitlements.</p>
<p><strong>Major new LNG projects:</strong> Three large projects - Pluto, Barossa, and Browse - are entering the scheme between 2025 and 2029. By 2030, these three projects alone account for approximately <strong>69% of annual emissions from new facilities</strong>, with new domestic gas extraction (Waitsia, Narrabri, Beetaloo) accounting for a further 13% (RepuTex).</p>
<p><strong>Assistance available:</strong> New entrants that are trade-exposed (including LNG) have access to:</p>
<ul>
<li>TEBA status (reduced decline rates)</li>
<li>$600 million Safeguard Transformation Stream under Powering the Regions Fund</li>
</ul>
<p><strong>Hard cap provisions:</strong> Under the emissions budget hard cap, the energy minister can decide whether to permit a new fossil fuel project based on Climate Change Authority advice on projected gross emissions - meaning without carbon offsets being used.</p>
<p><strong>Recent approvals:</strong> Despite climate commitments, Australia has continued approving major fossil fuel projects. In May 2025, the government approved a 40-year extension to Woodside’s North West Shelf LNG plant, allowing operation until 2070.</p>
<p><strong>Key tension:</strong> The entry of major new LNG projects risks consuming a substantial portion of the scheme’s remaining emissions budget, potentially forcing deeper cuts on other facilities or reliance on offsets to maintain budget integrity.</p>
</section>
<section id="what-is-the-pathway-to-net-zero-by-2049-50" class="level3">
<h3 class="anchored" data-anchor-id="what-is-the-pathway-to-net-zero-by-2049-50">What is the pathway to net zero by 2049-50?</h3>
<p><strong>Legislated trajectory:</strong> As shown in the Targets table above, the scheme targets net emissions ≤100 Mt by FY2029-30 and net zero by FY2049-50.</p>
<p><strong>Indicative post-2030 decline rate:</strong> 3.285% per year from 2030-31 to 2049-50 is set in the Safeguard Rules as an indicative rate. Actual rates will be confirmed through the 5-year baseline setting process.</p>
<p><strong>5-year baseline setting:</strong> Decline rates for 2030-31 to 2034-35 must be set by <strong>1 July 2027</strong>. This will be informed by Climate Change Authority advice and the latest Annual Climate Change Statements to Parliament.</p>
<p><strong>Trajectory uncertainty:</strong> The gap between the indicative 3.285% rate and rates required for the 2035 NDC (4.82-6.85%) creates uncertainty for facility operators attempting to plan long-term decarbonisation investments.</p>
<p><strong>Real vs offset reductions:</strong> Climate Action Tracker analysis notes that currently “less than a third of the ‘reductions’ achieved were from real emission reductions and two thirds due to the use of offsets” (Climate Action Tracker). The pathway to genuine net zero requires this ratio to shift substantially toward on-site abatement.</p>
</section>
<section id="how-does-the-scheme-interact-with-the-2035-ndc-62-70" class="level3">
<h3 class="anchored" data-anchor-id="how-does-the-scheme-interact-with-the-2035-ndc-62-70">How does the scheme interact with the 2035 NDC (62-70%)?</h3>
<p><strong>2035 target:</strong> On 18 September 2025, Prime Minister Albanese announced Australia’s 2035 NDC target at <strong>62-70% reduction</strong> below 2005 levels - framed as a five-year emissions budget for 2031-35 rather than a single-year goal.</p>
<p><strong>Safeguard Mechanism role:</strong> The Climate Change Authority identifies the Safeguard Mechanism as the primary policy for industry sector decarbonisation. “Accelerating the decline rate out to 2035 for baselines set under the Safeguard Mechanism is identified by the CCA as reducing emissions from the industry and resources sectors by almost a third” (Climate Change Authority).</p>
<p><strong>Timing alignment:</strong> The 2026-27 Safeguard review must set decline rates for 2030-35 by July 2027. This will be the critical mechanism for translating the NDC commitment into binding facility-level requirements.</p>
<p><strong>Industry uncertainty:</strong> Due to the target range, “baseline reductions from 2030 onwards will be harder for industry to forecast until the Safeguard review is complete” (CORE Markets). Facilities must plan for scenarios ranging from 4.82% to 6.85% annual decline rates.</p>
<p><strong>Other review items expected:</strong> TEBA determinations, multi-year monitoring periods, and banking/borrowing settings (whether banked ACCUs and SMCs can be used after 2030) will all be revisited alongside the core decline rate question (CORE Markets).</p>
</section>
<section id="are-teba-provisions-working-effectively" class="level3">
<h3 class="anchored" data-anchor-id="are-teba-provisions-working-effectively">Are TEBA provisions working effectively?</h3>
<p><strong>TEBA purpose:</strong> Trade-exposed baseline-adjusted facilities receive reduced decline rates to protect against “carbon leakage” - the risk that production and emissions simply shift to overseas competitors with weaker carbon policies.</p>
<p><strong>Eligibility and rates:</strong></p>
<p><strong>TEBA Reduced Decline Rates</strong></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Sector</th>
<th style="text-align: right;">Minimum Decline Rate</th>
<th style="text-align: left;">Scheme Impact Trigger</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Manufacturing</td>
<td style="text-align: right;">1.0%</td>
<td style="text-align: left;">Scheme cost &gt;3% of EBIT</td>
</tr>
<tr class="even">
<td style="text-align: left;">Non-manufacturing</td>
<td style="text-align: right;">2.0%</td>
<td style="text-align: left;">Scheme cost as % of revenue</td>
</tr>
</tbody>
</table>
<p><em>Source: Clean Energy Regulator</em></p>
<p><strong>FY2023-24 uptake:</strong> In the first reformed year, <strong>17 facilities received site-specific baseline decline rates set at a heavily discounted 1%</strong> (ICAP). This represents significant use of the concession.</p>
<p><strong>Fossil fuel sector concerns:</strong> As noted earlier, fossil fuel companies earn a disproportionate share of SMCs relative to their emissions, and that TEBA is available to trade-exposed LNG facilities, questions arise about whether the provisions are calibrated appropriately or are enabling continued high emissions from the resources sector.</p>
<p><strong>Review considerations:</strong> The 2026-27 review will examine “the extent to which Safeguard facilities are undertaking decarbonisation activities, accessing excess emissions management options such as TEBA status and multi-year monitoring periods, and the costs and availability of carbon credits”.</p>
<p><strong>Tension with 2035 targets:</strong> If substantial numbers of facilities receive TEBA status with 1-2% decline rates while the sector average needs to be 4.82-6.85% to meet NDC targets, the burden falls disproportionately on non-TEBA facilities or must be made up through offsets.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script data-isso="//comentario3.itkservices2.com/" data-isso-css="true" data-isso-css-url="null" data-isso-lang="en" data-isso-max-comments-top="10" data-isso-max-comments-nested="5" data-isso-reveal-on-click="5" data-isso-avatar="false" data-isso-avatar-bg="#f0f0f0" data-isso-avatar-fg="#9abf88 #5698c4 #e279a3 #9163b6 ..." data-isso-vote="true" data-isso-vote-levels="" data-isso-page-author-hashes="f124cf6b2f01,7831fe17a8cd" data-isso-reply-notifications-default-enabled="false" src="https://comentario3.itkservices2.com/js/embed.min.js"></script>
        <section id="isso-thread" data-title="Test tag"></section>
   
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/itkservices3\.com");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2024 ITK admin@itkservices.com.au</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>