-- docx-media.lua
-- For docx output only (attached under format: docx: filters in _quarto.yml).
-- Swap media/<img>.png for the white-canvas variant in _media_docx/ when one
-- exists. Variants are generated by scripts/make_docx_media.py; images without
-- a cream canvas have no variant and keep their original path.

local function file_exists(path)
  local f = io.open(path, "rb")
  if f then f:close() return true end
  return false
end

-- Resolve a src that is relative to the input document, trying both the
-- current working directory and the input file's directory.
local function resolvable(rel)
  if file_exists(rel) then return true end
  local ok, input = pcall(function() return quarto.doc.input_file end)
  if ok and input then
    local dir = pandoc.path.directory(input)
    return file_exists(pandoc.path.join({dir, rel}))
  end
  return false
end

function Image(el)
  local candidate, n = el.src:gsub("(%.%./)media/", "%1_media_docx/", 1)
  if n == 0 then
    candidate, n = el.src:gsub("^media/", "_media_docx/", 1)
  end
  if n > 0 and resolvable(candidate) then
    el.src = candidate
  end
  return el
end
