<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="David Leitch">
<meta name="dcterms.date" content="2026-06-28">

<title>Research memory: Australian diesel use &amp; oil imports (Mar–Apr 2026)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="diesel_oil_imports_2026_files/libs/clipboard/clipboard.min.js"></script>
<script src="diesel_oil_imports_2026_files/libs/quarto-html/quarto.js"></script>
<script src="diesel_oil_imports_2026_files/libs/quarto-html/popper.min.js"></script>
<script src="diesel_oil_imports_2026_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="diesel_oil_imports_2026_files/libs/quarto-html/anchor.min.js"></script>
<link href="diesel_oil_imports_2026_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="diesel_oil_imports_2026_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="diesel_oil_imports_2026_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="diesel_oil_imports_2026_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="diesel_oil_imports_2026_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<meta name="quarto:status" content="draft">


</head>

<body class="fullcontent"><div id="quarto-draft-alert" class="alert alert-warning"><i class="bi bi-pencil-square"></i>Draft</div>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Research memory: Australian diesel use &amp; oil imports (Mar–Apr 2026)</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>David Leitch </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 28, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="diesel-use-oil-imports-research-thread" class="level1">
<h1>Diesel use &amp; oil imports — research thread</h1>
<p><strong>Period:</strong> March–April 2026. <strong>Theme:</strong> Australia’s diesel dependence as (1) an energy-security and balance-of-trade problem that electrification can fix, and (2) a diagnostic signal — rising diesel intensity in coal mining as evidence coal has passed peak.</p>
<p>This memory exists mainly to record the <strong>input data sources</strong>, since the analysis hangs off a handful of official statistics and report extracts. All of these can be re-downloaded if lost; the value is knowing which series, which table, and the headline number each one supplied.</p>
<hr>
<section id="input-data-the-series-that-drive-everything" class="level2">
<h2 class="anchored" data-anchor-id="input-data-the-series-that-drive-everything">Input data — the series that drive everything</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 4%">
<col style="width: 12%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">#</th>
<th style="text-align: left;">Source</th>
<th style="text-align: left;">What it gives</th>
<th style="text-align: left;">Key figure(s)</th>
<th style="text-align: left;">Where to get it again</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;"><strong>DCCEEW — Australian Petroleum Statistics</strong></td>
<td style="text-align: left;">National diesel sales (the top-line consumption number)</td>
<td style="text-align: left;">Total diesel sales <strong>33,508 ML in 2025</strong> (up from ~30,000 ML in 2022)</td>
<td style="text-align: left;">energy.gov.au/publications/australian-petroleum-statistics — monthly extract; used Jan 2026 extract</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;"><strong>ABS — Survey of Motor Vehicle Use (Cat. 9208.0)</strong>, yr ended 30 Jun 2020</td>
<td style="text-align: left;">On-road diesel split by vehicle type (the <em>only</em> authoritative on-road breakdown — survey since <strong>discontinued</strong>)</td>
<td style="text-align: left;">Road transport fuel 33,019 ML (49.0% petrol / 49.1% diesel). Diesel: trucks 7,465 ML, LCV 5,014 ML, passenger 3,128 ML, buses 530 ML. Data file <code>92080DO001_202006.xls</code></td>
<td style="text-align: left;">abs.gov.au — Survey of Motor Vehicle Use, latest release. <strong>Note: final edition, not updated since 2020</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;"><strong>IEEFA — “Cutting Australian mining’s diesel emissions”</strong> (Andrew Gorringe, Jan 2026)</td>
<td style="text-align: left;">Mining (off-road) diesel + the coal-intensity trend</td>
<td style="text-align: left;">Mining <strong>9.6 BL FY2023-24</strong>, 22 Mt CO₂-e. Coal 48%, iron ore 26%, other 26%. <strong>Coal diesel intensity +50%</strong> FY2010-11→FY2023-24 (iron ore +6%). Built on NGER data</td>
<td style="text-align: left;">ieefa.org/resources/cutting-australian-minings-diesel-emissions</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;"><strong>DCCEEW — Australian Energy Statistics 2025, Table F</strong> (Energy Consumption by Industry &amp; Fuel)</td>
<td style="text-align: left;">Cross-check on mining/agriculture diesel in PJ</td>
<td style="text-align: left;">FY2023-24 mining diesel <strong>299.6 PJ</strong> (coal 151.4, oil&amp;gas 2.8, other 145.4). Agriculture diesel 88.8 PJ</td>
<td style="text-align: left;">energy.gov.au/energy-data/australian-energy-statistics/energy-consumption</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;"><strong>The Australia Institute — Fuel Tax Credit &amp; fossil fuel subsidies</strong> (R. Campbell, 2024)</td>
<td style="text-align: left;">FTC rebate by sector → off-road diesel allocation + the “kill the rebate” policy lever</td>
<td style="text-align: left;">FY2022-23 FTC <strong>$7.8 bn total</strong>; mining <strong>$3.5 bn (45%)</strong>; agriculture/forestry/fishing $1.3 bn</td>
<td style="text-align: left;">australiainstitute.org.au (P1481)</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;"><strong>Climate Change Authority — Sector Pathways Review: Transport</strong> (2024)</td>
<td style="text-align: left;">Transport emissions split (the 90 Mt framing)</td>
<td style="text-align: left;">Transport <strong>90 Mt CO₂-e (21% of national)</strong> 2022. Cars 38 Mt (42%), LCV 17 Mt, heavy trucks+buses 22 Mt (rigid 8.7 / artic 11.7 / bus 1.6). 23% of trucks &gt;21 yrs; 90% of operators small business</td>
<td style="text-align: left;">climatechangeauthority.gov.au/publications/sector-pathways-review</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;"><strong>ACAPMA / ATSE</strong></td>
<td style="text-align: left;">Qualitative framing — ~60% of liquid fuel is diesel, ~40% of diesel is non-transport; key diesel sectors</td>
<td style="text-align: left;">—</td>
<td style="text-align: left;">acapmag.com.au; atse.org.au decarbonising-diesel-industries</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;"><strong>renewables.ninja</strong> (Pfenninger &amp; Staffell)</td>
<td style="text-align: left;">Pilbara wind profile for the Fortescue model</td>
<td style="text-align: left;">Port Hedland Vestas V162 6MW <span class="citation" data-cites="120m">@120m</span>, annual CF <strong>36.1%</strong> (Jun 50% / Feb 29%)</td>
<td style="text-align: left;">renewables.ninja — MERRA-2 reanalysis</td>
</tr>
</tbody>
</table>
<p>Bibliographies holding full entries: <code>background/diesel_electrification_references.bib</code> (master, ~60 entries incl.&nbsp;all truck-OEM / charging-standard / mining-equipment sources) and <code>posts/diesel_to_electricity.bib</code> (subset for the flagship post).</p>
<hr>
</section>
<section id="published-outputs" class="level2">
<h2 class="anchored" data-anchor-id="published-outputs">Published outputs</h2>
<p><strong>Posts (<code>posts/</code>, published):</strong> - <code>Diesel_to_electricity.md</code> (2026-03-22) — flagship. Full fleet electrification redirects <strong>~$22 bn/yr from petroleum imports to domestic electricity</strong> (~1% of GDP import substitution), cuts <strong>~90 Mt CO₂ (~15% of emissions)</strong>, ~$15 bn welfare at AER $176/t. Priorities: long-haul trucking, mining (end diesel rebate), diesel passenger cars. Image: <code>media/diesel_policy_scorecard_table.png</code>. - <code>Diesel_symptom.md</code> (2026-04-28) — “Diesel consumption reveals the malaise in coal.” Diesel/tonne of coal +50% vs +6% iron ore ⇒ coal past peak, rising cost. - <code>Longhaul.md</code> (2026-03-06) — Sydney–Melbourne road freight: 2–4 yr payback, ~$0.9 bn/yr fuel savings, ~$2.5 bn incremental capex. ~22 Mt freight, ~1.2 bn freight-km. - <code>Twiggy.md</code> (2026-04-13) — Fortescue Pilbara electrification: ~16% pretax IRR, trucks carry it, battery-swap beats in-truck batteries. - <code>Freight_forward.md</code> (2026-03-31) — Smart Energy/Boundless conference reportage. - <code>tesla_semi.md</code> (2026-03-23) — Tesla Semi real-world performance/pricing.</p>
<p><strong>Background notes (<code>background/</code>, mostly <code>draft: true</code>):</strong> <code>diesel_electrification.md</code> (where diesel goes), <code>diesel_segment_profiles.md</code> (12-segment appendix), <code>diesel_economics.md</code> (TCO by segment — fuel share 2% passenger → 62% mining haul), <code>etruck_economics.md</code> (per-km consumption &amp; diesel→kWh ratios), <code>diesel_in_mining.md</code>, <code>Fortescue_diesel_replacement.md</code> (~$1.1 bn/yr savings, 5–6 yr payback), plus FTC, swap-vs-CCS, iron-bridge-magnetite notes.</p>
<hr>
</section>
<section id="methodology-notes" class="level2">
<h2 class="anchored" data-anchor-id="methodology-notes">Methodology notes</h2>
<ul>
<li><strong>National total</strong> comes from Petroleum Statistics (#1). <strong>On-road split</strong> from ABS SMVU (#2) — but that survey ended in 2020, so the split is scaled to the current national total rather than re-measured. <strong>Off-road (mining/ag)</strong> built from IEEFA (#3) + FTC claims (#5), cross-checked against Energy Statistics Table F (#4).</li>
<li><strong>13/12-segment scorecard</strong> is the analytical spine: each segment scored on diesel volume, economics (fuel share of TCO), and security/strategic value → bubble chart + policy scorecard.</li>
<li><strong>$22 bn import-substitution</strong> figure = full diesel volume × import price, framed as balance-of-trade. The oil-imports angle is woven through (import dependence, “crisis diesel price” scenarios sharply improve paybacks) rather than a standalone piece.</li>
<li>Fortescue model uses two capex sets (aggressive Chinese-supplier pricing vs conservative); headline IRR uses conservative; Pilbara wind CF from renewables.ninja (#8).</li>
</ul>
<hr>
</section>
<section id="open-questions-follow-ups" class="level2">
<h2 class="anchored" data-anchor-id="open-questions-follow-ups">Open questions / follow-ups</h2>
<ul>
<li>No dedicated oil-imports/energy-security standalone piece — the import-dependence and liquid-fuel-security argument could be developed further (IEA 90-day reserve obligation, refinery closures, single-source supply chains).</li>
<li>ABS SMVU discontinuation (#2) leaves the on-road split increasingly stale — watch for any replacement series.</li>
<li>Diesel passenger-car segment flagged as low-effort win (NVES + FBT levers already exist) but not deeply costed.</li>
</ul>
<hr>
</section>
<section id="synthesis-extension-june-2026-trade-flow-comparison" class="level2">
<h2 class="anchored" data-anchor-id="synthesis-extension-june-2026-trade-flow-comparison">Synthesis extension (June 2026): trade-flow comparison</h2>
<p>Added a synthesis comparing Australia’s big export earners against the oil import bill, framed as net trade balances. <strong>Chart:</strong> <code>media/trade_flows_net.png</code> — Flexoki diverging stacked bar. <strong>Script:</strong> <code>scripts/trade_flows_net.py</code>. <strong>Raw data:</strong> <code>scripts/data/abs_merch_{imp,exp}_may25_apr26.csv</code>.</p>
<section id="headline-net-positions-abn-trailing-12-months" class="level3">
<h3 class="anchored" data-anchor-id="headline-net-positions-abn-trailing-12-months">Headline net positions (A$bn, trailing 12 months)</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 26%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Flow</th>
<th style="text-align: right;">Net</th>
<th style="text-align: left;">Detail</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Coal</td>
<td style="text-align: right;"><strong>+64.2</strong></td>
<td style="text-align: left;">SITC 32; imports ~0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gas (LNG)</td>
<td style="text-align: right;"><strong>+58.1</strong></td>
<td style="text-align: left;">SITC 34 (343 LNG +56.4, 342 LPG +1.7); imports ~0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tourism — education</td>
<td style="text-align: right;"><strong>+54.7</strong></td>
<td style="text-align: left;">credits 55.1, debits 0.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tourism — personal ex-education</td>
<td style="text-align: right;"><strong>−43.2</strong></td>
<td style="text-align: left;">credits 25.7, debits 68.8 (deficit; Australians out-spend inbound)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oil (petroleum, SITC 33)</td>
<td style="text-align: right;"><strong>−45.0</strong></td>
<td style="text-align: left;">imports 59.1, exports 14.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">↳ crude (333)</td>
<td style="text-align: right;">+0.9</td>
<td style="text-align: left;">imp 7.8 / exp 8.8 — roughly net-neutral</td>
</tr>
<tr class="odd">
<td style="text-align: left;">↳ refined products (334)</td>
<td style="text-align: right;"><strong>−44.8</strong></td>
<td style="text-align: left;">imp 50.1 / exp 5.3 — the whole deficit</td>
</tr>
<tr class="even">
<td style="text-align: left;">↳ other petroleum (335)</td>
<td style="text-align: right;">−1.2</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<p><strong>Key finding:</strong> the entire oil deficit is <strong>refined-product imports</strong>; crude is net-neutral. Coal, gas and education are now within ~$10bn of each other ($64 / $58 / $55bn). Diesel alone (~−$28.5bn est.) is the single largest slice of the oil import bill.</p>
</section>
<section id="data-access-how-to-refresh-important-reproducible" class="level3">
<h3 class="anchored" data-anchor-id="data-access-how-to-refresh-important-reproducible">Data access — how to refresh (IMPORTANT, reproducible)</h3>
<p>Goods (coal/gas/oil) by SITC come from the ABS SDMX API dataflows <strong><code>MERCH_IMP</code></strong> / <strong><code>MERCH_EXP</code></strong> (these go to 3-digit SITC; dimension order <code>COMMODITY_SITC.COUNTRY.STATE.FREQ</code>, <code>TOT</code>=total, <code>M</code>=monthly; OBS_VALUE in thousands AUD, UNIT_MULT=3). The <code>Accept</code> header is essential — without it you get XML:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">-H</span> <span class="st">"Accept: application/vnd.sdmx.data+csv"</span> <span class="dt">\</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://data.api.abs.gov.au/rest/data/ABS,MERCH_IMP,1.0.0/.TOT..M?startPeriod=2025-05&amp;endPeriod=2026-04"</span> <span class="at">-o</span> merch_imp.csv</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">curl</span> <span class="at">-H</span> <span class="st">"Accept: application/vnd.sdmx.data+csv"</span> <span class="dt">\</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://data.api.abs.gov.au/rest/data/ABS,MERCH_EXP,1.0.0/.TOT..M?startPeriod=2025-05&amp;endPeriod=2026-04"</span> <span class="at">-o</span> merch_exp.csv</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Tourism (travel) is quarterly from ABS BoP cat. 5302.0 Tables 8/9 (see input-data table above).</p>
<p><strong>4-digit limitation:</strong> neither the ABS open cube nor DFAT pivot tables publish diesel (SITC 3344) vs petrol (3342) in dollars — they stop at “refined products” (334) as one lump. The diesel/petrol split in the chart is <strong>estimated</strong> by applying US EIA Australia Country Analysis Brief (Dec 2025, 2024 data) import-VOLUME shares — diesel/gasoil 57%, petrol 25%, jet 13%, other 5% — to the ABS refined-import VALUE; “other” is the residual so the bar sums to the exact −45.0. To get exact 4-digit dollars would need a custom ABS data request or DCCEEW APS value data.</p>
<p><strong>Petroleum import spike:</strong> Mar–Apr 2026 petroleum imports jumped (Apr ~$9.2bn vs ~$4.5bn run-rate) — this is the <strong>Hormuz crisis</strong> price/volume shock (real, not an artefact). It lifts the net oil deficit from a ~−$36bn run-rate to the reported −$45.0bn.</p>
</section>
</section>
<section id="diesel-sub-sector-breakdown-mining-reconciliation-settled-apr-2026" class="level2">
<h2 class="anchored" data-anchor-id="diesel-sub-sector-breakdown-mining-reconciliation-settled-apr-2026">Diesel sub-sector breakdown — mining reconciliation (settled Apr 2026)</h2>
<p>Chart <code>media/diesel_by_subsector.png</code> (script <code>scripts/diesel_by_subsector.py</code>), trailing diesel by sub-sector.</p>
<p><strong>Key rule: mining diesel = 7.8 BL, NOT 9.6 BL.</strong> IEEFA’s 9.6 BL is the <em>industry / Energy-Accounts</em> basis (counts a mining company’s own transport, on-site generation and mine construction). AES Table F <em>activity</em> basis reallocates those out → core extraction/processing = 299.6 PJ = <strong>7.8 BL</strong>. Combining 9.6 with the SMVU road split <strong>double-counts</strong> mining transport. Settled in email thread with IEEFA’s Andrew Gorringe (Fastmail “Finding source for a chart”, 16 Apr 2026).</p>
<p>Agreed segments (BL/yr): mining 7.8 (coal/iron/other = IEEFA 48/26/26 → 3.7/2.0/2.0); road 16.0 (B-doubles 4.0 + all other 12.0, SMVU FY19-20); construction 2.5 (kept vs AES 0.7 — gap is equipment-hire firms, not road trucks); agriculture 2.3; rail 1.3; utilities/commercial/mfg 2.3. Total ~32.2 BL (AES basis) vs APS sales 33.5 BL (sales-vs-consumption + vintage).</p>
</section>
<section id="related" class="level2">
<h2 class="anchored" data-anchor-id="related">Related</h2>
<ul>
<li>See <code>_research_memories/data_centre_backup_2026.md</code> — overlaps on diesel gensets and Fortescue/battery-swap.</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>